import type { IndustryToolMapEntry } from './types';

export const aerospaceEntries: IndustryToolMapEntry[] = [
  // ── 1. AS9100 Quality ─────────────────────────────────────────────────
  {
    id: 'aero-as9100',
    skill: 'AS9100 Quality',
    skill_zh: 'AS9100航空质量管理',
    industry: 'aerospace',
    industry_context: 'AS9100 is the mandatory quality management standard for the aerospace supply chain, built on ISO 9001 with additional requirements for safety, configuration management, and risk. Every Tier 1/2/3 supplier must be certified.',
    industry_context_zh: 'AS9100是航空供应链的强制质量管理标准，基于ISO 9001增加了安全、配置管理和风险要求。每个一/二/三级供应商都必须获得认证。',
    tools: [
      {
        name: 'IQS (ETQ Reliance)',
        name_zh: 'ETQ Reliance质量管理系统',
        vendor: 'ETQ (Hexagon)',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.etq.com/',
        alternatives: ['Qualio', 'MasterControl', 'Arena QMS'],
      },
      {
        name: 'Minitab',
        name_zh: 'Minitab统计软件',
        vendor: 'Minitab LLC',
        tier: 'essential',
        free_tier: true,
        free_tier_note: '30-day free trial',
        url: 'https://www.minitab.com/',
        alternatives: ['JMP (SAS)', 'R (free)'],
      },
      {
        name: 'OASIS (IAQG Database)',
        name_zh: 'OASIS航空质量数据库',
        vendor: 'IAQG',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.iaqg.org/oasis/',
      },
    ],
    training: [
      {
        name: 'SAE International — AS9100 Training',
        name_zh: 'SAE国际AS9100培训',
        region: 'global',
        url: 'https://www.sae.org/learn/professional-development',
        price_range: '$500-2000',
        format: 'hybrid',
        certification: 'SAE AS9100 Internal Auditor',
        language: ['en'],
      },
      {
        name: 'BSI — AS9100 Lead Auditor',
        name_zh: 'BSI AS9100主任审核员',
        region: 'global',
        url: 'https://www.bsigroup.com/en-GB/our-services/training/',
        price_range: '£1500-3000',
        format: 'hybrid',
        certification: 'IRCA Certified Lead Auditor',
        language: ['en'],
      },
      {
        name: 'TUV SUD — AS9100',
        name_zh: 'TUV南德AS9100培训',
        region: 'DE',
        url: 'https://www.tuvsud.com/en/services/training',
        price_range: '€1500-3500',
        format: 'hybrid',
        certification: 'TUV Certified AS9100 Auditor',
        language: ['de', 'en'],
      },
      {
        name: '中国航空综合技术研究所培训',
        name_zh: '中航综合技术所AS9100培训',
        region: 'CN',
        url: 'https://www.cast301.com/',
        price_range: '¥3000-8000',
        format: 'hybrid',
        certification: 'AS9100内审员证书',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'Quality Management Open Frameworks',
        repo_url: 'https://github.com/QualitySphere/QualitySphere',
        stars: '100+',
        what_to_learn: 'QMS data model design: CAPA workflows, nonconformance tracking, audit management',
        what_to_learn_zh: '质量管理系统数据模型设计：CAPA流程、不合格品跟踪、审核管理',
        estimated_hours: 15,
      },
      {
        order: 2,
        repo_name: 'SPC tools — Python',
        repo_url: 'https://github.com/carlosqsilva/pyspc',
        stars: '200+',
        what_to_learn: 'Statistical Process Control: control charts, capability analysis (Cp/Cpk), measurement system analysis',
        what_to_learn_zh: '统计过程控制：控制图、过程能力分析（Cp/Cpk）、测量系统分析',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'FMEA toolkit',
        repo_url: 'https://github.com/ddrpa/fmea-toolkit',
        stars: '100+',
        what_to_learn: 'FMEA methodology: risk priority number, severity/occurrence/detection analysis for aerospace',
        what_to_learn_zh: 'FMEA方法论：风险优先数、严重度/发生频率/可探测度分析（航空领域）',
        estimated_hours: 10,
      },
    ],
    capstone: {
      title: 'AS9100 Quality System Implementation for a Machining Shop',
      title_zh: '机加工车间AS9100质量体系实施',
      difficulty: 'intermediate',
      time_hours: 40,
      deliverables: [
        'Quality manual aligned with AS9100 Rev D clauses',
        'Process FMEA for critical machining process (PFMEA)',
        'Control plan with SPC for key characteristics',
        'Internal audit checklist and mock audit report',
      ],
      deliverables_zh: [
        '符合AS9100 Rev D条款的质量手册',
        '关键加工过程PFMEA',
        '含关键特性SPC的控制计划',
        '内审检查表和模拟审核报告',
      ],
      proves_to_employer: 'Can implement and audit an AS9100 quality system in an aerospace manufacturing environment',
      proves_to_employer_zh: '能够在航空制造环境中实施和审核AS9100质量体系',
    },
    monetization_potential: 'affiliate',
  },

  // ── 2. DO-178C Software ───────────────────────────────────────────────
  {
    id: 'aero-do178c',
    skill: 'DO-178C Airborne Software',
    skill_zh: 'DO-178C机载软件',
    industry: 'aerospace',
    industry_context: 'DO-178C is the FAA/EASA standard for safety-critical airborne software certification. Software at DAL A (catastrophic failure) requires 100% MC/DC coverage. This is a high-barrier, high-salary niche.',
    industry_context_zh: 'DO-178C是FAA/EASA针对安全关键机载软件的认证标准。DAL A级（灾难性故障）软件要求100% MC/DC覆盖率。这是一个高门槛、高薪资的细分领域。',
    tools: [
      {
        name: 'LDRA Tool Suite',
        name_zh: 'LDRA代码分析工具',
        vendor: 'LDRA',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.ldra.com/',
        alternatives: ['VectorCAST', 'Rapita RVS', 'Parasoft C/C++test'],
      },
      {
        name: 'VectorCAST',
        name_zh: 'VectorCAST单元测试',
        vendor: 'Vector',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.vector.com/int/en/products/products-a-z/software/vectorcast/',
        alternatives: ['LDRA TBrun', 'Cantata'],
      },
      {
        name: 'SCADE Suite',
        name_zh: 'SCADE模型化开发',
        vendor: 'Ansys',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.ansys.com/products/embedded-software/ansys-scade-suite',
      },
      {
        name: 'GCC/GDB + gcov',
        name_zh: 'GCC/GDB + gcov',
        vendor: 'GNU',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free and open-source — commonly used for DAL C/D projects',
        url: 'https://gcc.gnu.org/',
      },
    ],
    training: [
      {
        name: 'AFuzion — DO-178C Training',
        name_zh: 'AFuzion DO-178C培训',
        region: 'global',
        url: 'https://afuzion.com/do-178c-training/',
        price_range: '$2000-5000',
        format: 'hybrid',
        certification: 'AFuzion DO-178C Certificate',
        language: ['en'],
      },
      {
        name: 'EUROCAE — DO-178C/ED-12C Workshops',
        name_zh: 'EUROCAE DO-178C研讨会',
        region: 'EU',
        url: 'https://www.eurocae.net/',
        price_range: '€1500-4000',
        format: 'hybrid',
        language: ['en'],
      },
      {
        name: 'Udemy — DO-178C Fundamentals',
        name_zh: 'Udemy DO-178C基础',
        region: 'global',
        url: 'https://www.udemy.com/topic/do-178/',
        price_range: '¥79-299',
        format: 'online',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'CUnit',
        repo_url: 'https://github.com/jacklicn/CUnit',
        stars: '400+',
        what_to_learn: 'Unit testing in C — the foundation of DO-178C low-level testing',
        what_to_learn_zh: 'C语言单元测试——DO-178C底层测试的基础',
        estimated_hours: 10,
      },
      {
        order: 2,
        repo_name: 'MISRA C examples',
        repo_url: 'https://github.com/TexasInstruments/mcupsdk-core',
        stars: '200+',
        what_to_learn: 'MISRA C coding standards and static analysis practices used in safety-critical aerospace code',
        what_to_learn_zh: 'MISRA C编码标准和安全关键航空软件中的静态分析实践',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'PX4 Autopilot',
        repo_url: 'https://github.com/PX4/PX4-Autopilot',
        stars: '8k+',
        what_to_learn: 'Study a real avionics-adjacent codebase: architecture, coding standards, safety patterns, HITL testing',
        what_to_learn_zh: '研究真实的航电级代码库：架构、编码标准、安全模式、硬件在环测试',
        estimated_hours: 25,
      },
    ],
    capstone: {
      title: 'DAL C Software Lifecycle Package for a Flight Data Recorder Module',
      title_zh: 'DAL C级飞行数据记录模块软件生命周期包',
      difficulty: 'advanced',
      time_hours: 60,
      deliverables: [
        'Software requirements document (SRS) with traceability matrix',
        'C source code with MISRA C compliance, reviewed by static analysis tool',
        'Unit test suite with MC/DC coverage report',
        'Software Accomplishment Summary (SAS) document',
      ],
      deliverables_zh: [
        '软件需求规格书（SRS）含需求追溯矩阵',
        'MISRA C合规的C源代码（经静态分析工具审查）',
        '单元测试套件含MC/DC覆盖率报告',
        '软件完成总结（SAS）文档',
      ],
      proves_to_employer: 'Can execute a DO-178C software lifecycle from requirements through verification with traceability',
      proves_to_employer_zh: '能够执行DO-178C软件生命周期——从需求到验证，含完整追溯',
    },
    monetization_potential: 'affiliate',
  },

  // ── 3. Composite Materials (CATIA Composites) ─────────────────────────
  {
    id: 'aero-composites',
    skill: 'Composite Materials Engineering',
    skill_zh: '复合材料工程',
    industry: 'aerospace',
    industry_context: 'Carbon fiber composites make up 50%+ of modern aircraft structure (Boeing 787, Airbus A350). CATIA Composites Design and FEA tools are essential for ply design, draping, and structural analysis.',
    industry_context_zh: '碳纤维复合材料占现代飞机结构的50%以上（波音787、空客A350）。CATIA复合材料设计和FEA工具是铺层设计、成型和结构分析的核心。',
    tools: [
      {
        name: 'CATIA Composites Design',
        name_zh: 'CATIA复合材料设计',
        vendor: 'Dassault Systemes',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.3ds.com/products/catia/composites-design',
        alternatives: ['Siemens Fibersim', 'Anaglyph Laminate Tools'],
      },
      {
        name: 'Abaqus (Composites Module)',
        name_zh: 'Abaqus复合材料模块',
        vendor: 'Dassault Systemes',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.3ds.com/products/simulia/abaqus',
        alternatives: ['ANSYS ACP', 'MSC Marc'],
      },
      {
        name: 'eLamX² (TU Dresden)',
        name_zh: 'eLamX²层合板分析',
        vendor: 'TU Dresden',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free academic tool for classical laminate theory analysis',
        url: 'https://elamx2.de/',
      },
    ],
    training: [
      {
        name: 'Coursera — Composite Materials (Georgia Tech)',
        name_zh: 'Coursera复合材料（佐治亚理工）',
        region: 'global',
        url: 'https://www.coursera.org/learn/composite-materials',
        price_range: 'Free (audit)',
        format: 'online',
        certification: 'Coursera Certificate',
        language: ['en'],
      },
      {
        name: 'DLR / Fraunhofer — Composite Manufacturing',
        name_zh: 'DLR/Fraunhofer复合材料制造培训',
        region: 'DE',
        url: 'https://www.dlr.de/',
        price_range: '€1500-4000',
        format: 'hybrid',
        language: ['de', 'en'],
      },
      {
        name: '中国航空研究院复合材料技术培训',
        name_zh: '中航工业复合材料技术培训',
        region: 'CN',
        url: 'https://www.avic.com/',
        price_range: '¥3000-10000',
        format: 'hybrid',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'composites-python (material-mechanics)',
        repo_url: 'https://github.com/compositesresearch/composites',
        stars: '100+',
        what_to_learn: 'Classical Laminate Theory in Python: ABD matrix, failure criteria (Tsai-Wu, Hashin)',
        what_to_learn_zh: 'Python经典层合板理论：ABD矩阵、失效准则（Tsai-Wu、Hashin）',
        estimated_hours: 15,
      },
      {
        order: 2,
        repo_name: 'FEBio',
        repo_url: 'https://github.com/febiosoftware/FEBio',
        stars: '200+',
        what_to_learn: 'Finite element analysis fundamentals applicable to composite structures',
        what_to_learn_zh: '适用于复合材料结构的有限元分析基础',
        estimated_hours: 20,
      },
      {
        order: 3,
        repo_name: 'OpenAeroStruct',
        repo_url: 'https://github.com/mdolab/OpenAeroStruct',
        stars: '200+',
        what_to_learn: 'Aerostructural optimization: wing design combining aerodynamics and composite structure',
        what_to_learn_zh: '气动结构优化：结合空气动力学和复合材料结构的机翼设计',
        estimated_hours: 20,
      },
    ],
    capstone: {
      title: 'Composite Wing Skin Panel Design and Structural Analysis',
      title_zh: '复合材料机翼蒙皮面板设计与结构分析',
      difficulty: 'advanced',
      time_hours: 50,
      deliverables: [
        'Laminate layup design using CLT (eLamX² or Python)',
        'FEA model with progressive damage analysis (Abaqus or open-source)',
        'Ply-by-ply stacking sequence optimization for weight reduction',
        'Manufacturing feasibility report: draping analysis, tooling considerations',
      ],
      deliverables_zh: [
        '基于CLT的层合板铺层设计（eLamX²或Python）',
        '含渐进损伤分析的有限元模型（Abaqus或开源工具）',
        '逐层铺层序列优化实现减重',
        '制造可行性报告：成型分析、工装考虑',
      ],
      proves_to_employer: 'Can design composite laminates, perform structural analysis, and consider manufacturing constraints',
      proves_to_employer_zh: '能够设计复合材料层合板、进行结构分析并考虑制造约束',
    },
    monetization_potential: 'affiliate',
  },

  // ── 4. CFD / Aerodynamics (ANSYS Fluent) ──────────────────────────────
  {
    id: 'aero-cfd',
    skill: 'CFD / Aerodynamics',
    skill_zh: 'CFD/空气动力学',
    industry: 'aerospace',
    industry_context: 'Computational Fluid Dynamics is indispensable for aircraft design — from airfoil optimization to full aircraft drag prediction. ANSYS Fluent is the commercial standard; OpenFOAM is the powerful open-source alternative.',
    industry_context_zh: '计算流体动力学是飞机设计不可或缺的工具——从翼型优化到全机阻力预测。ANSYS Fluent是商业标准；OpenFOAM是强大的开源替代方案。',
    tools: [
      {
        name: 'ANSYS Fluent',
        name_zh: 'ANSYS Fluent流体仿真',
        vendor: 'Ansys',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Ansys Student license free (limited mesh size)',
        url: 'https://www.ansys.com/products/fluids/ansys-fluent',
        alternatives: ['STAR-CCM+ (Siemens)', 'COMSOL CFD Module'],
      },
      {
        name: 'OpenFOAM',
        name_zh: 'OpenFOAM开源CFD',
        vendor: 'OpenCFD / ESI Group',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Fully open-source, GPL license',
        url: 'https://www.openfoam.com/',
      },
      {
        name: 'XFOIL / XFoil.js',
        name_zh: 'XFOIL翼型分析',
        vendor: 'MIT (Mark Drela)',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free academic tool for subsonic airfoil analysis',
        url: 'https://web.mit.edu/drela/Public/web/xfoil/',
      },
    ],
    training: [
      {
        name: 'Ansys Innovation Courses — Fluent',
        name_zh: 'Ansys创新课程Fluent',
        region: 'global',
        url: 'https://courses.ansys.com/',
        price_range: 'Free',
        format: 'online',
        certification: 'Ansys Fluent Certified',
        language: ['en'],
      },
      {
        name: 'CFD Online — OpenFOAM Training',
        name_zh: 'CFD Online OpenFOAM培训',
        region: 'global',
        url: 'https://www.cfd-online.com/',
        price_range: 'Free',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'TU Munich — Aerodynamics Summer School',
        name_zh: '慕尼黑工大空气动力学暑期学校',
        region: 'DE',
        url: 'https://www.tum.de/',
        price_range: '€1000-3000',
        format: 'hybrid',
        language: ['en', 'de'],
      },
      {
        name: '北京航空航天大学CFD培训',
        name_zh: '北航CFD培训班',
        region: 'CN',
        url: 'https://www.buaa.edu.cn/',
        price_range: '¥2000-6000',
        format: 'hybrid',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'OpenFOAM',
        repo_url: 'https://github.com/OpenFOAM/OpenFOAM-dev',
        stars: '1.6k+',
        what_to_learn: 'CFD fundamentals: mesh generation, turbulence models (k-epsilon, SST), solver setup',
        what_to_learn_zh: 'CFD基础：网格生成、湍流模型（k-epsilon、SST）、求解器设置',
        estimated_hours: 30,
      },
      {
        order: 2,
        repo_name: 'SU2 — CFD Solver',
        repo_url: 'https://github.com/su2code/SU2',
        stars: '1.4k+',
        what_to_learn: 'Aerodynamic shape optimization: adjoint methods, design space exploration',
        what_to_learn_zh: '气动外形优化：伴随方法、设计空间探索',
        estimated_hours: 25,
      },
      {
        order: 3,
        repo_name: 'PyAeroDesign (NACA Tools)',
        repo_url: 'https://github.com/dgorissen/pyairfoil',
        stars: '100+',
        what_to_learn: 'Airfoil parametrization, lift/drag analysis, and wing design fundamentals in Python',
        what_to_learn_zh: 'Python翼型参数化、升力/阻力分析和机翼设计基础',
        estimated_hours: 10,
      },
    ],
    capstone: {
      title: 'UAV Wing Aerodynamic Optimization using CFD',
      title_zh: '基于CFD的无人机机翼气动优化',
      difficulty: 'advanced',
      time_hours: 50,
      deliverables: [
        'OpenFOAM or Fluent simulation of a UAV wing at multiple angles of attack',
        'Mesh convergence study and validation against XFOIL/experimental data',
        'Parametric study: sweep angle, taper ratio, airfoil selection',
        'Optimization report with Cl/Cd improvements and weight-drag tradeoff analysis',
      ],
      deliverables_zh: [
        'OpenFOAM或Fluent无人机机翼多攻角仿真',
        '网格收敛性研究和XFOIL/实验数据验证',
        '参数化研究：后掠角、梢根比、翼型选择',
        '优化报告含升阻比改进和重量-阻力权衡分析',
      ],
      proves_to_employer: 'Can set up, validate, and optimize aerospace CFD simulations for aerodynamic design',
      proves_to_employer_zh: '能够设置、验证和优化航空CFD仿真用于气动设计',
    },
    monetization_potential: 'affiliate',
  },

  // ── 5. Structural Analysis (MSC Nastran) ──────────────────────────────
  {
    id: 'aero-structures',
    skill: 'Structural Analysis',
    skill_zh: '结构分析（航空）',
    industry: 'aerospace',
    industry_context: 'Aerospace structural analysis ensures airframes withstand flight loads, fatigue, and damage tolerance requirements. MSC Nastran is the gold standard for linear/nonlinear FEA in aerospace since the 1960s.',
    industry_context_zh: '航空结构分析确保机体能承受飞行载荷、疲劳和损伤容限要求。MSC Nastran自1960年代以来一直是航空线性/非线性有限元分析的黄金标准。',
    tools: [
      {
        name: 'MSC Nastran',
        name_zh: 'MSC Nastran结构分析',
        vendor: 'Hexagon (MSC Software)',
        tier: 'essential',
        free_tier: false,
        url: 'https://hexagon.com/products/product-groups/computer-aided-engineering-software/msc-nastran',
        alternatives: ['ANSYS Mechanical', 'Abaqus', 'Optistruct'],
      },
      {
        name: 'MSC Patran',
        name_zh: 'MSC Patran前后处理',
        vendor: 'Hexagon (MSC Software)',
        tier: 'essential',
        free_tier: false,
        url: 'https://hexagon.com/products/product-groups/computer-aided-engineering-software/patran',
        alternatives: ['HyperMesh (Altair)', 'FEMAP'],
      },
      {
        name: 'CalculiX',
        name_zh: 'CalculiX开源FEA',
        vendor: 'Open Source',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Open-source FEA solver compatible with Abaqus input format',
        url: 'http://www.calculix.de/',
      },
      {
        name: 'FreeCAD FEM',
        name_zh: 'FreeCAD有限元模块',
        vendor: 'Open Source',
        tier: 'emerging',
        free_tier: true,
        free_tier_note: 'Open-source CAD with integrated FEM using CalculiX/Elmer',
        url: 'https://www.freecad.org/',
      },
    ],
    training: [
      {
        name: 'MSC Software Training (Nastran/Patran)',
        name_zh: 'MSC官方Nastran/Patran培训',
        region: 'global',
        url: 'https://hexagon.com/resources/resource-library?category=training',
        price_range: '$2000-5000',
        format: 'hybrid',
        certification: 'MSC Nastran Certified Analyst',
        language: ['en'],
      },
      {
        name: 'NAFEMS — FEA Training',
        name_zh: 'NAFEMS有限元分析培训',
        region: 'EU',
        url: 'https://www.nafems.org/training/',
        price_range: '£800-2500',
        format: 'hybrid',
        certification: 'NAFEMS PSE Certification',
        language: ['en'],
      },
      {
        name: 'Altair University — FEA Fundamentals',
        name_zh: 'Altair大学FEA基础',
        region: 'global',
        url: 'https://altairuniversity.com/',
        price_range: 'Free',
        format: 'online',
        language: ['en'],
      },
      {
        name: '中国航空计算技术研究所培训',
        name_zh: '中航计算所结构分析培训',
        region: 'CN',
        url: 'https://www.avic.com/',
        price_range: '¥3000-10000',
        format: 'hybrid',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'CalculiX',
        repo_url: 'https://github.com/calculix/ccx_prool',
        stars: '200+',
        what_to_learn: 'FEA fundamentals: element types, boundary conditions, linear static and modal analysis',
        what_to_learn_zh: '有限元基础：单元类型、边界条件、线性静力和模态分析',
        estimated_hours: 25,
      },
      {
        order: 2,
        repo_name: 'pyNastran',
        repo_url: 'https://github.com/SteveDoyle2/pyNastran',
        stars: '400+',
        what_to_learn: 'Read, write, and automate Nastran BDF/OP2 files with Python for parametric studies',
        what_to_learn_zh: '用Python读写和自动化Nastran BDF/OP2文件，进行参数化研究',
        estimated_hours: 20,
      },
      {
        order: 3,
        repo_name: 'OpenAeroStruct',
        repo_url: 'https://github.com/mdolab/OpenAeroStruct',
        stars: '200+',
        what_to_learn: 'Coupled aero-structural optimization: understand how structural sizing drives aircraft performance',
        what_to_learn_zh: '气动-结构耦合优化：理解结构尺寸如何影响飞机性能',
        estimated_hours: 20,
      },
    ],
    capstone: {
      title: 'Aircraft Fuselage Panel Stress Analysis and Fatigue Life Prediction',
      title_zh: '飞机机身壁板应力分析与疲劳寿命预测',
      difficulty: 'advanced',
      time_hours: 55,
      deliverables: [
        'FEA model of fuselage panel with stiffeners (CalculiX or Nastran)',
        'Static stress analysis under pressurization and flight loads',
        'Fatigue life estimation using S-N curves and Miner rule',
        'Damage tolerance analysis: crack growth and residual strength',
      ],
      deliverables_zh: [
        '含加筋的机身壁板有限元模型（CalculiX或Nastran）',
        '增压和飞行载荷下的静力应力分析',
        '基于S-N曲线和Miner法则的疲劳寿命估算',
        '损伤容限分析：裂纹扩展和剩余强度',
      ],
      proves_to_employer: 'Can perform aerospace structural analysis including fatigue and damage tolerance per certification requirements',
      proves_to_employer_zh: '能够按适航认证要求进行航空结构分析，包括疲劳和损伤容限',
    },
    monetization_potential: 'affiliate',
  },
];
