import type { IndustryToolMapEntry } from './types';

export const automotiveEntries: IndustryToolMapEntry[] = [
  // 1. AUTOSAR
  {
    id: 'auto-autosar',
    skill: 'AUTOSAR',
    skill_zh: 'AUTOSAR架构开发',
    industry: 'automotive',
    industry_context: 'AUTOSAR is the standard software architecture for automotive ECUs, required by nearly all OEMs and Tier-1 suppliers for body, powertrain, and ADAS controllers.',
    industry_context_zh: 'AUTOSAR是汽车ECU的标准软件架构，几乎所有主机厂和Tier-1供应商在车身、动力总成和ADAS控制器开发中都要求使用。',
    tools: [
      {
        name: 'Vector DaVinci Developer',
        name_zh: 'Vector DaVinci开发工具',
        vendor: 'Vector Informatik',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.vector.com/int/en/products/products-a-z/software/davinci-developer/',
        alternatives: ['EB tresos Studio', 'ARTOP'],
      },
      {
        name: 'ARTOP (AUTOSAR Tool Platform)',
        name_zh: 'ARTOP开源AUTOSAR工具平台',
        vendor: 'Eclipse Foundation',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Fully open-source Eclipse-based AUTOSAR tooling',
        url: 'https://www.artop.org/',
      },
      {
        name: 'EB tresos Studio',
        name_zh: 'EB tresos基础软件配置工具',
        vendor: 'Elektrobit (Continental)',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.elektrobit.com/products/ecu/eb-tresos/',
      },
    ],
    training: [
      {
        name: 'Vector Academy — AUTOSAR Training',
        name_zh: 'Vector学院 — AUTOSAR培训',
        region: 'global',
        url: 'https://www.vector.com/int/en/know-how/training/',
        price_range: '€1,500–€3,000',
        format: 'hybrid',
        certification: 'Vector Certificate of Completion',
        language: ['en', 'de'],
      },
      {
        name: 'KPIT AUTOSAR Training',
        name_zh: 'KPIT AUTOSAR培训',
        region: 'global',
        url: 'https://www.kpit.com/services/autosar/',
        price_range: '$500–$2,000',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'Udemy — AUTOSAR from Scratch',
        name_zh: 'Udemy — AUTOSAR从零开始',
        region: 'global',
        url: 'https://www.udemy.com/course/autosar-from-scratch/',
        price_range: '$15–$100',
        format: 'online',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'AUTOSARxEVA/autosar',
        repo_url: 'https://github.com/AUTOSARxEVA/autosar',
        stars: '200+',
        what_to_learn: 'Understand AUTOSAR classic platform architecture and SWC design patterns',
        what_to_learn_zh: '理解AUTOSAR经典平台架构和软件组件设计模式',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'openxc/openxc-python',
        repo_url: 'https://github.com/openxc/openxc-python',
        stars: '200+',
        what_to_learn: 'Learn vehicle data interfaces and CAN message handling used alongside AUTOSAR stacks',
        what_to_learn_zh: '学习与AUTOSAR堆栈配合使用的车辆数据接口和CAN消息处理',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'COVESA/vsomeip',
        repo_url: 'https://github.com/COVESA/vsomeip',
        stars: '1000+',
        what_to_learn: 'Study SOME/IP implementation, the key middleware protocol in AUTOSAR Adaptive',
        what_to_learn_zh: '学习SOME/IP实现，AUTOSAR Adaptive平台的关键中间件协议',
        estimated_hours: 25,
      },
    ],
    capstone: {
      title: 'AUTOSAR-Compliant Window Lifter SWC',
      title_zh: 'AUTOSAR标准车窗升降器软件组件',
      difficulty: 'intermediate',
      time_hours: 40,
      deliverables: [
        'ARXML configuration files for SWC, RTE, and BSW modules',
        'Runnable entities with inter-ECU communication via COM',
        'Documentation of component interfaces and port mappings',
      ],
      deliverables_zh: [
        'SWC、RTE和BSW模块的ARXML配置文件',
        '具有通过COM进行ECU间通信的可运行实体',
        '组件接口和端口映射文档',
      ],
      proves_to_employer: 'Demonstrates ability to design and configure AUTOSAR software components — the #1 skill OEMs and Tier-1s test in embedded interviews.',
      proves_to_employer_zh: '展示设计和配置AUTOSAR软件组件的能力——这是主机厂和Tier-1在嵌入式面试中考察的第一技能。',
    },
    monetization_potential: 'affiliate',
  },

  // 2. Functional Safety (ISO 26262)
  {
    id: 'auto-functional-safety',
    skill: 'Functional Safety (ISO 26262)',
    skill_zh: '功能安全（ISO 26262）',
    industry: 'automotive',
    industry_context: 'ISO 26262 is the mandatory functional safety standard for road vehicles. Every automotive E/E system must have an ASIL rating and safety concept.',
    industry_context_zh: 'ISO 26262是道路车辆的强制性功能安全标准。每个汽车E/E系统都必须有ASIL评级和安全概念。',
    tools: [
      {
        name: 'Medini Analyze',
        name_zh: 'Medini安全分析工具',
        vendor: 'Ansys (formerly ikv++)',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.ansys.com/products/safety-analysis/ansys-medini-analyze',
      },
      {
        name: 'IBM DOORS',
        name_zh: 'IBM DOORS需求管理工具',
        vendor: 'IBM',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.ibm.com/products/requirements-management',
        alternatives: ['Polarion', 'Jama Connect'],
      },
      {
        name: 'APIS IQ-FMEA',
        name_zh: 'APIS IQ-FMEA分析工具',
        vendor: 'APIS Informationstechnologien',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.apis-iq.com/en/',
      },
    ],
    training: [
      {
        name: 'TÜV SÜD — Functional Safety Engineer (ISO 26262)',
        name_zh: 'TÜV SÜD — 功能安全工程师认证',
        region: 'DE',
        url: 'https://www.tuvsud.com/en/themes/functional-safety',
        price_range: '€3,000–€6,000',
        format: 'hybrid',
        certification: 'TÜV Functional Safety Engineer (FSCP)',
        language: ['en', 'de'],
      },
      {
        name: 'SGS-TÜV Saar — ISO 26262 Certification',
        name_zh: 'SGS-TÜV Saar — ISO 26262认证',
        region: 'EU',
        url: 'https://www.sgs-tuev-saar.com/en/functional-safety',
        price_range: '€2,500–€5,000',
        format: 'hybrid',
        certification: 'Functional Safety Professional',
        language: ['en', 'de'],
      },
      {
        name: 'Udemy — ISO 26262 Functional Safety',
        name_zh: 'Udemy — ISO 26262功能安全入门',
        region: 'global',
        url: 'https://www.udemy.com/course/iso-26262-functional-safety/',
        price_range: '$15–$100',
        format: 'online',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'openSAFETY/openSAFETY',
        repo_url: 'https://github.com/openSAFETY/openSAFETY',
        stars: '100+',
        what_to_learn: 'Understand safety communication protocols and their implementation patterns',
        what_to_learn_zh: '理解安全通信协议及其实现模式',
        estimated_hours: 15,
      },
      {
        order: 2,
        repo_name: 'nasa/fprime',
        repo_url: 'https://github.com/nasa/fprime',
        stars: '10000+',
        what_to_learn: 'Study NASA flight software framework for safety-critical design patterns (applicable to automotive ASIL)',
        what_to_learn_zh: '学习NASA飞行软件框架的安全关键设计模式（可应用于汽车ASIL）',
        estimated_hours: 25,
      },
      {
        order: 3,
        repo_name: 'SPDX/spdx-spec',
        repo_url: 'https://github.com/spdx/spdx-spec',
        stars: '300+',
        what_to_learn: 'Learn SBOM practices for safety-critical software traceability and compliance',
        what_to_learn_zh: '学习安全关键软件可追溯性和合规性的SBOM实践',
        estimated_hours: 10,
      },
    ],
    capstone: {
      title: 'ASIL-B Safety Concept for an EPS System',
      title_zh: 'EPS系统ASIL-B安全概念设计',
      difficulty: 'advanced',
      time_hours: 60,
      deliverables: [
        'Hazard and risk analysis (HARA) with ASIL ratings',
        'Functional safety concept with safety goals and safe states',
        'FMEA/FTA analysis documents',
        'Safety requirements specification in DOORS-compatible format',
      ],
      deliverables_zh: [
        '包含ASIL评级的危害和风险分析（HARA）',
        '包含安全目标和安全状态的功能安全概念',
        'FMEA/FTA分析文档',
        'DOORS兼容格式的安全需求规范',
      ],
      proves_to_employer: 'Shows hands-on ability to perform HARA, derive safety goals, and create a safety concept — the core deliverables of any FuSa engineer role.',
      proves_to_employer_zh: '展示执行HARA、推导安全目标和创建安全概念的实践能力——这是任何功能安全工程师岗位的核心交付物。',
    },
    monetization_potential: 'affiliate',
  },

  // 3. CAN/LIN
  {
    id: 'auto-can-lin',
    skill: 'CAN/LIN Bus',
    skill_zh: 'CAN/LIN总线通信',
    industry: 'automotive',
    industry_context: 'CAN and LIN are the backbone communication protocols in every vehicle. CAN handles powertrain/chassis; LIN handles body electronics like mirrors and seats.',
    industry_context_zh: 'CAN和LIN是每辆车的骨干通信协议。CAN处理动力总成/底盘通信；LIN处理后视镜、座椅等车身电子。',
    tools: [
      {
        name: 'Vector CANoe',
        name_zh: 'Vector CANoe总线分析工具',
        vendor: 'Vector Informatik',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.vector.com/int/en/products/products-a-z/software/canoe/',
        alternatives: ['CANalyzer', 'PCAN-View'],
      },
      {
        name: 'Vector CANalyzer',
        name_zh: 'Vector CANalyzer总线监控工具',
        vendor: 'Vector Informatik',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.vector.com/int/en/products/products-a-z/software/canalyzer/',
      },
      {
        name: 'PEAK PCAN-Basic',
        name_zh: 'PEAK PCAN基础工具',
        vendor: 'PEAK-System',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free PCAN-View software with purchase of PCAN-USB adapter (~€50)',
        url: 'https://www.peak-system.com/PCAN-USB.199.0.html',
      },
    ],
    training: [
      {
        name: 'Vector Academy — CAN/LIN Training',
        name_zh: 'Vector学院 — CAN/LIN培训',
        region: 'global',
        url: 'https://www.vector.com/int/en/know-how/training/',
        price_range: '€1,000–€2,500',
        format: 'hybrid',
        certification: 'Vector Certificate',
        language: ['en', 'de'],
      },
      {
        name: 'CAN in Automation (CiA) — CAN Training',
        name_zh: 'CAN in Automation — CAN培训',
        region: 'EU',
        url: 'https://www.can-cia.org/services/training/',
        price_range: '€500–€1,500',
        format: 'hybrid',
        language: ['en', 'de'],
      },
      {
        name: 'Udemy — Automotive CAN Bus',
        name_zh: 'Udemy — 汽车CAN总线课程',
        region: 'global',
        url: 'https://www.udemy.com/course/can-protocol-decoding/',
        price_range: '$15–$100',
        format: 'online',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'hardbyte/python-can',
        repo_url: 'https://github.com/hardbyte/python-can',
        stars: '2000+',
        what_to_learn: 'Learn CAN bus fundamentals through Python — send/receive frames, decode DBC files',
        what_to_learn_zh: '通过Python学习CAN总线基础——收发帧、解码DBC文件',
        estimated_hours: 15,
      },
      {
        order: 2,
        repo_name: 'commaai/opendbc',
        repo_url: 'https://github.com/commaai/opendbc',
        stars: '2000+',
        what_to_learn: 'Study real-world vehicle DBC files to understand CAN signal definitions across OEMs',
        what_to_learn_zh: '研究真实车辆DBC文件，理解各主机厂的CAN信号定义',
        estimated_hours: 20,
      },
      {
        order: 3,
        repo_name: 'linux-can/can-utils',
        repo_url: 'https://github.com/linux-can/can-utils',
        stars: '2000+',
        what_to_learn: 'Master Linux SocketCAN tools — candump, cansend, cangen for bus testing',
        what_to_learn_zh: '掌握Linux SocketCAN工具——candump、cansend、cangen用于总线测试',
        estimated_hours: 10,
      },
    ],
    capstone: {
      title: 'CAN Bus Dashboard Decoder',
      title_zh: 'CAN总线仪表盘信号解码器',
      difficulty: 'intermediate',
      time_hours: 30,
      deliverables: [
        'Python application that reads CAN frames from a log/interface',
        'DBC file parsing and signal decoding',
        'Live dashboard showing speed, RPM, temperature from real CAN data',
      ],
      deliverables_zh: [
        '从日志/接口读取CAN帧的Python应用',
        'DBC文件解析和信号解码',
        '显示来自真实CAN数据的速度、转速、温度的实时仪表盘',
      ],
      proves_to_employer: 'Demonstrates CAN protocol understanding, DBC handling, and data visualization — exactly what OEMs need from network/diagnostics engineers.',
      proves_to_employer_zh: '展示CAN协议理解、DBC处理和数据可视化能力——正是主机厂对网络/诊断工程师的核心要求。',
    },
    monetization_potential: 'affiliate',
  },

  // 4. MATLAB/Simulink (Automotive)
  {
    id: 'auto-matlab-simulink',
    skill: 'MATLAB/Simulink',
    skill_zh: 'MATLAB/Simulink仿真建模',
    industry: 'automotive',
    industry_context: 'MATLAB/Simulink is the de-facto standard for model-based development (MBD) in automotive — used for control algorithm design, plant modeling, and auto code generation.',
    industry_context_zh: 'MATLAB/Simulink是汽车行业基于模型开发（MBD）的事实标准——用于控制算法设计、被控对象建模和自动代码生成。',
    tools: [
      {
        name: 'MATLAB',
        name_zh: 'MATLAB数值计算环境',
        vendor: 'MathWorks',
        tier: 'essential',
        free_tier: false,
        free_tier_note: 'MATLAB Online free for basic use; academic licenses ~$50/year',
        url: 'https://www.mathworks.com/products/matlab.html',
      },
      {
        name: 'Simulink',
        name_zh: 'Simulink系统建模仿真',
        vendor: 'MathWorks',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.mathworks.com/products/simulink.html',
      },
      {
        name: 'Stateflow',
        name_zh: 'Stateflow状态机建模',
        vendor: 'MathWorks',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.mathworks.com/products/stateflow.html',
      },
    ],
    training: [
      {
        name: 'MathWorks — MATLAB and Simulink Training',
        name_zh: 'MathWorks — MATLAB和Simulink官方培训',
        region: 'global',
        url: 'https://www.mathworks.com/services/training.html',
        price_range: '$500–$3,000',
        format: 'hybrid',
        certification: 'MathWorks Certification',
        language: ['en', 'zh'],
      },
      {
        name: 'Coursera — MATLAB Programming for Engineers',
        name_zh: 'Coursera — MATLAB工程编程',
        region: 'global',
        url: 'https://www.coursera.org/learn/matlab',
        price_range: '$0–$49/month',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'MathWorks — Simulink Onramp (Free)',
        name_zh: 'MathWorks — Simulink入门（免费）',
        region: 'global',
        url: 'https://www.mathworks.com/learn/tutorials/simulink-onramp.html',
        price_range: 'Free',
        format: 'online',
        language: ['en', 'zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'mathworks/MATLAB-Simulink-Challenge-Project-Hub',
        repo_url: 'https://github.com/mathworks/MATLAB-Simulink-Challenge-Project-Hub',
        stars: '300+',
        what_to_learn: 'Explore MathWorks official challenge projects to understand MBD workflow and Simulink patterns',
        what_to_learn_zh: '通过MathWorks官方挑战项目理解MBD工作流和Simulink设计模式',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'mathworks/MathWorks-Excellence-in-Innovation',
        repo_url: 'https://github.com/mathworks/MathWorks-Excellence-in-Innovation',
        stars: '600+',
        what_to_learn: 'Study real engineering projects using Simulink for control, signal processing, and AI',
        what_to_learn_zh: '学习使用Simulink进行控制、信号处理和AI的真实工程项目',
        estimated_hours: 25,
      },
      {
        order: 3,
        repo_name: 'gnu-octave/octave',
        repo_url: 'https://github.com/gnu-octave/octave',
        stars: '2000+',
        what_to_learn: 'Use GNU Octave as free MATLAB alternative to practice scripting and algorithms',
        what_to_learn_zh: '使用GNU Octave作为免费MATLAB替代品练习脚本编写和算法',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'PID Controller for Cruise Control in Simulink',
      title_zh: 'Simulink巡航控制PID控制器',
      difficulty: 'intermediate',
      time_hours: 35,
      deliverables: [
        'Vehicle longitudinal dynamics plant model in Simulink',
        'PID controller with anti-windup and gain scheduling',
        'Auto-generated C code using Simulink Coder (or Embedded Coder)',
        'Test harness with step response and disturbance rejection plots',
      ],
      deliverables_zh: [
        'Simulink中的车辆纵向动力学被控对象模型',
        '具有抗积分饱和和增益调度的PID控制器',
        '使用Simulink Coder（或Embedded Coder）自动生成的C代码',
        '包含阶跃响应和抗干扰图的测试工具',
      ],
      proves_to_employer: 'Shows end-to-end MBD workflow: model → simulate → auto-code — the exact process used at every OEM and Tier-1 for control software.',
      proves_to_employer_zh: '展示端到端MBD工作流：建模→仿真→自动代码生成——这是每家主机厂和Tier-1开发控制软件的标准流程。',
    },
    monetization_potential: 'affiliate',
  },

  // 5. ADAS/Autonomous Driving
  {
    id: 'auto-adas',
    skill: 'ADAS/Autonomous Driving',
    skill_zh: 'ADAS/自动驾驶',
    industry: 'automotive',
    industry_context: 'ADAS and autonomous driving represent the highest-growth segment in automotive. Engineers skilled in perception, planning, and simulation are in extreme demand.',
    industry_context_zh: 'ADAS和自动驾驶是汽车行业增长最快的领域。具备感知、规划和仿真能力的工程师需求极其旺盛。',
    tools: [
      {
        name: 'NVIDIA DriveWorks SDK',
        name_zh: 'NVIDIA DriveWorks自动驾驶SDK',
        vendor: 'NVIDIA',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free for development with NVIDIA DRIVE hardware',
        url: 'https://developer.nvidia.com/drive',
      },
      {
        name: 'CARLA Simulator',
        name_zh: 'CARLA自动驾驶仿真器',
        vendor: 'Intel Labs / Computer Vision Center',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Fully open-source (MIT license)',
        url: 'https://carla.org/',
      },
      {
        name: 'Mobileye Developer Tools',
        name_zh: 'Mobileye开发者工具',
        vendor: 'Mobileye (Intel)',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.mobileye.com/',
      },
    ],
    training: [
      {
        name: 'Udacity — Self-Driving Car Engineer Nanodegree',
        name_zh: 'Udacity — 自动驾驶工程师纳米学位',
        region: 'global',
        url: 'https://www.udacity.com/course/self-driving-car-engineer-nanodegree--nd0013',
        price_range: '$500–$1,500',
        format: 'online',
        certification: 'Udacity Nanodegree',
        language: ['en'],
      },
      {
        name: 'Coursera — Self-Driving Cars Specialization (U of Toronto)',
        name_zh: 'Coursera — 自动驾驶汽车专项课程（多伦多大学）',
        region: 'global',
        url: 'https://www.coursera.org/specializations/self-driving-cars',
        price_range: '$0–$49/month',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'Apollo Auto — Open Course',
        name_zh: '百度Apollo — 开放课程',
        region: 'CN',
        url: 'https://apollo.baidu.com/community/course',
        price_range: 'Free',
        format: 'online',
        language: ['zh', 'en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'carla-simulator/carla',
        repo_url: 'https://github.com/carla-simulator/carla',
        stars: '11000+',
        what_to_learn: 'Set up CARLA simulation environment and learn sensor configuration, scenarios, and autopilot basics',
        what_to_learn_zh: '搭建CARLA仿真环境，学习传感器配置、场景和自动驾驶基础',
        estimated_hours: 25,
      },
      {
        order: 2,
        repo_name: 'ApolloAuto/apollo',
        repo_url: 'https://github.com/ApolloAuto/apollo',
        stars: '25000+',
        what_to_learn: 'Study Baidu Apollo full-stack AD architecture: perception, planning, control, HD map',
        what_to_learn_zh: '学习百度Apollo全栈自动驾驶架构：感知、规划、控制、高精地图',
        estimated_hours: 40,
      },
      {
        order: 3,
        repo_name: 'autowarefoundation/autoware',
        repo_url: 'https://github.com/autowarefoundation/autoware',
        stars: '9000+',
        what_to_learn: 'Explore Autoware open-source AD stack based on ROS 2 — widely used in research and industry',
        what_to_learn_zh: '探索基于ROS 2的Autoware开源自动驾驶栈——在科研和工业中广泛使用',
        estimated_hours: 30,
      },
    ],
    capstone: {
      title: 'Lane-Keeping + Obstacle Avoidance in CARLA',
      title_zh: 'CARLA中的车道保持+避障系统',
      difficulty: 'advanced',
      time_hours: 60,
      deliverables: [
        'CARLA-based simulation with camera and LiDAR sensor fusion',
        'Lane detection using computer vision (OpenCV)',
        'Simple path planner with obstacle avoidance',
        'Performance metrics: lane departure rate, collision rate, average speed',
      ],
      deliverables_zh: [
        '基于CARLA的摄像头和LiDAR传感器融合仿真',
        '使用计算机视觉（OpenCV）的车道检测',
        '具有避障功能的简单路径规划器',
        '性能指标：车道偏离率、碰撞率、平均速度',
      ],
      proves_to_employer: 'Demonstrates perception + planning pipeline in a realistic simulator — the exact workflow used at AD companies like Waymo, Mobileye, and Momenta.',
      proves_to_employer_zh: '在真实仿真器中展示感知+规划管线——Waymo、Mobileye和Momenta等自动驾驶公司的核心工作流。',
    },
    monetization_potential: 'affiliate',
  },

  // 6. Battery/BMS
  {
    id: 'auto-battery-bms',
    skill: 'Battery Management System (BMS)',
    skill_zh: '电池管理系统（BMS）',
    industry: 'automotive',
    industry_context: 'BMS is the brain of every EV battery pack — managing cell balancing, SOC estimation, thermal control, and safety. Demand has exploded with EV adoption.',
    industry_context_zh: 'BMS是每个电动汽车电池包的大脑——管理电芯均衡、SOC估算、热管理和安全。随着电动汽车普及，需求爆发式增长。',
    tools: [
      {
        name: 'MATLAB Simscape Battery',
        name_zh: 'MATLAB Simscape电池仿真',
        vendor: 'MathWorks',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.mathworks.com/products/simscape-battery.html',
      },
      {
        name: 'BatPaC (Battery Performance and Cost)',
        name_zh: 'BatPaC电池性能与成本工具',
        vendor: 'Argonne National Laboratory',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free government-funded tool for battery pack design and cost estimation',
        url: 'https://www.anl.gov/cse/batpac-model-software',
      },
      {
        name: 'COMSOL Multiphysics (Battery Module)',
        name_zh: 'COMSOL多物理场电池模块',
        vendor: 'COMSOL',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.comsol.com/battery-design-module',
      },
    ],
    training: [
      {
        name: 'Coursera — Battery Management Systems Specialization (CU Boulder)',
        name_zh: 'Coursera — 电池管理系统专项课程（科罗拉多大学）',
        region: 'global',
        url: 'https://www.coursera.org/specializations/battery-management-systems',
        price_range: '$0–$49/month',
        format: 'online',
        certification: 'Coursera Certificate',
        language: ['en'],
      },
      {
        name: 'RWTH Aachen — Battery Engineering (MOOC)',
        name_zh: 'RWTH亚琛工大 — 电池工程MOOC',
        region: 'DE',
        url: 'https://www.academy.rwth-aachen.de/',
        price_range: '€0–€500',
        format: 'online',
        language: ['en', 'de'],
      },
      {
        name: 'MathWorks — Battery Modeling and BMS Design',
        name_zh: 'MathWorks — 电池建模与BMS设计',
        region: 'global',
        url: 'https://www.mathworks.com/solutions/electrification/battery-management-system.html',
        price_range: 'Free (tutorials) / $500+ (training)',
        format: 'online',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'pybamm-team/PyBaMM',
        repo_url: 'https://github.com/pybamm-team/PyBaMM',
        stars: '1000+',
        what_to_learn: 'Learn battery physics modeling with Python — equivalent circuit, single particle, and DFN models',
        what_to_learn_zh: '用Python学习电池物理建模——等效电路、单颗粒和DFN模型',
        estimated_hours: 25,
      },
      {
        order: 2,
        repo_name: 'foxBMS/foxbms-2',
        repo_url: 'https://github.com/foxBMS/foxbms-2',
        stars: '200+',
        what_to_learn: 'Study a production-grade open-source BMS implementation: cell monitoring, SOC, balancing',
        what_to_learn_zh: '学习生产级开源BMS实现：电芯监控、SOC估算、均衡',
        estimated_hours: 30,
      },
      {
        order: 3,
        repo_name: 'TUMFTM/TUM-battery-model',
        repo_url: 'https://github.com/TUMFTM/sim_battery_system',
        stars: '100+',
        what_to_learn: 'Explore TU Munich battery simulation models for thermal and electrical analysis',
        what_to_learn_zh: '探索慕尼黑工大电池仿真模型的热电分析',
        estimated_hours: 20,
      },
    ],
    capstone: {
      title: 'SOC Estimator with Extended Kalman Filter',
      title_zh: '扩展卡尔曼滤波器SOC估算器',
      difficulty: 'intermediate',
      time_hours: 40,
      deliverables: [
        'Equivalent circuit model (ECM) for a Li-ion cell in Python/MATLAB',
        'Extended Kalman Filter (EKF) for real-time SOC estimation',
        'Validation against experimental data (public datasets)',
        'Error analysis: RMSE < 3% under drive cycle conditions',
      ],
      deliverables_zh: [
        'Python/MATLAB中的锂离子电芯等效电路模型（ECM）',
        '用于实时SOC估算的扩展卡尔曼滤波器（EKF）',
        '基于实验数据的验证（使用公开数据集）',
        '误差分析：驾驶工况下RMSE < 3%',
      ],
      proves_to_employer: 'SOC estimation via EKF is the most-asked BMS interview question. This project proves you can implement it from scratch with real data.',
      proves_to_employer_zh: '基于EKF的SOC估算是BMS面试中最常被问到的问题。该项目证明你能用真实数据从零实现。',
    },
    monetization_potential: 'affiliate',
  },

  // 7. IATF 16949/VDA 6.3
  {
    id: 'auto-iatf-vda',
    skill: 'IATF 16949 / VDA 6.3',
    skill_zh: 'IATF 16949 / VDA 6.3质量管理',
    industry: 'automotive',
    industry_context: 'IATF 16949 is the global quality management standard for automotive suppliers. VDA 6.3 is the German process audit standard used by all German OEMs (VW, BMW, Mercedes).',
    industry_context_zh: 'IATF 16949是汽车供应商的全球质量管理标准。VDA 6.3是所有德国主机厂（大众、宝马、奔驰）使用的过程审核标准。',
    tools: [
      {
        name: 'VDA 6.3 Audit Software (Red Point)',
        name_zh: 'VDA 6.3审核软件（红点评级）',
        vendor: 'VDA QMC',
        tier: 'essential',
        free_tier: false,
        url: 'https://vda-qmc.de/en/software/',
      },
      {
        name: 'SAP QM (Quality Management)',
        name_zh: 'SAP QM质量管理模块',
        vendor: 'SAP',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.sap.com/products/scm/quality-management.html',
        alternatives: ['IQS', 'QAD QMS'],
      },
      {
        name: 'Minitab',
        name_zh: 'Minitab统计分析工具',
        vendor: 'Minitab',
        tier: 'recommended',
        free_tier: false,
        free_tier_note: '30-day free trial available',
        url: 'https://www.minitab.com/',
        alternatives: ['JMP', 'R (free)'],
      },
    ],
    training: [
      {
        name: 'VDA QMC — VDA 6.3 Process Auditor',
        name_zh: 'VDA QMC — VDA 6.3过程审核员认证',
        region: 'DE',
        url: 'https://vda-qmc.de/en/training/',
        price_range: '€1,500–€3,000',
        format: 'hybrid',
        certification: 'VDA 6.3 Certified Process Auditor',
        language: ['de', 'en'],
      },
      {
        name: 'TÜV SÜD — IATF 16949 Internal Auditor',
        name_zh: 'TÜV SÜD — IATF 16949内审员',
        region: 'global',
        url: 'https://www.tuvsud.com/en/themes/quality-management/iatf-16949',
        price_range: '€800–€2,000',
        format: 'hybrid',
        certification: 'IATF 16949 Internal Auditor',
        language: ['en', 'de', 'zh'],
      },
      {
        name: 'AIAG — Core Tools Training (APQP, PPAP, FMEA, MSA, SPC)',
        name_zh: 'AIAG — 核心工具培训',
        region: 'global',
        url: 'https://www.aiag.org/quality/automotive-core-tools',
        price_range: '$200–$1,500',
        format: 'hybrid',
        certification: 'AIAG Certificate',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'jmportilla/Python-for-Data-Science-and-Machine-Learning-Bootcamp',
        repo_url: 'https://github.com/jmportilla/Python-for-Data-Science-and-Machine-Learning-Bootcamp',
        stars: '700+',
        what_to_learn: 'Build data analysis skills in Python — essential for SPC, capability studies, and quality data',
        what_to_learn_zh: '建立Python数据分析能力——对SPC、过程能力研究和质量数据分析至关重要',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'gedeck/practical-statistics-for-data-scientists',
        repo_url: 'https://github.com/gedeck/practical-statistics-for-data-scientists',
        stars: '2000+',
        what_to_learn: 'Learn applied statistics: hypothesis testing, ANOVA, regression — core quality engineering math',
        what_to_learn_zh: '学习应用统计学：假设检验、方差分析、回归——质量工程核心数学',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'paulgp/applied-methods-phd',
        repo_url: 'https://github.com/paulgp/applied-methods-phd',
        stars: '600+',
        what_to_learn: 'Deepen statistical methods knowledge for advanced quality analysis and DOE',
        what_to_learn_zh: '深化统计方法知识，用于高级质量分析和DOE实验设计',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'VDA 6.3 Mock Audit Report for an Injection Molding Process',
      title_zh: 'VDA 6.3注塑工艺模拟审核报告',
      difficulty: 'intermediate',
      time_hours: 30,
      deliverables: [
        'Complete VDA 6.3 audit questionnaire (P2–P7 elements)',
        'Red/Yellow/Green scoring with evidence notes',
        'Corrective action recommendations with 8D format',
        'SPC analysis of key quality characteristics (Cpk calculations)',
      ],
      deliverables_zh: [
        '完整的VDA 6.3审核问卷（P2-P7要素）',
        '红/黄/绿评分及证据记录',
        '8D格式的纠正措施建议',
        '关键质量特性的SPC分析（Cpk计算）',
      ],
      proves_to_employer: 'Shows you can conduct a VDA 6.3 process audit independently — the exact deliverable German OEMs require from their SQE teams.',
      proves_to_employer_zh: '展示你能独立进行VDA 6.3过程审核——正是德国主机厂要求其SQE团队的核心交付物。',
    },
    monetization_potential: 'affiliate',
  },

  // 8. Vehicle Testing/Homologation
  {
    id: 'auto-vehicle-testing',
    skill: 'Vehicle Testing / HIL Simulation',
    skill_zh: '整车测试 / HIL仿真',
    industry: 'automotive',
    industry_context: 'Hardware-in-the-loop (HIL) testing is mandatory before any ECU goes to production. Test engineers who can build and maintain HIL rigs are critical at every OEM.',
    industry_context_zh: '硬件在环（HIL）测试是任何ECU投产前的必须步骤。能搭建和维护HIL测试台架的测试工程师在每家主机厂都是关键角色。',
    tools: [
      {
        name: 'dSPACE SCALEXIO',
        name_zh: 'dSPACE SCALEXIO HIL系统',
        vendor: 'dSPACE',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.dspace.com/en/pub/home/products/hw/simulator_hardware/scalexio.cfm',
      },
      {
        name: 'NI TestStand',
        name_zh: 'NI TestStand测试管理软件',
        vendor: 'National Instruments',
        tier: 'essential',
        free_tier: false,
        free_tier_note: 'Community edition available for evaluation',
        url: 'https://www.ni.com/en/shop/electronic-test-instrumentation/application-software-for-electronic-test-and-instrumentation-category/teststand.html',
      },
      {
        name: 'AVL CRUISE',
        name_zh: 'AVL CRUISE车辆仿真',
        vendor: 'AVL',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.avl.com/en/simulation-solutions',
      },
    ],
    training: [
      {
        name: 'dSPACE Academy',
        name_zh: 'dSPACE学院',
        region: 'global',
        url: 'https://www.dspace.com/en/pub/home/support/trainingprg.cfm',
        price_range: '€1,000–€3,000',
        format: 'hybrid',
        certification: 'dSPACE Certificate',
        language: ['en', 'de'],
      },
      {
        name: 'NI Learning — TestStand & LabVIEW',
        name_zh: 'NI学习中心 — TestStand和LabVIEW',
        region: 'global',
        url: 'https://learn.ni.com/',
        price_range: '$0–$2,000',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'Coursera — Introduction to Test and Measurement',
        name_zh: 'Coursera — 测试与测量入门',
        region: 'global',
        url: 'https://www.coursera.org/learn/sensors-circuit-interface',
        price_range: '$0–$49/month',
        format: 'online',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'openMCx/openMCx',
        repo_url: 'https://github.com/CATIA-Systems/FMPy',
        stars: '400+',
        what_to_learn: 'Learn FMI/FMU standard for co-simulation — the interoperability standard for HIL environments',
        what_to_learn_zh: '学习FMI/FMU联合仿真标准——HIL环境的互操作性标准',
        estimated_hours: 15,
      },
      {
        order: 2,
        repo_name: 'robotframework/robotframework',
        repo_url: 'https://github.com/robotframework/robotframework',
        stars: '9000+',
        what_to_learn: 'Master test automation framework — widely used for automotive test case management and execution',
        what_to_learn_zh: '掌握测试自动化框架——在汽车测试用例管理和执行中广泛使用',
        estimated_hours: 20,
      },
      {
        order: 3,
        repo_name: 'eclipse/sumo',
        repo_url: 'https://github.com/eclipse-sumo/sumo',
        stars: '2500+',
        what_to_learn: 'Use SUMO traffic simulation to create test scenarios for vehicle validation',
        what_to_learn_zh: '使用SUMO交通仿真创建车辆验证的测试场景',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'Automated ECU Test Suite with Python + Robot Framework',
      title_zh: 'Python + Robot Framework自动化ECU测试套件',
      difficulty: 'intermediate',
      time_hours: 35,
      deliverables: [
        'Robot Framework test suite for a simulated ECU (CAN-based)',
        'Python test library for CAN frame injection and validation',
        'Test report generation (HTML/PDF) with pass/fail summary',
        'CI/CD integration for automated test runs',
      ],
      deliverables_zh: [
        '针对模拟ECU的Robot Framework测试套件（基于CAN）',
        '用于CAN帧注入和验证的Python测试库',
        '测试报告生成（HTML/PDF），含通过/失败摘要',
        'CI/CD集成实现自动化测试运行',
      ],
      proves_to_employer: 'Shows test automation skills with automotive protocols — directly applicable to HIL/SIL validation roles at OEMs and test equipment companies.',
      proves_to_employer_zh: '展示汽车协议的测试自动化能力——直接适用于主机厂和测试设备公司的HIL/SIL验证岗位。',
    },
    monetization_potential: 'affiliate',
  },

  // 9. EV Powertrain
  {
    id: 'auto-ev-powertrain',
    skill: 'EV Powertrain Design',
    skill_zh: '电动汽车动力总成设计',
    industry: 'automotive',
    industry_context: 'EV powertrain (motor, inverter, transmission) design is the most sought-after skill in automotive as the industry transitions from ICE. Demand exceeds supply globally.',
    industry_context_zh: '电动汽车动力总成（电机、逆变器、变速箱）设计是汽车行业从内燃机转型中最热门的技能。全球需求远超供给。',
    tools: [
      {
        name: 'ANSYS Motor-CAD',
        name_zh: 'ANSYS Motor-CAD电机设计',
        vendor: 'Ansys',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.ansys.com/products/electronics/ansys-motor-cad',
      },
      {
        name: 'JMAG',
        name_zh: 'JMAG电磁场仿真',
        vendor: 'JSOL Corporation',
        tier: 'essential',
        free_tier: false,
        free_tier_note: 'Free student version available',
        url: 'https://www.jmag-international.com/',
      },
      {
        name: 'MATLAB Simscape Electrical',
        name_zh: 'MATLAB Simscape电气仿真',
        vendor: 'MathWorks',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.mathworks.com/products/simscape-electrical.html',
      },
    ],
    training: [
      {
        name: 'Coursera — Electric Vehicles and Mobility (by UMich)',
        name_zh: 'Coursera — 电动汽车与出行（密歇根大学）',
        region: 'global',
        url: 'https://www.coursera.org/learn/electric-vehicles',
        price_range: '$0–$49/month',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'edX — Electric Cars: Technology (TU Delft)',
        name_zh: 'edX — 电动汽车技术（代尔夫特理工大学）',
        region: 'global',
        url: 'https://www.edx.org/learn/electric-vehicles/delft-university-of-technology-electric-cars-technology',
        price_range: '$0–$150',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'RWTH Aachen — E-Motor Design Seminar',
        name_zh: 'RWTH亚琛工大 — 电机设计研讨会',
        region: 'DE',
        url: 'https://www.academy.rwth-aachen.de/',
        price_range: '€500–€2,000',
        format: 'hybrid',
        language: ['en', 'de'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'TUMFTM/EV-Simulation',
        repo_url: 'https://github.com/TUMFTM/sim_vehicle_dynamics',
        stars: '300+',
        what_to_learn: 'Study TU Munich EV vehicle dynamics simulation — motor, battery, and drivetrain models',
        what_to_learn_zh: '学习慕尼黑工大电动汽车动力学仿真——电机、电池和传动系统模型',
        estimated_hours: 25,
      },
      {
        order: 2,
        repo_name: 'pyleecan-project/pyleecan',
        repo_url: 'https://github.com/Eomys/pyleecan',
        stars: '200+',
        what_to_learn: 'Design and simulate electric machines in Python — open-source alternative to Motor-CAD',
        what_to_learn_zh: '用Python设计和仿真电机——Motor-CAD的开源替代方案',
        estimated_hours: 30,
      },
      {
        order: 3,
        repo_name: 'SciML/ModelingToolkit.jl',
        repo_url: 'https://github.com/SciML/ModelingToolkit.jl',
        stars: '1400+',
        what_to_learn: 'Build multi-physics system models for powertrain simulation using Julia',
        what_to_learn_zh: '使用Julia构建动力总成仿真的多物理场系统模型',
        estimated_hours: 20,
      },
    ],
    capstone: {
      title: 'PMSM Motor Efficiency Map and Drive Cycle Simulation',
      title_zh: '永磁同步电机效率MAP图和驾驶工况仿真',
      difficulty: 'advanced',
      time_hours: 50,
      deliverables: [
        'PMSM motor model with efficiency map generation (torque vs speed)',
        'WLTP/NEDC drive cycle simulation with energy consumption calculation',
        'Inverter loss model (switching + conduction losses)',
        'Comparison report: different motor topologies (IPM vs SPM)',
      ],
      deliverables_zh: [
        '永磁同步电机模型与效率MAP图生成（转矩-转速）',
        'WLTP/NEDC驾驶工况仿真与能耗计算',
        '逆变器损耗模型（开关损耗+导通损耗）',
        '对比报告：不同电机拓扑（IPM vs SPM）',
      ],
      proves_to_employer: 'Shows end-to-end EV powertrain analysis skills — motor design, efficiency optimization, and system-level simulation. Directly applicable at any EV OEM or Tier-1.',
      proves_to_employer_zh: '展示端到端电动汽车动力总成分析能力——电机设计、效率优化和系统级仿真。直接适用于任何电动汽车主机厂或Tier-1。',
    },
    monetization_potential: 'affiliate',
  },

  // 10. Supplier Quality (SQE)
  {
    id: 'auto-sqe',
    skill: 'Supplier Quality Engineering (SQE)',
    skill_zh: '供应商质量工程（SQE）',
    industry: 'automotive',
    industry_context: 'SQE is the bridge between OEM quality requirements and supplier capability. Every automotive OEM and Tier-1 has dedicated SQE teams managing hundreds of suppliers.',
    industry_context_zh: 'SQE是主机厂质量要求与供应商能力之间的桥梁。每家汽车主机厂和Tier-1都有专门的SQE团队管理数百家供应商。',
    tools: [
      {
        name: 'SAP QM (Quality Management)',
        name_zh: 'SAP QM质量管理模块',
        vendor: 'SAP',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.sap.com/products/scm/quality-management.html',
      },
      {
        name: 'AIAG Core Tools Templates (PPAP, FMEA, CP)',
        name_zh: 'AIAG核心工具模板（PPAP、FMEA、控制计划）',
        vendor: 'AIAG',
        tier: 'essential',
        free_tier: false,
        free_tier_note: 'Standards documents ~$50–$200; templates widely available',
        url: 'https://www.aiag.org/quality/automotive-core-tools',
      },
      {
        name: 'Minitab (for SPC/MSA)',
        name_zh: 'Minitab（用于SPC/MSA）',
        vendor: 'Minitab',
        tier: 'recommended',
        free_tier: false,
        free_tier_note: '30-day free trial',
        url: 'https://www.minitab.com/',
        alternatives: ['JMP', 'Python scipy/statsmodels (free)'],
      },
    ],
    training: [
      {
        name: 'AIAG — Core Tools Workshop',
        name_zh: 'AIAG — 核心工具研讨会',
        region: 'global',
        url: 'https://www.aiag.org/quality/automotive-core-tools',
        price_range: '$200–$1,500',
        format: 'hybrid',
        certification: 'AIAG Core Tools Certificate',
        language: ['en'],
      },
      {
        name: 'VDA QMC — Supplier Quality Management',
        name_zh: 'VDA QMC — 供应商质量管理',
        region: 'DE',
        url: 'https://vda-qmc.de/en/training/',
        price_range: '€1,000–€2,500',
        format: 'hybrid',
        certification: 'VDA Certified',
        language: ['de', 'en'],
      },
      {
        name: 'ASQ — Certified Quality Engineer (CQE)',
        name_zh: 'ASQ — 注册质量工程师',
        region: 'global',
        url: 'https://asq.org/cert/quality-engineer',
        price_range: '$200–$600',
        format: 'online',
        certification: 'ASQ CQE',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'lutzroeder/netron',
        repo_url: 'https://github.com/lutzroeder/netron',
        stars: '27000+',
        what_to_learn: 'Understand data visualization for quality metrics — applicable to building SQE dashboards',
        what_to_learn_zh: '理解质量指标的数据可视化——可应用于构建SQE仪表盘',
        estimated_hours: 10,
      },
      {
        order: 2,
        repo_name: 'streamlit/streamlit',
        repo_url: 'https://github.com/streamlit/streamlit',
        stars: '35000+',
        what_to_learn: 'Build rapid quality dashboards and 8D report tools using Python + Streamlit',
        what_to_learn_zh: '使用Python + Streamlit快速构建质量仪表盘和8D报告工具',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'pandas-dev/pandas',
        repo_url: 'https://github.com/pandas-dev/pandas',
        stars: '43000+',
        what_to_learn: 'Master data analysis with pandas — essential for warranty data, PPM tracking, and supplier scoring',
        what_to_learn_zh: '掌握pandas数据分析——对保修数据、PPM跟踪和供应商评分至关重要',
        estimated_hours: 20,
      },
    ],
    capstone: {
      title: 'Supplier Scorecard Dashboard with 8D Report Generator',
      title_zh: '供应商评分卡仪表盘与8D报告生成器',
      difficulty: 'intermediate',
      time_hours: 35,
      deliverables: [
        'Python/Streamlit dashboard showing supplier PPM, delivery, and audit scores',
        'Automated 8D report template generator',
        'SPC charts (X-bar/R) for incoming inspection data',
        'Supplier ranking algorithm based on quality, cost, and delivery metrics',
      ],
      deliverables_zh: [
        'Python/Streamlit仪表盘显示供应商PPM、交付和审核评分',
        '自动化8D报告模板生成器',
        '来料检验数据的SPC控制图（X-bar/R图）',
        '基于质量、成本和交付指标的供应商排名算法',
      ],
      proves_to_employer: 'Demonstrates data-driven supplier management — the modern SQE skillset that OEMs are increasingly requiring beyond traditional audit skills.',
      proves_to_employer_zh: '展示数据驱动的供应商管理能力——这是主机厂在传统审核技能之外越来越要求的现代SQE技能。',
    },
    monetization_potential: 'none',
  },
];
