import type { IndustryToolMapEntry } from './types';

export const commonEntries: IndustryToolMapEntry[] = [
  // ─── 1. Lean Manufacturing ───
  {
    id: 'common-lean',
    skill: 'Lean Manufacturing',
    skill_zh: '精益生产',
    industry: 'common',
    industry_context: 'Foundational methodology for eliminating waste across all manufacturing sectors',
    industry_context_zh: '所有制造业消除浪费的基础方法论，适用于汽车、电子、医疗器械等行业',
    tools: [
      {
        name: 'eVSM',
        name_zh: 'eVSM价值流图软件',
        vendor: 'eVSM International',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.evsm.com/',
        alternatives: ['Lucidchart', 'Miro'],
      },
      {
        name: 'Minitab',
        name_zh: 'Minitab统计软件',
        vendor: 'Minitab LLC',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: '30-day free trial',
        url: 'https://www.minitab.com/',
        alternatives: ['R', 'Python scipy'],
      },
      {
        name: 'LeanKit (Planview AgilePlace)',
        name_zh: 'LeanKit看板工具',
        vendor: 'Planview',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free plan for small teams',
        url: 'https://www.planview.com/products-solutions/products/agileplace/',
      },
    ],
    training: [
      {
        name: 'Lean Enterprise Institute',
        name_zh: '精益企业研究院',
        region: 'global',
        url: 'https://www.lean.org/',
        price_range: '$200-$2,500',
        format: 'hybrid',
        certification: 'LEI Lean Certification',
        language: ['en'],
      },
      {
        name: 'TPS Academy China',
        name_zh: 'TPS精益学堂（中国）',
        region: 'CN',
        url: 'https://www.lean.org.cn/',
        price_range: '¥2,000-¥15,000',
        format: 'hybrid',
        certification: '精益生产工程师认证',
        language: ['zh'],
      },
      {
        name: 'TÜV SÜD Lean Training',
        name_zh: 'TÜV南德精益培训',
        region: 'DE',
        url: 'https://www.tuvsud.com/en/services/training',
        price_range: '€1,500-€3,500',
        format: 'hybrid',
        certification: 'TÜV Lean Management Certificate',
        language: ['de', 'en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'lean-manufacturing',
        repo_url: 'https://github.com/leankitkanban/LeanKitKanban',
        stars: '100+',
        what_to_learn: 'Understand Kanban board concepts and pull-based production systems',
        what_to_learn_zh: '理解看板概念和拉动式生产系统',
        estimated_hours: 8,
      },
      {
        order: 2,
        repo_name: 'awesome-lean-manufacturing',
        repo_url: 'https://github.com/cirosantilli/lean-manufacturing',
        stars: '100+',
        what_to_learn: 'Survey of lean manufacturing tools, templates, and case studies',
        what_to_learn_zh: '精益制造工具、模板和案例研究概览',
        estimated_hours: 10,
      },
    ],
    capstone: {
      title: 'Value Stream Map & Kaizen Plan for a Production Line',
      title_zh: '某生产线价值流图绘制与改善计划',
      difficulty: 'intermediate',
      time_hours: 40,
      deliverables: [
        'Current-state VSM with takt time calculations',
        'Future-state VSM with improvement targets',
        'A3 problem-solving report for top 3 wastes',
        'Implementation roadmap (90-day Kaizen plan)',
      ],
      deliverables_zh: [
        '含节拍时间计算的现状价值流图',
        '含改善目标的未来状态价值流图',
        '前3大浪费的A3问题解决报告',
        '实施路线图（90天改善计划）',
      ],
      proves_to_employer: 'Can identify waste, design future-state processes, and create actionable improvement plans',
      proves_to_employer_zh: '能识别浪费、设计未来状态流程并制定可执行的改善计划',
    },
    monetization_potential: 'affiliate',
  },

  // ─── 2. Six Sigma ───
  {
    id: 'common-six-sigma',
    skill: 'Six Sigma',
    skill_zh: '六西格玛',
    industry: 'common',
    industry_context: 'Data-driven quality methodology used across automotive, aerospace, electronics, and medical devices',
    industry_context_zh: '数据驱动的质量方法论，广泛应用于汽车、航空航天、电子和医疗器械行业',
    tools: [
      {
        name: 'Minitab',
        name_zh: 'Minitab统计软件',
        vendor: 'Minitab LLC',
        tier: 'essential',
        free_tier: true,
        free_tier_note: '30-day free trial',
        url: 'https://www.minitab.com/',
        alternatives: ['R', 'Python statsmodels'],
      },
      {
        name: 'JMP',
        name_zh: 'JMP统计发现软件',
        vendor: 'SAS Institute',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: '30-day free trial; academic licenses available',
        url: 'https://www.jmp.com/',
        alternatives: ['Minitab', 'R'],
      },
      {
        name: 'SigmaXL',
        name_zh: 'SigmaXL',
        vendor: 'SigmaXL Inc.',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: '30-day free trial',
        url: 'https://www.sigmaxl.com/',
      },
    ],
    training: [
      {
        name: 'ASQ Six Sigma Certification',
        name_zh: 'ASQ六西格玛认证',
        region: 'global',
        url: 'https://asq.org/cert/six-sigma-green-belt',
        price_range: '$438-$2,500',
        format: 'hybrid',
        certification: 'ASQ Certified Six Sigma Green Belt / Black Belt',
        language: ['en'],
      },
      {
        name: 'TÜV SÜD Six Sigma',
        name_zh: 'TÜV南德六西格玛',
        region: 'DE',
        url: 'https://www.tuvsud.com/en/services/training',
        price_range: '€2,000-€5,000',
        format: 'hybrid',
        certification: 'TÜV Six Sigma Green Belt / Black Belt',
        language: ['de', 'en'],
      },
      {
        name: '优思学院 (UCOURSE)',
        name_zh: '优思学院',
        region: 'CN',
        url: 'https://www.ucourse.org/',
        price_range: '¥2,000-¥12,000',
        format: 'online',
        certification: '六西格玛绿带/黑带认证',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'scipy',
        repo_url: 'https://github.com/scipy/scipy',
        stars: '13k+',
        what_to_learn: 'Statistical functions for hypothesis testing, ANOVA, regression — core Six Sigma tools',
        what_to_learn_zh: '假设检验、方差分析、回归分析等统计功能——六西格玛核心工具',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'statsmodels',
        repo_url: 'https://github.com/statsmodels/statsmodels',
        stars: '10k+',
        what_to_learn: 'DOE, regression analysis, and statistical modeling for DMAIC projects',
        what_to_learn_zh: '实验设计、回归分析和统计建模，用于DMAIC项目',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'DMAIC Project: Reduce Defect Rate by 50%',
      title_zh: 'DMAIC项目：将缺陷率降低50%',
      difficulty: 'advanced',
      time_hours: 60,
      deliverables: [
        'Project charter with CTQ tree',
        'Measurement system analysis (Gage R&R)',
        'Process capability analysis (Cp/Cpk)',
        'Root cause analysis with DOE results',
        'Control plan with SPC charts',
      ],
      deliverables_zh: [
        '含CTQ树的项目章程',
        '测量系统分析（Gage R&R）',
        '过程能力分析（Cp/Cpk）',
        '含DOE结果的根因分析',
        '含SPC控制图的控制计划',
      ],
      proves_to_employer: 'Can lead a full DMAIC cycle with statistical rigor and deliver measurable quality improvements',
      proves_to_employer_zh: '能主导完整DMAIC循环，具备统计严谨性并交付可量化的质量改善成果',
    },
    monetization_potential: 'affiliate',
  },

  // ─── 3. SolidWorks ───
  {
    id: 'common-solidworks',
    skill: 'SolidWorks',
    skill_zh: 'SolidWorks三维建模',
    industry: 'common',
    industry_context: 'Industry-standard 3D CAD for mechanical design in automotive, consumer products, and industrial equipment',
    industry_context_zh: '机械设计行业标准3D CAD软件，广泛用于汽车、消费品和工业设备设计',
    tools: [
      {
        name: 'SolidWorks',
        name_zh: 'SolidWorks',
        vendor: 'Dassault Systèmes',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free for students via SolidWorks Student Edition (SEK); makers can use 3DEXPERIENCE for free',
        url: 'https://www.solidworks.com/',
        alternatives: ['Fusion 360', 'FreeCAD', 'Onshape'],
      },
      {
        name: 'FreeCAD',
        name_zh: 'FreeCAD开源CAD',
        vendor: 'FreeCAD Community',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Fully open-source and free',
        url: 'https://www.freecad.org/',
      },
      {
        name: 'Onshape',
        name_zh: 'Onshape云端CAD',
        vendor: 'PTC',
        tier: 'emerging',
        free_tier: true,
        free_tier_note: 'Free plan for public projects and education',
        url: 'https://www.onshape.com/',
      },
    ],
    training: [
      {
        name: 'MySolidWorks Training',
        name_zh: 'MySolidWorks官方培训',
        region: 'global',
        url: 'https://my.solidworks.com/training',
        price_range: 'Free - $5,000',
        format: 'online',
        certification: 'CSWA / CSWP (Certified SolidWorks Associate / Professional)',
        language: ['en'],
      },
      {
        name: '我要自学网 (51zxw)',
        name_zh: '我要自学网',
        region: 'CN',
        url: 'https://www.51zxw.net/',
        price_range: '¥0-¥299',
        format: 'online',
        language: ['zh'],
      },
      {
        name: 'Udemy SolidWorks Courses',
        name_zh: 'Udemy SolidWorks课程',
        region: 'global',
        url: 'https://www.udemy.com/topic/solidworks/',
        price_range: '$12-$100',
        format: 'online',
        language: ['en', 'zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'FreeCAD',
        repo_url: 'https://github.com/FreeCAD/FreeCAD',
        stars: '20k+',
        what_to_learn: 'Understand parametric 3D modeling internals; practice part design and assembly',
        what_to_learn_zh: '理解参数化3D建模内部原理；练习零件设计和装配',
        estimated_hours: 30,
      },
      {
        order: 2,
        repo_name: 'swig-solidworks',
        repo_url: 'https://github.com/SolidCode/SolidPython',
        stars: '900+',
        what_to_learn: 'Learn programmatic 3D model generation with Python — bridges coding and CAD',
        what_to_learn_zh: '学习用Python程序化生成3D模型——连接编程与CAD',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'Design a Multi-Part Assembly with Full Drawing Package',
      title_zh: '设计一套多零件装配体并输出完整工程图',
      difficulty: 'intermediate',
      time_hours: 50,
      deliverables: [
        'Multi-part assembly (10+ parts) with mates and motion',
        'Engineering drawings with GD&T annotations',
        'BOM (Bill of Materials) with part numbers',
        'DXF/STEP export for manufacturing',
      ],
      deliverables_zh: [
        '多零件装配体（10+零件），含配合和运动仿真',
        '含GD&T标注的工程图纸',
        '含零件号的物料清单（BOM）',
        'DXF/STEP格式制造输出文件',
      ],
      proves_to_employer: 'Can design production-ready assemblies, create manufacturing-grade drawings, and manage BOM',
      proves_to_employer_zh: '能设计量产级装配体、创建制造级图纸并管理物料清单',
    },
    monetization_potential: 'affiliate',
  },

  // ─── 4. ANSYS / FEA ───
  {
    id: 'common-ansys-fea',
    skill: 'ANSYS / FEA',
    skill_zh: 'ANSYS有限元分析',
    industry: 'common',
    industry_context: 'Finite Element Analysis for structural, thermal, and fluid simulation across all engineering sectors',
    industry_context_zh: '有限元分析用于各工程领域的结构、热力学和流体仿真',
    tools: [
      {
        name: 'ANSYS Mechanical / Fluent',
        name_zh: 'ANSYS Mechanical/Fluent',
        vendor: 'Ansys Inc.',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Ansys Student version free (limited mesh size)',
        url: 'https://www.ansys.com/',
        alternatives: ['CalculiX', 'OpenFOAM', 'Abaqus'],
      },
      {
        name: 'CalculiX',
        name_zh: 'CalculiX开源FEA',
        vendor: 'Open Source (MTU)',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Fully open-source and free (GPL)',
        url: 'http://www.calculix.de/',
      },
      {
        name: 'SimScale',
        name_zh: 'SimScale云端仿真',
        vendor: 'SimScale GmbH',
        tier: 'emerging',
        free_tier: true,
        free_tier_note: 'Free Community plan with 3,000 core hours',
        url: 'https://www.simscale.com/',
      },
    ],
    training: [
      {
        name: 'Ansys Learning Hub',
        name_zh: 'Ansys学习中心',
        region: 'global',
        url: 'https://www.ansys.com/academic/learning-resources',
        price_range: 'Free - $2,500/year',
        format: 'online',
        certification: 'Ansys Certified Professional',
        language: ['en'],
      },
      {
        name: 'Coursera FEA Courses (U Michigan)',
        name_zh: 'Coursera有限元课程',
        region: 'global',
        url: 'https://www.coursera.org/learn/finite-element-method',
        price_range: 'Free audit / $49/month',
        format: 'online',
        certification: 'Coursera Certificate',
        language: ['en'],
      },
      {
        name: '仿真秀 (fangzhenxiu)',
        name_zh: '仿真秀',
        region: 'CN',
        url: 'https://www.fangzhenxiu.com/',
        price_range: '¥0-¥2,000',
        format: 'online',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'calculix-examples',
        repo_url: 'https://github.com/calculix/examples',
        stars: '100+',
        what_to_learn: 'Run FEA simulations with open-source tools; understand meshing, boundary conditions, solvers',
        what_to_learn_zh: '用开源工具运行FEA仿真；理解网格划分、边界条件和求解器',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'OpenFOAM',
        repo_url: 'https://github.com/OpenFOAM/OpenFOAM-dev',
        stars: '1.5k+',
        what_to_learn: 'CFD fundamentals and practical fluid dynamics simulation',
        what_to_learn_zh: 'CFD基础和实际流体力学仿真',
        estimated_hours: 30,
      },
    ],
    capstone: {
      title: 'FEA Structural Analysis of a Mechanical Component Under Load',
      title_zh: '某机械零件受载有限元结构分析',
      difficulty: 'advanced',
      time_hours: 45,
      deliverables: [
        'CAD model imported into FEA environment',
        'Mesh convergence study',
        'Stress/strain results with safety factor analysis',
        'Comparison report: simulation vs analytical solution',
      ],
      deliverables_zh: [
        'CAD模型导入FEA环境',
        '网格收敛性研究',
        '含安全系数分析的应力/应变结果',
        '仿真与解析解对比报告',
      ],
      proves_to_employer: 'Can set up, validate, and interpret FEA simulations for engineering decisions',
      proves_to_employer_zh: '能设置、验证和解读FEA仿真结果以支持工程决策',
    },
    monetization_potential: 'affiliate',
  },

  // ─── 5. SAP PP/PM ───
  {
    id: 'common-sap-pp-pm',
    skill: 'SAP PP/PM',
    skill_zh: 'SAP生产计划/工厂维护',
    industry: 'common',
    industry_context: 'SAP Production Planning (PP) and Plant Maintenance (PM) modules used across discrete and process manufacturing',
    industry_context_zh: 'SAP生产计划(PP)和工厂维护(PM)模块，广泛用于离散和流程制造业',
    tools: [
      {
        name: 'SAP GUI',
        name_zh: 'SAP GUI客户端',
        vendor: 'SAP SE',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.sap.com/',
        alternatives: ['SAP Fiori'],
      },
      {
        name: 'SAP S/4HANA Trial',
        name_zh: 'SAP S/4HANA试用版',
        vendor: 'SAP SE',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'SAP Learning Hub trial system available; SAP BTP free tier',
        url: 'https://www.sap.com/products/erp/s4hana.html',
      },
    ],
    training: [
      {
        name: 'SAP Learning Hub',
        name_zh: 'SAP学习中心',
        region: 'global',
        url: 'https://learning.sap.com/',
        price_range: '€199-€599/year',
        format: 'online',
        certification: 'SAP Certified Associate — Manufacturing',
        language: ['en', 'de'],
      },
      {
        name: 'openSAP',
        name_zh: 'openSAP免费课程',
        region: 'global',
        url: 'https://open.sap.com/',
        price_range: 'Free',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'Udemy SAP PP Course',
        name_zh: 'Udemy SAP PP课程',
        region: 'global',
        url: 'https://www.udemy.com/topic/sap-pp/',
        price_range: '$12-$100',
        format: 'online',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'SAP-samples',
        repo_url: 'https://github.com/SAP-samples/abap-cheat-sheets',
        stars: '2k+',
        what_to_learn: 'ABAP programming fundamentals for SAP customization and reporting',
        what_to_learn_zh: 'ABAP编程基础，用于SAP定制和报表开发',
        estimated_hours: 25,
      },
      {
        order: 2,
        repo_name: 'SAP BTP tutorials',
        repo_url: 'https://github.com/SAP-samples/btp-setup-automator',
        stars: '500+',
        what_to_learn: 'SAP Business Technology Platform automation and extension development',
        what_to_learn_zh: 'SAP BTP平台自动化和扩展开发',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'Configure SAP PP End-to-End for a Production Scenario',
      title_zh: '配置SAP PP端到端生产场景',
      difficulty: 'advanced',
      time_hours: 60,
      deliverables: [
        'Master data setup (material, BOM, routing, work center)',
        'MRP run configuration and execution',
        'Production order creation, confirmation, goods receipt',
        'Custom ABAP report for production KPIs',
      ],
      deliverables_zh: [
        '主数据设置（物料、BOM、工艺路线、工作中心）',
        'MRP运行配置和执行',
        '生产订单创建、确认、收货',
        '自定义ABAP生产KPI报表',
      ],
      proves_to_employer: 'Can configure and operate SAP PP module end-to-end for discrete manufacturing',
      proves_to_employer_zh: '能为离散制造配置和操作SAP PP模块的端到端流程',
    },
    monetization_potential: 'affiliate',
  },

  // ─── 6. ISO 9001 ───
  {
    id: 'common-iso-9001',
    skill: 'ISO 9001 Quality Management',
    skill_zh: 'ISO 9001质量管理体系',
    industry: 'common',
    industry_context: 'Quality management system standard required by virtually all manufacturing companies worldwide',
    industry_context_zh: '全球几乎所有制造企业都要求的质量管理体系标准',
    tools: [
      {
        name: 'Qualio',
        name_zh: 'Qualio质量管理软件',
        vendor: 'Qualio',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.qualio.com/',
        alternatives: ['MasterControl', 'Greenlight Guru'],
      },
      {
        name: 'iAuditor (SafetyCulture)',
        name_zh: 'iAuditor审核工具',
        vendor: 'SafetyCulture',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free plan for small teams',
        url: 'https://safetyculture.com/iauditor/',
        alternatives: ['Nimonik', 'Qualityze'],
      },
      {
        name: 'Process Street',
        name_zh: 'Process Street流程管理',
        vendor: 'Process Street',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free plan available',
        url: 'https://www.process.st/',
      },
    ],
    training: [
      {
        name: 'BSI Training',
        name_zh: 'BSI培训',
        region: 'global',
        url: 'https://www.bsigroup.com/en-GB/our-services/training-courses/',
        price_range: '£500-£2,000',
        format: 'hybrid',
        certification: 'BSI ISO 9001 Lead Auditor',
        language: ['en'],
      },
      {
        name: 'TÜV SÜD QM Training',
        name_zh: 'TÜV南德质量管理培训',
        region: 'DE',
        url: 'https://www.tuvsud.com/en/services/training',
        price_range: '€1,200-€3,000',
        format: 'hybrid',
        certification: 'TÜV ISO 9001 Auditor',
        language: ['de', 'en'],
      },
      {
        name: 'SGS Academy',
        name_zh: 'SGS管理学院',
        region: 'CN',
        url: 'https://www.sgsgroup.com.cn/',
        price_range: '¥2,000-¥8,000',
        format: 'hybrid',
        certification: 'SGS认证内审员/外审员',
        language: ['zh', 'en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'quality-management-templates',
        repo_url: 'https://github.com/QualityManagement/quality-management',
        stars: '100+',
        what_to_learn: 'QMS documentation templates: quality manual, procedures, work instructions',
        what_to_learn_zh: 'QMS文件模板：质量手册、程序文件、作业指导书',
        estimated_hours: 10,
      },
      {
        order: 2,
        repo_name: 'awesome-quality-assurance',
        repo_url: 'https://github.com/mfaisalkhatri/awesome-quality-assurance',
        stars: '200+',
        what_to_learn: 'Quality assurance tools, processes, and best practices overview',
        what_to_learn_zh: '质量保证工具、流程和最佳实践概览',
        estimated_hours: 8,
      },
    ],
    capstone: {
      title: 'Build a Mini QMS Documentation Package for ISO 9001',
      title_zh: '构建ISO 9001迷你质量管理体系文件包',
      difficulty: 'intermediate',
      time_hours: 35,
      deliverables: [
        'Quality policy and objectives',
        'Process map (turtle diagrams)',
        'Internal audit checklist and report template',
        'Corrective action procedure (CAPA)',
        'Management review meeting template',
      ],
      deliverables_zh: [
        '质量方针和目标',
        '过程图（乌龟图）',
        '内审检查表和报告模板',
        '纠正措施程序（CAPA）',
        '管理评审会议模板',
      ],
      proves_to_employer: 'Can build and maintain ISO 9001-compliant documentation and conduct internal audits',
      proves_to_employer_zh: '能建立和维护符合ISO 9001的文件体系并进行内审',
    },
    monetization_potential: 'none',
  },

  // ─── 7. FMEA ───
  {
    id: 'common-fmea',
    skill: 'FMEA (Failure Mode and Effects Analysis)',
    skill_zh: 'FMEA失效模式与影响分析',
    industry: 'common',
    industry_context: 'Risk analysis methodology mandated in automotive (IATF 16949), aerospace (AS9100), and medical devices (ISO 13485)',
    industry_context_zh: '风险分析方法论，汽车(IATF 16949)、航空航天(AS9100)和医疗器械(ISO 13485)强制要求',
    tools: [
      {
        name: 'APIS IQ-FMEA',
        name_zh: 'APIS IQ-FMEA',
        vendor: 'APIS Informationstechnologien GmbH',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free demo version available',
        url: 'https://www.apis-iq.com/',
        alternatives: ['Relyence FMEA', 'Plexus FMEA-Pro'],
      },
      {
        name: 'Relyence FMEA',
        name_zh: 'Relyence FMEA',
        vendor: 'Relyence Corporation',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: '30-day free trial',
        url: 'https://www.relyence.com/products/fmea/',
      },
      {
        name: 'Excel FMEA Template',
        name_zh: 'Excel FMEA模板',
        vendor: 'Various / Open',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free templates widely available',
        url: 'https://www.aiag.org/',
      },
    ],
    training: [
      {
        name: 'AIAG FMEA Training',
        name_zh: 'AIAG FMEA培训',
        region: 'global',
        url: 'https://www.aiag.org/quality/automotive-core-tools/fmea',
        price_range: '$500-$1,500',
        format: 'hybrid',
        certification: 'AIAG FMEA Practitioner',
        language: ['en'],
      },
      {
        name: 'VDA QMC FMEA Training',
        name_zh: 'VDA质量管理中心FMEA培训',
        region: 'DE',
        url: 'https://vda-qmc.de/',
        price_range: '€800-€2,500',
        format: 'hybrid',
        certification: 'VDA FMEA Moderator',
        language: ['de', 'en'],
      },
      {
        name: '中国汽车技术研究中心 (CATARC)',
        name_zh: '中汽中心',
        region: 'CN',
        url: 'https://www.catarc.ac.cn/',
        price_range: '¥2,000-¥6,000',
        format: 'hybrid',
        certification: 'FMEA内部培训师资格',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'fmea-tools',
        repo_url: 'https://github.com/teddylee777/machine-learning',
        stars: '2k+',
        what_to_learn: 'Data analysis fundamentals for FMEA risk priority number (RPN) analysis and trending',
        what_to_learn_zh: '数据分析基础，用于FMEA风险优先数(RPN)分析和趋势跟踪',
        estimated_hours: 12,
      },
      {
        order: 2,
        repo_name: 'reliability',
        repo_url: 'https://github.com/MatthewReid854/reliability',
        stars: '900+',
        what_to_learn: 'Reliability engineering library — failure analysis, Weibull distributions, FMEA data processing',
        what_to_learn_zh: '可靠性工程库——失效分析、威布尔分布、FMEA数据处理',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'Complete DFMEA + PFMEA for a New Product Launch',
      title_zh: '新产品导入完整DFMEA+PFMEA',
      difficulty: 'advanced',
      time_hours: 50,
      deliverables: [
        'DFMEA with structure tree, function analysis, and failure analysis',
        'PFMEA linked to process flow diagram',
        'Action priority (AP) based risk evaluation (AIAG-VDA 2019 method)',
        'Optimization tracking sheet with before/after RPN',
      ],
      deliverables_zh: [
        '含结构树、功能分析和失效分析的DFMEA',
        '与过程流程图关联的PFMEA',
        '基于行动优先级(AP)的风险评估（AIAG-VDA 2019方法）',
        '含优化前后RPN的跟踪表',
      ],
      proves_to_employer: 'Can facilitate cross-functional FMEA sessions using the latest AIAG-VDA methodology',
      proves_to_employer_zh: '能运用最新AIAG-VDA方法论主持跨职能FMEA评审会',
    },
    monetization_potential: 'affiliate',
  },

  // ─── 8. GD&T ───
  {
    id: 'common-gdt',
    skill: 'GD&T (Geometric Dimensioning & Tolerancing)',
    skill_zh: 'GD&T几何尺寸与公差',
    industry: 'common',
    industry_context: 'Universal engineering language for defining part geometry on drawings — required for any precision manufacturing role',
    industry_context_zh: '工程图上定义零件几何的通用语言——所有精密制造岗位必备',
    tools: [
      {
        name: 'Zeiss Calypso',
        name_zh: '蔡司Calypso测量软件',
        vendor: 'Carl Zeiss',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.zeiss.com/metrology/products/software/calypso.html',
        alternatives: ['PC-DMIS', 'PolyWorks'],
      },
      {
        name: 'PC-DMIS',
        name_zh: 'PC-DMIS测量软件',
        vendor: 'Hexagon Manufacturing Intelligence',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.hexagonmi.com/products/software/pc-dmis',
      },
      {
        name: 'GD&T Advisor (by Sigmetrix)',
        name_zh: 'GD&T Advisor',
        vendor: 'Sigmetrix',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free online GD&T reference tool',
        url: 'https://www.sigmetrix.com/',
      },
    ],
    training: [
      {
        name: 'ETI (Effective Training Inc.)',
        name_zh: 'ETI GD&T培训',
        region: 'global',
        url: 'https://www.etinews.com/',
        price_range: '$500-$2,000',
        format: 'hybrid',
        certification: 'ETI GD&T Technologist Certificate',
        language: ['en'],
      },
      {
        name: 'ASME GD&T Training',
        name_zh: 'ASME GD&T培训',
        region: 'global',
        url: 'https://www.asme.org/learning-development',
        price_range: '$500-$2,500',
        format: 'hybrid',
        certification: 'ASME GDTP (GD&T Professional)',
        language: ['en'],
      },
      {
        name: 'TÜV Rheinland GD&T',
        name_zh: 'TÜV莱茵GD&T培训',
        region: 'DE',
        url: 'https://www.tuv.com/world/en/',
        price_range: '€800-€2,000',
        format: 'hybrid',
        language: ['de', 'en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'GD-and-T',
        repo_url: 'https://github.com/FreeCAD/FreeCAD',
        stars: '20k+',
        what_to_learn: 'Practice applying GD&T annotations in open-source CAD; understand datum systems',
        what_to_learn_zh: '在开源CAD中练习GD&T标注；理解基准系统',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'tolerance-analysis',
        repo_url: 'https://github.com/numpy/numpy',
        stars: '27k+',
        what_to_learn: 'Use NumPy for tolerance stack-up analysis and Monte Carlo simulation',
        what_to_learn_zh: '用NumPy进行公差叠加分析和蒙特卡洛仿真',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'GD&T Tolerance Stack-Up Analysis for an Assembly',
      title_zh: '某装配体GD&T公差叠加分析',
      difficulty: 'intermediate',
      time_hours: 30,
      deliverables: [
        'Annotated engineering drawing with full GD&T per ASME Y14.5',
        '1D tolerance stack-up (worst case + RSS)',
        'Monte Carlo simulation (Python) with yield prediction',
        'Datum scheme justification document',
      ],
      deliverables_zh: [
        '按ASME Y14.5标准完整标注GD&T的工程图',
        '一维公差叠加（极值法+均方根法）',
        '蒙特卡洛仿真（Python）含良率预测',
        '基准方案论证文件',
      ],
      proves_to_employer: 'Can apply GD&T correctly, perform stack-up analysis, and optimize tolerances for manufacturing',
      proves_to_employer_zh: '能正确应用GD&T、进行公差叠加分析并优化制造公差',
    },
    monetization_potential: 'none',
  },

  // ─── 9. Project Management ───
  {
    id: 'common-project-management',
    skill: 'Project Management',
    skill_zh: '项目管理',
    industry: 'common',
    industry_context: 'Essential for leading NPI, process improvement, and cross-functional manufacturing projects',
    industry_context_zh: '新产品导入、工艺改进和跨职能制造项目的必备技能',
    tools: [
      {
        name: 'Microsoft Project',
        name_zh: 'Microsoft Project',
        vendor: 'Microsoft',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.microsoft.com/en-us/microsoft-365/project/project-management-software',
        alternatives: ['Smartsheet', 'Monday.com'],
      },
      {
        name: 'Jira',
        name_zh: 'Jira项目管理',
        vendor: 'Atlassian',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free for up to 10 users',
        url: 'https://www.atlassian.com/software/jira',
        alternatives: ['Asana', 'Trello', 'ClickUp'],
      },
      {
        name: 'GanttProject',
        name_zh: 'GanttProject开源项目管理',
        vendor: 'Open Source',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Fully open-source and free',
        url: 'https://www.ganttproject.biz/',
      },
    ],
    training: [
      {
        name: 'PMI PMP Certification',
        name_zh: 'PMI PMP认证',
        region: 'global',
        url: 'https://www.pmi.org/certifications/project-management-pmp',
        price_range: '$555-$2,500',
        format: 'hybrid',
        certification: 'PMP (Project Management Professional)',
        language: ['en', 'zh'],
      },
      {
        name: 'PRINCE2 Foundation/Practitioner',
        name_zh: 'PRINCE2认证',
        region: 'EU',
        url: 'https://www.axelos.com/certifications/prince2',
        price_range: '£500-£1,500',
        format: 'hybrid',
        certification: 'PRINCE2 Foundation / Practitioner',
        language: ['en', 'de'],
      },
      {
        name: '清晖项目管理 (Tsinghui)',
        name_zh: '清晖项目管理',
        region: 'CN',
        url: 'https://www.tsinghui.com/',
        price_range: '¥3,000-¥8,000',
        format: 'hybrid',
        certification: 'PMP认证备考',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'ganttproject',
        repo_url: 'https://github.com/bardsoftware/ganttproject',
        stars: '3k+',
        what_to_learn: 'Understand Gantt chart data structures and project scheduling algorithms',
        what_to_learn_zh: '理解甘特图数据结构和项目排程算法',
        estimated_hours: 10,
      },
      {
        order: 2,
        repo_name: 'awesome-project-management',
        repo_url: 'https://github.com/shahedbd/awesome-project-management',
        stars: '1k+',
        what_to_learn: 'Curated list of PM tools, methodologies, and frameworks',
        what_to_learn_zh: '项目管理工具、方法论和框架精选列表',
        estimated_hours: 8,
      },
    ],
    capstone: {
      title: 'NPI (New Product Introduction) Project Plan',
      title_zh: '新产品导入(NPI)项目计划',
      difficulty: 'intermediate',
      time_hours: 35,
      deliverables: [
        'Project charter with scope, timeline, and budget',
        'WBS (Work Breakdown Structure) with APQP phases',
        'Gantt chart with critical path and milestones',
        'Risk register with mitigation plans',
        'Stakeholder communication plan',
      ],
      deliverables_zh: [
        '含范围、时间和预算的项目章程',
        '按APQP阶段的工作分解结构（WBS）',
        '含关键路径和里程碑的甘特图',
        '含缓解计划的风险登记册',
        '干系人沟通计划',
      ],
      proves_to_employer: 'Can plan and track a complex NPI project with APQP methodology and standard PM tools',
      proves_to_employer_zh: '能用APQP方法论和标准PM工具规划和跟踪复杂的新产品导入项目',
    },
    monetization_potential: 'affiliate',
  },

  // ─── 10. Python (Manufacturing) ───
  {
    id: 'common-python-manufacturing',
    skill: 'Python for Manufacturing',
    skill_zh: 'Python制造业数据分析',
    industry: 'common',
    industry_context: 'Python is increasingly essential for manufacturing data analysis, SPC automation, predictive maintenance, and Industry 4.0',
    industry_context_zh: 'Python在制造业数据分析、SPC自动化、预测性维护和工业4.0中越来越重要',
    tools: [
      {
        name: 'Python + pandas + scipy',
        name_zh: 'Python数据分析栈',
        vendor: 'Open Source',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Fully open-source and free',
        url: 'https://www.python.org/',
        alternatives: ['R', 'MATLAB'],
      },
      {
        name: 'Jupyter Notebook',
        name_zh: 'Jupyter Notebook',
        vendor: 'Project Jupyter',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Fully open-source and free; also available on Google Colab',
        url: 'https://jupyter.org/',
      },
      {
        name: 'VS Code + Python Extension',
        name_zh: 'VS Code Python开发环境',
        vendor: 'Microsoft',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Fully free',
        url: 'https://code.visualstudio.com/',
      },
    ],
    training: [
      {
        name: 'Coursera Python for Everybody',
        name_zh: 'Coursera人人学Python',
        region: 'global',
        url: 'https://www.coursera.org/specializations/python',
        price_range: 'Free audit / $49/month',
        format: 'online',
        certification: 'Coursera Specialization Certificate',
        language: ['en', 'zh'],
      },
      {
        name: 'DataCamp',
        name_zh: 'DataCamp数据科学培训',
        region: 'global',
        url: 'https://www.datacamp.com/',
        price_range: '$0-$25/month',
        format: 'online',
        certification: 'DataCamp Certificate',
        language: ['en'],
      },
      {
        name: '网易云课堂 (163 Study)',
        name_zh: '网易云课堂',
        region: 'CN',
        url: 'https://study.163.com/',
        price_range: '¥0-¥499',
        format: 'online',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'pandas',
        repo_url: 'https://github.com/pandas-dev/pandas',
        stars: '43k+',
        what_to_learn: 'Data manipulation fundamentals: read production data, clean, aggregate, pivot',
        what_to_learn_zh: '数据处理基础：读取生产数据、清洗、聚合、透视',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'scipy',
        repo_url: 'https://github.com/scipy/scipy',
        stars: '13k+',
        what_to_learn: 'Statistical testing for manufacturing: t-tests, ANOVA, process capability',
        what_to_learn_zh: '制造业统计检验：t检验、方差分析、过程能力',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'matplotlib',
        repo_url: 'https://github.com/matplotlib/matplotlib',
        stars: '20k+',
        what_to_learn: 'Create SPC charts, Pareto diagrams, and production dashboards',
        what_to_learn_zh: '创建SPC控制图、帕累托图和生产仪表盘',
        estimated_hours: 10,
      },
    ],
    capstone: {
      title: 'Manufacturing Data Analysis Dashboard with Python',
      title_zh: 'Python制造业数据分析仪表盘',
      difficulty: 'intermediate',
      time_hours: 40,
      deliverables: [
        'Python script to parse production CSV/Excel data',
        'SPC control charts (X-bar R, p-chart) auto-generated',
        'Process capability report (Cp/Cpk/Pp/Ppk)',
        'Pareto analysis of top defects',
        'Interactive dashboard (Streamlit or Plotly Dash)',
      ],
      deliverables_zh: [
        '解析生产CSV/Excel数据的Python脚本',
        '自动生成SPC控制图（X-bar R图、p图）',
        '过程能力报告（Cp/Cpk/Pp/Ppk）',
        '主要缺陷帕累托分析',
        '交互式仪表盘（Streamlit或Plotly Dash）',
      ],
      proves_to_employer: 'Can automate quality data analysis and build dashboards that replace manual Excel reporting',
      proves_to_employer_zh: '能自动化质量数据分析并构建替代手工Excel报表的仪表盘',
    },
    monetization_potential: 'affiliate',
  },

  // ─── 11. ERP (SAP) ───
  {
    id: 'common-erp-sap',
    skill: 'ERP Systems (SAP S/4HANA)',
    skill_zh: 'ERP系统（SAP S/4HANA）',
    industry: 'common',
    industry_context: 'Enterprise resource planning backbone for manufacturing operations — procurement, production, logistics, finance',
    industry_context_zh: '制造运营的企业资源计划核心——采购、生产、物流、财务',
    tools: [
      {
        name: 'SAP S/4HANA',
        name_zh: 'SAP S/4HANA',
        vendor: 'SAP SE',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'SAP Learning Hub includes trial system access',
        url: 'https://www.sap.com/products/erp/s4hana.html',
        alternatives: ['Oracle ERP Cloud', 'Microsoft Dynamics 365'],
      },
      {
        name: 'SAP Fiori',
        name_zh: 'SAP Fiori用户界面',
        vendor: 'SAP SE',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Included with SAP Learning Hub',
        url: 'https://experience.sap.com/fiori-design-web/',
      },
    ],
    training: [
      {
        name: 'SAP Learning Hub',
        name_zh: 'SAP学习中心',
        region: 'global',
        url: 'https://learning.sap.com/',
        price_range: '€199-€599/year',
        format: 'online',
        certification: 'SAP Certified Associate — SAP S/4HANA',
        language: ['en', 'de'],
      },
      {
        name: 'openSAP',
        name_zh: 'openSAP免费课程',
        region: 'global',
        url: 'https://open.sap.com/',
        price_range: 'Free',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'Michael Management',
        name_zh: 'Michael Management SAP培训',
        region: 'global',
        url: 'https://www.michaelmanagement.com/',
        price_range: '$50-$500',
        format: 'online',
        certification: 'Michael Management SAP Certificate',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'abap-cheat-sheets',
        repo_url: 'https://github.com/SAP-samples/abap-cheat-sheets',
        stars: '2k+',
        what_to_learn: 'Core ABAP programming patterns for SAP customization',
        what_to_learn_zh: 'SAP定制的核心ABAP编程模式',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'cloud-cap-samples',
        repo_url: 'https://github.com/SAP-samples/cloud-cap-samples',
        stars: '1.5k+',
        what_to_learn: 'SAP Cloud Application Programming model — modern SAP extensions',
        what_to_learn_zh: 'SAP云应用编程模型——现代SAP扩展开发',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'End-to-End Order-to-Cash Process in SAP S/4HANA',
      title_zh: 'SAP S/4HANA端到端订单到收款流程',
      difficulty: 'advanced',
      time_hours: 50,
      deliverables: [
        'Master data configuration (customer, material, pricing)',
        'Sales order → delivery → billing → payment flow',
        'Custom CDS view for order status reporting',
        'Fiori app extension for sales dashboard',
      ],
      deliverables_zh: [
        '主数据配置（客户、物料、定价）',
        '销售订单→交货→开票→收款全流程',
        '自定义CDS视图用于订单状态报表',
        'Fiori App扩展用于销售仪表盘',
      ],
      proves_to_employer: 'Can navigate SAP S/4HANA end-to-end and build custom reporting extensions',
      proves_to_employer_zh: '能端到端操作SAP S/4HANA并构建自定义报表扩展',
    },
    monetization_potential: 'affiliate',
  },

  // ─── 12. SPC / Statistical Process Control ───
  {
    id: 'common-spc',
    skill: 'SPC (Statistical Process Control)',
    skill_zh: 'SPC统计过程控制',
    industry: 'common',
    industry_context: 'Real-time quality monitoring fundamental to all manufacturing — one of the AIAG core tools',
    industry_context_zh: '所有制造业实时质量监控的基础——AIAG五大核心工具之一',
    tools: [
      {
        name: 'Minitab',
        name_zh: 'Minitab',
        vendor: 'Minitab LLC',
        tier: 'essential',
        free_tier: true,
        free_tier_note: '30-day free trial',
        url: 'https://www.minitab.com/',
        alternatives: ['Python pyspc', 'R qcc package'],
      },
      {
        name: 'InfinityQS ProFicient',
        name_zh: 'InfinityQS质量管理',
        vendor: 'InfinityQS International',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.infinityqs.com/',
      },
      {
        name: 'QI Macros (Excel add-in)',
        name_zh: 'QI Macros Excel插件',
        vendor: 'KnowWare International',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: '30-day free trial',
        url: 'https://www.qimacros.com/',
      },
    ],
    training: [
      {
        name: 'ASQ SPC Training',
        name_zh: 'ASQ SPC培训',
        region: 'global',
        url: 'https://asq.org/training',
        price_range: '$200-$1,500',
        format: 'hybrid',
        certification: 'ASQ Certified Quality Engineer',
        language: ['en'],
      },
      {
        name: 'DataCamp Statistics Courses',
        name_zh: 'DataCamp统计课程',
        region: 'global',
        url: 'https://www.datacamp.com/tracks/statistician-with-python',
        price_range: '$0-$25/month',
        format: 'online',
        language: ['en'],
      },
      {
        name: '中国质量协会 (CAQ)',
        name_zh: '中国质量协会',
        region: 'CN',
        url: 'https://www.caq.org.cn/',
        price_range: '¥1,000-¥5,000',
        format: 'hybrid',
        certification: '质量工程师认证',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'pyspc',
        repo_url: 'https://github.com/carlosqsilva/pyspc',
        stars: '200+',
        what_to_learn: 'Build SPC control charts (X-bar, R, S, p, np, c, u) with Python',
        what_to_learn_zh: '用Python创建SPC控制图（X-bar、R、S、p、np、c、u图）',
        estimated_hours: 12,
      },
      {
        order: 2,
        repo_name: 'qcc (R package)',
        repo_url: 'https://github.com/luca-scr/qcc',
        stars: '100+',
        what_to_learn: 'Statistical quality control with R — control charts, capability analysis, Pareto',
        what_to_learn_zh: '用R进行统计质量控制——控制图、能力分析、帕累托',
        estimated_hours: 10,
      },
    ],
    capstone: {
      title: 'Automated SPC Monitoring System for a Production Line',
      title_zh: '某产线自动化SPC监控系统',
      difficulty: 'intermediate',
      time_hours: 35,
      deliverables: [
        'Python script to read measurement data (CSV/database)',
        'Auto-generated X-bar R and p-charts with control limits',
        'Out-of-control alarm detection (Western Electric rules)',
        'Process capability report with Cp/Cpk trending',
        'Email/WeChat alert when process goes out of control',
      ],
      deliverables_zh: [
        '读取测量数据（CSV/数据库）的Python脚本',
        '自动生成X-bar R图和p图（含控制限）',
        '失控报警检测（Western Electric规则）',
        '含Cp/Cpk趋势的过程能力报告',
        '过程失控时发送邮件/微信提醒',
      ],
      proves_to_employer: 'Can build automated SPC systems that replace manual charting and provide real-time quality alerts',
      proves_to_employer_zh: '能构建替代手工绘图的自动化SPC系统，提供实时质量预警',
    },
    monetization_potential: 'none',
  },

  // ─── 13. Root Cause Analysis (8D) ───
  {
    id: 'common-rca-8d',
    skill: 'Root Cause Analysis (8D)',
    skill_zh: '根因分析（8D方法）',
    industry: 'common',
    industry_context: 'Structured problem-solving methodology used across all manufacturing — especially automotive supplier quality',
    industry_context_zh: '所有制造业的结构化问题解决方法论——尤其是汽车供应商质量管理',
    tools: [
      {
        name: 'Ishikawa / Fishbone Templates',
        name_zh: '石川图/鱼骨图模板',
        vendor: 'Various / Open',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free templates in Excel, Visio, Miro',
        url: 'https://miro.com/templates/fishbone-diagram/',
      },
      {
        name: '5 Why Analysis Tool',
        name_zh: '5Why分析工具',
        vendor: 'Various',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free templates widely available',
        url: 'https://www.mindtools.com/a3mi00v/5-whys',
      },
      {
        name: 'Kepner-Tregoe Resolve',
        name_zh: 'KT法问题解决工具',
        vendor: 'Kepner-Tregoe',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.kepner-tregoe.com/',
      },
    ],
    training: [
      {
        name: 'TÜV SÜD 8D Training',
        name_zh: 'TÜV南德8D培训',
        region: 'DE',
        url: 'https://www.tuvsud.com/en/services/training',
        price_range: '€800-€2,000',
        format: 'hybrid',
        certification: 'TÜV 8D Problem Solving Certificate',
        language: ['de', 'en'],
      },
      {
        name: 'ASQ Problem Solving',
        name_zh: 'ASQ问题解决培训',
        region: 'global',
        url: 'https://asq.org/training',
        price_range: '$200-$1,000',
        format: 'hybrid',
        language: ['en'],
      },
      {
        name: 'AIAG 8D Training',
        name_zh: 'AIAG 8D培训',
        region: 'global',
        url: 'https://www.aiag.org/',
        price_range: '$300-$800',
        format: 'online',
        certification: 'AIAG 8D Practitioner',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'reliability',
        repo_url: 'https://github.com/MatthewReid854/reliability',
        stars: '900+',
        what_to_learn: 'Statistical failure analysis tools that support root cause investigation',
        what_to_learn_zh: '支持根因调查的统计失效分析工具',
        estimated_hours: 12,
      },
      {
        order: 2,
        repo_name: 'plotly',
        repo_url: 'https://github.com/plotly/plotly.py',
        stars: '16k+',
        what_to_learn: 'Create interactive Pareto charts, fishbone visualizations, and failure trend analysis',
        what_to_learn_zh: '创建交互式帕累托图、鱼骨图可视化和失效趋势分析',
        estimated_hours: 10,
      },
    ],
    capstone: {
      title: 'Complete 8D Report for a Customer Quality Complaint',
      title_zh: '客户质量投诉完整8D报告',
      difficulty: 'intermediate',
      time_hours: 25,
      deliverables: [
        'D1-D8 report with team formation and problem description',
        'Containment action plan (D3)',
        'Root cause analysis with Ishikawa + 5Why + verification test (D4-D6)',
        'Corrective and preventive actions with effectiveness validation (D7)',
        'Lessons learned documentation (D8)',
      ],
      deliverables_zh: [
        '含团队组建和问题描述的D1-D8报告',
        '围堵措施计划（D3）',
        '含鱼骨图+5Why+验证试验的根因分析（D4-D6）',
        '含有效性验证的纠正和预防措施（D7）',
        '经验教训文档（D8）',
      ],
      proves_to_employer: 'Can lead a structured 8D investigation and deliver a professional customer-facing report',
      proves_to_employer_zh: '能主导结构化8D调查并交付专业的面客报告',
    },
    monetization_potential: 'none',
  },

  // ─── 14. Value Stream Mapping ───
  {
    id: 'common-vsm',
    skill: 'Value Stream Mapping',
    skill_zh: '价值流图析',
    industry: 'common',
    industry_context: 'Key lean tool for visualizing material and information flow — identifies waste and improvement opportunities',
    industry_context_zh: '精益核心工具，可视化物料和信息流——识别浪费和改善机会',
    tools: [
      {
        name: 'Lucidchart',
        name_zh: 'Lucidchart在线绘图',
        vendor: 'Lucid Software',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free plan with limited documents',
        url: 'https://www.lucidchart.com/',
        alternatives: ['Visio', 'Miro', 'draw.io'],
      },
      {
        name: 'eVSM',
        name_zh: 'eVSM专业价值流图软件',
        vendor: 'eVSM International',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.evsm.com/',
      },
      {
        name: 'draw.io (diagrams.net)',
        name_zh: 'draw.io免费绘图',
        vendor: 'JGraph Ltd',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Fully free and open-source',
        url: 'https://www.drawio.com/',
      },
    ],
    training: [
      {
        name: 'Lean Enterprise Institute',
        name_zh: '精益企业研究院',
        region: 'global',
        url: 'https://www.lean.org/training-education/learning-to-see/',
        price_range: '$200-$1,500',
        format: 'hybrid',
        language: ['en'],
      },
      {
        name: 'Kaizen Institute',
        name_zh: '改善研究院',
        region: 'global',
        url: 'https://www.kaizen.com/',
        price_range: '€500-€3,000',
        format: 'hybrid',
        certification: 'Kaizen Practitioner',
        language: ['en', 'de'],
      },
      {
        name: '精益企业中国 (Lean China)',
        name_zh: '精益企业中国',
        region: 'CN',
        url: 'https://www.lean.org.cn/',
        price_range: '¥1,500-¥8,000',
        format: 'hybrid',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'drawio',
        repo_url: 'https://github.com/jgraph/drawio',
        stars: '42k+',
        what_to_learn: 'Use open-source diagramming tool to create VSMs; learn VSM symbol library',
        what_to_learn_zh: '用开源绘图工具创建价值流图；学习VSM符号库',
        estimated_hours: 8,
      },
      {
        order: 2,
        repo_name: 'mermaid',
        repo_url: 'https://github.com/mermaid-js/mermaid',
        stars: '72k+',
        what_to_learn: 'Create text-based process flow diagrams that can be version-controlled',
        what_to_learn_zh: '创建可版本控制的文本化流程图',
        estimated_hours: 6,
      },
    ],
    capstone: {
      title: 'Current & Future State VSM with Implementation Plan',
      title_zh: '现状与未来状态价值流图及实施计划',
      difficulty: 'intermediate',
      time_hours: 30,
      deliverables: [
        'Current-state VSM with all data boxes (cycle time, changeover, uptime, inventory)',
        'Takt time and bottleneck analysis',
        'Future-state VSM with supermarket pull, FIFO lanes, level mix',
        'Kaizen burst action items with owners and deadlines',
        'Implementation roadmap (30-60-90 day plan)',
      ],
      deliverables_zh: [
        '含所有数据框的现状价值流图（周期时间、换型、稼动率、库存）',
        '节拍时间和瓶颈分析',
        '含超市拉动、FIFO通道、均衡化的未来状态价值流图',
        '含负责人和截止日期的改善突破行动项',
        '实施路线图（30-60-90天计划）',
      ],
      proves_to_employer: 'Can map complex value streams, identify bottlenecks, and design lean future-state processes',
      proves_to_employer_zh: '能绘制复杂价值流、识别瓶颈并设计精益的未来状态流程',
    },
    monetization_potential: 'none',
  },

  // ─── 15. DFM/DFA ───
  {
    id: 'common-dfm-dfa',
    skill: 'DFM/DFA (Design for Manufacturing/Assembly)',
    skill_zh: 'DFM/DFA面向制造与装配的设计',
    industry: 'common',
    industry_context: 'Methodology to optimize product designs for cost-effective manufacturing and easy assembly — bridges design and production',
    industry_context_zh: '优化产品设计以实现低成本制造和便捷装配的方法论——连接设计与生产',
    tools: [
      {
        name: 'DFMA Software (Boothroyd Dewhurst)',
        name_zh: 'DFMA软件（Boothroyd Dewhurst）',
        vendor: 'Boothroyd Dewhurst Inc.',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.dfma.com/',
        alternatives: ['SolidWorks DFMXpress', 'Manual DFM checklists'],
      },
      {
        name: 'SolidWorks DFMXpress',
        name_zh: 'SolidWorks DFMXpress',
        vendor: 'Dassault Systèmes',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Included free with SolidWorks',
        url: 'https://www.solidworks.com/product/solidworks-dfmxpress',
      },
      {
        name: 'Moldflow (Injection Molding DFM)',
        name_zh: 'Moldflow注塑DFM分析',
        vendor: 'Autodesk',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free for students via Autodesk Education',
        url: 'https://www.autodesk.com/products/moldflow/',
      },
    ],
    training: [
      {
        name: 'SME (Society of Manufacturing Engineers)',
        name_zh: 'SME制造工程师学会',
        region: 'global',
        url: 'https://www.sme.org/',
        price_range: '$200-$1,500',
        format: 'hybrid',
        certification: 'SME DFM Certificate',
        language: ['en'],
      },
      {
        name: 'Udemy DFM Courses',
        name_zh: 'Udemy DFM课程',
        region: 'global',
        url: 'https://www.udemy.com/topic/design-for-manufacturing/',
        price_range: '$12-$100',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'Protolabs Design Tips',
        name_zh: 'Protolabs设计指南',
        region: 'global',
        url: 'https://www.protolabs.com/resources/design-tips/',
        price_range: 'Free',
        format: 'online',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'FreeCAD',
        repo_url: 'https://github.com/FreeCAD/FreeCAD',
        stars: '20k+',
        what_to_learn: 'Practice applying DFM principles in 3D models — draft angles, wall thickness, undercuts',
        what_to_learn_zh: '在3D模型中练习DFM原则——拔模角、壁厚、倒扣',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'CadQuery',
        repo_url: 'https://github.com/CadQuery/cadquery',
        stars: '3k+',
        what_to_learn: 'Programmatic CAD for parametric DFM optimization — automate design rule checks',
        what_to_learn_zh: '程序化CAD用于参数化DFM优化——自动化设计规则检查',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'DFM/DFA Redesign of a Multi-Part Product',
      title_zh: '某多零件产品DFM/DFA再设计',
      difficulty: 'advanced',
      time_hours: 45,
      deliverables: [
        'Original vs redesigned BOM comparison (target: 30% part count reduction)',
        'DFM analysis report for each critical part (material, process, tolerance)',
        'DFA analysis: assembly time estimate before/after',
        'Cost comparison: tooling, material, labor savings',
        'Design review presentation with trade-off analysis',
      ],
      deliverables_zh: [
        '原始vs再设计BOM对比（目标：减少30%零件数）',
        '每个关键零件的DFM分析报告（材料、工艺、公差）',
        'DFA分析：改善前后装配时间估算',
        '成本对比：模具、材料、人工节省',
        '含权衡分析的设计评审演示',
      ],
      proves_to_employer: 'Can optimize product designs for manufacturability, reduce costs, and present data-driven trade-offs',
      proves_to_employer_zh: '能优化产品的可制造性设计、降低成本并展示数据驱动的权衡分析',
    },
    monetization_potential: 'none',
  },
];
