import type { IndustryToolMapEntry } from './types';

export const consultingEntries: IndustryToolMapEntry[] = [
  // ─── 1. Strategy Frameworks ───
  {
    id: 'consulting-strategy',
    skill: 'Strategy Frameworks',
    skill_zh: '战略咨询框架',
    industry: 'consulting',
    industry_context: 'Core consulting skill — structuring ambiguous problems using proven frameworks (Porter, McKinsey 7S, BCG Matrix)',
    industry_context_zh: '咨询核心技能——使用成熟框架（波特、麦肯锡7S、BCG矩阵）结构化解决模糊问题',
    tools: [
      {
        name: 'Microsoft PowerPoint',
        name_zh: 'Microsoft PowerPoint',
        vendor: 'Microsoft',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free web version via Office.com; student licenses available',
        url: 'https://www.microsoft.com/en-us/microsoft-365/powerpoint',
        alternatives: ['Google Slides', 'Keynote'],
      },
      {
        name: 'Miro',
        name_zh: 'Miro在线白板',
        vendor: 'Miro',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free plan with 3 editable boards',
        url: 'https://miro.com/',
        alternatives: ['FigJam', 'Lucidspark'],
      },
      {
        name: 'think-cell',
        name_zh: 'think-cell图表插件',
        vendor: 'think-cell Software GmbH',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free for students and academics',
        url: 'https://www.think-cell.com/',
      },
    ],
    training: [
      {
        name: 'Victor Cheng — Case Interview Secrets',
        name_zh: 'Victor Cheng案例面试课程',
        region: 'global',
        url: 'https://www.caseinterview.com/',
        price_range: '$50-$500',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'CraftingCases',
        name_zh: 'CraftingCases案例培训',
        region: 'global',
        url: 'https://www.craftingcases.com/',
        price_range: '$0-$300',
        format: 'online',
        language: ['en'],
      },
      {
        name: '蔓藤教育 (MentorX)',
        name_zh: '蔓藤教育',
        region: 'CN',
        url: 'https://www.mentorx.net/',
        price_range: '¥2,000-¥20,000',
        format: 'online',
        language: ['zh', 'en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'awesome-strategy',
        repo_url: 'https://github.com/alextanhongpin/awesome-slides',
        stars: '200+',
        what_to_learn: 'Presentation design patterns and slide frameworks used in consulting',
        what_to_learn_zh: '咨询行业常用的演示设计模式和幻灯片框架',
        estimated_hours: 8,
      },
      {
        order: 2,
        repo_name: 'reveal.js',
        repo_url: 'https://github.com/hakimel/reveal.js',
        stars: '68k+',
        what_to_learn: 'Build interactive HTML presentations — useful for digital strategy deliverables',
        what_to_learn_zh: '构建交互式HTML演示——适用于数字化战略交付物',
        estimated_hours: 10,
      },
    ],
    capstone: {
      title: 'Market Entry Strategy Case Study',
      title_zh: '市场进入战略案例分析',
      difficulty: 'intermediate',
      time_hours: 30,
      deliverables: [
        'Market sizing analysis (top-down and bottom-up)',
        'Competitive landscape mapping (Porter\'s Five Forces)',
        'Go/No-Go recommendation with financial model',
        'Executive presentation deck (10-15 slides, consulting format)',
      ],
      deliverables_zh: [
        '市场规模分析（自上而下和自下而上法）',
        '竞争格局分析（波特五力模型）',
        '含财务模型的进入/不进入建议',
        '高管演示文稿（10-15页，咨询格式）',
      ],
      proves_to_employer: 'Can structure ambiguous problems, conduct rigorous analysis, and deliver compelling executive presentations',
      proves_to_employer_zh: '能结构化模糊问题、进行严谨分析并交付有说服力的高管演示',
    },
    monetization_potential: 'affiliate',
  },

  // ─── 2. Financial Modeling ───
  {
    id: 'consulting-financial-modeling',
    skill: 'Financial Modeling',
    skill_zh: '财务建模',
    industry: 'consulting',
    industry_context: 'Essential for M&A advisory, due diligence, valuation, and business case development in consulting engagements',
    industry_context_zh: '咨询项目中并购顾问、尽职调查、估值和商业论证的必备技能',
    tools: [
      {
        name: 'Microsoft Excel',
        name_zh: 'Microsoft Excel',
        vendor: 'Microsoft',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free web version via Office.com',
        url: 'https://www.microsoft.com/en-us/microsoft-365/excel',
        alternatives: ['Google Sheets'],
      },
      {
        name: 'Wall Street Prep Financial Model Templates',
        name_zh: 'Wall Street Prep财务模型模板',
        vendor: 'Wall Street Prep',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free basic templates available',
        url: 'https://www.wallstreetprep.com/',
      },
      {
        name: 'Capital IQ',
        name_zh: 'Capital IQ金融数据库',
        vendor: 'S&P Global',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.capitaliq.com/',
        alternatives: ['Bloomberg Terminal', 'PitchBook'],
      },
    ],
    training: [
      {
        name: 'Wall Street Prep',
        name_zh: 'Wall Street Prep',
        region: 'global',
        url: 'https://www.wallstreetprep.com/',
        price_range: '$399-$999',
        format: 'online',
        certification: 'WSP Financial Modeling Certificate',
        language: ['en'],
      },
      {
        name: 'Breaking Into Wall Street (BIWS)',
        name_zh: 'BIWS财务建模培训',
        region: 'global',
        url: 'https://breakingintowallstreet.com/',
        price_range: '$497-$797',
        format: 'online',
        certification: 'BIWS Certificate',
        language: ['en'],
      },
      {
        name: 'Corporate Finance Institute (CFI)',
        name_zh: 'CFI企业金融学院',
        region: 'global',
        url: 'https://corporatefinanceinstitute.com/',
        price_range: '$0-$497/year',
        format: 'online',
        certification: 'FMVA (Financial Modeling & Valuation Analyst)',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'OpenBBTerminal',
        repo_url: 'https://github.com/OpenBB-finance/OpenBB',
        stars: '33k+',
        what_to_learn: 'Open-source financial analysis platform — learn financial data APIs and analysis workflows',
        what_to_learn_zh: '开源金融分析平台——学习金融数据API和分析流程',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'FinanceDatabase',
        repo_url: 'https://github.com/JerBouma/FinanceDatabase',
        stars: '3k+',
        what_to_learn: 'Comprehensive financial data for building DCF and comparable company models',
        what_to_learn_zh: '全面的金融数据，用于构建DCF和可比公司模型',
        estimated_hours: 12,
      },
    ],
    capstone: {
      title: 'Three-Statement Financial Model with DCF Valuation',
      title_zh: '三表联动财务模型与DCF估值',
      difficulty: 'advanced',
      time_hours: 50,
      deliverables: [
        'Three-statement model (Income Statement, Balance Sheet, Cash Flow)',
        'DCF valuation with WACC calculation',
        'Sensitivity analysis (data tables) on key assumptions',
        'Comparable company analysis (trading comps)',
        'Executive summary with investment recommendation',
      ],
      deliverables_zh: [
        '三表联动模型（利润表、资产负债表、现金流量表）',
        '含WACC计算的DCF估值',
        '关键假设敏感性分析（数据表）',
        '可比公司分析（交易倍数）',
        '含投资建议的执行摘要',
      ],
      proves_to_employer: 'Can build robust financial models from scratch and derive data-driven valuation conclusions',
      proves_to_employer_zh: '能从零构建稳健的财务模型并得出数据驱动的估值结论',
    },
    monetization_potential: 'affiliate',
  },

  // ─── 3. Change Management ───
  {
    id: 'consulting-change-management',
    skill: 'Change Management',
    skill_zh: '变革管理',
    industry: 'consulting',
    industry_context: 'Critical for ERP implementations, digital transformations, and organizational restructuring projects',
    industry_context_zh: 'ERP实施、数字化转型和组织重构项目的关键能力',
    tools: [
      {
        name: 'Prosci ADKAR Model',
        name_zh: 'Prosci ADKAR变革模型',
        vendor: 'Prosci',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free ADKAR overview and assessment tools on website',
        url: 'https://www.prosci.com/',
        alternatives: ['Kotter 8-Step', 'McKinsey 7S'],
      },
      {
        name: 'ServiceNow Change Management',
        name_zh: 'ServiceNow变更管理模块',
        vendor: 'ServiceNow',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Personal Developer Instance available free',
        url: 'https://www.servicenow.com/',
      },
      {
        name: 'Miro (Workshop Facilitation)',
        name_zh: 'Miro工作坊辅助工具',
        vendor: 'Miro',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free plan with 3 editable boards',
        url: 'https://miro.com/',
      },
    ],
    training: [
      {
        name: 'Prosci Change Management Certification',
        name_zh: 'Prosci变革管理认证',
        region: 'global',
        url: 'https://www.prosci.com/certification',
        price_range: '$4,500-$5,500',
        format: 'hybrid',
        certification: 'Prosci Certified Change Practitioner',
        language: ['en'],
      },
      {
        name: 'Kotter Change Management',
        name_zh: 'Kotter变革管理课程',
        region: 'global',
        url: 'https://www.kotterinc.com/',
        price_range: '$500-$3,000',
        format: 'hybrid',
        language: ['en'],
      },
      {
        name: 'APMG Change Management Foundation',
        name_zh: 'APMG变革管理基础认证',
        region: 'EU',
        url: 'https://apmg-international.com/product/change-management',
        price_range: '£500-£1,500',
        format: 'hybrid',
        certification: 'APMG Change Management Foundation / Practitioner',
        language: ['en', 'de'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'awesome-leading-and-managing',
        repo_url: 'https://github.com/LappleApple/awesome-leading-and-managing',
        stars: '8k+',
        what_to_learn: 'Leadership and management frameworks applicable to organizational change',
        what_to_learn_zh: '适用于组织变革的领导力和管理框架',
        estimated_hours: 10,
      },
      {
        order: 2,
        repo_name: 'awesome-retrospectives',
        repo_url: 'https://github.com/josephearl/awesome-retrospectives',
        stars: '200+',
        what_to_learn: 'Retrospective facilitation techniques — essential for change management check-ins',
        what_to_learn_zh: '回顾会引导技术——变革管理检查点的必备技能',
        estimated_hours: 6,
      },
    ],
    capstone: {
      title: 'Change Management Plan for an ERP Implementation',
      title_zh: 'ERP实施项目变革管理计划',
      difficulty: 'intermediate',
      time_hours: 35,
      deliverables: [
        'Stakeholder analysis and influence mapping',
        'ADKAR assessment for key user groups',
        'Communication plan (by audience, channel, frequency)',
        'Training needs analysis and delivery plan',
        'Resistance management strategy with escalation paths',
      ],
      deliverables_zh: [
        '干系人分析和影响力地图',
        '关键用户群ADKAR评估',
        '沟通计划（按受众、渠道、频率）',
        '培训需求分析和交付计划',
        '含升级路径的阻力管理策略',
      ],
      proves_to_employer: 'Can design and execute structured change management plans for large-scale technology implementations',
      proves_to_employer_zh: '能为大规模技术实施设计和执行结构化的变革管理计划',
    },
    monetization_potential: 'affiliate',
  },

  // ─── 4. Data Analysis (Consulting) ───
  {
    id: 'consulting-data-analysis',
    skill: 'Data Analysis for Consulting',
    skill_zh: '咨询数据分析',
    industry: 'consulting',
    industry_context: 'Data-driven consulting requires visualization and statistical analysis to support strategic recommendations',
    industry_context_zh: '数据驱动的咨询需要可视化和统计分析来支撑战略建议',
    tools: [
      {
        name: 'Tableau',
        name_zh: 'Tableau数据可视化',
        vendor: 'Salesforce',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Tableau Public free; Tableau Desktop free for students',
        url: 'https://www.tableau.com/',
        alternatives: ['Power BI', 'Looker'],
      },
      {
        name: 'Power BI',
        name_zh: 'Power BI商业智能',
        vendor: 'Microsoft',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Power BI Desktop free; Pro free trial 60 days',
        url: 'https://powerbi.microsoft.com/',
      },
      {
        name: 'Python (pandas + plotly)',
        name_zh: 'Python数据分析',
        vendor: 'Open Source',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Fully open-source and free',
        url: 'https://www.python.org/',
      },
    ],
    training: [
      {
        name: 'DataCamp',
        name_zh: 'DataCamp数据科学',
        region: 'global',
        url: 'https://www.datacamp.com/',
        price_range: '$0-$25/month',
        format: 'online',
        certification: 'DataCamp Professional Certificate',
        language: ['en'],
      },
      {
        name: '365 Data Science',
        name_zh: '365 Data Science',
        region: 'global',
        url: 'https://365datascience.com/',
        price_range: '$0-$21/month',
        format: 'online',
        certification: '365 Data Science Certificate',
        language: ['en'],
      },
      {
        name: 'Coursera Google Data Analytics',
        name_zh: 'Coursera谷歌数据分析',
        region: 'global',
        url: 'https://www.coursera.org/professional-certificates/google-data-analytics',
        price_range: 'Free audit / $49/month',
        format: 'online',
        certification: 'Google Data Analytics Professional Certificate',
        language: ['en', 'zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'pandas',
        repo_url: 'https://github.com/pandas-dev/pandas',
        stars: '43k+',
        what_to_learn: 'Data wrangling fundamentals for business analysis — pivot tables, groupby, merging datasets',
        what_to_learn_zh: '商业分析数据处理基础——透视表、分组、数据集合并',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'plotly',
        repo_url: 'https://github.com/plotly/plotly.py',
        stars: '16k+',
        what_to_learn: 'Create interactive consulting-grade visualizations and dashboards',
        what_to_learn_zh: '创建咨询级别的交互式可视化和仪表盘',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'streamlit',
        repo_url: 'https://github.com/streamlit/streamlit',
        stars: '36k+',
        what_to_learn: 'Build interactive data apps for client presentations — no frontend skills needed',
        what_to_learn_zh: '构建面向客户演示的交互式数据应用——无需前端技能',
        estimated_hours: 12,
      },
    ],
    capstone: {
      title: 'Business Analytics Dashboard for Executive Decision-Making',
      title_zh: '高管决策商业分析仪表盘',
      difficulty: 'intermediate',
      time_hours: 40,
      deliverables: [
        'Data pipeline: ingest, clean, and transform business data (Python)',
        'Interactive Tableau/Power BI dashboard with KPI scorecards',
        'Cohort analysis and trend identification',
        'Recommendation memo with data-backed insights (2-3 pages)',
        'Live demo presentation for stakeholders',
      ],
      deliverables_zh: [
        '数据管道：采集、清洗和转换业务数据（Python）',
        '含KPI计分卡的交互式Tableau/Power BI仪表盘',
        '队列分析和趋势识别',
        '含数据支撑洞察的建议备忘录（2-3页）',
        '面向干系人的现场演示',
      ],
      proves_to_employer: 'Can transform raw business data into actionable insights and present them in a compelling, executive-ready format',
      proves_to_employer_zh: '能将原始业务数据转化为可执行的洞察并以高管级别的格式呈现',
    },
    monetization_potential: 'affiliate',
  },

  // ─── 5. SAP Consulting ───
  {
    id: 'consulting-sap',
    skill: 'SAP Consulting',
    skill_zh: 'SAP咨询',
    industry: 'consulting',
    industry_context: 'SAP implementation consulting is one of the largest consulting markets — S/4HANA migrations drive massive demand',
    industry_context_zh: 'SAP实施咨询是最大的咨询市场之一——S/4HANA迁移带来巨大需求',
    tools: [
      {
        name: 'SAP S/4HANA',
        name_zh: 'SAP S/4HANA',
        vendor: 'SAP SE',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'SAP Learning Hub includes trial system access',
        url: 'https://www.sap.com/products/erp/s4hana.html',
      },
      {
        name: 'SAP Activate Methodology',
        name_zh: 'SAP Activate方法论',
        vendor: 'SAP SE',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Methodology documentation freely available; SAP Activate Roadmap Viewer is free',
        url: 'https://support.sap.com/en/offerings-programs/methodology.html',
      },
      {
        name: 'SAP Solution Manager',
        name_zh: 'SAP Solution Manager',
        vendor: 'SAP SE',
        tier: 'recommended',
        free_tier: false,
        url: 'https://support.sap.com/en/alm/solution-manager.html',
        alternatives: ['Jira', 'Azure DevOps'],
      },
    ],
    training: [
      {
        name: 'SAP Learning Hub',
        name_zh: 'SAP学习中心',
        region: 'global',
        url: 'https://learning.sap.com/',
        price_range: '€199-€599/year',
        format: 'online',
        certification: 'SAP Certified Associate / Professional — various modules',
        language: ['en', 'de'],
      },
      {
        name: 'openSAP',
        name_zh: 'openSAP免费课程',
        region: 'global',
        url: 'https://open.sap.com/',
        price_range: 'Free',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'Michael Management',
        name_zh: 'Michael Management SAP培训',
        region: 'global',
        url: 'https://www.michaelmanagement.com/',
        price_range: '$50-$500',
        format: 'online',
        certification: 'Michael Management SAP Certificate',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'abap-cheat-sheets',
        repo_url: 'https://github.com/SAP-samples/abap-cheat-sheets',
        stars: '2k+',
        what_to_learn: 'ABAP programming patterns for SAP consultants — custom reports, enhancements, data migration',
        what_to_learn_zh: 'SAP顾问的ABAP编程模式——自定义报表、增强、数据迁移',
        estimated_hours: 25,
      },
      {
        order: 2,
        repo_name: 'SAP BTP samples',
        repo_url: 'https://github.com/SAP-samples/btp-setup-automator',
        stars: '500+',
        what_to_learn: 'SAP BTP platform for cloud extensions — increasingly required in S/4HANA projects',
        what_to_learn_zh: 'SAP BTP云扩展平台——在S/4HANA项目中越来越重要',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'cloud-cap-samples',
        repo_url: 'https://github.com/SAP-samples/cloud-cap-samples',
        stars: '1.5k+',
        what_to_learn: 'SAP CAP framework for building side-by-side extensions on BTP',
        what_to_learn_zh: 'SAP CAP框架，用于在BTP上构建并行扩展',
        estimated_hours: 20,
      },
    ],
    capstone: {
      title: 'SAP S/4HANA Implementation Blueprint',
      title_zh: 'SAP S/4HANA实施蓝图',
      difficulty: 'advanced',
      time_hours: 60,
      deliverables: [
        'Fit-gap analysis document for a target industry (e.g., discrete manufacturing)',
        'SAP Activate project plan with Explore/Realize/Deploy phases',
        'Data migration strategy and cutover plan',
        'Custom ABAP report or Fiori app for a key business process',
        'Go-live readiness checklist and hypercare plan',
      ],
      deliverables_zh: [
        '目标行业（如离散制造）适配差距分析文档',
        '含探索/实现/部署阶段的SAP Activate项目计划',
        '数据迁移策略和切换计划',
        '关键业务流程的自定义ABAP报表或Fiori应用',
        '上线准备检查清单和超级关怀计划',
      ],
      proves_to_employer: 'Can plan and execute SAP S/4HANA implementations using SAP Activate methodology with hands-on technical skills',
      proves_to_employer_zh: '能使用SAP Activate方法论规划和执行S/4HANA实施，具备实际技术能力',
    },
    monetization_potential: 'premium',
  },
];
