import type { IndustryToolMapEntry } from './types';

export const electronicsEntries: IndustryToolMapEntry[] = [
  // 1. PCB Design
  {
    id: 'elec-pcb-design',
    skill: 'PCB Design',
    skill_zh: 'PCB设计',
    industry: 'electronics',
    industry_context: 'PCB design is the foundation of all electronic products. Every hardware team needs engineers who can take a schematic to a manufacturable board with signal integrity and DFM compliance.',
    industry_context_zh: 'PCB设计是所有电子产品的基础。每个硬件团队都需要能将原理图转化为具有信号完整性和DFM合规性的可制造电路板的工程师。',
    tools: [
      {
        name: 'Altium Designer',
        name_zh: 'Altium Designer PCB设计工具',
        vendor: 'Altium',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.altium.com/altium-designer',
        alternatives: ['KiCad (free)', 'OrCAD'],
      },
      {
        name: 'KiCad',
        name_zh: 'KiCad开源PCB设计工具',
        vendor: 'KiCad Community (CERN origin)',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Fully open-source (GPL), professional-grade PCB design tool',
        url: 'https://www.kicad.org/',
      },
      {
        name: 'Cadence OrCAD',
        name_zh: 'Cadence OrCAD原理图和PCB设计',
        vendor: 'Cadence Design Systems',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.orcad.com/',
      },
    ],
    training: [
      {
        name: 'Altium Academy',
        name_zh: 'Altium学院',
        region: 'global',
        url: 'https://www.altium.com/altium-academy',
        price_range: 'Free (video courses)',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'Fedevel Academy — Advanced PCB Layout',
        name_zh: 'Fedevel学院 — 高级PCB布局',
        region: 'global',
        url: 'https://fedevel.com/academy',
        price_range: '$50–$500',
        format: 'online',
        certification: 'Fedevel Certificate',
        language: ['en'],
      },
      {
        name: 'Würth Elektronik — PCB Design Seminars',
        name_zh: 'Würth Elektronik — PCB设计研讨会',
        region: 'DE',
        url: 'https://www.we-online.com/en/support/knowledge/seminars',
        price_range: 'Free–€200',
        format: 'hybrid',
        language: ['en', 'de'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'KiCad/kicad-source-mirror',
        repo_url: 'https://github.com/KiCad/kicad-source-mirror',
        stars: '2500+',
        what_to_learn: 'Understand KiCad internals and learn to create custom footprints, symbols, and plugins',
        what_to_learn_zh: '理解KiCad内部结构，学习创建自定义封装、符号和插件',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'openscopeproject/InteractiveHtmlBom',
        repo_url: 'https://github.com/openscopeproject/InteractiveHtmlBom',
        stars: '3500+',
        what_to_learn: 'Learn BOM management and interactive assembly documentation for PCB manufacturing',
        what_to_learn_zh: '学习BOM管理和PCB制造的交互式装配文档',
        estimated_hours: 8,
      },
      {
        order: 3,
        repo_name: 'INTI-CMNB/KiBot',
        repo_url: 'https://github.com/INTI-CMNB/KiBot',
        stars: '500+',
        what_to_learn: 'Automate KiCad output generation (Gerbers, BOM, 3D) — CI/CD for hardware design',
        what_to_learn_zh: '自动化KiCad输出生成（Gerber、BOM、3D）——硬件设计的CI/CD',
        estimated_hours: 10,
      },
    ],
    capstone: {
      title: '4-Layer STM32 Development Board in KiCad',
      title_zh: 'KiCad四层STM32开发板设计',
      difficulty: 'intermediate',
      time_hours: 40,
      deliverables: [
        'Complete schematic with STM32 MCU, power supply, USB, and debug interfaces',
        '4-layer PCB layout with proper impedance control and ground planes',
        'Manufacturing files: Gerbers, drill files, BOM, pick-and-place',
        'Design review checklist covering DFM, DFA, and signal integrity',
      ],
      deliverables_zh: [
        '包含STM32 MCU、电源、USB和调试接口的完整原理图',
        '具有正确阻抗控制和地平面的四层PCB布局',
        '制造文件：Gerber、钻孔文件、BOM、贴片坐标',
        '涵盖DFM、DFA和信号完整性的设计评审清单',
      ],
      proves_to_employer: 'Shows full PCB design cycle from schematic to manufacturing files — the exact deliverable hardware companies expect in interviews.',
      proves_to_employer_zh: '展示从原理图到制造文件的完整PCB设计周期——硬件公司面试中期望的核心交付物。',
    },
    monetization_potential: 'affiliate',
  },

  // 2. IC Design
  {
    id: 'elec-ic-design',
    skill: 'IC Design (VLSI)',
    skill_zh: '集成电路设计（VLSI）',
    industry: 'electronics',
    industry_context: 'IC design is the highest-value skill in electronics. With the global chip shortage and national semiconductor strategies (China, EU, US CHIPS Act), demand is at an all-time high.',
    industry_context_zh: '集成电路设计是电子行业最高价值的技能。随着全球芯片短缺和各国半导体战略（中国、欧盟、美国CHIPS法案），需求达到历史新高。',
    tools: [
      {
        name: 'Cadence Virtuoso',
        name_zh: 'Cadence Virtuoso模拟IC设计',
        vendor: 'Cadence Design Systems',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.cadence.com/en_US/home/tools/custom-ic-analog-rf-design/virtuoso-studio.html',
      },
      {
        name: 'Synopsys Design Compiler',
        name_zh: 'Synopsys Design Compiler综合工具',
        vendor: 'Synopsys',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.synopsys.com/implementation-and-signoff/rtl-synthesis-test/design-compiler-graphical.html',
      },
      {
        name: 'Yosys (Open-Source Synthesis)',
        name_zh: 'Yosys开源综合工具',
        vendor: 'YosysHQ',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Fully open-source RTL synthesis framework',
        url: 'https://yosyshq.net/yosys/',
      },
    ],
    training: [
      {
        name: 'Cadence University Program',
        name_zh: 'Cadence大学计划',
        region: 'global',
        url: 'https://www.cadence.com/en_US/home/company/cadence-academic-network.html',
        price_range: 'Free (for universities)',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'VLSI Expert — Online VLSI Training',
        name_zh: 'VLSI Expert — 在线VLSI培训',
        region: 'global',
        url: 'https://www.vlsiexpert.com/',
        price_range: '$100–$1,000',
        format: 'online',
        certification: 'VLSI Expert Certificate',
        language: ['en'],
      },
      {
        name: 'Coursera — VLSI CAD: Logic to Layout (UIUC)',
        name_zh: 'Coursera — VLSI CAD：从逻辑到版图（伊利诺伊大学）',
        region: 'global',
        url: 'https://www.coursera.org/learn/vlsi-cad-layout',
        price_range: '$0–$49/month',
        format: 'online',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'YosysHQ/yosys',
        repo_url: 'https://github.com/YosysHQ/yosys',
        stars: '3500+',
        what_to_learn: 'Learn RTL synthesis flow with open-source tools — write Verilog, synthesize, and analyze netlists',
        what_to_learn_zh: '用开源工具学习RTL综合流程——编写Verilog、综合并分析网表',
        estimated_hours: 25,
      },
      {
        order: 2,
        repo_name: 'The-OpenROAD-Project/OpenROAD',
        repo_url: 'https://github.com/The-OpenROAD-Project/OpenROAD',
        stars: '1500+',
        what_to_learn: 'Explore full RTL-to-GDS flow with open-source tools — floorplanning, placement, routing',
        what_to_learn_zh: '用开源工具探索完整RTL到GDS流程——布图规划、布局、布线',
        estimated_hours: 30,
      },
      {
        order: 3,
        repo_name: 'efabless/caravel',
        repo_url: 'https://github.com/efabless/caravel',
        stars: '600+',
        what_to_learn: 'Study a real tapeout-ready SoC design used in Google/Efabless open MPW shuttle program',
        what_to_learn_zh: '学习Google/Efabless开放MPW流片项目中的真实SoC设计',
        estimated_hours: 20,
      },
    ],
    capstone: {
      title: 'RISC-V Tiny Core RTL-to-GDS with OpenROAD',
      title_zh: '使用OpenROAD的RISC-V微核RTL到GDS',
      difficulty: 'advanced',
      time_hours: 60,
      deliverables: [
        'Simple RISC-V RV32I core in Verilog (or use PicoRV32)',
        'Synthesis with Yosys, place-and-route with OpenROAD',
        'GDS-II layout file ready for tapeout',
        'Timing analysis report and area/power summary',
      ],
      deliverables_zh: [
        'Verilog编写的简单RISC-V RV32I核（或使用PicoRV32）',
        '使用Yosys综合，使用OpenROAD布局布线',
        '可用于流片的GDS-II版图文件',
        '时序分析报告和面积/功耗摘要',
      ],
      proves_to_employer: 'Demonstrates full digital IC design flow from RTL to GDS — the exact workflow used at every semiconductor company. Open-source flow shows initiative.',
      proves_to_employer_zh: '展示从RTL到GDS的完整数字IC设计流程——每家半导体公司使用的标准工作流。使用开源流程体现主动性。',
    },
    monetization_potential: 'affiliate',
  },

  // 3. EMC Testing
  {
    id: 'elec-emc-testing',
    skill: 'EMC Testing & Design',
    skill_zh: 'EMC测试与设计',
    industry: 'electronics',
    industry_context: 'EMC compliance is legally required for all electronic products sold in EU (CE), US (FCC), and China (CCC). EMC engineers are scarce and highly valued.',
    industry_context_zh: 'EMC合规是所有在欧盟（CE）、美国（FCC）和中国（CCC）销售的电子产品的法定要求。EMC工程师稀缺且高度受重视。',
    tools: [
      {
        name: 'Rohde & Schwarz EMC Test Systems',
        name_zh: 'Rohde & Schwarz EMC测试系统',
        vendor: 'Rohde & Schwarz',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.rohde-schwarz.com/products/test-and-measurement/emc-test-systems_229650.html',
      },
      {
        name: 'Keysight EMI Receivers',
        name_zh: 'Keysight EMI接收机',
        vendor: 'Keysight Technologies',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.keysight.com/us/en/products/spectrum-analyzers-signal-analyzers/emi-receivers.html',
      },
      {
        name: 'CST Studio Suite',
        name_zh: 'CST Studio Suite电磁仿真',
        vendor: 'Dassault Systèmes',
        tier: 'recommended',
        free_tier: false,
        free_tier_note: 'Student license available through universities',
        url: 'https://www.3ds.com/products/simulia/cst-studio-suite',
      },
    ],
    training: [
      {
        name: 'Würth Elektronik — EMC Seminars',
        name_zh: 'Würth Elektronik — EMC研讨会',
        region: 'DE',
        url: 'https://www.we-online.com/en/support/knowledge/seminars',
        price_range: 'Free–€300',
        format: 'hybrid',
        language: ['en', 'de'],
      },
      {
        name: 'Rohde & Schwarz Academy — EMC Testing',
        name_zh: 'R&S学院 — EMC测试培训',
        region: 'global',
        url: 'https://www.rohde-schwarz.com/knowledge-center/webinars_230498.html',
        price_range: 'Free (webinars) / €500–€2,000 (workshops)',
        format: 'hybrid',
        language: ['en', 'de'],
      },
      {
        name: 'LearnEMC — Henry Ott Consultants',
        name_zh: 'LearnEMC — Henry Ott电磁兼容课程',
        region: 'global',
        url: 'https://learnemc.com/',
        price_range: '$500–$2,000',
        format: 'hybrid',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'openEMS/openEMS',
        repo_url: 'https://github.com/thliebig/openEMS',
        stars: '400+',
        what_to_learn: 'Learn FDTD electromagnetic simulation — model PCB traces, shielding, and antenna coupling',
        what_to_learn_zh: '学习FDTD电磁仿真——建模PCB走线、屏蔽和天线耦合',
        estimated_hours: 25,
      },
      {
        order: 2,
        repo_name: 'scikit-rf/scikit-rf',
        repo_url: 'https://github.com/scikit-rf/scikit-rf',
        stars: '900+',
        what_to_learn: 'RF/microwave engineering with Python — S-parameter analysis, impedance matching, network analysis',
        what_to_learn_zh: '用Python进行射频/微波工程——S参数分析、阻抗匹配、网络分析',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'KiCad/kicad-source-mirror',
        repo_url: 'https://github.com/KiCad/kicad-source-mirror',
        stars: '2500+',
        what_to_learn: 'Practice EMC-conscious PCB layout: ground planes, decoupling, trace routing for EMI reduction',
        what_to_learn_zh: '练习EMC导向的PCB布局：地平面、去耦、走线布线以减少EMI',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'EMC Pre-Compliance Test Setup and PCB Redesign',
      title_zh: 'EMC预合规测试搭建与PCB重新设计',
      difficulty: 'intermediate',
      time_hours: 35,
      deliverables: [
        'Pre-compliance measurement setup using near-field probes and spectrum analyzer',
        'EMC problem identification on an existing PCB design',
        'Redesigned PCB with EMC improvements (grounding, shielding, filtering)',
        'Before/after comparison report with measurement data',
      ],
      deliverables_zh: [
        '使用近场探头和频谱分析仪的预合规测量搭建',
        '对现有PCB设计的EMC问题识别',
        '包含EMC改进的重新设计PCB（接地、屏蔽、滤波）',
        '包含测量数据的改进前后对比报告',
      ],
      proves_to_employer: 'Shows practical EMC troubleshooting skills — finding emission sources and fixing them at the PCB level. This is what EMC labs and product companies need.',
      proves_to_employer_zh: '展示实际EMC排查能力——在PCB层面找到辐射源并解决。这是EMC实验室和产品公司的核心需求。',
    },
    monetization_potential: 'affiliate',
  },

  // 4. FPGA
  {
    id: 'elec-fpga',
    skill: 'FPGA Development',
    skill_zh: 'FPGA开发',
    industry: 'electronics',
    industry_context: 'FPGAs are used in telecom (5G), defense, data centers, and automotive. FPGA engineers command premium salaries due to the steep learning curve and persistent talent shortage.',
    industry_context_zh: 'FPGA应用于电信（5G）、国防、数据中心和汽车。由于学习曲线陡峭和人才持续短缺，FPGA工程师薪资溢价显著。',
    tools: [
      {
        name: 'AMD Vivado (Xilinx)',
        name_zh: 'AMD Vivado（Xilinx）FPGA开发工具',
        vendor: 'AMD (Xilinx)',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Vivado ML Standard Edition is free (supports most devices)',
        url: 'https://www.xilinx.com/products/design-tools/vivado.html',
      },
      {
        name: 'Intel Quartus Prime',
        name_zh: 'Intel Quartus Prime FPGA开发工具',
        vendor: 'Intel (Altera)',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Lite Edition is free (supports Cyclone/MAX devices)',
        url: 'https://www.intel.com/content/www/us/en/products/details/fpga/development-tools/quartus-prime.html',
      },
      {
        name: 'Lattice Diamond / Radiant',
        name_zh: 'Lattice Diamond/Radiant FPGA工具',
        vendor: 'Lattice Semiconductor',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free license for Lattice FPGAs',
        url: 'https://www.latticesemi.com/latticeradiant',
      },
    ],
    training: [
      {
        name: 'AMD/Xilinx — Training and Certification',
        name_zh: 'AMD/Xilinx — 培训与认证',
        region: 'global',
        url: 'https://www.xilinx.com/support/university.html',
        price_range: 'Free–$2,000',
        format: 'hybrid',
        certification: 'Xilinx Certified',
        language: ['en'],
      },
      {
        name: 'Digilent — FPGA Learning Resources',
        name_zh: 'Digilent — FPGA学习资源',
        region: 'global',
        url: 'https://digilent.com/reference/learn/programmable-logic/start',
        price_range: 'Free (tutorials) + $100–$400 (dev boards)',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'Nandland — FPGA Fundamentals (Free)',
        name_zh: 'Nandland — FPGA基础（免费）',
        region: 'global',
        url: 'https://nandland.com/',
        price_range: 'Free',
        format: 'online',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'Obijuan/open-fpga-verilog-tutorial',
        repo_url: 'https://github.com/Obijuan/open-fpga-verilog-tutorial',
        stars: '600+',
        what_to_learn: 'Start with open-source FPGA Verilog tutorials — LED blink to UART to simple CPU',
        what_to_learn_zh: '从开源FPGA Verilog教程入手——从LED闪烁到UART到简单CPU',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'ZipCPU/zipcpu',
        repo_url: 'https://github.com/ZipCPU/zipcpu',
        stars: '800+',
        what_to_learn: 'Study a complete soft CPU implementation on FPGA — understand bus architecture and peripherals',
        what_to_learn_zh: '学习完整的FPGA软核CPU实现——理解总线架构和外设',
        estimated_hours: 30,
      },
      {
        order: 3,
        repo_name: 'hdl/awesome',
        repo_url: 'https://github.com/hdl/awesome',
        stars: '2500+',
        what_to_learn: 'Curated list of open-source HDL projects — find IP cores, verification tools, and design examples',
        what_to_learn_zh: '开源HDL项目精选列表——查找IP核、验证工具和设计示例',
        estimated_hours: 10,
      },
    ],
    capstone: {
      title: 'UART + SPI Peripheral Controller on FPGA',
      title_zh: 'FPGA上的UART + SPI外设控制器',
      difficulty: 'intermediate',
      time_hours: 40,
      deliverables: [
        'Verilog/VHDL UART transmitter and receiver with configurable baud rate',
        'SPI master controller for interfacing with sensors',
        'Top-level design integrating both peripherals on a Xilinx or Intel FPGA board',
        'Testbench with simulation waveforms and FPGA resource utilization report',
      ],
      deliverables_zh: [
        '可配置波特率的Verilog/VHDL UART发送器和接收器',
        '用于传感器接口的SPI主控制器',
        '在Xilinx或Intel FPGA板上集成两个外设的顶层设计',
        '包含仿真波形和FPGA资源利用率报告的测试平台',
      ],
      proves_to_employer: 'Demonstrates practical RTL design, simulation, and FPGA implementation skills — the core competency for any FPGA engineer role.',
      proves_to_employer_zh: '展示实际的RTL设计、仿真和FPGA实现能力——任何FPGA工程师岗位的核心能力。',
    },
    monetization_potential: 'none',
  },

  // 5. Embedded C/C++ (Electronics)
  {
    id: 'elec-embedded-c',
    skill: 'Embedded C/C++',
    skill_zh: '嵌入式C/C++开发',
    industry: 'electronics',
    industry_context: 'Embedded C/C++ is the bread-and-butter of electronics product development. From consumer gadgets to industrial controllers, firmware engineers are always in demand.',
    industry_context_zh: '嵌入式C/C++是电子产品开发的基础技能。从消费电子到工业控制器，固件工程师始终供不应求。',
    tools: [
      {
        name: 'STM32CubeIDE',
        name_zh: 'STM32CubeIDE集成开发环境',
        vendor: 'STMicroelectronics',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Completely free — Eclipse-based IDE with HAL/LL drivers and code generator',
        url: 'https://www.st.com/en/development-tools/stm32cubeide.html',
      },
      {
        name: 'Keil MDK (ARM)',
        name_zh: 'Keil MDK ARM开发工具',
        vendor: 'ARM (Keil)',
        tier: 'essential',
        free_tier: false,
        free_tier_note: 'Community edition free for up to 32KB code',
        url: 'https://www.keil.com/mdk5',
      },
      {
        name: 'IAR Embedded Workbench',
        name_zh: 'IAR嵌入式工作台',
        vendor: 'IAR Systems',
        tier: 'recommended',
        free_tier: false,
        free_tier_note: 'Size-limited evaluation available',
        url: 'https://www.iar.com/ewarm',
      },
    ],
    training: [
      {
        name: 'Udemy — Mastering Microcontroller with Embedded Driver Development',
        name_zh: 'Udemy — 嵌入式驱动开发掌握微控制器',
        region: 'global',
        url: 'https://www.udemy.com/course/mastering-microcontroller-with-peripheral-driver-development/',
        price_range: '$15–$100',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'FastBit Embedded Brain Academy',
        name_zh: 'FastBit嵌入式学院',
        region: 'global',
        url: 'https://fastbitlab.com/',
        price_range: '$15–$200',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'STMicroelectronics — STM32 Online Training',
        name_zh: 'ST官方 — STM32在线培训',
        region: 'global',
        url: 'https://www.st.com/content/st_com/en/support/learning/stm32-education.html',
        price_range: 'Free',
        format: 'online',
        language: ['en', 'zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'cpq/bare-metal-programming-guide',
        repo_url: 'https://github.com/cpq/bare-metal-programming-guide',
        stars: '3000+',
        what_to_learn: 'Learn bare-metal ARM programming from scratch — registers, linker scripts, startup code',
        what_to_learn_zh: '从零学习ARM裸机编程——寄存器、链接脚本、启动代码',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'STMicroelectronics/STM32CubeF4',
        repo_url: 'https://github.com/STMicroelectronics/STM32CubeF4',
        stars: '800+',
        what_to_learn: 'Study STM32 HAL drivers and example projects — GPIO, UART, SPI, I2C, ADC, DMA',
        what_to_learn_zh: '学习STM32 HAL驱动和示例项目——GPIO、UART、SPI、I2C、ADC、DMA',
        estimated_hours: 25,
      },
      {
        order: 3,
        repo_name: 'zephyrproject-rtos/zephyr',
        repo_url: 'https://github.com/zephyrproject-rtos/zephyr',
        stars: '11000+',
        what_to_learn: 'Explore Zephyr RTOS — industry-standard RTOS for modern embedded development',
        what_to_learn_zh: '探索Zephyr RTOS——现代嵌入式开发的行业标准实时操作系统',
        estimated_hours: 30,
      },
    ],
    capstone: {
      title: 'IoT Sensor Node with STM32 + FreeRTOS',
      title_zh: 'STM32 + FreeRTOS物联网传感器节点',
      difficulty: 'intermediate',
      time_hours: 40,
      deliverables: [
        'STM32 firmware with FreeRTOS multitasking (sensor read, data process, communication)',
        'I2C/SPI sensor driver (temperature, humidity, or IMU)',
        'UART or BLE communication for data transmission',
        'Low-power mode implementation with wake-on-event',
      ],
      deliverables_zh: [
        'STM32固件，使用FreeRTOS多任务（传感器读取、数据处理、通信）',
        'I2C/SPI传感器驱动（温湿度或IMU）',
        'UART或BLE通信用于数据传输',
        '事件唤醒的低功耗模式实现',
      ],
      proves_to_employer: 'Demonstrates RTOS multitasking, peripheral driver development, and low-power design — the three pillars of embedded engineering interviews.',
      proves_to_employer_zh: '展示RTOS多任务、外设驱动开发和低功耗设计——嵌入式工程面试的三大核心。',
    },
    monetization_potential: 'affiliate',
  },

  // 6. Power Electronics
  {
    id: 'elec-power-electronics',
    skill: 'Power Electronics',
    skill_zh: '电力电子',
    industry: 'electronics',
    industry_context: 'Power electronics is critical for EV chargers, solar inverters, UPS, motor drives, and power supplies. The energy transition has made this a high-demand, high-salary field.',
    industry_context_zh: '电力电子对电动汽车充电器、太阳能逆变器、UPS、电机驱动和电源至关重要。能源转型使其成为高需求、高薪酬领域。',
    tools: [
      {
        name: 'LTspice',
        name_zh: 'LTspice电路仿真工具',
        vendor: 'Analog Devices',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Completely free — industry-standard SPICE simulator',
        url: 'https://www.analog.com/en/resources/design-tools-and-calculators/ltspice-simulator.html',
      },
      {
        name: 'PSIM',
        name_zh: 'PSIM电力电子仿真',
        vendor: 'Powersim',
        tier: 'recommended',
        free_tier: false,
        free_tier_note: 'Demo version available with limited features',
        url: 'https://powersimtech.com/',
      },
      {
        name: 'PLECS',
        name_zh: 'PLECS电力电子仿真',
        vendor: 'Plexim',
        tier: 'recommended',
        free_tier: false,
        free_tier_note: 'PLECS Standalone viewer is free',
        url: 'https://www.plexim.com/products/plecs',
      },
    ],
    training: [
      {
        name: 'Coursera — Introduction to Power Electronics (CU Boulder)',
        name_zh: 'Coursera — 电力电子导论（科罗拉多大学）',
        region: 'global',
        url: 'https://www.coursera.org/learn/power-electronics',
        price_range: '$0–$49/month',
        format: 'online',
        certification: 'Coursera Certificate',
        language: ['en'],
      },
      {
        name: 'Texas Instruments — Power Management Training',
        name_zh: 'TI — 电源管理培训',
        region: 'global',
        url: 'https://training.ti.com/power-management',
        price_range: 'Free',
        format: 'online',
        language: ['en', 'zh'],
      },
      {
        name: 'Infineon — Power Electronics Training',
        name_zh: 'Infineon — 电力电子培训',
        region: 'EU',
        url: 'https://www.infineon.com/cms/en/tools/landing/infineontechnicaltraining/',
        price_range: 'Free (webinars)',
        format: 'online',
        language: ['en', 'de'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'PySpice-org/PySpice',
        repo_url: 'https://github.com/PySpice-org/PySpice',
        stars: '700+',
        what_to_learn: 'Run SPICE simulations from Python — script buck/boost converter analysis and parameter sweeps',
        what_to_learn_zh: '用Python运行SPICE仿真——脚本化Buck/Boost变换器分析和参数扫描',
        estimated_hours: 15,
      },
      {
        order: 2,
        repo_name: 'pybamm-team/PyBaMM',
        repo_url: 'https://github.com/pybamm-team/PyBaMM',
        stars: '1000+',
        what_to_learn: 'Understand battery models that interface with power electronics in EV charging and BMS',
        what_to_learn_zh: '理解在电动汽车充电和BMS中与电力电子对接的电池模型',
        estimated_hours: 20,
      },
      {
        order: 3,
        repo_name: 'SciML/ModelingToolkit.jl',
        repo_url: 'https://github.com/SciML/ModelingToolkit.jl',
        stars: '1400+',
        what_to_learn: 'Build physics-based power converter models — applicable to switched-mode power supply design',
        what_to_learn_zh: '构建基于物理的功率变换器模型——适用于开关电源设计',
        estimated_hours: 20,
      },
    ],
    capstone: {
      title: 'Buck Converter Design: Simulation to PCB',
      title_zh: 'Buck变换器设计：从仿真到PCB',
      difficulty: 'intermediate',
      time_hours: 35,
      deliverables: [
        'LTspice simulation of synchronous buck converter (12V→3.3V, 3A)',
        'Component selection with thermal analysis',
        'PCB layout in KiCad with proper power loop optimization',
        'Efficiency analysis across load range (light load to full load)',
      ],
      deliverables_zh: [
        '同步Buck变换器的LTspice仿真（12V→3.3V，3A）',
        '包含热分析的元件选型',
        '在KiCad中进行PCB布局并优化功率回路',
        '负载范围（轻载到满载）的效率分析',
      ],
      proves_to_employer: 'Shows end-to-end power supply design skills — simulation, component selection, and PCB layout. Every electronics company needs power supply engineers.',
      proves_to_employer_zh: '展示端到端电源设计能力——仿真、选型和PCB布局。每家电子公司都需要电源工程师。',
    },
    monetization_potential: 'none',
  },

  // 7. RF Design
  {
    id: 'elec-rf-design',
    skill: 'RF/Microwave Design',
    skill_zh: 'RF/微波设计',
    industry: 'electronics',
    industry_context: 'RF design is essential for 5G, WiFi, Bluetooth, radar, and satellite communication. With 5G deployment and IoT expansion, RF engineers are in high demand globally.',
    industry_context_zh: 'RF设计对5G、WiFi、蓝牙、雷达和卫星通信至关重要。随着5G部署和IoT扩展，RF工程师在全球需求旺盛。',
    tools: [
      {
        name: 'Keysight ADS (Advanced Design System)',
        name_zh: 'Keysight ADS高级设计系统',
        vendor: 'Keysight Technologies',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.keysight.com/us/en/products/software/pathwave-design-software/pathwave-advanced-design-system.html',
      },
      {
        name: 'CST Studio Suite',
        name_zh: 'CST Studio Suite 3D电磁仿真',
        vendor: 'Dassault Systèmes',
        tier: 'essential',
        free_tier: false,
        free_tier_note: 'Student license through university programs',
        url: 'https://www.3ds.com/products/simulia/cst-studio-suite',
      },
      {
        name: 'ANSYS HFSS',
        name_zh: 'ANSYS HFSS高频结构仿真',
        vendor: 'Ansys',
        tier: 'recommended',
        free_tier: false,
        free_tier_note: 'Free student version available',
        url: 'https://www.ansys.com/products/electronics/ansys-hfss',
      },
    ],
    training: [
      {
        name: 'Keysight University — RF/Microwave Design',
        name_zh: 'Keysight大学 — RF/微波设计',
        region: 'global',
        url: 'https://www.keysight.com/us/en/support/key-education.html',
        price_range: 'Free–$2,000',
        format: 'hybrid',
        language: ['en'],
      },
      {
        name: 'Coursera — Introduction to Wireless Communications (Yonsei)',
        name_zh: 'Coursera — 无线通信导论（延世大学）',
        region: 'global',
        url: 'https://www.coursera.org/learn/wireless-communications',
        price_range: '$0–$49/month',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'Rohde & Schwarz — RF Measurement Webinars',
        name_zh: 'R&S — RF测量网络研讨会',
        region: 'global',
        url: 'https://www.rohde-schwarz.com/knowledge-center/webinars_230498.html',
        price_range: 'Free',
        format: 'online',
        language: ['en', 'de'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'scikit-rf/scikit-rf',
        repo_url: 'https://github.com/scikit-rf/scikit-rf',
        stars: '900+',
        what_to_learn: 'Learn RF network analysis in Python — S-parameters, Smith charts, impedance matching',
        what_to_learn_zh: '用Python学习RF网络分析——S参数、Smith圆图、阻抗匹配',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'gnuradio/gnuradio',
        repo_url: 'https://github.com/gnuradio/gnuradio',
        stars: '5500+',
        what_to_learn: 'Explore software-defined radio — signal processing, modulation/demodulation, spectrum analysis',
        what_to_learn_zh: '探索软件定义无线电——信号处理、调制解调、频谱分析',
        estimated_hours: 30,
      },
      {
        order: 3,
        repo_name: 'thliebig/openEMS',
        repo_url: 'https://github.com/thliebig/openEMS',
        stars: '400+',
        what_to_learn: 'Design and simulate antennas and RF structures using open-source FDTD solver',
        what_to_learn_zh: '使用开源FDTD求解器设计和仿真天线及RF结构',
        estimated_hours: 20,
      },
    ],
    capstone: {
      title: '2.4 GHz Patch Antenna Design and Simulation',
      title_zh: '2.4 GHz贴片天线设计与仿真',
      difficulty: 'intermediate',
      time_hours: 30,
      deliverables: [
        'Patch antenna design for 2.4 GHz ISM band (WiFi/Bluetooth)',
        'Full-wave 3D electromagnetic simulation (openEMS or HFSS)',
        'Radiation pattern, gain, S11 return loss analysis',
        'PCB integration guidelines with ground plane considerations',
      ],
      deliverables_zh: [
        '2.4 GHz ISM频段（WiFi/蓝牙）贴片天线设计',
        '全波3D电磁仿真（openEMS或HFSS）',
        '方向图、增益、S11回波损耗分析',
        '考虑地平面的PCB集成指南',
      ],
      proves_to_employer: 'Shows antenna design and EM simulation skills — directly applicable to any IoT, wireless, or telecom hardware role.',
      proves_to_employer_zh: '展示天线设计和电磁仿真能力——直接适用于任何IoT、无线或电信硬件岗位。',
    },
    monetization_potential: 'affiliate',
  },

  // 8. Semiconductor Process
  {
    id: 'elec-semiconductor-process',
    skill: 'Semiconductor Process Engineering',
    skill_zh: '半导体工艺工程',
    industry: 'electronics',
    industry_context: 'Semiconductor fabs are being built worldwide (TSMC Arizona, Intel Ohio, Samsung Texas, EU Chips Act fabs). Process engineers are critical and extremely well-compensated.',
    industry_context_zh: '半导体晶圆厂在全球兴建（台积电亚利桑那、英特尔俄亥俄、三星德克萨斯、欧盟芯片法案工厂）。工艺工程师至关重要且薪酬极高。',
    tools: [
      {
        name: 'Silvaco TCAD',
        name_zh: 'Silvaco TCAD工艺和器件仿真',
        vendor: 'Silvaco',
        tier: 'essential',
        free_tier: false,
        url: 'https://silvaco.com/tcad/',
      },
      {
        name: 'Synopsys Sentaurus TCAD',
        name_zh: 'Synopsys Sentaurus TCAD仿真',
        vendor: 'Synopsys',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.synopsys.com/manufacturing/tcad.html',
      },
      {
        name: 'COMSOL Semiconductor Module',
        name_zh: 'COMSOL半导体模块',
        vendor: 'COMSOL',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.comsol.com/semiconductor-module',
      },
    ],
    training: [
      {
        name: 'Applied Materials — Online Learning',
        name_zh: 'Applied Materials — 在线学习',
        region: 'global',
        url: 'https://www.appliedmaterials.com/',
        price_range: 'Internal/partner training',
        format: 'hybrid',
        language: ['en'],
      },
      {
        name: 'Coursera — Nanotechnology and Nanosensors (Technion)',
        name_zh: 'Coursera — 纳米技术与纳米传感器（以色列理工）',
        region: 'global',
        url: 'https://www.coursera.org/learn/nanotechnology',
        price_range: '$0–$49/month',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'edX — Semiconductor Physics (Purdue)',
        name_zh: 'edX — 半导体物理（普渡大学）',
        region: 'global',
        url: 'https://www.edx.org/learn/semiconductors',
        price_range: '$0–$150',
        format: 'online',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'devsim/devsim',
        repo_url: 'https://github.com/devsim/devsim',
        stars: '200+',
        what_to_learn: 'Learn semiconductor device simulation — MOSFET, diode, and solar cell modeling',
        what_to_learn_zh: '学习半导体器件仿真——MOSFET、二极管和太阳能电池建模',
        estimated_hours: 25,
      },
      {
        order: 2,
        repo_name: 'gdsfactory/gdsfactory',
        repo_url: 'https://github.com/gdsfactory/gdsfactory',
        stars: '800+',
        what_to_learn: 'Create photonic and semiconductor layouts programmatically in Python — GDS generation',
        what_to_learn_zh: '用Python程序化创建光子和半导体版图——GDS生成',
        estimated_hours: 20,
      },
      {
        order: 3,
        repo_name: 'klayout/klayout',
        repo_url: 'https://github.com/KLayout/klayout',
        stars: '1800+',
        what_to_learn: 'Master open-source layout viewer/editor for GDS-II — used in many semiconductor companies',
        what_to_learn_zh: '掌握开源GDS-II版图查看器/编辑器——在许多半导体公司使用',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'MOSFET Process Simulation and Electrical Characterization',
      title_zh: 'MOSFET工艺仿真与电学特性分析',
      difficulty: 'advanced',
      time_hours: 45,
      deliverables: [
        'TCAD process simulation of a simple NMOS transistor (oxidation, implant, etch)',
        'Device simulation extracting Vth, Id-Vg, Id-Vd characteristics',
        'Parameter sensitivity analysis (doping, oxide thickness, channel length)',
        'Comparison with published MOSFET data from foundry PDKs',
      ],
      deliverables_zh: [
        '简单NMOS晶体管的TCAD工艺仿真（氧化、注入、刻蚀）',
        '提取Vth、Id-Vg、Id-Vd特性的器件仿真',
        '参数灵敏度分析（掺杂、氧化层厚度、沟道长度）',
        '与代工厂PDK发布的MOSFET数据对比',
      ],
      proves_to_employer: 'Shows understanding of semiconductor physics and process-device interaction — the foundation knowledge every fab and design house requires.',
      proves_to_employer_zh: '展示对半导体物理和工艺-器件交互的理解——每家晶圆厂和设计公司要求的基础知识。',
    },
    monetization_potential: 'affiliate',
  },

  // 9. Sensor Technology
  {
    id: 'elec-sensor-technology',
    skill: 'Sensor Technology & Interfacing',
    skill_zh: '传感器技术与接口',
    industry: 'electronics',
    industry_context: 'Sensors are the eyes and ears of every IoT, automotive, industrial, and medical device. Engineers who can select, interface, and calibrate sensors are essential for product development.',
    industry_context_zh: '传感器是每个IoT、汽车、工业和医疗设备的眼睛和耳朵。能选型、接口和校准传感器的工程师对产品开发至关重要。',
    tools: [
      {
        name: 'COMSOL Multiphysics',
        name_zh: 'COMSOL多物理场仿真',
        vendor: 'COMSOL',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.comsol.com/',
      },
      {
        name: 'NI LabVIEW',
        name_zh: 'NI LabVIEW图形化编程',
        vendor: 'National Instruments',
        tier: 'essential',
        free_tier: false,
        free_tier_note: 'Community edition available for non-commercial use',
        url: 'https://www.ni.com/en/shop/labview.html',
      },
      {
        name: 'Arduino IDE + PlatformIO',
        name_zh: 'Arduino IDE + PlatformIO开发环境',
        vendor: 'Arduino / PlatformIO',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Both fully free and open-source',
        url: 'https://platformio.org/',
      },
    ],
    training: [
      {
        name: 'NI Learning — Data Acquisition and Sensors',
        name_zh: 'NI学习中心 — 数据采集与传感器',
        region: 'global',
        url: 'https://learn.ni.com/',
        price_range: '$0–$2,000',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'Coursera — An Introduction to Programming the IoT (UC Irvine)',
        name_zh: 'Coursera — IoT编程入门（加州大学尔湾分校）',
        region: 'global',
        url: 'https://www.coursera.org/specializations/iot',
        price_range: '$0–$49/month',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'Bosch Sensortec — Sensor Academy',
        name_zh: 'Bosch Sensortec — 传感器学院',
        region: 'global',
        url: 'https://www.bosch-sensortec.com/software-tools/tools/',
        price_range: 'Free',
        format: 'online',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'adafruit/Adafruit_CircuitPython_Bundle',
        repo_url: 'https://github.com/adafruit/Adafruit_CircuitPython_Bundle',
        stars: '1000+',
        what_to_learn: 'Learn sensor interfacing through Adafruit driver library — I2C, SPI, analog sensors',
        what_to_learn_zh: '通过Adafruit驱动库学习传感器接口——I2C、SPI、模拟传感器',
        estimated_hours: 15,
      },
      {
        order: 2,
        repo_name: 'micropython/micropython',
        repo_url: 'https://github.com/micropython/micropython',
        stars: '19000+',
        what_to_learn: 'Rapid sensor prototyping with MicroPython — ADC, I2C, SPI drivers on real hardware',
        what_to_learn_zh: '使用MicroPython快速传感器原型开发——在真实硬件上的ADC、I2C、SPI驱动',
        estimated_hours: 20,
      },
      {
        order: 3,
        repo_name: 'jrowberg/i2cdevlib',
        repo_url: 'https://github.com/jrowberg/i2cdevlib',
        stars: '3900+',
        what_to_learn: 'Study I2C sensor driver implementations for dozens of popular sensors (MPU6050, BMP180, etc.)',
        what_to_learn_zh: '学习数十种常用传感器的I2C驱动实现（MPU6050、BMP180等）',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'Multi-Sensor Data Logger with Calibration',
      title_zh: '多传感器数据采集器（含校准）',
      difficulty: 'beginner',
      time_hours: 25,
      deliverables: [
        'MCU-based data logger reading temperature, humidity, accelerometer, and light sensors',
        'Sensor calibration routines with documented methodology',
        'SD card data logging with timestamped CSV output',
        'Python visualization script for logged data analysis',
      ],
      deliverables_zh: [
        '基于MCU的数据采集器，读取温湿度、加速度计和光传感器',
        '传感器校准程序及文档化方法',
        'SD卡数据记录，带时间戳的CSV输出',
        '用于记录数据分析的Python可视化脚本',
      ],
      proves_to_employer: 'Shows ability to interface multiple sensors, implement calibration, and handle data — the core skills for any IoT or instrumentation role.',
      proves_to_employer_zh: '展示多传感器接口、校准实现和数据处理能力——任何IoT或仪器仪表岗位的核心技能。',
    },
    monetization_potential: 'none',
  },

  // 10. EDA Tools (General)
  {
    id: 'elec-eda-tools',
    skill: 'EDA Tools & Design Flow',
    skill_zh: 'EDA工具与设计流程',
    industry: 'electronics',
    industry_context: 'EDA (Electronic Design Automation) tools form the backbone of all chip and board design. Understanding the full design flow — from RTL to GDS or schematic to Gerber — is a meta-skill that multiplies all other electronics skills.',
    industry_context_zh: 'EDA（电子设计自动化）工具是所有芯片和电路板设计的基础。理解从RTL到GDS或从原理图到Gerber的完整设计流程是一项元技能，能倍增所有其他电子技能。',
    tools: [
      {
        name: 'Cadence Design Suite',
        name_zh: 'Cadence设计套件',
        vendor: 'Cadence Design Systems',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.cadence.com/',
        alternatives: ['Synopsys', 'Siemens EDA (Mentor)'],
      },
      {
        name: 'Synopsys Design Suite',
        name_zh: 'Synopsys设计套件',
        vendor: 'Synopsys',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.synopsys.com/',
      },
      {
        name: 'Siemens EDA (Mentor Graphics)',
        name_zh: 'Siemens EDA（Mentor Graphics）',
        vendor: 'Siemens',
        tier: 'essential',
        free_tier: false,
        url: 'https://eda.sw.siemens.com/',
      },
    ],
    training: [
      {
        name: 'Cadence University Program',
        name_zh: 'Cadence大学计划',
        region: 'global',
        url: 'https://www.cadence.com/en_US/home/company/cadence-academic-network.html',
        price_range: 'Free (for universities)',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'Siemens EDA — Learning Center',
        name_zh: 'Siemens EDA — 学习中心',
        region: 'global',
        url: 'https://eda.sw.siemens.com/en-US/training/',
        price_range: '$500–$3,000',
        format: 'hybrid',
        language: ['en'],
      },
      {
        name: 'edX — Circuits and Electronics (MIT)',
        name_zh: 'edX — 电路与电子（MIT）',
        region: 'global',
        url: 'https://www.edx.org/learn/circuits/massachusetts-institute-of-technology-circuits-and-electronics-1-basic-circuit-analysis',
        price_range: '$0–$150',
        format: 'online',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'The-OpenROAD-Project/OpenROAD',
        repo_url: 'https://github.com/The-OpenROAD-Project/OpenROAD',
        stars: '1500+',
        what_to_learn: 'Experience a complete open-source RTL-to-GDS digital design flow',
        what_to_learn_zh: '体验完整的开源RTL到GDS数字设计流程',
        estimated_hours: 25,
      },
      {
        order: 2,
        repo_name: 'YosysHQ/oss-cad-suite-build',
        repo_url: 'https://github.com/YosysHQ/oss-cad-suite-build',
        stars: '700+',
        what_to_learn: 'Set up complete open-source EDA toolchain: synthesis, place-and-route, simulation, formal verification',
        what_to_learn_zh: '搭建完整的开源EDA工具链：综合、布局布线、仿真、形式化验证',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'google/skywater-pdk',
        repo_url: 'https://github.com/google/skywater-pdk',
        stars: '2400+',
        what_to_learn: 'Study Google/SkyWater open-source 130nm PDK — understand process design kits used in real tapeouts',
        what_to_learn_zh: '学习Google/SkyWater开源130nm PDK——理解真实流片使用的工艺设计套件',
        estimated_hours: 20,
      },
    ],
    capstone: {
      title: 'Open-Source EDA Flow: Verilog to GDS with SkyWater PDK',
      title_zh: '开源EDA流程：使用SkyWater PDK从Verilog到GDS',
      difficulty: 'advanced',
      time_hours: 50,
      deliverables: [
        'Simple digital design (e.g., ALU or timer) in Verilog',
        'Full flow: Yosys synthesis → OpenROAD PnR → KLayout GDS viewing',
        'Timing closure report with setup/hold analysis',
        'Documentation of the complete flow for reproducibility',
      ],
      deliverables_zh: [
        '用Verilog编写简单数字设计（如ALU或定时器）',
        '完整流程：Yosys综合 → OpenROAD布局布线 → KLayout GDS查看',
        '包含建立/保持分析的时序收敛报告',
        '完整流程文档以确保可重复性',
      ],
      proves_to_employer: 'Shows mastery of the full digital design flow using industry-relevant tools. Semiconductor companies value engineers who understand the entire flow, not just one step.',
      proves_to_employer_zh: '展示使用行业相关工具的完整数字设计流程掌握。半导体公司重视理解整个流程而非仅某一步的工程师。',
    },
    monetization_potential: 'affiliate',
  },
];
