import type { IndustryToolMapEntry } from './types';

export const energyEquipmentEntries: IndustryToolMapEntry[] = [
  // ── 1. Wind Engineering ───────────────────────────────────────────────
  {
    id: 'energy-wind',
    skill: 'Wind Engineering',
    skill_zh: '风力发电工程',
    industry: 'energy-equipment',
    industry_context: 'Wind energy is the fastest-growing renewable sector. Engineers use Bladed for turbine design and WindPRO for site assessment and energy yield prediction.',
    industry_context_zh: '风力发电是增长最快的可再生能源领域。工程师使用Bladed进行风机设计，WindPRO进行风场评估和发电量预测。',
    tools: [
      {
        name: 'DNV Bladed',
        name_zh: 'DNV Bladed风机设计',
        vendor: 'DNV',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.dnv.com/services/wind-turbine-design-software-bladed/',
        alternatives: ['QBlade', 'OpenFAST (NREL)', 'Flex5'],
      },
      {
        name: 'WindPRO',
        name_zh: 'WindPRO风场规划',
        vendor: 'EMD International',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free demo version with limited features',
        url: 'https://www.emd.dk/windpro/',
        alternatives: ['WAsP (DTU)', 'Openwind'],
      },
      {
        name: 'OpenFAST',
        name_zh: 'OpenFAST开源风机仿真',
        vendor: 'NREL (US DOE)',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Fully open-source, Apache 2.0 — NREL reference tool',
        url: 'https://www.nrel.gov/wind/nwtc/openfast.html',
      },
      {
        name: 'QBlade',
        name_zh: 'QBlade',
        vendor: 'TU Berlin / QBlade.org',
        tier: 'emerging',
        free_tier: true,
        free_tier_note: 'Community Edition free; Enterprise version paid',
        url: 'https://qblade.org/',
      },
    ],
    training: [
      {
        name: 'DTU Wind Energy — Online Courses',
        name_zh: 'DTU丹麦科技大学风能课程',
        region: 'EU',
        url: 'https://www.coursera.org/learn/wind-energy',
        price_range: 'Free (audit)',
        format: 'online',
        certification: 'Coursera Certificate',
        language: ['en'],
      },
      {
        name: 'DNV Training — Wind Turbine Technology',
        name_zh: 'DNV风电技术培训',
        region: 'EU',
        url: 'https://www.dnv.com/training/',
        price_range: '€1500-4000',
        format: 'hybrid',
        certification: 'DNV Wind Certification',
        language: ['en', 'de'],
      },
      {
        name: '金风科技学院',
        name_zh: '金风科技学院',
        region: 'CN',
        url: 'https://www.goldwind.com/',
        price_range: '¥2000-8000',
        format: 'hybrid',
        language: ['zh'],
      },
      {
        name: 'ForWind Academy (Uni Oldenburg)',
        name_zh: 'ForWind学院（奥尔登堡大学）',
        region: 'DE',
        url: 'https://www.forwind.de/',
        price_range: '€500-2000',
        format: 'hybrid',
        language: ['de', 'en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'OpenFAST',
        repo_url: 'https://github.com/OpenFAST/openfast',
        stars: '700+',
        what_to_learn: 'Wind turbine aeroelastic simulation: blade aerodynamics, structural dynamics, controller design',
        what_to_learn_zh: '风机气弹仿真：叶片气动力学、结构动力学、控制器设计',
        estimated_hours: 30,
      },
      {
        order: 2,
        repo_name: 'WISDEM — Wind Plant System Design',
        repo_url: 'https://github.com/WISDEM/WISDEM',
        stars: '200+',
        what_to_learn: 'Systems engineering for wind turbines: cost modeling, optimization, plant layout',
        what_to_learn_zh: '风机系统工程：成本建模、优化、风场布局',
        estimated_hours: 20,
      },
      {
        order: 3,
        repo_name: 'FLORIS — Wind Farm Wake Modeling',
        repo_url: 'https://github.com/NREL/floris',
        stars: '200+',
        what_to_learn: 'Wake modeling and farm optimization: maximize energy yield through turbine placement and yaw control',
        what_to_learn_zh: '尾流建模和风场优化：通过风机布置和偏航控制最大化发电量',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'Wind Farm Layout Optimization with Wake Modeling',
      title_zh: '基于尾流模型的风场布局优化',
      difficulty: 'advanced',
      time_hours: 50,
      deliverables: [
        'FLORIS-based wind farm simulation with 10+ turbines',
        'Layout optimization algorithm (genetic/particle swarm) maximizing AEP',
        'Wake loss analysis report with visualization',
        'Economic analysis: LCOE comparison of optimized vs baseline layout',
      ],
      deliverables_zh: [
        '基于FLORIS的10+台风机风场仿真',
        '布局优化算法（遗传/粒子群）最大化年发电量',
        '尾流损失分析报告含可视化',
        '经济性分析：优化布局与基线布局的度电成本对比',
      ],
      proves_to_employer: 'Can model wind farm aerodynamics and optimize turbine placement for maximum energy yield',
      proves_to_employer_zh: '能够建模风场气动特性并优化风机布置以最大化发电量',
    },
    monetization_potential: 'affiliate',
  },

  // ── 2. Solar / PV Engineering ─────────────────────────────────────────
  {
    id: 'energy-solar',
    skill: 'Solar / PV Engineering',
    skill_zh: '光伏发电工程',
    industry: 'energy-equipment',
    industry_context: 'Solar PV is the cheapest new electricity source globally. PVsyst is the industry standard for system design and bankable yield simulations; SAM (NREL) is the free alternative.',
    industry_context_zh: '光伏是全球最便宜的新建电力来源。PVsyst是系统设计和可融资发电量仿真的行业标准；SAM（NREL）是免费替代方案。',
    tools: [
      {
        name: 'PVsyst',
        name_zh: 'PVsyst光伏仿真',
        vendor: 'PVsyst SA',
        tier: 'essential',
        free_tier: true,
        free_tier_note: '30-day trial with full features; limited demo mode afterward',
        url: 'https://www.pvsyst.com/',
        alternatives: ['SAM (NREL)', 'PV*SOL', 'Helioscope'],
      },
      {
        name: 'System Advisor Model (SAM)',
        name_zh: 'SAM系统顾问模型',
        vendor: 'NREL (US DOE)',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Fully free, open-source — NREL reference tool',
        url: 'https://sam.nrel.gov/',
      },
      {
        name: 'Helioscope',
        name_zh: 'Helioscope在线设计',
        vendor: 'Aurora Solar',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free tier for small projects',
        url: 'https://helioscope.aurorasolar.com/',
      },
    ],
    training: [
      {
        name: 'PVsyst Official Training',
        name_zh: 'PVsyst官方培训',
        region: 'EU',
        url: 'https://www.pvsyst.com/training/',
        price_range: '€800-1500',
        format: 'hybrid',
        certification: 'PVsyst Certified Designer',
        language: ['en'],
      },
      {
        name: 'edX — Solar Energy (TU Delft)',
        name_zh: 'edX太阳能课程（代尔夫特理工）',
        region: 'global',
        url: 'https://www.edx.org/learn/solar-energy/delft-university-of-technology-solar-energy',
        price_range: 'Free (audit)',
        format: 'online',
        certification: 'edX Verified Certificate',
        language: ['en'],
      },
      {
        name: '阳光学院（隆基/阳光电源）',
        name_zh: '阳光学院光伏培训',
        region: 'CN',
        url: 'https://www.sungrowpower.com/',
        price_range: '¥500-3000',
        format: 'hybrid',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'pvlib-python',
        repo_url: 'https://github.com/pvlib/pvlib-python',
        stars: '1.2k+',
        what_to_learn: 'Solar resource modeling, PV system performance simulation, irradiance decomposition',
        what_to_learn_zh: '太阳能资源建模、光伏系统性能仿真、辐照度分解',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'SAM (System Advisor Model)',
        repo_url: 'https://github.com/NREL/SAM',
        stars: '300+',
        what_to_learn: 'Financial modeling for renewable projects: PPA, LCOE, cash flow analysis',
        what_to_learn_zh: '可再生能源项目财务建模：PPA、度电成本、现金流分析',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'SolarNetwork',
        repo_url: 'https://github.com/SolarNetwork/solarnetwork',
        stars: '100+',
        what_to_learn: 'IoT data collection for solar assets: monitoring, data aggregation, and API design',
        what_to_learn_zh: '光伏资产IoT数据采集：监控、数据聚合和API设计',
        estimated_hours: 10,
      },
    ],
    capstone: {
      title: 'Rooftop Solar System Design with Bankable Yield Report',
      title_zh: '屋顶光伏系统设计（含可融资发电量报告）',
      difficulty: 'intermediate',
      time_hours: 35,
      deliverables: [
        'PVsyst or SAM project for a 100kW+ rooftop system',
        'Shading analysis with 3D modeling',
        'Bankable yield report: P50/P90 energy estimates, loss breakdown',
        'Financial analysis: payback period, IRR, LCOE',
      ],
      deliverables_zh: [
        'PVsyst或SAM的100kW+屋顶光伏项目',
        '3D建模遮挡分析',
        '可融资发电量报告：P50/P90发电量估算、损失分解',
        '财务分析：回收期、IRR、度电成本',
      ],
      proves_to_employer: 'Can design PV systems and produce bankable yield reports accepted by financial institutions',
      proves_to_employer_zh: '能够设计光伏系统并出具被金融机构认可的可融资发电量报告',
    },
    monetization_potential: 'affiliate',
  },

  // ── 3. Battery / Energy Storage ───────────────────────────────────────
  {
    id: 'energy-battery',
    skill: 'Battery / Energy Storage',
    skill_zh: '电池/储能技术',
    industry: 'energy-equipment',
    industry_context: 'Lithium-ion batteries and energy storage systems (ESS) are critical for EVs, grid stabilization, and renewable integration. BMS design and cell characterization are key skills.',
    industry_context_zh: '锂离子电池和储能系统对电动汽车、电网稳定和可再生能源并网至关重要。BMS设计和电芯特性分析是核心技能。',
    tools: [
      {
        name: 'MATLAB / Simulink — Simscape Battery',
        name_zh: 'MATLAB/Simulink Simscape电池',
        vendor: 'MathWorks',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.mathworks.com/products/simscape-battery.html',
        alternatives: ['PyBaMM (free)', 'COMSOL Battery Module'],
      },
      {
        name: 'PyBaMM',
        name_zh: 'PyBaMM开源电池建模',
        vendor: 'Open Source (Faraday Institution)',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Fully open-source, BSD license — physics-based battery modeling',
        url: 'https://www.pybamm.org/',
      },
      {
        name: 'BatPaC (Argonne)',
        name_zh: 'BatPaC电池成本模型',
        vendor: 'Argonne National Lab',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free Excel-based battery cost model from Argonne',
        url: 'https://www.anl.gov/cse/batpac-model-software',
      },
    ],
    training: [
      {
        name: 'Coursera — Battery Design (Univ. of Colorado Boulder)',
        name_zh: 'Coursera电池设计（科罗拉多大学）',
        region: 'global',
        url: 'https://www.coursera.org/specializations/battery-design',
        price_range: 'Free (audit)',
        format: 'online',
        certification: 'Coursera Specialization Certificate',
        language: ['en'],
      },
      {
        name: 'RWTH Aachen — Battery Training',
        name_zh: 'RWTH亚琛工大电池培训',
        region: 'DE',
        url: 'https://www.isea.rwth-aachen.de/',
        price_range: '€1000-3000',
        format: 'hybrid',
        language: ['de', 'en'],
      },
      {
        name: '中国化学与物理电源行业协会培训',
        name_zh: '电源行业协会电池技术培训',
        region: 'CN',
        url: 'https://www.ciaps.org.cn/',
        price_range: '¥1000-5000',
        format: 'hybrid',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'PyBaMM',
        repo_url: 'https://github.com/pybamm-team/PyBaMM',
        stars: '1.1k+',
        what_to_learn: 'Physics-based battery models: SPM, DFN; parameterization and degradation modeling',
        what_to_learn_zh: '基于物理的电池模型：SPM、DFN；参数化和退化建模',
        estimated_hours: 25,
      },
      {
        order: 2,
        repo_name: 'liionpack',
        repo_url: 'https://github.com/pybamm-team/liionpack',
        stars: '100+',
        what_to_learn: 'Battery pack simulation: series/parallel configurations, thermal coupling between cells',
        what_to_learn_zh: '电池包仿真：串并联配置、电芯间热耦合',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'foxBMS 2',
        repo_url: 'https://github.com/foxBMS/foxbms-2',
        stars: '300+',
        what_to_learn: 'Open-source BMS reference design: SOC estimation, cell balancing, safety monitoring',
        what_to_learn_zh: '开源BMS参考设计：SOC估算、电芯均衡、安全监控',
        estimated_hours: 20,
      },
    ],
    capstone: {
      title: 'Battery Pack BMS Simulation with Thermal Management',
      title_zh: '带热管理的电池包BMS仿真',
      difficulty: 'advanced',
      time_hours: 45,
      deliverables: [
        'PyBaMM model of a battery pack (96S configuration)',
        'BMS algorithm: SOC estimation (EKF), cell balancing strategy',
        'Thermal simulation showing temperature distribution under fast charging',
        'Report: cycle life prediction under different usage profiles',
      ],
      deliverables_zh: [
        'PyBaMM电池包模型（96S配置）',
        'BMS算法：SOC估算（扩展卡尔曼滤波）、电芯均衡策略',
        '快充工况下温度分布热仿真',
        '报告：不同使用工况下的循环寿命预测',
      ],
      proves_to_employer: 'Can model battery pack behavior, design BMS algorithms, and analyze thermal management strategies',
      proves_to_employer_zh: '能够建模电池包行为、设计BMS算法并分析热管理策略',
    },
    monetization_potential: 'none',
  },

  // ── 4. Hydrogen / Fuel Cell ───────────────────────────────────────────
  {
    id: 'energy-hydrogen',
    skill: 'Hydrogen / Fuel Cell',
    skill_zh: '氢能/燃料电池',
    industry: 'energy-equipment',
    industry_context: 'Green hydrogen and PEM fuel cells are key for decarbonizing heavy transport and industry. This is an emerging field with strong demand in Germany, China, and Japan.',
    industry_context_zh: '绿氢和PEM燃料电池是重型运输和工业脱碳的关键。这是一个新兴领域，在德国、中国和日本需求强劲。',
    tools: [
      {
        name: 'MATLAB / Simulink — Fuel Cell Toolbox',
        name_zh: 'MATLAB/Simulink燃料电池工具箱',
        vendor: 'MathWorks',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.mathworks.com/solutions/electrification/fuel-cell.html',
        alternatives: ['OpenFCST (free)', 'COMSOL Fuel Cell Module'],
      },
      {
        name: 'Cantera',
        name_zh: 'Cantera化学动力学',
        vendor: 'Open Source',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Open-source chemical kinetics and thermodynamics',
        url: 'https://cantera.org/',
      },
      {
        name: 'DWSIM',
        name_zh: 'DWSIM开源流程模拟',
        vendor: 'Open Source',
        tier: 'emerging',
        free_tier: true,
        free_tier_note: 'Open-source process simulator for hydrogen production modeling',
        url: 'https://dwsim.org/',
      },
    ],
    training: [
      {
        name: 'edX — Hydrogen and Fuel Cells (TU Delft)',
        name_zh: 'edX氢能与燃料电池（代尔夫特理工）',
        region: 'global',
        url: 'https://www.edx.org/learn/renewable-energy',
        price_range: 'Free (audit)',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'Fraunhofer ISE — Hydrogen Technology',
        name_zh: 'Fraunhofer ISE氢能技术',
        region: 'DE',
        url: 'https://www.ise.fraunhofer.de/',
        price_range: '€1500-4000',
        format: 'hybrid',
        language: ['de', 'en'],
      },
      {
        name: '中国氢能联盟培训',
        name_zh: '中国氢能联盟培训',
        region: 'CN',
        url: 'https://www.h2cn.org/',
        price_range: '¥2000-6000',
        format: 'hybrid',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'Cantera',
        repo_url: 'https://github.com/Cantera/cantera',
        stars: '600+',
        what_to_learn: 'Chemical thermodynamics and kinetics: reaction mechanisms relevant to electrolysis and fuel cells',
        what_to_learn_zh: '化学热力学和动力学：电解和燃料电池相关反应机制',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'OpenFCST',
        repo_url: 'https://github.com/OpenFCST/OpenFCST',
        stars: '100+',
        what_to_learn: 'PEM fuel cell simulation: membrane electrode assembly modeling, polarization curves',
        what_to_learn_zh: 'PEM燃料电池仿真：膜电极组件建模、极化曲线',
        estimated_hours: 25,
      },
      {
        order: 3,
        repo_name: 'DWSIM',
        repo_url: 'https://github.com/DanWBR/dwsim',
        stars: '500+',
        what_to_learn: 'Process simulation for green hydrogen production: electrolyzer system design and optimization',
        what_to_learn_zh: '绿氢生产流程仿真：电解槽系统设计和优化',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'Green Hydrogen Production System Design and Techno-Economic Analysis',
      title_zh: '绿氢制备系统设计与技术经济分析',
      difficulty: 'advanced',
      time_hours: 45,
      deliverables: [
        'PEM electrolyzer system model (Cantera or MATLAB)',
        'Process flow diagram for hydrogen production, compression, and storage',
        'Techno-economic analysis: LCOH under different electricity price scenarios',
        'Comparison report: PEM vs alkaline vs SOEC technologies',
      ],
      deliverables_zh: [
        'PEM电解槽系统模型（Cantera或MATLAB）',
        '氢气制备、压缩、储存流程图',
        '技术经济分析：不同电价场景下的制氢成本',
        '技术对比报告：PEM vs 碱性 vs SOEC',
      ],
      proves_to_employer: 'Can design hydrogen production systems and perform techno-economic analysis for project feasibility',
      proves_to_employer_zh: '能够设计氢气制备系统并进行项目可行性技术经济分析',
    },
    monetization_potential: 'none',
  },

  // ── 5. Grid Integration / Smart Grid ──────────────────────────────────
  {
    id: 'energy-grid',
    skill: 'Grid Integration / Smart Grid',
    skill_zh: '电网集成/智能电网',
    industry: 'energy-equipment',
    industry_context: 'Integrating renewables into power grids requires understanding of grid codes, power electronics, and energy management systems. SCADA, DERMS, and grid simulation are essential.',
    industry_context_zh: '可再生能源并网需要了解电网规范、电力电子和能源管理系统。SCADA、分布式能源管理和电网仿真是核心技能。',
    tools: [
      {
        name: 'PSS/E (Siemens PTI)',
        name_zh: 'PSS/E电力系统仿真',
        vendor: 'Siemens',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.siemens.com/global/en/products/energy/grid-software/planning/pss-software/pss-e.html',
        alternatives: ['DIgSILENT PowerFactory', 'ETAP', 'OpenDSS (EPRI, free)'],
      },
      {
        name: 'OpenDSS',
        name_zh: 'OpenDSS配电系统仿真',
        vendor: 'EPRI',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Fully free, open-source distribution system simulator',
        url: 'https://www.epri.com/pages/sa/opendss',
      },
      {
        name: 'GridLAB-D',
        name_zh: 'GridLAB-D电网仿真',
        vendor: 'US DOE / PNNL',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Open-source agent-based grid simulation',
        url: 'https://www.gridlabd.org/',
      },
    ],
    training: [
      {
        name: 'IEEE Power & Energy Society — Online Courses',
        name_zh: 'IEEE电力与能源协会在线课程',
        region: 'global',
        url: 'https://www.ieee-pes.org/education',
        price_range: '$200-1000',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'Fraunhofer IEE — Grid Integration',
        name_zh: 'Fraunhofer IEE电网集成培训',
        region: 'DE',
        url: 'https://www.iee.fraunhofer.de/',
        price_range: '€1000-3000',
        format: 'hybrid',
        language: ['de', 'en'],
      },
      {
        name: '国家电网技术学院',
        name_zh: '国家电网技术学院',
        region: 'CN',
        url: 'https://www.sgcc.com.cn/',
        price_range: '¥1000-5000',
        format: 'hybrid',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'pandapower',
        repo_url: 'https://github.com/e2nIEE/pandapower',
        stars: '900+',
        what_to_learn: 'Power system analysis in Python: load flow, optimal power flow, short circuit calculation',
        what_to_learn_zh: 'Python电力系统分析：潮流计算、最优潮流、短路计算',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'GridLAB-D',
        repo_url: 'https://github.com/gridlab-d/gridlab-d',
        stars: '200+',
        what_to_learn: 'Smart grid simulation: demand response, distributed generation, storage integration',
        what_to_learn_zh: '智能电网仿真：需求响应、分布式发电、储能集成',
        estimated_hours: 20,
      },
      {
        order: 3,
        repo_name: 'OpenDSS',
        repo_url: 'https://github.com/dss-extensions/OpenDSSDirect.py',
        stars: '200+',
        what_to_learn: 'Distribution system modeling: PV hosting capacity, voltage regulation, feeder analysis',
        what_to_learn_zh: '配电系统建模：光伏承载力、电压调节、馈线分析',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'Microgrid Design with Renewable Integration and Battery Storage',
      title_zh: '含可再生能源和储能的微电网设计',
      difficulty: 'advanced',
      time_hours: 50,
      deliverables: [
        'pandapower/OpenDSS model of a microgrid with PV, wind, battery, and loads',
        'Energy management algorithm for optimal dispatch',
        'Grid-connected and islanded mode simulation',
        'Technical report: power quality analysis, protection coordination, economic feasibility',
      ],
      deliverables_zh: [
        'pandapower/OpenDSS微电网模型（含光伏、风电、储能和负荷）',
        '最优调度能量管理算法',
        '并网和离网模式仿真',
        '技术报告：电能质量分析、保护协调、经济可行性',
      ],
      proves_to_employer: 'Can design microgrids with renewable integration, energy storage, and optimal dispatch strategies',
      proves_to_employer_zh: '能够设计含可再生能源集成、储能和最优调度策略的微电网',
    },
    monetization_potential: 'none',
  },
];
