import type { IndustryToolMapEntry } from './types';

export const industrialAutomationEntries: IndustryToolMapEntry[] = [
  // ── 1. PLC Programming (Siemens TIA Portal) ──────────────────────────
  {
    id: 'ia-plc',
    skill: 'PLC Programming',
    skill_zh: 'PLC编程',
    industry: 'industrial-automation',
    industry_context: 'PLC programming is the backbone of industrial automation — every production line, packaging machine, and material handling system runs on PLCs. Siemens TIA Portal dominates in Europe and China.',
    industry_context_zh: 'PLC编程是工业自动化的核心——每条产线、包装机、物流系统都依赖PLC运行。西门子TIA Portal在欧洲和中国市场占主导地位。',
    tools: [
      {
        name: 'Siemens TIA Portal',
        name_zh: '西门子TIA博途',
        vendor: 'Siemens',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'TIA Portal Trial available for 21 days; PLCSIM included',
        url: 'https://www.siemens.com/global/en/products/automation/industry-software/automation-software/tia-portal.html',
        alternatives: ['Rockwell Studio 5000', 'Mitsubishi GX Works3', 'Beckhoff TwinCAT 3'],
      },
      {
        name: 'CODESYS',
        name_zh: 'CODESYS',
        vendor: 'CODESYS GmbH',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free development environment; runtime licenses per device',
        url: 'https://www.codesys.com/',
      },
      {
        name: 'OpenPLC',
        name_zh: 'OpenPLC',
        vendor: 'Open Source',
        tier: 'emerging',
        free_tier: true,
        free_tier_note: 'Fully open-source IEC 61131-3 PLC',
        url: 'https://autonomylogic.com/',
      },
    ],
    training: [
      {
        name: 'Siemens SCE (Siemens Cooperates with Education)',
        name_zh: '西门子SCE教育合作项目',
        region: 'global',
        url: 'https://www.siemens.com/global/en/products/automation/industry-software/sce.html',
        price_range: 'Free',
        format: 'online',
        certification: 'Siemens Certified Programmer',
        language: ['en', 'de', 'zh'],
      },
      {
        name: 'Udemy — PLC Programming From Scratch',
        name_zh: 'Udemy PLC编程从零开始',
        region: 'global',
        url: 'https://www.udemy.com/topic/plc/',
        price_range: '¥79-199',
        format: 'online',
        language: ['en'],
      },
      {
        name: '技成培训网',
        name_zh: '技成培训网',
        region: 'CN',
        url: 'https://www.jcpeixun.com/',
        price_range: '¥299-1999',
        format: 'online',
        certification: '技成PLC编程证书',
        language: ['zh'],
      },
      {
        name: 'Festo Didactic',
        name_zh: 'Festo教学',
        region: 'DE',
        url: 'https://www.festo-didactic.com/',
        price_range: '€500-2000',
        format: 'hybrid',
        certification: 'Festo Certified Automation Professional',
        language: ['de', 'en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'OpenPLC Runtime',
        repo_url: 'https://github.com/thiagoralves/OpenPLC_v3',
        stars: '1.1k+',
        what_to_learn: 'Understand IEC 61131-3 standard, Structured Text, and Ladder Diagram fundamentals on real hardware',
        what_to_learn_zh: '理解IEC 61131-3标准、结构化文本和梯形图基础，在真实硬件上实践',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'CODESYS Example Projects',
        repo_url: 'https://github.com/CODESYS/codesys-sample-projects',
        stars: '200+',
        what_to_learn: 'Learn function blocks, state machines, and OOP in IEC 61131-3',
        what_to_learn_zh: '学习功能块、状态机和IEC 61131-3中的面向对象编程',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'TcOpen — TwinCAT Open Framework',
        repo_url: 'https://github.com/TcOpenGroup/TcOpen',
        stars: '500+',
        what_to_learn: 'Study industrial-grade PLC framework patterns: encapsulation, unit testing, CI/CD for PLC code',
        what_to_learn_zh: '学习工业级PLC框架模式：封装、单元测试、PLC代码的CI/CD',
        estimated_hours: 25,
      },
    ],
    capstone: {
      title: 'Automated Bottle Filling Line with Safety PLC',
      title_zh: '带安全PLC的自动灌装生产线',
      difficulty: 'intermediate',
      time_hours: 40,
      deliverables: [
        'TIA Portal / OpenPLC project with Structured Text and Ladder Diagram',
        'HMI screen mockup for operator interaction',
        'Safety circuit design (E-stop, light curtain integration)',
        'Documentation: I/O list, state diagram, commissioning checklist',
      ],
      deliverables_zh: [
        'TIA Portal / OpenPLC项目（含结构化文本和梯形图）',
        'HMI操作界面原型',
        '安全回路设计（急停、光幕集成）',
        '文档：I/O清单、状态图、调试检查表',
      ],
      proves_to_employer: 'Can design, program, and commission a PLC-controlled production line with safety integration',
      proves_to_employer_zh: '能够设计、编程和调试带安全集成的PLC控制产线',
    },
    monetization_potential: 'affiliate',
  },

  // ── 2. SCADA / DCS ───────────────────────────────────────────────────
  {
    id: 'ia-scada',
    skill: 'SCADA / DCS',
    skill_zh: 'SCADA/DCS监控系统',
    industry: 'industrial-automation',
    industry_context: 'SCADA and DCS systems provide real-time monitoring and control for large-scale industrial processes — power plants, water treatment, oil & gas, and smart factories.',
    industry_context_zh: 'SCADA和DCS系统为大规模工业过程提供实时监控——发电厂、水处理、油气和智能工厂都离不开它们。',
    tools: [
      {
        name: 'Ignition by Inductive Automation',
        name_zh: 'Ignition SCADA',
        vendor: 'Inductive Automation',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free Trial license with full features; Maker Edition free for non-commercial',
        url: 'https://inductiveautomation.com/',
        alternatives: ['WinCC (Siemens)', 'FactoryTalk View (Rockwell)', 'AVEVA System Platform'],
      },
      {
        name: 'Rapid SCADA',
        name_zh: 'Rapid SCADA',
        vendor: 'Open Source',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Open-source SCADA system, Apache 2.0 license',
        url: 'https://rapidscada.org/',
      },
      {
        name: 'ScadaBR',
        name_zh: 'ScadaBR',
        vendor: 'Open Source',
        tier: 'emerging',
        free_tier: true,
        free_tier_note: 'Open-source SCADA based on Mango Automation',
        url: 'https://www.scadabr.com.br/',
      },
    ],
    training: [
      {
        name: 'Inductive University (Ignition)',
        name_zh: 'Inductive University (Ignition培训)',
        region: 'global',
        url: 'https://inductiveuniversity.com/',
        price_range: 'Free',
        format: 'online',
        certification: 'Ignition Core Certified',
        language: ['en'],
      },
      {
        name: 'Siemens SITRAIN — WinCC',
        name_zh: '西门子SITRAIN WinCC课程',
        region: 'DE',
        url: 'https://www.siemens.com/global/en/products/services/sitrain.html',
        price_range: '€1500-3000',
        format: 'hybrid',
        certification: 'Siemens WinCC Certified',
        language: ['de', 'en'],
      },
      {
        name: '工控网在线课堂',
        name_zh: '工控网在线课堂',
        region: 'CN',
        url: 'https://www.gongkong.com/',
        price_range: '¥199-999',
        format: 'online',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'Rapid SCADA',
        repo_url: 'https://github.com/RapidScada/scada-v6',
        stars: '400+',
        what_to_learn: 'Understand SCADA architecture: server, communicator, webstation; learn Modbus/OPC communication',
        what_to_learn_zh: '理解SCADA架构：服务器、通讯器、Web站；学习Modbus/OPC通讯',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'GRFICSv2 — SCADA Simulation',
        repo_url: 'https://github.com/Fortiphyd/GRFICSv2',
        stars: '500+',
        what_to_learn: 'Learn SCADA/ICS security concepts via a virtual environment with PLC, HMI, and physical process simulation',
        what_to_learn_zh: '通过虚拟环境学习SCADA/ICS安全概念，含PLC、HMI和物理过程仿真',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'ScadaLTS',
        repo_url: 'https://github.com/SCADA-LTS/Scada-LTS',
        stars: '800+',
        what_to_learn: 'Build dashboards, configure data points, understand historian and alarm management',
        what_to_learn_zh: '构建仪表盘、配置数据点、理解历史数据库和报警管理',
        estimated_hours: 20,
      },
    ],
    capstone: {
      title: 'Water Treatment Plant SCADA Dashboard',
      title_zh: '水处理厂SCADA监控仪表盘',
      difficulty: 'intermediate',
      time_hours: 35,
      deliverables: [
        'SCADA project with real-time dashboard (Ignition or Rapid SCADA)',
        'Modbus TCP simulation for pump/valve/level sensors',
        'Alarm configuration with priority levels and escalation',
        'Historical trending and report generation',
      ],
      deliverables_zh: [
        'SCADA项目含实时仪表盘（Ignition或Rapid SCADA）',
        'Modbus TCP仿真（泵/阀/液位传感器）',
        '报警配置（优先级和升级机制）',
        '历史趋势和报告生成',
      ],
      proves_to_employer: 'Can design and configure SCADA systems with communication protocols, alarming, and data historian',
      proves_to_employer_zh: '能够设计和配置含通讯协议、报警和历史数据库的SCADA系统',
    },
    monetization_potential: 'affiliate',
  },

  // ── 3. Industrial Robotics ────────────────────────────────────────────
  {
    id: 'ia-robotics',
    skill: 'Industrial Robotics',
    skill_zh: '工业机器人',
    industry: 'industrial-automation',
    industry_context: 'Industrial robots (KUKA, ABB, Fanuc) are essential for welding, assembly, painting, and material handling. Offline programming and simulation skills are in high demand.',
    industry_context_zh: '工业机器人（KUKA、ABB、发那科）是焊接、装配、喷涂和物料搬运的核心。离线编程和仿真技能需求旺盛。',
    tools: [
      {
        name: 'RoboDK',
        name_zh: 'RoboDK',
        vendor: 'RoboDK Inc.',
        tier: 'essential',
        free_tier: true,
        free_tier_note: '30-day trial; Education license available',
        url: 'https://robodk.com/',
        alternatives: ['KUKA.Sim', 'ABB RobotStudio', 'Fanuc ROBOGUIDE'],
      },
      {
        name: 'ABB RobotStudio',
        name_zh: 'ABB RobotStudio',
        vendor: 'ABB',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free version with virtual controller; Premium for advanced features',
        url: 'https://new.abb.com/products/robotics/robotstudio',
      },
      {
        name: 'ROS 2 (Robot Operating System)',
        name_zh: 'ROS 2机器人操作系统',
        vendor: 'Open Robotics',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Fully open-source, Apache 2.0',
        url: 'https://www.ros.org/',
      },
      {
        name: 'MoveIt 2',
        name_zh: 'MoveIt 2运动规划',
        vendor: 'PickNik Robotics',
        tier: 'emerging',
        free_tier: true,
        free_tier_note: 'Open-source motion planning framework for ROS 2',
        url: 'https://moveit.ros.org/',
      },
    ],
    training: [
      {
        name: 'ABB Robotics Learning Portal',
        name_zh: 'ABB机器人学习门户',
        region: 'global',
        url: 'https://new.abb.com/products/robotics/service/training',
        price_range: '€800-3000',
        format: 'hybrid',
        certification: 'ABB Certified Robot Programmer',
        language: ['en', 'de'],
      },
      {
        name: 'KUKA College',
        name_zh: 'KUKA学院',
        region: 'DE',
        url: 'https://www.kuka.com/en-de/services/kuka-college',
        price_range: '€1000-4000',
        format: 'hybrid',
        certification: 'KUKA Programming Certificate',
        language: ['de', 'en'],
      },
      {
        name: '哈工海渡机器人学院',
        name_zh: '哈工海渡机器人学院',
        region: 'CN',
        url: 'https://www.irobot-edu.com/',
        price_range: '¥2000-8000',
        format: 'hybrid',
        certification: '工业机器人操作员证书',
        language: ['zh'],
      },
      {
        name: 'The Construct — ROS 2 Training',
        name_zh: 'The Construct ROS 2培训',
        region: 'global',
        url: 'https://www.theconstruct.ai/',
        price_range: '$20-50/month',
        format: 'online',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'ROS 2 Documentation',
        repo_url: 'https://github.com/ros2/ros2_documentation',
        stars: '400+',
        what_to_learn: 'Learn ROS 2 fundamentals: nodes, topics, services, actions — the lingua franca of modern robotics',
        what_to_learn_zh: '学习ROS 2基础：节点、话题、服务、动作——现代机器人的通用语言',
        estimated_hours: 25,
      },
      {
        order: 2,
        repo_name: 'MoveIt 2',
        repo_url: 'https://github.com/moveit/moveit2',
        stars: '1k+',
        what_to_learn: 'Motion planning, kinematics, collision detection — core skills for robot arm applications',
        what_to_learn_zh: '运动规划、运动学、碰撞检测——机械臂应用的核心技能',
        estimated_hours: 30,
      },
      {
        order: 3,
        repo_name: 'RoboDK API',
        repo_url: 'https://github.com/RoboDK/RoboDK-API',
        stars: '200+',
        what_to_learn: 'Offline programming via Python API: simulate, optimize, and post-process for real robot brands',
        what_to_learn_zh: '通过Python API离线编程：仿真、优化和后处理，适用于各品牌机器人',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'Pick-and-Place Robot Cell with Vision Guidance',
      title_zh: '视觉引导的拾放机器人工作站',
      difficulty: 'advanced',
      time_hours: 50,
      deliverables: [
        'RoboDK or RobotStudio simulation of a pick-and-place cell',
        'Python script for path planning and cycle time optimization',
        'Simulated vision integration for part detection',
        'Technical report: cycle time analysis, ROI calculation, safety layout',
      ],
      deliverables_zh: [
        'RoboDK或RobotStudio拾放工作站仿真',
        'Python脚本实现路径规划和节拍优化',
        '视觉集成仿真实现零件检测',
        '技术报告：节拍分析、ROI计算、安全布局',
      ],
      proves_to_employer: 'Can design, simulate, and optimize a robotic workcell with vision integration',
      proves_to_employer_zh: '能够设计、仿真和优化带视觉集成的机器人工作站',
    },
    monetization_potential: 'affiliate',
  },

  // ── 4. Machine Vision ─────────────────────────────────────────────────
  {
    id: 'ia-vision',
    skill: 'Machine Vision',
    skill_zh: '机器视觉',
    industry: 'industrial-automation',
    industry_context: 'Machine vision systems inspect, measure, and guide in manufacturing. Cognex and Keyence dominate dedicated hardware; HALCON and OpenCV power the software side.',
    industry_context_zh: '机器视觉系统在制造中进行检测、测量和引导。Cognex和Keyence主导专用硬件，HALCON和OpenCV是软件侧的核心。',
    tools: [
      {
        name: 'MVTec HALCON',
        name_zh: 'HALCON机器视觉库',
        vendor: 'MVTec',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free evaluation license; student license available',
        url: 'https://www.mvtec.com/products/halcon',
        alternatives: ['Cognex VisionPro', 'Keyence CV-X Series', 'National Instruments Vision'],
      },
      {
        name: 'OpenCV',
        name_zh: 'OpenCV开源视觉库',
        vendor: 'Open Source',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Fully open-source, BSD license',
        url: 'https://opencv.org/',
      },
      {
        name: 'NVIDIA Isaac SDK',
        name_zh: 'NVIDIA Isaac SDK',
        vendor: 'NVIDIA',
        tier: 'emerging',
        free_tier: true,
        free_tier_note: 'Free for development; GPU required',
        url: 'https://developer.nvidia.com/isaac',
      },
    ],
    training: [
      {
        name: 'MVTec HALCON Training',
        name_zh: 'MVTec HALCON官方培训',
        region: 'DE',
        url: 'https://www.mvtec.com/services/training',
        price_range: '€1500-3000',
        format: 'hybrid',
        certification: 'HALCON Certified Developer',
        language: ['en', 'de'],
      },
      {
        name: 'Cognex Self-Study',
        name_zh: 'Cognex自学平台',
        region: 'global',
        url: 'https://www.cognex.com/support/training',
        price_range: 'Free',
        format: 'online',
        language: ['en'],
      },
      {
        name: '机器视觉网课堂',
        name_zh: '机器视觉网课堂',
        region: 'CN',
        url: 'https://www.china-vision.org/',
        price_range: '¥499-2999',
        format: 'online',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'OpenCV',
        repo_url: 'https://github.com/opencv/opencv',
        stars: '79k+',
        what_to_learn: 'Image processing fundamentals: filtering, edge detection, morphology, color spaces',
        what_to_learn_zh: '图像处理基础：滤波、边缘检测、形态学、色彩空间',
        estimated_hours: 25,
      },
      {
        order: 2,
        repo_name: 'Ultralytics YOLOv8',
        repo_url: 'https://github.com/ultralytics/ultralytics',
        stars: '35k+',
        what_to_learn: 'Deep learning for defect detection: train custom models for industrial inspection',
        what_to_learn_zh: '深度学习缺陷检测：训练自定义工业检测模型',
        estimated_hours: 20,
      },
      {
        order: 3,
        repo_name: 'Anomalib',
        repo_url: 'https://github.com/openvinotoolkit/anomalib',
        stars: '3.5k+',
        what_to_learn: 'Anomaly detection for industrial quality inspection — unsupervised defect detection',
        what_to_learn_zh: '工业质检异常检测——无监督缺陷检测',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'Automated Surface Defect Inspection System',
      title_zh: '自动化表面缺陷检测系统',
      difficulty: 'intermediate',
      time_hours: 40,
      deliverables: [
        'Python application with OpenCV + YOLO for defect classification',
        'Web dashboard showing pass/fail statistics and defect heatmaps',
        'Performance report: accuracy, false positive rate, throughput (parts/min)',
        'Deployment guide for edge device (Jetson Nano or Raspberry Pi)',
      ],
      deliverables_zh: [
        'Python应用（OpenCV + YOLO缺陷分类）',
        'Web仪表盘展示合格率和缺陷热图',
        '性能报告：准确率、误报率、吞吐量（件/分钟）',
        '边缘设备部署指南（Jetson Nano或树莓派）',
      ],
      proves_to_employer: 'Can build and deploy a machine vision inspection system from data collection to edge deployment',
      proves_to_employer_zh: '能够从数据采集到边缘部署构建和部署机器视觉检测系统',
    },
    monetization_potential: 'affiliate',
  },

  // ── 5. IIoT / OPC UA ─────────────────────────────────────────────────
  {
    id: 'ia-iiot',
    skill: 'IIoT / OPC UA',
    skill_zh: 'IIoT工业物联网/OPC UA',
    industry: 'industrial-automation',
    industry_context: 'IIoT connects machines to the cloud for predictive maintenance, OEE tracking, and digital twins. OPC UA is the standard protocol for secure, interoperable industrial communication.',
    industry_context_zh: 'IIoT将机器连接到云端，实现预测性维护、OEE跟踪和数字孪生。OPC UA是安全、可互操作的工业通讯标准协议。',
    tools: [
      {
        name: 'Unified Automation UaExpert',
        name_zh: 'UaExpert OPC UA客户端',
        vendor: 'Unified Automation',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free OPC UA test client',
        url: 'https://www.unified-automation.com/products/development-tools/uaexpert.html',
        alternatives: ['Prosys OPC UA Browser', 'Kepware KEPServerEX'],
      },
      {
        name: 'Node-RED',
        name_zh: 'Node-RED',
        vendor: 'OpenJS Foundation',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Open-source, Apache 2.0',
        url: 'https://nodered.org/',
      },
      {
        name: 'AWS IoT Greengrass',
        name_zh: 'AWS IoT Greengrass',
        vendor: 'Amazon',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free tier: 3 Greengrass core devices; pay for additional',
        url: 'https://aws.amazon.com/greengrass/',
        alternatives: ['Azure IoT Edge', 'Siemens MindSphere'],
      },
    ],
    training: [
      {
        name: 'OPC Foundation Training',
        name_zh: 'OPC基金会培训',
        region: 'global',
        url: 'https://opcfoundation.org/training/',
        price_range: '$500-1500',
        format: 'online',
        certification: 'OPC UA Certified Professional',
        language: ['en'],
      },
      {
        name: 'AWS IoT Training',
        name_zh: 'AWS IoT培训',
        region: 'global',
        url: 'https://aws.amazon.com/training/learn-about/iot/',
        price_range: 'Free',
        format: 'online',
        certification: 'AWS IoT Specialty',
        language: ['en', 'zh'],
      },
      {
        name: 'HiveMQ MQTT Academy',
        name_zh: 'HiveMQ MQTT学院',
        region: 'global',
        url: 'https://www.hivemq.com/mqtt-academy/',
        price_range: 'Free',
        format: 'online',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'open62541 — OPC UA in C',
        repo_url: 'https://github.com/open62541/open62541',
        stars: '2.8k+',
        what_to_learn: 'Understand OPC UA information model, server/client architecture, and security',
        what_to_learn_zh: '理解OPC UA信息模型、服务器/客户端架构和安全机制',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'Node-RED',
        repo_url: 'https://github.com/node-red/node-red',
        stars: '20k+',
        what_to_learn: 'Build IIoT data flows: connect OPC UA, MQTT, databases, and dashboards visually',
        what_to_learn_zh: '构建IIoT数据流：可视化连接OPC UA、MQTT、数据库和仪表盘',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'Eclipse Mosquitto',
        repo_url: 'https://github.com/eclipse/mosquitto',
        stars: '9k+',
        what_to_learn: 'Set up MQTT broker for industrial messaging; understand QoS, topics, and bridging',
        what_to_learn_zh: '搭建MQTT消息代理；理解QoS、主题和桥接',
        estimated_hours: 10,
      },
    ],
    capstone: {
      title: 'Factory OEE Dashboard with OPC UA + MQTT',
      title_zh: 'OPC UA + MQTT工厂OEE仪表盘',
      difficulty: 'intermediate',
      time_hours: 35,
      deliverables: [
        'OPC UA server simulating 3+ machines with production data',
        'Node-RED flow collecting data via OPC UA and publishing to MQTT',
        'Grafana or custom dashboard showing OEE, availability, quality metrics',
        'Alert system for machine downtime via email/Telegram',
      ],
      deliverables_zh: [
        'OPC UA服务器仿真3+台设备的生产数据',
        'Node-RED数据流通过OPC UA采集并发布到MQTT',
        'Grafana或自定义仪表盘展示OEE、可用率、质量指标',
        '设备停机邮件/Telegram告警系统',
      ],
      proves_to_employer: 'Can architect an IIoT data pipeline from shop floor to cloud dashboard',
      proves_to_employer_zh: '能够架构从车间到云端仪表盘的IIoT数据管道',
    },
    monetization_potential: 'affiliate',
  },

  // ── 6. MES / MOM ─────────────────────────────────────────────────────
  {
    id: 'ia-mes',
    skill: 'MES / MOM',
    skill_zh: 'MES制造执行系统',
    industry: 'industrial-automation',
    industry_context: 'MES (Manufacturing Execution Systems) bridge ERP and shop floor — tracking production orders, quality, traceability, and WIP in real time. ISA-95 is the guiding standard.',
    industry_context_zh: 'MES制造执行系统连接ERP和车间——实时跟踪生产工单、质量、追溯和在制品。ISA-95是指导标准。',
    tools: [
      {
        name: 'AVEVA MES (formerly Wonderware)',
        name_zh: 'AVEVA MES',
        vendor: 'AVEVA',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.aveva.com/en/solutions/operations/manufacturing-execution-system/',
        alternatives: ['Siemens Opcenter', 'SAP ME', 'Rockwell Plex MES'],
      },
      {
        name: 'OpenMES (QAD)',
        name_zh: 'OpenMES',
        vendor: 'QAD / Open Source Community',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Open-source MES framework',
        url: 'https://www.2bfree.org/',
      },
      {
        name: 'Apache Kafka',
        name_zh: 'Apache Kafka',
        vendor: 'Apache Foundation',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Open-source, commonly used as MES event backbone',
        url: 'https://kafka.apache.org/',
      },
    ],
    training: [
      {
        name: 'MESA International — MES Methodologies',
        name_zh: 'MESA国际MES方法论',
        region: 'global',
        url: 'https://www.mesa.org/',
        price_range: '$500-2000',
        format: 'online',
        certification: 'MESA MES/MOM Certificate',
        language: ['en'],
      },
      {
        name: 'Siemens Opcenter Training',
        name_zh: '西门子Opcenter培训',
        region: 'DE',
        url: 'https://www.siemens.com/global/en/products/software/opcenter.html',
        price_range: '€2000-5000',
        format: 'hybrid',
        certification: 'Siemens Opcenter Certified',
        language: ['de', 'en'],
      },
      {
        name: '中国智能制造系统解决方案供应商联盟',
        name_zh: '智能制造联盟MES课程',
        region: 'CN',
        url: 'https://www.cm2025.org/',
        price_range: '¥1000-5000',
        format: 'hybrid',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'Apache Kafka',
        repo_url: 'https://github.com/apache/kafka',
        stars: '29k+',
        what_to_learn: 'Event-driven architecture fundamentals — the backbone of modern MES systems',
        what_to_learn_zh: '事件驱动架构基础——现代MES系统的数据骨干',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'ISA-95 / B2MML Schemas',
        repo_url: 'https://github.com/MESAInternational/B2MML-BatchML',
        stars: '100+',
        what_to_learn: 'ISA-95 data models: operations definition, scheduling, and performance analysis',
        what_to_learn_zh: '学习ISA-95数据模型：运营定义、调度和绩效分析',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'ERPNext Manufacturing',
        repo_url: 'https://github.com/frappe/erpnext',
        stars: '20k+',
        what_to_learn: 'Study open-source MES/ERP integration: BOM, work orders, quality inspection modules',
        what_to_learn_zh: '学习开源MES/ERP集成：BOM、工单、质量检验模块',
        estimated_hours: 20,
      },
    ],
    capstone: {
      title: 'Production Tracking MES Prototype with ISA-95 Data Model',
      title_zh: '基于ISA-95数据模型的生产跟踪MES原型',
      difficulty: 'advanced',
      time_hours: 50,
      deliverables: [
        'Web-based MES application (React + Node.js or Python)',
        'ISA-95 compliant data model for work orders, materials, and equipment',
        'Real-time production dashboard with OEE, scrap rate, and WIP tracking',
        'REST API documentation for ERP/PLC integration',
      ],
      deliverables_zh: [
        'Web端MES应用（React + Node.js或Python）',
        '符合ISA-95的工单、物料和设备数据模型',
        '实时生产仪表盘（OEE、废品率、在制品跟踪）',
        'REST API文档用于ERP/PLC集成',
      ],
      proves_to_employer: 'Can design MES architecture following ISA-95 and build production tracking applications',
      proves_to_employer_zh: '能够按照ISA-95设计MES架构并构建生产跟踪应用',
    },
    monetization_potential: 'affiliate',
  },

  // ── 7. HMI Design ────────────────────────────────────────────────────
  {
    id: 'ia-hmi',
    skill: 'HMI Design',
    skill_zh: 'HMI人机界面设计',
    industry: 'industrial-automation',
    industry_context: 'HMI (Human-Machine Interface) screens are how operators interact with machines. Good HMI design reduces errors, improves safety, and follows ISA-101 high-performance standards.',
    industry_context_zh: 'HMI人机界面是操作员与机器交互的窗口。优秀的HMI设计能减少操作失误、提高安全性，遵循ISA-101高性能标准。',
    tools: [
      {
        name: 'Siemens WinCC Unified',
        name_zh: '西门子WinCC Unified',
        vendor: 'Siemens',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Trial available within TIA Portal',
        url: 'https://www.siemens.com/global/en/products/automation/industry-software/automation-software/scada/simatic-wincc-unified.html',
        alternatives: ['Rockwell FactoryTalk View', 'Schneider Vijeo Designer', 'Weintek EasyBuilder Pro'],
      },
      {
        name: 'Figma',
        name_zh: 'Figma',
        vendor: 'Figma Inc.',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free tier for up to 3 projects — great for HMI prototyping',
        url: 'https://www.figma.com/',
      },
      {
        name: 'Qt for MCUs',
        name_zh: 'Qt嵌入式HMI',
        vendor: 'The Qt Company',
        tier: 'emerging',
        free_tier: true,
        free_tier_note: 'Open-source LGPL license for Qt; commercial for MCU deployment',
        url: 'https://www.qt.io/product/qt-for-mcus',
      },
    ],
    training: [
      {
        name: 'ISA — HMI Design (ISA-101)',
        name_zh: 'ISA HMI设计标准（ISA-101）',
        region: 'global',
        url: 'https://www.isa.org/training-and-certification',
        price_range: '$500-1500',
        format: 'online',
        certification: 'ISA-101 HMI Design Specialist',
        language: ['en'],
      },
      {
        name: 'Siemens SITRAIN — WinCC Unified',
        name_zh: '西门子SITRAIN WinCC Unified培训',
        region: 'DE',
        url: 'https://www.siemens.com/global/en/products/services/sitrain.html',
        price_range: '€1000-2500',
        format: 'hybrid',
        language: ['de', 'en'],
      },
      {
        name: '中国仪器仪表学会培训',
        name_zh: '中国仪器仪表学会HMI培训',
        region: 'CN',
        url: 'https://www.cis.org.cn/',
        price_range: '¥800-3000',
        format: 'hybrid',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'Qt Examples',
        repo_url: 'https://github.com/qt/qtbase',
        stars: '2.8k+',
        what_to_learn: 'Learn Qt framework basics for building cross-platform industrial HMI applications',
        what_to_learn_zh: '学习Qt框架基础，构建跨平台工业HMI应用',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'Grafana',
        repo_url: 'https://github.com/grafana/grafana',
        stars: '65k+',
        what_to_learn: 'Dashboard design patterns: panels, variables, alerting — applicable to industrial HMI',
        what_to_learn_zh: '仪表盘设计模式：面板、变量、告警——适用于工业HMI',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'ISA-101 HMI Style Guide (ASM Consortium)',
        repo_url: 'https://github.com/grafana/grafana-iot-twinmaker-app',
        stars: '100+',
        what_to_learn: 'Study IoT/industrial dashboard patterns with digital twin visualization',
        what_to_learn_zh: '学习IoT/工业仪表盘模式和数字孪生可视化',
        estimated_hours: 10,
      },
    ],
    capstone: {
      title: 'High-Performance HMI for a Packaging Line (ISA-101 Compliant)',
      title_zh: '符合ISA-101的包装线高性能HMI',
      difficulty: 'intermediate',
      time_hours: 30,
      deliverables: [
        'Figma prototype of 5+ HMI screens following ISA-101 high-performance design',
        'Color coding strategy document (gray-scale base, color for abnormals only)',
        'Alarm summary screen with priority-based filtering',
        'Implementation in WinCC Unified or web-based (React + WebSocket)',
      ],
      deliverables_zh: [
        'Figma原型：5+个HMI画面遵循ISA-101高性能设计',
        '配色策略文档（灰度底色，仅异常着色）',
        '基于优先级过滤的报警汇总画面',
        'WinCC Unified或Web端实现（React + WebSocket）',
      ],
      proves_to_employer: 'Can design ISA-101 compliant high-performance HMI screens that reduce operator errors',
      proves_to_employer_zh: '能够设计符合ISA-101的高性能HMI画面，降低操作员失误率',
    },
    monetization_potential: 'affiliate',
  },

  // ── 8. Motion Control ─────────────────────────────────────────────────
  {
    id: 'ia-motion',
    skill: 'Motion Control',
    skill_zh: '运动控制',
    industry: 'industrial-automation',
    industry_context: 'Motion control systems drive servo motors, CNC axes, and multi-axis coordinated motion. Critical for precision machining, semiconductor manufacturing, and high-speed packaging.',
    industry_context_zh: '运动控制系统驱动伺服电机、CNC轴和多轴协调运动。对精密加工、半导体制造和高速包装至关重要。',
    tools: [
      {
        name: 'Beckhoff TwinCAT 3',
        name_zh: 'Beckhoff TwinCAT 3',
        vendor: 'Beckhoff',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free XAE engineering environment; 7-day trial for XAR runtime',
        url: 'https://www.beckhoff.com/en-en/products/automation/twincat/',
        alternatives: ['Siemens SIMOTION', 'Rockwell Kinetix', 'B&R Automation Studio'],
      },
      {
        name: 'LinuxCNC',
        name_zh: 'LinuxCNC',
        vendor: 'Open Source',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Fully open-source CNC/motion control, GPL license',
        url: 'https://linuxcnc.org/',
      },
      {
        name: 'MATLAB / Simulink — Motion Control Toolbox',
        name_zh: 'MATLAB/Simulink运动控制工具箱',
        vendor: 'MathWorks',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.mathworks.com/products/simscape.html',
        alternatives: ['Scilab/Xcos (free)', 'GNU Octave'],
      },
    ],
    training: [
      {
        name: 'Beckhoff TwinCAT Training',
        name_zh: 'Beckhoff TwinCAT培训',
        region: 'DE',
        url: 'https://www.beckhoff.com/en-en/support/training/',
        price_range: '€500-2000',
        format: 'hybrid',
        certification: 'TwinCAT Certified Engineer',
        language: ['de', 'en'],
      },
      {
        name: 'Coursera — Control of Mobile Robots (Georgia Tech)',
        name_zh: 'Coursera 移动机器人控制（佐治亚理工）',
        region: 'global',
        url: 'https://www.coursera.org/learn/mobile-robot',
        price_range: 'Free (audit)',
        format: 'online',
        certification: 'Coursera Certificate',
        language: ['en'],
      },
      {
        name: '深圳固高科技运动控制培训',
        name_zh: '固高科技运动控制培训',
        region: 'CN',
        url: 'https://www.googoltech.com/',
        price_range: '¥2000-6000',
        format: 'hybrid',
        certification: '运动控制工程师证书',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'LinuxCNC',
        repo_url: 'https://github.com/LinuxCNC/linuxcnc',
        stars: '1k+',
        what_to_learn: 'Understand real-time motion planning, G-code interpretation, and servo loop fundamentals',
        what_to_learn_zh: '理解实时运动规划、G代码解析和伺服环路基础',
        estimated_hours: 25,
      },
      {
        order: 2,
        repo_name: 'TcOpen — TwinCAT Motion',
        repo_url: 'https://github.com/TcOpenGroup/TcOpen',
        stars: '500+',
        what_to_learn: 'Study PLCopen motion function blocks: MC_MoveAbsolute, MC_MoveRelative, cam tables',
        what_to_learn_zh: '学习PLCopen运动功能块：MC_MoveAbsolute、MC_MoveRelative、凸轮表',
        estimated_hours: 20,
      },
      {
        order: 3,
        repo_name: 'GRBL',
        repo_url: 'https://github.com/gnea/grbl',
        stars: '5.5k+',
        what_to_learn: 'Embedded motion control: acceleration planning, step generation, real-time constraints',
        what_to_learn_zh: '嵌入式运动控制：加速度规划、脉冲生成、实时约束',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'Multi-Axis Pick-and-Place with Electronic Cam Profile',
      title_zh: '带电子凸轮的多轴拾放运动控制',
      difficulty: 'advanced',
      time_hours: 45,
      deliverables: [
        'TwinCAT 3 or LinuxCNC project with 3+ coordinated axes',
        'Electronic cam profile for synchronized motion',
        'Simulation or real hardware demo with position/velocity plots',
        'Technical document: motion profile calculations, settling time analysis',
      ],
      deliverables_zh: [
        'TwinCAT 3或LinuxCNC项目（3+协调轴）',
        '电子凸轮配置实现同步运动',
        '仿真或实物演示（含位置/速度曲线）',
        '技术文档：运动曲线计算、定位时间分析',
      ],
      proves_to_employer: 'Can design and tune multi-axis motion control systems with electronic camming and coordinated motion',
      proves_to_employer_zh: '能够设计和调试带电子凸轮和协调运动的多轴运动控制系统',
    },
    monetization_potential: 'affiliate',
  },
];
