import type { IndustryToolMapEntry } from './types';

export const medicalDevicesEntries: IndustryToolMapEntry[] = [
  // ── 1. ISO 13485 / FDA 21 CFR ────────────────────────────────────────
  {
    id: 'med-iso13485',
    skill: 'ISO 13485 / FDA 21 CFR 820',
    skill_zh: 'ISO 13485/FDA 21 CFR 820医疗器械质量',
    industry: 'medical-devices',
    industry_context: 'ISO 13485 is the international QMS standard for medical devices; FDA 21 CFR Part 820 is the US equivalent. Both are mandatory for market access and require robust CAPA, risk management, and document control.',
    industry_context_zh: 'ISO 13485是医疗器械国际质量管理体系标准，FDA 21 CFR Part 820是美国等效要求。两者都是市场准入的强制要求，需要完善的CAPA、风险管理和文件控制。',
    tools: [
      {
        name: 'Greenlight Guru',
        name_zh: 'Greenlight Guru医疗器械QMS',
        vendor: 'Greenlight Guru',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.greenlight.guru/',
        alternatives: ['MasterControl', 'Qualio', 'Veeva Vault Quality'],
      },
      {
        name: 'MasterControl',
        name_zh: 'MasterControl质量管理',
        vendor: 'MasterControl',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.mastercontrol.com/',
      },
      {
        name: 'Jama Connect',
        name_zh: 'Jama Connect需求管理',
        vendor: 'Jama Software',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: '30-day free trial for requirements management',
        url: 'https://www.jamasoftware.com/',
      },
    ],
    training: [
      {
        name: 'BSI — ISO 13485 Lead Auditor',
        name_zh: 'BSI ISO 13485主任审核员',
        region: 'global',
        url: 'https://www.bsigroup.com/en-GB/our-services/training/',
        price_range: '£1500-3000',
        format: 'hybrid',
        certification: 'IRCA Certified Lead Auditor (ISO 13485)',
        language: ['en'],
      },
      {
        name: 'TUV SUD — Medical Device QMS',
        name_zh: 'TUV南德医疗器械质量管理培训',
        region: 'DE',
        url: 'https://www.tuvsud.com/en/services/training',
        price_range: '€1500-4000',
        format: 'hybrid',
        certification: 'TUV Medical Device QMS Auditor',
        language: ['de', 'en'],
      },
      {
        name: 'RAPS — Regulatory Affairs Certificate',
        name_zh: 'RAPS法规事务认证',
        region: 'global',
        url: 'https://www.raps.org/rac',
        price_range: '$3000-6000',
        format: 'hybrid',
        certification: 'RAC (Regulatory Affairs Certification)',
        language: ['en'],
      },
      {
        name: '中国食品药品国际交流中心培训',
        name_zh: '中国医疗器械法规培训（CFDI）',
        region: 'CN',
        url: 'https://www.cfdi.org.cn/',
        price_range: '¥2000-6000',
        format: 'hybrid',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'OpenRegulatory Templates',
        repo_url: 'https://github.com/openregulatory/templates',
        stars: '300+',
        what_to_learn: 'Medical device QMS document templates: SOPs, risk management, design controls per ISO 13485',
        what_to_learn_zh: '医疗器械QMS文档模板：SOP、风险管理、ISO 13485设计控制',
        estimated_hours: 15,
      },
      {
        order: 2,
        repo_name: 'SOUP (Software of Unknown Provenance) Management',
        repo_url: 'https://github.com/openregulatory/openregulatory.github.io',
        stars: '100+',
        what_to_learn: 'Understand regulatory requirements for open-source software in medical devices (SOUP management)',
        what_to_learn_zh: '理解医疗器械中开源软件的法规要求（SOUP管理）',
        estimated_hours: 10,
      },
      {
        order: 3,
        repo_name: 'FDA 510(k) Database API',
        repo_url: 'https://github.com/FDA/openfda',
        stars: '1.2k+',
        what_to_learn: 'Explore FDA device databases: predicate device search, adverse event analysis, recall data',
        what_to_learn_zh: '探索FDA器械数据库：等同器械检索、不良事件分析、召回数据',
        estimated_hours: 10,
      },
    ],
    capstone: {
      title: 'ISO 13485 QMS Implementation for a Class II Medical Device Startup',
      title_zh: 'II类医疗器械创业公司ISO 13485体系搭建',
      difficulty: 'intermediate',
      time_hours: 45,
      deliverables: [
        'Quality manual with ISO 13485:2016 clause mapping',
        'Risk management file per ISO 14971 (hazard analysis, risk matrix)',
        'CAPA procedure with workflow diagram',
        'Supplier qualification procedure and approved supplier list template',
      ],
      deliverables_zh: [
        '符合ISO 13485:2016条款映射的质量手册',
        'ISO 14971风险管理文件（危害分析、风险矩阵）',
        'CAPA程序含流程图',
        '供应商评审程序和合格供应商清单模板',
      ],
      proves_to_employer: 'Can build an ISO 13485 QMS from scratch for a medical device company seeking regulatory approval',
      proves_to_employer_zh: '能够从零搭建ISO 13485质量管理体系，助力医疗器械公司获取法规批准',
    },
    monetization_potential: 'affiliate',
  },

  // ── 2. IEC 62304 Software ─────────────────────────────────────────────
  {
    id: 'med-iec62304',
    skill: 'IEC 62304 Medical Software',
    skill_zh: 'IEC 62304医疗软件',
    industry: 'medical-devices',
    industry_context: 'IEC 62304 governs the software development lifecycle for medical devices, including SaMD (Software as a Medical Device). Safety classification (A/B/C) determines the rigor of documentation, testing, and maintenance.',
    industry_context_zh: 'IEC 62304规范医疗器械软件开发生命周期，包括SaMD（软件作为医疗器械）。安全分类（A/B/C）决定文档、测试和维护的严格程度。',
    tools: [
      {
        name: 'Jama Connect',
        name_zh: 'Jama Connect需求追溯',
        vendor: 'Jama Software',
        tier: 'essential',
        free_tier: true,
        free_tier_note: '30-day trial',
        url: 'https://www.jamasoftware.com/',
        alternatives: ['Polarion (Siemens)', 'Helix RM (Perforce)'],
      },
      {
        name: 'SonarQube',
        name_zh: 'SonarQube代码质量',
        vendor: 'SonarSource',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Community Edition free and open-source',
        url: 'https://www.sonarsource.com/products/sonarqube/',
      },
      {
        name: 'GitHub Actions + Git',
        name_zh: 'GitHub Actions + Git版本控制',
        vendor: 'GitHub',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free for public repos; 2000 min/month for private',
        url: 'https://github.com/features/actions',
      },
    ],
    training: [
      {
        name: 'Johner Institute — IEC 62304 Training',
        name_zh: 'Johner研究所IEC 62304培训',
        region: 'DE',
        url: 'https://www.johner-institut.de/',
        price_range: '€1500-3500',
        format: 'hybrid',
        certification: 'Johner IEC 62304 Certificate',
        language: ['de', 'en'],
      },
      {
        name: 'AAMI — Software Lifecycle for Medical Devices',
        name_zh: 'AAMI医疗设备软件生命周期',
        region: 'global',
        url: 'https://www.aami.org/',
        price_range: '$1000-3000',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'Udemy — IEC 62304 Practical Guide',
        name_zh: 'Udemy IEC 62304实用指南',
        region: 'global',
        url: 'https://www.udemy.com/topic/medical-device-development/',
        price_range: '¥79-299',
        format: 'online',
        language: ['en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'OpenRegulatory — IEC 62304 Templates',
        repo_url: 'https://github.com/openregulatory/templates',
        stars: '300+',
        what_to_learn: 'Software development plan, architecture docs, and testing documentation per IEC 62304',
        what_to_learn_zh: '按IEC 62304的软件开发计划、架构文档和测试文档',
        estimated_hours: 15,
      },
      {
        order: 2,
        repo_name: 'OpenFDA',
        repo_url: 'https://github.com/FDA/openfda',
        stars: '1.2k+',
        what_to_learn: 'Understand FDA software validation expectations through a real government open-source project',
        what_to_learn_zh: '通过真实的政府开源项目理解FDA软件验证期望',
        estimated_hours: 10,
      },
      {
        order: 3,
        repo_name: 'OWASP Medical Device Security',
        repo_url: 'https://github.com/OWASP/www-project-medical-device-security',
        stars: '100+',
        what_to_learn: 'Cybersecurity requirements for medical software: threat modeling, secure coding, penetration testing',
        what_to_learn_zh: '医疗软件网络安全要求：威胁建模、安全编码、渗透测试',
        estimated_hours: 10,
      },
    ],
    capstone: {
      title: 'IEC 62304 Class B Software Lifecycle for a Patient Monitoring App',
      title_zh: 'IEC 62304 B级患者监测App软件生命周期',
      difficulty: 'advanced',
      time_hours: 50,
      deliverables: [
        'Software Development Plan (SDP) per IEC 62304',
        'Software Requirements Specification with risk traceability (ISO 14971)',
        'Implemented app prototype with unit tests and integration tests',
        'Software release package: test reports, anomaly list, release notes',
      ],
      deliverables_zh: [
        '按IEC 62304的软件开发计划（SDP）',
        '含风险追溯的软件需求规格书（ISO 14971）',
        '实现的App原型含单元测试和集成测试',
        '软件发布包：测试报告、异常清单、发布说明',
      ],
      proves_to_employer: 'Can execute a complete IEC 62304 software lifecycle for a medical device with full documentation',
      proves_to_employer_zh: '能够执行完整的IEC 62304医疗器械软件生命周期并提供完整文档',
    },
    monetization_potential: 'affiliate',
  },

  // ── 3. Design Controls (DHF/DMR) ──────────────────────────────────────
  {
    id: 'med-design-controls',
    skill: 'Design Controls (DHF/DMR)',
    skill_zh: '设计控制（DHF/DMR）',
    industry: 'medical-devices',
    industry_context: 'Design Controls are required by FDA 21 CFR 820.30 and ISO 13485 clause 7.3. The Design History File (DHF) documents the entire design process; the Device Master Record (DMR) captures the final approved design.',
    industry_context_zh: '设计控制是FDA 21 CFR 820.30和ISO 13485第7.3条的要求。设计历史文件（DHF）记录整个设计过程；器械主记录（DMR）记录最终批准的设计。',
    tools: [
      {
        name: 'Greenlight Guru (Design Controls)',
        name_zh: 'Greenlight Guru设计控制模块',
        vendor: 'Greenlight Guru',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.greenlight.guru/design-controls',
        alternatives: ['Arena PLM', 'Omnify Empower'],
      },
      {
        name: 'Arena PLM',
        name_zh: 'Arena PLM产品生命周期管理',
        vendor: 'PTC',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.ptc.com/en/products/arena',
      },
      {
        name: 'draw.io / diagrams.net',
        name_zh: 'draw.io流程图工具',
        vendor: 'Open Source',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free and open-source — excellent for design input/output flowcharts',
        url: 'https://www.drawio.com/',
      },
    ],
    training: [
      {
        name: 'Greenlight Guru Academy',
        name_zh: 'Greenlight Guru学院',
        region: 'global',
        url: 'https://www.greenlight.guru/academy',
        price_range: 'Free',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'ASQ — Certified Quality Engineer (Medical)',
        name_zh: 'ASQ注册质量工程师（医疗）',
        region: 'global',
        url: 'https://asq.org/cert/quality-engineer',
        price_range: '$500-1500',
        format: 'hybrid',
        certification: 'ASQ CQE',
        language: ['en'],
      },
      {
        name: 'TUV Rheinland — Design Controls Workshop',
        name_zh: 'TUV莱茵设计控制研讨会',
        region: 'DE',
        url: 'https://www.tuv.com/world/en/medical-device-training.html',
        price_range: '€1000-3000',
        format: 'hybrid',
        language: ['de', 'en'],
      },
      {
        name: '上海医疗器械行业协会培训',
        name_zh: '上海医疗器械行业协会培训',
        region: 'CN',
        url: 'https://www.smdia.org.cn/',
        price_range: '¥1500-5000',
        format: 'hybrid',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'OpenRegulatory — Design Control Templates',
        repo_url: 'https://github.com/openregulatory/templates',
        stars: '300+',
        what_to_learn: 'Design input, design output, verification & validation document templates',
        what_to_learn_zh: '设计输入、设计输出、验证与确认文档模板',
        estimated_hours: 10,
      },
      {
        order: 2,
        repo_name: 'OpenFDA Device Classification',
        repo_url: 'https://github.com/FDA/openfda',
        stars: '1.2k+',
        what_to_learn: 'Research device classification, predicate devices, and regulatory pathways (510(k) vs PMA)',
        what_to_learn_zh: '研究器械分类、等同器械和法规路径（510(k) vs PMA）',
        estimated_hours: 8,
      },
      {
        order: 3,
        repo_name: 'Risk Management (ISO 14971 tools)',
        repo_url: 'https://github.com/openregulatory/openregulatory.github.io',
        stars: '100+',
        what_to_learn: 'ISO 14971 risk management integration with design controls: FTA, FMEA for medical devices',
        what_to_learn_zh: 'ISO 14971风险管理与设计控制集成：FTA、FMEA用于医疗器械',
        estimated_hours: 12,
      },
    ],
    capstone: {
      title: 'Complete Design History File for a Class II Wearable Medical Device',
      title_zh: 'II类可穿戴医疗器械完整设计历史文件',
      difficulty: 'intermediate',
      time_hours: 40,
      deliverables: [
        'Design input document (user needs → design requirements with acceptance criteria)',
        'Design output document (specifications, drawings, BOM)',
        'Verification test protocols and reports (bench testing)',
        'Design review meeting minutes and traceability matrix (input → output → V&V)',
      ],
      deliverables_zh: [
        '设计输入文档（用户需求 → 设计要求含接受准则）',
        '设计输出文档（规格、图纸、BOM）',
        '验证测试方案和报告（台架测试）',
        '设计评审会议记录和追溯矩阵（输入 → 输出 → V&V）',
      ],
      proves_to_employer: 'Can manage the full design control process and produce a complete DHF ready for FDA/notified body submission',
      proves_to_employer_zh: '能够管理完整的设计控制流程并生成可提交FDA/公告机构的DHF',
    },
    monetization_potential: 'affiliate',
  },

  // ── 4. Validation (IQ/OQ/PQ) ──────────────────────────────────────────
  {
    id: 'med-validation',
    skill: 'Validation (IQ/OQ/PQ)',
    skill_zh: '验证（IQ/OQ/PQ）',
    industry: 'medical-devices',
    industry_context: 'Equipment and process validation (IQ/OQ/PQ) is required by FDA and ISO 13485 to prove that manufacturing processes consistently produce conforming product. Critical for sterilization, molding, welding, and cleanroom processes.',
    industry_context_zh: '设备和过程验证（IQ/OQ/PQ）是FDA和ISO 13485要求的，以证明制造过程持续生产合格产品。对灭菌、注塑、焊接和洁净室过程至关重要。',
    tools: [
      {
        name: 'ValGenesis VLMS',
        name_zh: 'ValGenesis验证管理',
        vendor: 'ValGenesis',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.valgenesis.com/',
        alternatives: ['Kneat.com', 'MasterControl Validation'],
      },
      {
        name: 'Minitab (Process Capability)',
        name_zh: 'Minitab过程能力分析',
        vendor: 'Minitab LLC',
        tier: 'essential',
        free_tier: true,
        free_tier_note: '30-day trial; student license available',
        url: 'https://www.minitab.com/',
      },
      {
        name: 'Python + SciPy (Statistical Validation)',
        name_zh: 'Python + SciPy统计验证',
        vendor: 'Open Source',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Open-source statistical analysis',
        url: 'https://scipy.org/',
      },
    ],
    training: [
      {
        name: 'PDA (Parenteral Drug Association) — Validation',
        name_zh: 'PDA验证培训',
        region: 'global',
        url: 'https://www.pda.org/education',
        price_range: '$1000-3000',
        format: 'hybrid',
        certification: 'PDA Validation Certificate',
        language: ['en'],
      },
      {
        name: 'ISPE — Process Validation',
        name_zh: 'ISPE过程验证培训',
        region: 'global',
        url: 'https://ispe.org/training',
        price_range: '$800-2500',
        format: 'hybrid',
        certification: 'ISPE Validation Professional',
        language: ['en'],
      },
      {
        name: 'TUV Rheinland — Medical Device Validation',
        name_zh: 'TUV莱茵医疗器械验证培训',
        region: 'DE',
        url: 'https://www.tuv.com/world/en/medical-device-training.html',
        price_range: '€1000-3000',
        format: 'hybrid',
        language: ['de', 'en'],
      },
      {
        name: '中国医疗器械行业协会验证培训',
        name_zh: '中国医疗器械协会验证培训',
        region: 'CN',
        url: 'https://www.camdi.org/',
        price_range: '¥1500-5000',
        format: 'hybrid',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'SciPy — Statistical Tests',
        repo_url: 'https://github.com/scipy/scipy',
        stars: '13k+',
        what_to_learn: 'Statistical methods for validation: normality tests, capability analysis, sample size calculation',
        what_to_learn_zh: '验证统计方法：正态性检验、过程能力分析、样本量计算',
        estimated_hours: 15,
      },
      {
        order: 2,
        repo_name: 'pyspc — Statistical Process Control',
        repo_url: 'https://github.com/carlosqsilva/pyspc',
        stars: '200+',
        what_to_learn: 'Build SPC charts and capability studies (Ppk/Cpk) for IQ/OQ/PQ validation',
        what_to_learn_zh: '构建SPC控制图和过程能力研究（Ppk/Cpk）用于IQ/OQ/PQ验证',
        estimated_hours: 10,
      },
      {
        order: 3,
        repo_name: 'reliability — Python Reliability Engineering',
        repo_url: 'https://github.com/MatthewReid854/reliability',
        stars: '600+',
        what_to_learn: 'Reliability analysis: Weibull, sample size for reliability demonstration testing',
        what_to_learn_zh: '可靠性分析：Weibull分布、可靠性验证测试的样本量',
        estimated_hours: 12,
      },
    ],
    capstone: {
      title: 'Process Validation (IQ/OQ/PQ) for an Injection Molding Process',
      title_zh: '注塑成型过程验证（IQ/OQ/PQ）',
      difficulty: 'intermediate',
      time_hours: 35,
      deliverables: [
        'Validation Master Plan (VMP) for the injection molding process',
        'IQ protocol: equipment verification, utility checks, calibration records',
        'OQ protocol: DOE for critical process parameters (temperature, pressure, cycle time)',
        'PQ protocol: 3-lot study with Ppk/Cpk analysis and acceptance criteria',
      ],
      deliverables_zh: [
        '注塑过程验证主计划（VMP）',
        'IQ方案：设备确认、公用工程检查、校准记录',
        'OQ方案：关键工艺参数DOE（温度、压力、周期时间）',
        'PQ方案：3批次研究含Ppk/Cpk分析和接受准则',
      ],
      proves_to_employer: 'Can plan and execute IQ/OQ/PQ validation for manufacturing processes per FDA and ISO requirements',
      proves_to_employer_zh: '能够按FDA和ISO要求规划和执行制造过程IQ/OQ/PQ验证',
    },
    monetization_potential: 'affiliate',
  },

  // ── 5. Biocompatibility / Sterilization ───────────────────────────────
  {
    id: 'med-biocompat',
    skill: 'Biocompatibility / Sterilization',
    skill_zh: '生物相容性/灭菌',
    industry: 'medical-devices',
    industry_context: 'ISO 10993 governs biocompatibility testing for materials in contact with the body. Sterilization validation (EO, gamma, e-beam) per ISO 11135/11137 is mandatory for sterile devices. These are the most common FDA warning letter topics.',
    industry_context_zh: 'ISO 10993规范与人体接触材料的生物相容性测试。灭菌验证（环氧乙烷、伽马、电子束）遵循ISO 11135/11137，是无菌器械的强制要求。这些是FDA警告信中最常见的主题。',
    tools: [
      {
        name: 'NAMSA Testing Services Portal',
        name_zh: 'NAMSA测试服务平台',
        vendor: 'NAMSA',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.namsa.com/',
        alternatives: ['Nelson Labs (Sotera Health)', 'WuXi AppTec Medical Device Testing'],
      },
      {
        name: 'Toxikon / Toxicology Database',
        name_zh: '毒理学数据库',
        vendor: 'Various',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'FDA MAUDE database is free for adverse event research',
        url: 'https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfmaude/search.cfm',
      },
      {
        name: 'BPAC (Biocompatibility Package)',
        name_zh: '生物相容性评估包',
        vendor: 'Internal (company-specific)',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'ISO 10993-1 flowchart is publicly available',
        url: 'https://www.iso.org/standard/68936.html',
      },
    ],
    training: [
      {
        name: 'NAMSA — Biocompatibility Workshops',
        name_zh: 'NAMSA生物相容性研讨会',
        region: 'global',
        url: 'https://www.namsa.com/education/',
        price_range: '$500-2000',
        format: 'hybrid',
        language: ['en'],
      },
      {
        name: 'AAMI — Sterilization Standards',
        name_zh: 'AAMI灭菌标准培训',
        region: 'global',
        url: 'https://www.aami.org/',
        price_range: '$500-2000',
        format: 'online',
        language: ['en'],
      },
      {
        name: 'TUV SUD — Biocompatibility (ISO 10993)',
        name_zh: 'TUV南德生物相容性培训',
        region: 'DE',
        url: 'https://www.tuvsud.com/en/services/training',
        price_range: '€1000-2500',
        format: 'hybrid',
        language: ['de', 'en'],
      },
      {
        name: '苏州医疗器械检测中心培训',
        name_zh: '苏州医疗器械检测中心培训',
        region: 'CN',
        url: 'https://www.cmdc.org.cn/',
        price_range: '¥2000-5000',
        format: 'hybrid',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'OpenFDA — MAUDE Device Adverse Events',
        repo_url: 'https://github.com/FDA/openfda',
        stars: '1.2k+',
        what_to_learn: 'Mine FDA adverse event data to understand real biocompatibility failures and sterilization issues',
        what_to_learn_zh: '挖掘FDA不良事件数据，了解真实的生物相容性失败和灭菌问题',
        estimated_hours: 10,
      },
      {
        order: 2,
        repo_name: 'BioPython — Toxicology Analysis',
        repo_url: 'https://github.com/biopython/biopython',
        stars: '4k+',
        what_to_learn: 'Biological data analysis fundamentals applicable to biocompatibility test result interpretation',
        what_to_learn_zh: '适用于生物相容性测试结果分析的生物数据分析基础',
        estimated_hours: 12,
      },
      {
        order: 3,
        repo_name: 'RDKit — Chemistry Toolkit',
        repo_url: 'https://github.com/rdkit/rdkit',
        stars: '2.7k+',
        what_to_learn: 'Chemical structure analysis for material characterization and extractable/leachable studies',
        what_to_learn_zh: '化学结构分析用于材料表征和可提取物/可浸出物研究',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'Biocompatibility Evaluation and Sterilization Validation Plan for a Surgical Instrument',
      title_zh: '手术器械生物相容性评估和灭菌验证计划',
      difficulty: 'intermediate',
      time_hours: 35,
      deliverables: [
        'Biological evaluation plan per ISO 10993-1 (material characterization, endpoint selection)',
        'Biocompatibility test matrix with rationale for test selection or exemption',
        'EO sterilization validation protocol per ISO 11135 (half-cycle approach)',
        'Sterile barrier system validation per ISO 11607 (seal strength, aging studies)',
      ],
      deliverables_zh: [
        '按ISO 10993-1的生物学评价计划（材料表征、终点选择）',
        '生物相容性测试矩阵含测试选择或豁免理由',
        '按ISO 11135的EO灭菌验证方案（半周期法）',
        '按ISO 11607的无菌屏障系统验证（密封强度、老化试验）',
      ],
      proves_to_employer: 'Can plan biocompatibility testing per ISO 10993 and sterilization validation per ISO 11135/11137',
      proves_to_employer_zh: '能够按ISO 10993规划生物相容性测试并按ISO 11135/11137规划灭菌验证',
    },
    monetization_potential: 'none',
  },
];
