import type { IndustryToolMapEntry } from './types';

export const processManufacturingEntries: IndustryToolMapEntry[] = [
  // ── 1. Process Simulation (Aspen HYSYS) ───────────────────────────────
  {
    id: 'proc-hysys',
    skill: 'Process Simulation',
    skill_zh: '流程模拟',
    industry: 'process-manufacturing',
    industry_context: 'Aspen HYSYS and Aspen Plus are the industry standard for chemical/petrochemical process simulation — heat & mass balance, equipment sizing, and economic evaluation. Essential for process design engineers.',
    industry_context_zh: 'Aspen HYSYS和Aspen Plus是化工/石化流程模拟的行业标准——热量质量平衡、设备选型和经济评估。是工艺设计工程师的核心工具。',
    tools: [
      {
        name: 'Aspen HYSYS',
        name_zh: 'Aspen HYSYS',
        vendor: 'AspenTech',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'Free student license via aspenONE for Education',
        url: 'https://www.aspentech.com/en/products/engineering/aspen-hysys',
        alternatives: ['Aspen Plus', 'PRO/II (AVEVA)', 'ChemCAD'],
      },
      {
        name: 'DWSIM',
        name_zh: 'DWSIM开源流程模拟',
        vendor: 'Open Source',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Fully open-source process simulator, GPL license',
        url: 'https://dwsim.org/',
      },
      {
        name: 'COCO/COFE (CAPE-OPEN)',
        name_zh: 'COCO/COFE流程模拟',
        vendor: 'AmsterCHEM',
        tier: 'emerging',
        free_tier: true,
        free_tier_note: 'Free CAPE-OPEN compliant simulator with thermodynamic packages',
        url: 'https://www.cocosimulator.org/',
      },
    ],
    training: [
      {
        name: 'AspenTech University',
        name_zh: 'AspenTech大学',
        region: 'global',
        url: 'https://esupport.aspentech.com/s/training',
        price_range: '$500-3000',
        format: 'online',
        certification: 'AspenTech Certified User',
        language: ['en'],
      },
      {
        name: 'Coursera — Chemical Engineering: Process Modeling',
        name_zh: 'Coursera化工过程建模',
        region: 'global',
        url: 'https://www.coursera.org/courses?query=chemical%20engineering',
        price_range: 'Free (audit)',
        format: 'online',
        language: ['en'],
      },
      {
        name: '华东理工大学化工过程模拟培训',
        name_zh: '华东理工化工模拟培训',
        region: 'CN',
        url: 'https://www.ecust.edu.cn/',
        price_range: '¥1000-5000',
        format: 'hybrid',
        language: ['zh'],
      },
      {
        name: 'DECHEMA — Process Engineering Courses',
        name_zh: 'DECHEMA过程工程课程',
        region: 'DE',
        url: 'https://dechema.de/en/courses.html',
        price_range: '€800-3000',
        format: 'hybrid',
        language: ['de', 'en'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'DWSIM',
        repo_url: 'https://github.com/DanWBR/dwsim',
        stars: '500+',
        what_to_learn: 'Process simulation fundamentals: thermodynamic models, unit operations, flowsheet convergence',
        what_to_learn_zh: '流程模拟基础：热力学模型、单元操作、流程图收敛',
        estimated_hours: 25,
      },
      {
        order: 2,
        repo_name: 'Cantera — Chemical Kinetics',
        repo_url: 'https://github.com/Cantera/cantera',
        stars: '600+',
        what_to_learn: 'Chemical reaction engineering: kinetics, equilibrium, reactor modeling',
        what_to_learn_zh: '化学反应工程：动力学、平衡、反应器建模',
        estimated_hours: 20,
      },
      {
        order: 3,
        repo_name: 'CoolProp — Thermophysical Properties',
        repo_url: 'https://github.com/CoolProp/CoolProp',
        stars: '800+',
        what_to_learn: 'Thermophysical property calculations: equation of state, transport properties, mixture models',
        what_to_learn_zh: '热物性计算：状态方程、输运性质、混合物模型',
        estimated_hours: 10,
      },
    ],
    capstone: {
      title: 'Crude Oil Distillation Unit Process Simulation and Heat Integration',
      title_zh: '原油蒸馏装置流程模拟与热集成',
      difficulty: 'advanced',
      time_hours: 50,
      deliverables: [
        'HYSYS or DWSIM model of a crude distillation unit (CDU) with 5+ product streams',
        'Heat exchanger network design using pinch analysis',
        'Equipment sizing: column diameter, tray specifications, condenser/reboiler duty',
        'Economic evaluation: CAPEX/OPEX estimate, energy cost savings from heat integration',
      ],
      deliverables_zh: [
        'HYSYS或DWSIM原油蒸馏装置模型（5+产品流）',
        '基于夹点分析的换热网络设计',
        '设备选型：塔径、塔盘规格、冷凝器/再沸器负荷',
        '经济评估：CAPEX/OPEX估算、热集成节能分析',
      ],
      proves_to_employer: 'Can design and simulate industrial-scale chemical processes with heat integration and economic analysis',
      proves_to_employer_zh: '能够设计和模拟工业规模化工过程，含热集成和经济分析',
    },
    monetization_potential: 'affiliate',
  },

  // ── 2. DCS / Process Control (DeltaV / Honeywell) ─────────────────────
  {
    id: 'proc-dcs',
    skill: 'DCS / Process Control',
    skill_zh: 'DCS/过程控制',
    industry: 'process-manufacturing',
    industry_context: 'DCS (Distributed Control System) is the backbone of process industry control — refineries, chemical plants, power plants. DeltaV (Emerson) and Honeywell Experion are the dominant platforms. Advanced process control (APC) is a high-value skill.',
    industry_context_zh: 'DCS分散控制系统是过程工业控制的核心——炼油厂、化工厂、发电厂。DeltaV（艾默生）和霍尼韦尔Experion是主流平台。先进过程控制（APC）是高价值技能。',
    tools: [
      {
        name: 'Emerson DeltaV',
        name_zh: '艾默生DeltaV',
        vendor: 'Emerson',
        tier: 'essential',
        free_tier: true,
        free_tier_note: 'DeltaV Simulate free for educational use',
        url: 'https://www.emerson.com/en-us/automation/deltav',
        alternatives: ['Honeywell Experion', 'ABB Ability 800xA', 'Yokogawa CENTUM VP'],
      },
      {
        name: 'MATLAB / Simulink — Control System Toolbox',
        name_zh: 'MATLAB/Simulink控制系统工具箱',
        vendor: 'MathWorks',
        tier: 'recommended',
        free_tier: false,
        url: 'https://www.mathworks.com/products/control.html',
        alternatives: ['GNU Octave (free)', 'Scilab (free)'],
      },
      {
        name: 'Python Control Systems Library',
        name_zh: 'Python控制系统库',
        vendor: 'Open Source',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Open-source python-control library',
        url: 'https://python-control.readthedocs.io/',
      },
    ],
    training: [
      {
        name: 'Emerson Educational Services — DeltaV',
        name_zh: '艾默生教育服务DeltaV培训',
        region: 'global',
        url: 'https://www.emerson.com/en-us/automation/services-consulting/educational-services',
        price_range: '$2000-5000',
        format: 'hybrid',
        certification: 'Emerson DeltaV Certified',
        language: ['en'],
      },
      {
        name: 'ISA — Control Systems Engineer (CSE)',
        name_zh: 'ISA控制系统工程师认证',
        region: 'global',
        url: 'https://www.isa.org/certification/cse',
        price_range: '$500-2000',
        format: 'hybrid',
        certification: 'ISA CSE (Certified Control Systems Engineer)',
        language: ['en'],
      },
      {
        name: 'NAMUR (German Process Automation)',
        name_zh: 'NAMUR德国过程自动化培训',
        region: 'DE',
        url: 'https://www.namur.net/',
        price_range: '€1000-3000',
        format: 'hybrid',
        language: ['de', 'en'],
      },
      {
        name: '中控技术学院',
        name_zh: '中控技术学院DCS培训',
        region: 'CN',
        url: 'https://www.supcon.com/',
        price_range: '¥2000-8000',
        format: 'hybrid',
        certification: '中控DCS工程师证书',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'python-control',
        repo_url: 'https://github.com/python-control/python-control',
        stars: '800+',
        what_to_learn: 'Control theory in Python: PID tuning, transfer functions, Bode/Nyquist plots, state-space',
        what_to_learn_zh: 'Python控制理论：PID整定、传递函数、Bode/Nyquist图、状态空间',
        estimated_hours: 20,
      },
      {
        order: 2,
        repo_name: 'OpenModelica',
        repo_url: 'https://github.com/OpenModelica/OpenModelica',
        stars: '800+',
        what_to_learn: 'Dynamic process modeling: simulate chemical reactors, heat exchangers, and control loops',
        what_to_learn_zh: '动态过程建模：仿真化学反应器、换热器和控制回路',
        estimated_hours: 25,
      },
      {
        order: 3,
        repo_name: 'APMonitor — Process Control',
        repo_url: 'https://github.com/APMonitor/data_science',
        stars: '300+',
        what_to_learn: 'Model predictive control (MPC) and advanced process control fundamentals',
        what_to_learn_zh: '模型预测控制（MPC）和先进过程控制基础',
        estimated_hours: 15,
      },
    ],
    capstone: {
      title: 'PID and MPC Controller Design for a Chemical Reactor',
      title_zh: '化学反应器PID与MPC控制器设计',
      difficulty: 'advanced',
      time_hours: 45,
      deliverables: [
        'Dynamic process model of a CSTR (Continuous Stirred-Tank Reactor)',
        'PID controller with auto-tuning (Ziegler-Nichols, IMC methods)',
        'Model Predictive Controller (MPC) implementation with constraint handling',
        'Performance comparison report: PID vs MPC (ISE, overshoot, disturbance rejection)',
      ],
      deliverables_zh: [
        'CSTR（连续搅拌釜式反应器）动态过程模型',
        '带自整定的PID控制器（Ziegler-Nichols、IMC方法）',
        '模型预测控制器（MPC）实现（含约束处理）',
        '性能对比报告：PID vs MPC（ISE、超调量、抗扰性能）',
      ],
      proves_to_employer: 'Can design both PID and MPC controllers for chemical processes and quantify control performance',
      proves_to_employer_zh: '能够为化工过程设计PID和MPC控制器并量化控制性能',
    },
    monetization_potential: 'affiliate',
  },

  // ── 3. HACCP / Food Safety ────────────────────────────────────────────
  {
    id: 'proc-haccp',
    skill: 'HACCP / Food Safety',
    skill_zh: 'HACCP/食品安全',
    industry: 'process-manufacturing',
    industry_context: 'HACCP (Hazard Analysis and Critical Control Points) is the global standard for food safety management. Paired with FSSC 22000 or SQF, it is mandatory for food manufacturers worldwide. Increasingly integrated with IoT and real-time monitoring.',
    industry_context_zh: 'HACCP（危害分析和关键控制点）是全球食品安全管理标准。与FSSC 22000或SQF结合，是全球食品生产商的强制要求。越来越多地与IoT和实时监控集成。',
    tools: [
      {
        name: 'SafetyChain Software',
        name_zh: 'SafetyChain食品安全管理',
        vendor: 'SafetyChain',
        tier: 'essential',
        free_tier: false,
        url: 'https://safetychain.com/',
        alternatives: ['Ideagen (formerly Achiever Plus)', 'FoodReady', 'Safefood360'],
      },
      {
        name: 'Safefood360',
        name_zh: 'Safefood360',
        vendor: 'Safefood360',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free trial available',
        url: 'https://safefood360.com/',
      },
      {
        name: 'Lucidchart (HACCP Flow Diagrams)',
        name_zh: 'Lucidchart流程图',
        vendor: 'Lucid Software',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free tier with limited diagrams',
        url: 'https://www.lucidchart.com/',
      },
    ],
    training: [
      {
        name: 'IFST — HACCP Training (UK)',
        name_zh: 'IFST HACCP培训（英国）',
        region: 'EU',
        url: 'https://www.ifst.org/',
        price_range: '£500-1500',
        format: 'hybrid',
        certification: 'IFST HACCP Certificate',
        language: ['en'],
      },
      {
        name: 'SGS — FSSC 22000 / HACCP',
        name_zh: 'SGS FSSC 22000/HACCP培训',
        region: 'global',
        url: 'https://www.sgs.com/en/our-services/training',
        price_range: '$500-2000',
        format: 'hybrid',
        certification: 'SGS HACCP Lead Auditor',
        language: ['en', 'zh'],
      },
      {
        name: 'Coursera — Food Safety (Johns Hopkins)',
        name_zh: 'Coursera食品安全（约翰霍普金斯）',
        region: 'global',
        url: 'https://www.coursera.org/learn/food-safety',
        price_range: 'Free (audit)',
        format: 'online',
        language: ['en'],
      },
      {
        name: '中国食品科学技术学会培训',
        name_zh: '中国食品科学技术学会HACCP培训',
        region: 'CN',
        url: 'https://www.cifst.org.cn/',
        price_range: '¥800-3000',
        format: 'hybrid',
        certification: 'HACCP内审员证书',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'Open Food Facts',
        repo_url: 'https://github.com/openfoodfacts/openfoodfacts-server',
        stars: '600+',
        what_to_learn: 'Food data models: ingredients, allergens, nutritional information — the digital side of food safety',
        what_to_learn_zh: '食品数据模型：配料、过敏原、营养信息——食品安全的数字化',
        estimated_hours: 10,
      },
      {
        order: 2,
        repo_name: 'FoodOntology',
        repo_url: 'https://github.com/FoodOntology/foodon',
        stars: '100+',
        what_to_learn: 'Food safety ontology: hazard classification, allergen tracking, traceability data models',
        what_to_learn_zh: '食品安全本体论：危害分类、过敏原追踪、追溯数据模型',
        estimated_hours: 8,
      },
      {
        order: 3,
        repo_name: 'Node-RED (IoT for Food Monitoring)',
        repo_url: 'https://github.com/node-red/node-red',
        stars: '20k+',
        what_to_learn: 'Build real-time temperature/humidity monitoring systems for cold chain and CCP monitoring',
        what_to_learn_zh: '构建实时温湿度监控系统用于冷链和CCP监控',
        estimated_hours: 12,
      },
    ],
    capstone: {
      title: 'HACCP Plan for a Dairy Processing Plant with IoT CCP Monitoring',
      title_zh: '乳品加工厂HACCP计划（含IoT CCP监控）',
      difficulty: 'intermediate',
      time_hours: 35,
      deliverables: [
        'Complete HACCP plan: hazard analysis, CCP identification, critical limits, monitoring procedures',
        'Process flow diagram for pasteurized milk production',
        'IoT prototype: temperature sensor → Node-RED → dashboard with CCP alerts',
        'Prerequisite program (PRP) documentation: cleaning, pest control, employee hygiene',
      ],
      deliverables_zh: [
        '完整HACCP计划：危害分析、CCP识别、关键限值、监控程序',
        '巴氏杀菌乳生产过程流程图',
        'IoT原型：温度传感器 → Node-RED → 含CCP报警的仪表盘',
        '前提方案（PRP）文档：清洁、虫害控制、员工卫生',
      ],
      proves_to_employer: 'Can develop a HACCP plan per Codex Alimentarius and integrate IoT for real-time CCP monitoring',
      proves_to_employer_zh: '能够按Codex Alimentarius制定HACCP计划并集成IoT实时CCP监控',
    },
    monetization_potential: 'none',
  },

  // ── 4. Pharma GMP (GAMP 5) ───────────────────────────────────────────
  {
    id: 'proc-gmp',
    skill: 'Pharma GMP / GAMP 5',
    skill_zh: '制药GMP/GAMP 5',
    industry: 'process-manufacturing',
    industry_context: 'GMP (Good Manufacturing Practice) is mandatory for pharmaceutical production worldwide. GAMP 5 provides guidance for computerized system validation. These skills command premium salaries due to regulatory complexity.',
    industry_context_zh: 'GMP良好生产规范是全球制药生产的强制要求。GAMP 5为计算机化系统验证提供指南。由于法规复杂性，这些技能薪资溢价显著。',
    tools: [
      {
        name: 'Kneat.com (Validation Management)',
        name_zh: 'Kneat验证管理平台',
        vendor: 'Kneat Solutions',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.kneat.com/',
        alternatives: ['ValGenesis', 'MasterControl Validation'],
      },
      {
        name: 'Veeva Vault Quality',
        name_zh: 'Veeva Vault质量管理',
        vendor: 'Veeva Systems',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.veeva.com/products/vault-quality/',
        alternatives: ['TrackWise (Honeywell)', 'ComplianceQuest'],
      },
      {
        name: 'EDMS (Electronic Document Management)',
        name_zh: '电子文档管理系统',
        vendor: 'Various',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Open-source options like OpenDocMan available',
        url: 'https://www.opendocman.com/',
      },
    ],
    training: [
      {
        name: 'ISPE — GAMP 5 Training',
        name_zh: 'ISPE GAMP 5培训',
        region: 'global',
        url: 'https://ispe.org/training',
        price_range: '$1000-3000',
        format: 'hybrid',
        certification: 'ISPE GAMP 5 Professional',
        language: ['en'],
      },
      {
        name: 'PDA — Pharmaceutical GMP',
        name_zh: 'PDA制药GMP培训',
        region: 'global',
        url: 'https://www.pda.org/education',
        price_range: '$1000-4000',
        format: 'hybrid',
        certification: 'PDA GMP Certificate',
        language: ['en'],
      },
      {
        name: 'GMP-Berater (Germany)',
        name_zh: 'GMP-Berater德国GMP培训',
        region: 'DE',
        url: 'https://www.gmp-verlag.de/',
        price_range: '€1000-3500',
        format: 'hybrid',
        language: ['de', 'en'],
      },
      {
        name: '中国药科大学GMP培训',
        name_zh: '中国药科大学GMP培训',
        region: 'CN',
        url: 'https://www.cpu.edu.cn/',
        price_range: '¥2000-6000',
        format: 'hybrid',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'OpenFDA — Drug APIs',
        repo_url: 'https://github.com/FDA/openfda',
        stars: '1.2k+',
        what_to_learn: 'Understand FDA drug databases: adverse events, recalls, labeling — the data behind GMP enforcement',
        what_to_learn_zh: '理解FDA药品数据库：不良事件、召回、标签——GMP执法背后的数据',
        estimated_hours: 10,
      },
      {
        order: 2,
        repo_name: 'ERPNext (Pharma Module)',
        repo_url: 'https://github.com/frappe/erpnext',
        stars: '20k+',
        what_to_learn: 'Study batch tracking, lot genealogy, and quality control modules needed for GMP compliance',
        what_to_learn_zh: '学习GMP合规所需的批次跟踪、批号系谱和质量控制模块',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'CSV (Computer System Validation) Templates',
        repo_url: 'https://github.com/openregulatory/templates',
        stars: '300+',
        what_to_learn: 'GAMP 5 validation templates: URS, FS, DS, test protocols — transferable to pharma CSV',
        what_to_learn_zh: 'GAMP 5验证模板：URS、FS、DS、测试方案——可迁移到制药CSV',
        estimated_hours: 12,
      },
    ],
    capstone: {
      title: 'GAMP 5 Computer System Validation for a MES in a Pharma Plant',
      title_zh: '制药工厂MES的GAMP 5计算机系统验证',
      difficulty: 'advanced',
      time_hours: 45,
      deliverables: [
        'Validation Plan per GAMP 5 (system categorization, risk assessment)',
        'User Requirements Specification (URS) for MES in pharma context',
        'IQ/OQ/PQ protocols with test scripts and expected results',
        'Validation Summary Report (VSR) with deviation handling',
      ],
      deliverables_zh: [
        '按GAMP 5的验证计划（系统分类、风险评估）',
        '制药MES用户需求规格书（URS）',
        'IQ/OQ/PQ方案含测试脚本和预期结果',
        '验证总结报告（VSR）含偏差处理',
      ],
      proves_to_employer: 'Can plan and execute GAMP 5 computer system validation in a GMP-regulated pharmaceutical environment',
      proves_to_employer_zh: '能够在GMP法规环境下规划和执行GAMP 5计算机系统验证',
    },
    monetization_potential: 'affiliate',
  },

  // ── 5. Chemical Safety (HAZOP) ────────────────────────────────────────
  {
    id: 'proc-hazop',
    skill: 'Chemical Safety / HAZOP',
    skill_zh: '化工安全/HAZOP',
    industry: 'process-manufacturing',
    industry_context: 'HAZOP (Hazard and Operability Study) is the gold standard for process safety risk assessment in chemical/petrochemical/oil&gas. Combined with LOPA and SIL, it determines the required safety integrity level for Safety Instrumented Systems.',
    industry_context_zh: 'HAZOP（危害与可操作性分析）是化工/石化/油气行业过程安全风险评估的黄金标准。结合LOPA和SIL确定安全仪表系统所需的安全完整性等级。',
    tools: [
      {
        name: 'PHA-Pro (Sphera)',
        name_zh: 'PHA-Pro过程安全分析',
        vendor: 'Sphera',
        tier: 'essential',
        free_tier: false,
        url: 'https://sphera.com/process-safety/',
        alternatives: ['PHAWorks (Primatech)', 'LEADER HAZOP (ABB)'],
      },
      {
        name: 'Phast/Safeti (DNV)',
        name_zh: 'Phast/Safeti后果分析',
        vendor: 'DNV',
        tier: 'essential',
        free_tier: false,
        url: 'https://www.dnv.com/services/process-hazard-analysis-software-phast/',
        alternatives: ['ALOHA (EPA, free)', 'EFFECTS (TNO)'],
      },
      {
        name: 'ALOHA (EPA/NOAA)',
        name_zh: 'ALOHA大气扩散模型',
        vendor: 'US EPA / NOAA',
        tier: 'recommended',
        free_tier: true,
        free_tier_note: 'Free atmospheric dispersion model for emergency response',
        url: 'https://www.epa.gov/cameo/aloha-software',
      },
    ],
    training: [
      {
        name: 'IChemE — HAZOP Training',
        name_zh: 'IChemE HAZOP培训',
        region: 'global',
        url: 'https://www.icheme.org/training/',
        price_range: '£1500-3500',
        format: 'hybrid',
        certification: 'IChemE HAZOP Leader Certificate',
        language: ['en'],
      },
      {
        name: 'TUV Rheinland — Functional Safety (SIL/IEC 61511)',
        name_zh: 'TUV莱茵功能安全培训',
        region: 'DE',
        url: 'https://www.tuv.com/world/en/functional-safety-training.html',
        price_range: '€2000-5000',
        format: 'hybrid',
        certification: 'TUV FS Engineer (IEC 61511)',
        language: ['de', 'en'],
      },
      {
        name: 'CCPS (AIChE) — Process Safety',
        name_zh: 'CCPS过程安全培训',
        region: 'global',
        url: 'https://www.aiche.org/ccps/education',
        price_range: '$1000-3000',
        format: 'hybrid',
        certification: 'CCPS Process Safety Certificate',
        language: ['en'],
      },
      {
        name: '中国化工安全协会培训',
        name_zh: '中国化工安全协会HAZOP培训',
        region: 'CN',
        url: 'https://www.chemicalsafety.org.cn/',
        price_range: '¥2000-6000',
        format: 'hybrid',
        certification: 'HAZOP分析师证书',
        language: ['zh'],
      },
    ],
    github_path: [
      {
        order: 1,
        repo_name: 'ALOHA Source (Consequence Modeling)',
        repo_url: 'https://github.com/USEPA/ALOHA',
        stars: '100+',
        what_to_learn: 'Consequence modeling: toxic gas dispersion, pool fire radiation, BLEVE overpressure',
        what_to_learn_zh: '后果建模：有毒气体扩散、池火热辐射、BLEVE超压',
        estimated_hours: 15,
      },
      {
        order: 2,
        repo_name: 'Cantera — Chemical Safety',
        repo_url: 'https://github.com/Cantera/cantera',
        stars: '600+',
        what_to_learn: 'Combustion and explosion modeling: flammability limits, auto-ignition temperatures',
        what_to_learn_zh: '燃烧和爆炸建模：可燃极限、自燃温度',
        estimated_hours: 15,
      },
      {
        order: 3,
        repo_name: 'Fault Tree Analysis — pyfta',
        repo_url: 'https://github.com/scipy/scipy',
        stars: '13k+',
        what_to_learn: 'Reliability and fault tree analysis using probability distributions — foundation for LOPA/SIL calculations',
        what_to_learn_zh: '使用概率分布的可靠性和故障树分析——LOPA/SIL计算的基础',
        estimated_hours: 12,
      },
    ],
    capstone: {
      title: 'HAZOP Study and SIL Assessment for a Chemical Reactor System',
      title_zh: '化学反应器系统HAZOP分析和SIL评估',
      difficulty: 'advanced',
      time_hours: 45,
      deliverables: [
        'HAZOP worksheets for a reactor + distillation system (10+ nodes)',
        'LOPA analysis for high-risk scenarios with SIL determination',
        'Safety Instrumented Function (SIF) specification for 2 critical loops',
        'Consequence modeling report: toxic release scenario using ALOHA',
      ],
      deliverables_zh: [
        '反应器+蒸馏系统HAZOP工作表（10+节点）',
        '高风险场景LOPA分析含SIL确定',
        '2个关键回路的安全仪表功能（SIF）规格',
        '后果建模报告：使用ALOHA的有毒物质泄漏场景',
      ],
      proves_to_employer: 'Can lead HAZOP studies, perform LOPA/SIL assessments, and specify safety instrumented functions',
      proves_to_employer_zh: '能够主持HAZOP分析、执行LOPA/SIL评估并制定安全仪表功能规格',
    },
    monetization_potential: 'affiliate',
  },
];
