import type { Job } from './data';

export const chinaJobs: Job[] = [
  // ============================================================
  // Manufacturing Engineering (制造工程) ~15 jobs
  // ============================================================
  {
    code: 'CN-PE',
    title: 'Process Engineer',
    title_zh: '工艺工程师',
    country: 'CN',
    opportunity_score: 62,
    breakdown: { salary: 55, competition: 50, growth: 60, barrier: 55, ai_resilience: 70, demand_growth: 60, remote: 15 },
    salary_display: '¥18K',
    salary_raw: 18000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['SPC', 'FMEA', 'Lean Manufacturing', 'AutoCAD', 'Six Sigma'],
    technology_skills: ['Minitab', 'SAP PP'],
    industry: 'manufacturing',
  },
  {
    code: 'CN-ME',
    title: 'Manufacturing Engineer',
    title_zh: '制造工程师',
    country: 'CN',
    opportunity_score: 63,
    breakdown: { salary: 58, competition: 48, growth: 62, barrier: 52, ai_resilience: 72, demand_growth: 62, remote: 10 },
    salary_display: '¥20K',
    salary_raw: 20000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Lean Manufacturing', 'Kaizen', 'DFM/DFA', 'AutoCAD', 'Root Cause Analysis', 'GD&T'],
    technology_skills: ['SAP PP', 'MES Systems'],
    industry: 'manufacturing',
  },
  {
    code: 'CN-CNC',
    title: 'CNC Programmer',
    title_zh: 'CNC编程工程师',
    country: 'CN',
    opportunity_score: 58,
    breakdown: { salary: 50, competition: 45, growth: 50, barrier: 60, ai_resilience: 65, demand_growth: 50, remote: 5 },
    salary_display: '¥15K',
    salary_raw: 15000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['G-code', 'Mastercam', 'Fanuc', 'Siemens NX CAM', 'GD&T'],
    technology_skills: ['Vericut', 'PowerMill'],
    industry: 'manufacturing',
  },
  {
    code: 'CN-TE',
    title: 'Tooling Engineer',
    title_zh: '模具工程师',
    country: 'CN',
    opportunity_score: 56,
    breakdown: { salary: 48, competition: 42, growth: 45, barrier: 58, ai_resilience: 72, demand_growth: 45, remote: 5 },
    salary_display: '¥14K',
    salary_raw: 14000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Mold Design', 'CATIA', 'UG/NX', 'Injection Molding', 'Die Casting'],
    technology_skills: ['Moldflow', 'AutoForm'],
    industry: 'manufacturing',
  },
  {
    code: 'CN-PLE',
    title: 'Plant Engineer',
    title_zh: '工厂工程师',
    country: 'CN',
    opportunity_score: 59,
    breakdown: { salary: 52, competition: 45, growth: 55, barrier: 50, ai_resilience: 68, demand_growth: 55, remote: 8 },
    salary_display: '¥16K',
    salary_raw: 16000,
    currency: 'CNY',
    source: 'Robert Walters Greater China Salary Survey 2025',
    skills: ['Facility Management', 'Utilities', 'HVAC', 'Project Management', 'Safety Standards'],
    technology_skills: ['AutoCAD', 'BMS Systems'],
    industry: 'manufacturing',
  },
  {
    code: 'CN-MNE',
    title: 'Maintenance Engineer',
    title_zh: '设备维护工程师',
    country: 'CN',
    opportunity_score: 55,
    breakdown: { salary: 45, competition: 40, growth: 48, barrier: 55, ai_resilience: 70, demand_growth: 50, remote: 5 },
    salary_display: '¥13K',
    salary_raw: 13000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['PLC', 'Preventive Maintenance', 'TPM', 'Hydraulics', 'Electrical Troubleshooting'],
    technology_skills: ['Siemens S7', 'CMMS'],
    industry: 'manufacturing',
  },
  {
    code: 'CN-LEAN',
    title: 'Lean Specialist',
    title_zh: '精益生产专家',
    country: 'CN',
    opportunity_score: 65,
    breakdown: { salary: 62, competition: 55, growth: 65, barrier: 48, ai_resilience: 60, demand_growth: 65, remote: 20 },
    salary_display: '¥22K',
    salary_raw: 22000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['Lean Manufacturing', 'Value Stream Mapping', 'Kaizen', '5S', 'TPM', 'Change Management'],
    technology_skills: ['Minitab', 'Power BI'],
    industry: 'manufacturing',
  },
  {
    code: 'CN-NPI',
    title: 'NPI Engineer',
    title_zh: '新产品导入工程师',
    country: 'CN',
    opportunity_score: 64,
    breakdown: { salary: 60, competition: 52, growth: 65, barrier: 50, ai_resilience: 68, demand_growth: 65, remote: 12 },
    salary_display: '¥20K',
    salary_raw: 20000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['APQP', 'PPAP', 'DFM/DFA', 'Project Management', 'Cross-functional Leadership'],
    technology_skills: ['SAP', 'PLM Systems'],
    industry: 'manufacturing',
  },
  {
    code: 'CN-RDE',
    title: 'R&D Engineer',
    title_zh: '研发工程师',
    country: 'CN',
    opportunity_score: 68,
    breakdown: { salary: 65, competition: 55, growth: 70, barrier: 58, ai_resilience: 72, demand_growth: 70, remote: 25 },
    salary_display: '¥25K',
    salary_raw: 25000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['Product Development', 'CAD/CAE', 'DFMEA', 'Prototyping', 'Patent Writing', 'DOE'],
    technology_skills: ['SolidWorks', 'ANSYS', 'MATLAB'],
    industry: 'manufacturing',
  },
  {
    code: 'CN-WE',
    title: 'Welding Engineer',
    title_zh: '焊接工程师',
    country: 'CN',
    opportunity_score: 54,
    breakdown: { salary: 48, competition: 38, growth: 45, barrier: 62, ai_resilience: 75, demand_growth: 45, remote: 5 },
    salary_display: '¥14K',
    salary_raw: 14000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['MIG/TIG/Spot Welding', 'Welding Metallurgy', 'WPS/PQR', 'NDT', 'Robot Programming'],
    technology_skills: ['Fanuc/ABB Robot', 'Fronius WeldConnect'],
    industry: 'manufacturing',
  },
  {
    code: 'CN-CFE',
    title: 'Casting/Forging Engineer',
    title_zh: '铸造/锻造工程师',
    country: 'CN',
    opportunity_score: 51,
    breakdown: { salary: 42, competition: 35, growth: 40, barrier: 60, ai_resilience: 78, demand_growth: 38, remote: 5 },
    salary_display: '¥12K',
    salary_raw: 12000,
    currency: 'CNY',
    source: 'Robert Walters Greater China Salary Survey 2025',
    skills: ['Metallurgy', 'Die Casting', 'Sand Casting', 'Heat Treatment', 'Defect Analysis'],
    technology_skills: ['MAGMASOFT', 'ProCAST'],
    industry: 'manufacturing',
  },
  {
    code: 'CN-STE',
    title: 'Surface Treatment Engineer',
    title_zh: '表面处理工程师',
    country: 'CN',
    opportunity_score: 52,
    breakdown: { salary: 44, competition: 38, growth: 42, barrier: 58, ai_resilience: 72, demand_growth: 42, remote: 5 },
    salary_display: '¥12K',
    salary_raw: 12000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Electroplating', 'Anodizing', 'Painting', 'PVD/CVD', 'Corrosion Testing'],
    technology_skills: ['SEM/EDS', 'Salt Spray Testing'],
    industry: 'manufacturing',
  },
  {
    code: 'CN-ASE',
    title: 'Assembly Engineer',
    title_zh: '装配工程师',
    country: 'CN',
    opportunity_score: 53,
    breakdown: { salary: 45, competition: 40, growth: 45, barrier: 50, ai_resilience: 60, demand_growth: 45, remote: 5 },
    salary_display: '¥13K',
    salary_raw: 13000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['Assembly Line Design', 'Time Study', 'Ergonomics', 'Poka-Yoke', 'Torque Control'],
    technology_skills: ['AutoCAD', 'Arena Simulation'],
    industry: 'manufacturing',
  },
  {
    code: 'CN-IE',
    title: 'Industrial Engineer',
    title_zh: '工业工程师',
    country: 'CN',
    opportunity_score: 61,
    breakdown: { salary: 55, competition: 48, growth: 58, barrier: 48, ai_resilience: 55, demand_growth: 58, remote: 15 },
    salary_display: '¥17K',
    salary_raw: 17000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Time & Motion Study', 'Layout Optimization', 'Capacity Planning', 'Simulation', 'Data Analysis'],
    technology_skills: ['FlexSim', 'Python', 'Power BI'],
    industry: 'manufacturing',
  },
  {
    code: 'CN-PKE',
    title: 'Packaging Engineer',
    title_zh: '包装工程师',
    country: 'CN',
    opportunity_score: 50,
    breakdown: { salary: 40, competition: 35, growth: 42, barrier: 45, ai_resilience: 55, demand_growth: 42, remote: 10 },
    salary_display: '¥11K',
    salary_raw: 11000,
    currency: 'CNY',
    source: 'Robert Walters Greater China Salary Survey 2025',
    skills: ['Packaging Design', 'ISTA Testing', 'Sustainability', 'Material Science', 'Cost Reduction'],
    technology_skills: ['ArtiosCAD', 'SolidWorks'],
    industry: 'manufacturing',
  },

  // ============================================================
  // Automotive (汽车) ~15 jobs
  // ============================================================
  {
    code: 'CN-NEV',
    title: 'NEV Powertrain Engineer',
    title_zh: '新能源动力总成工程师',
    country: 'CN',
    opportunity_score: 82,
    breakdown: { salary: 82, competition: 65, growth: 92, barrier: 65, ai_resilience: 80, demand_growth: 95, remote: 20 },
    salary_display: '¥35K',
    salary_raw: 35000,
    currency: 'CNY',
    source: '中汽协 CAAM 2025; Hays Asia Salary Guide 2025',
    skills: ['Electric Motor Design', 'Power Electronics', 'Thermal Management', 'MATLAB/Simulink', 'Battery Integration'],
    technology_skills: ['ANSYS Maxwell', 'Altium Designer', 'Vector CANoe'],
    industry: 'automotive',
  },
  {
    code: 'CN-ADAS',
    title: 'ADAS/Autonomous Driving Engineer',
    title_zh: 'ADAS/自动驾驶工程师',
    country: 'CN',
    opportunity_score: 85,
    breakdown: { salary: 90, competition: 62, growth: 95, barrier: 72, ai_resilience: 85, demand_growth: 95, remote: 30 },
    salary_display: '¥45K',
    salary_raw: 45000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025; 中汽协 CAAM 2025',
    skills: ['Computer Vision', 'Sensor Fusion', 'C++', 'Python', 'ROS', 'Deep Learning'],
    technology_skills: ['TensorRT', 'CUDA', 'Autoware', 'CARLA'],
    industry: 'automotive',
  },
  {
    code: 'CN-BMS',
    title: 'Battery/BMS Engineer',
    title_zh: '电池/BMS工程师',
    country: 'CN',
    opportunity_score: 81,
    breakdown: { salary: 80, competition: 60, growth: 90, barrier: 65, ai_resilience: 78, demand_growth: 92, remote: 15 },
    salary_display: '¥32K',
    salary_raw: 32000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025; CATL Industry Report 2025',
    skills: ['Battery Chemistry', 'BMS Algorithm', 'Thermal Management', 'SOC/SOH Estimation', 'Cell Balancing'],
    technology_skills: ['MATLAB/Simulink', 'LabVIEW', 'COMSOL'],
    industry: 'automotive',
  },
  {
    code: 'CN-VIE',
    title: 'Vehicle Integration Engineer',
    title_zh: '整车集成工程师',
    country: 'CN',
    opportunity_score: 72,
    breakdown: { salary: 72, competition: 55, growth: 75, barrier: 62, ai_resilience: 72, demand_growth: 75, remote: 10 },
    salary_display: '¥28K',
    salary_raw: 28000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['Systems Engineering', 'V-Model', 'Requirements Management', 'Vehicle Dynamics', 'NVH'],
    technology_skills: ['DOORS', 'CATIA', 'Adams'],
    industry: 'automotive',
  },
  {
    code: 'CN-CHE',
    title: 'Chassis Engineer',
    title_zh: '底盘工程师',
    country: 'CN',
    opportunity_score: 64,
    breakdown: { salary: 62, competition: 48, growth: 60, barrier: 60, ai_resilience: 72, demand_growth: 58, remote: 8 },
    salary_display: '¥22K',
    salary_raw: 22000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Suspension Design', 'Vehicle Dynamics', 'FEA', 'GD&T', 'DFMEA'],
    technology_skills: ['CATIA', 'Adams', 'HyperMesh'],
    industry: 'automotive',
  },
  {
    code: 'CN-BIW',
    title: 'Body-in-White Engineer',
    title_zh: '白车身工程师',
    country: 'CN',
    opportunity_score: 58,
    breakdown: { salary: 52, competition: 42, growth: 50, barrier: 58, ai_resilience: 68, demand_growth: 48, remote: 5 },
    salary_display: '¥16K',
    salary_raw: 16000,
    currency: 'CNY',
    source: 'Robert Walters Greater China Salary Survey 2025',
    skills: ['Sheet Metal Design', 'Spot Welding', 'Adhesive Bonding', 'Crash Simulation', 'GD&T'],
    technology_skills: ['CATIA', 'AutoForm', 'LS-DYNA'],
    industry: 'automotive',
  },
  {
    code: 'CN-APQP',
    title: 'APQP/Launch Engineer',
    title_zh: 'APQP/项目投产工程师',
    country: 'CN',
    opportunity_score: 63,
    breakdown: { salary: 58, competition: 50, growth: 62, barrier: 52, ai_resilience: 65, demand_growth: 62, remote: 12 },
    salary_display: '¥20K',
    salary_raw: 20000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['APQP', 'PPAP', 'MSA', 'Control Plan', 'Project Management', 'IATF 16949'],
    technology_skills: ['MS Project', 'SAP QM'],
    industry: 'automotive',
  },
  {
    code: 'CN-SQE',
    title: 'Supplier Quality Engineer (SQE)',
    title_zh: '供应商质量工程师',
    country: 'CN',
    opportunity_score: 62,
    breakdown: { salary: 58, competition: 50, growth: 58, barrier: 50, ai_resilience: 68, demand_growth: 60, remote: 15 },
    salary_display: '¥19K',
    salary_raw: 19000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['Supplier Audit', 'APQP/PPAP', '8D', 'SPC', 'VDA 6.3', 'IATF 16949'],
    technology_skills: ['SAP QM', 'Minitab'],
    industry: 'automotive',
  },
  {
    code: 'CN-CQE',
    title: 'Customer Quality Engineer (CQE)',
    title_zh: '客户质量工程师',
    country: 'CN',
    opportunity_score: 60,
    breakdown: { salary: 55, competition: 48, growth: 55, barrier: 48, ai_resilience: 62, demand_growth: 55, remote: 15 },
    salary_display: '¥18K',
    salary_raw: 18000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Customer Complaints', '8D/5Why', 'FMEA', 'Communication', 'VDA 6.3'],
    technology_skills: ['SAP QM', 'Power BI'],
    industry: 'automotive',
  },
  {
    code: 'CN-STMP',
    title: 'Stamping Engineer',
    title_zh: '冲压工程师',
    country: 'CN',
    opportunity_score: 52,
    breakdown: { salary: 44, competition: 38, growth: 42, barrier: 58, ai_resilience: 70, demand_growth: 40, remote: 5 },
    salary_display: '¥13K',
    salary_raw: 13000,
    currency: 'CNY',
    source: 'Robert Walters Greater China Salary Survey 2025',
    skills: ['Die Design', 'Press Operation', 'Sheet Metal Forming', 'Tryout', 'FEA'],
    technology_skills: ['AutoForm', 'CATIA', 'Dynaform'],
    industry: 'automotive',
  },
  {
    code: 'CN-PNT',
    title: 'Paint Engineer',
    title_zh: '涂装工程师',
    country: 'CN',
    opportunity_score: 51,
    breakdown: { salary: 42, competition: 38, growth: 40, barrier: 55, ai_resilience: 68, demand_growth: 38, remote: 5 },
    salary_display: '¥12K',
    salary_raw: 12000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['E-coat', 'Primer/Basecoat/Clearcoat', 'Color Matching', 'Environmental Compliance', 'Film Thickness'],
    technology_skills: ['Spectrophotometer', 'PLC'],
    industry: 'automotive',
  },
  {
    code: 'CN-EVC',
    title: 'EV Charging Engineer',
    title_zh: '充电桩/充电系统工程师',
    country: 'CN',
    opportunity_score: 76,
    breakdown: { salary: 72, competition: 62, growth: 85, barrier: 55, ai_resilience: 70, demand_growth: 88, remote: 15 },
    salary_display: '¥28K',
    salary_raw: 28000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025; 中汽协 CAAM 2025',
    skills: ['Power Electronics', 'GB/T Standards', 'CCS/CHAdeMO', 'Embedded C', 'V2G'],
    technology_skills: ['Altium Designer', 'MATLAB', 'LabVIEW'],
    industry: 'automotive',
  },
  {
    code: 'CN-CCV',
    title: 'Connected Car Engineer',
    title_zh: '车联网工程师',
    country: 'CN',
    opportunity_score: 78,
    breakdown: { salary: 78, competition: 60, growth: 88, barrier: 62, ai_resilience: 75, demand_growth: 90, remote: 30 },
    salary_display: '¥32K',
    salary_raw: 32000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['V2X', 'OTA', 'Telematics', 'Linux/QNX', 'Cybersecurity', 'MQTT/DDS'],
    technology_skills: ['Android Automotive', 'AWS IoT', 'Vector CANoe'],
    industry: 'automotive',
  },
  {
    code: 'CN-ATE',
    title: 'Automotive Testing Engineer',
    title_zh: '汽车测试工程师',
    country: 'CN',
    opportunity_score: 60,
    breakdown: { salary: 55, competition: 48, growth: 58, barrier: 52, ai_resilience: 65, demand_growth: 58, remote: 8 },
    salary_display: '¥18K',
    salary_raw: 18000,
    currency: 'CNY',
    source: 'Robert Walters Greater China Salary Survey 2025',
    skills: ['Durability Testing', 'EMC Testing', 'NVH', 'Test Planning', 'Data Acquisition'],
    technology_skills: ['LMS Test.Lab', 'dSPACE', 'INCA'],
    industry: 'automotive',
  },
  {
    code: 'CN-HOM',
    title: 'Homologation Engineer',
    title_zh: '认证/法规工程师',
    country: 'CN',
    opportunity_score: 61,
    breakdown: { salary: 55, competition: 45, growth: 58, barrier: 55, ai_resilience: 60, demand_growth: 60, remote: 20 },
    salary_display: '¥18K',
    salary_raw: 18000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['GB Standards', 'ECE Regulations', 'Type Approval', 'WVTA', 'Documentation'],
    technology_skills: ['IMDS', 'REACH/RoHS Database'],
    industry: 'automotive',
  },

  // ============================================================
  // Electronics/Semiconductor (电子/半导体) ~12 jobs
  // ============================================================
  {
    code: 'CN-ICD',
    title: 'IC Design Engineer',
    title_zh: '集成电路设计工程师',
    country: 'CN',
    opportunity_score: 83,
    breakdown: { salary: 88, competition: 65, growth: 92, barrier: 75, ai_resilience: 82, demand_growth: 95, remote: 25 },
    salary_display: '¥40K',
    salary_raw: 40000,
    currency: 'CNY',
    source: 'CSIA 中国半导体行业协会 2025; Hays Asia Salary Guide 2025',
    skills: ['Verilog/VHDL', 'Digital/Analog Design', 'Synthesis', 'Timing Analysis', 'Low Power Design'],
    technology_skills: ['Synopsys DC', 'Cadence Virtuoso', 'Mentor Calibre'],
    industry: 'electronics',
  },
  {
    code: 'CN-SPE',
    title: 'Semiconductor Process Engineer',
    title_zh: '半导体制程工程师',
    country: 'CN',
    opportunity_score: 80,
    breakdown: { salary: 82, competition: 62, growth: 88, barrier: 72, ai_resilience: 80, demand_growth: 90, remote: 8 },
    salary_display: '¥35K',
    salary_raw: 35000,
    currency: 'CNY',
    source: 'CSIA 2025; Michael Page Greater China Salary Guide 2025',
    skills: ['Photolithography', 'Etching', 'CVD/PVD', 'CMP', 'Defect Analysis', 'Yield Enhancement'],
    technology_skills: ['KLA-Tencor', 'Applied Materials', 'TCAD'],
    industry: 'electronics',
  },
  {
    code: 'CN-PCB',
    title: 'PCB Design Engineer',
    title_zh: 'PCB设计工程师',
    country: 'CN',
    opportunity_score: 62,
    breakdown: { salary: 55, competition: 48, growth: 58, barrier: 52, ai_resilience: 58, demand_growth: 58, remote: 20 },
    salary_display: '¥18K',
    salary_raw: 18000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['High-Speed PCB', 'Signal Integrity', 'Power Integrity', 'EMC Design', 'DFM'],
    technology_skills: ['Altium Designer', 'Cadence Allegro', 'HyperLynx'],
    industry: 'electronics',
  },
  {
    code: 'CN-EMC',
    title: 'EMC Engineer',
    title_zh: 'EMC工程师',
    country: 'CN',
    opportunity_score: 63,
    breakdown: { salary: 58, competition: 45, growth: 60, barrier: 58, ai_resilience: 70, demand_growth: 62, remote: 15 },
    salary_display: '¥20K',
    salary_raw: 20000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['EMI/EMS Testing', 'Shielding Design', 'Filter Design', 'CISPR/IEC Standards', 'Pre-compliance'],
    technology_skills: ['CST Studio', 'Spectrum Analyzer', 'Near-field Scanner'],
    industry: 'electronics',
  },
  {
    code: 'CN-FWE',
    title: 'Firmware/Embedded Engineer',
    title_zh: '固件/嵌入式工程师',
    country: 'CN',
    opportunity_score: 74,
    breakdown: { salary: 72, competition: 58, growth: 78, barrier: 62, ai_resilience: 72, demand_growth: 80, remote: 30 },
    salary_display: '¥28K',
    salary_raw: 28000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['C/C++', 'RTOS', 'ARM Cortex', 'Linux Kernel', 'Device Drivers', 'Debugging'],
    technology_skills: ['Keil/IAR', 'JTAG', 'Oscilloscope', 'Logic Analyzer'],
    industry: 'electronics',
  },
  {
    code: 'CN-RF',
    title: 'RF Engineer',
    title_zh: '射频工程师',
    country: 'CN',
    opportunity_score: 72,
    breakdown: { salary: 70, competition: 55, growth: 75, barrier: 68, ai_resilience: 78, demand_growth: 78, remote: 15 },
    salary_display: '¥28K',
    salary_raw: 28000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['RF Circuit Design', 'Antenna Design', '5G/mmWave', 'Impedance Matching', 'EM Simulation'],
    technology_skills: ['HFSS', 'ADS', 'VNA'],
    industry: 'electronics',
  },
  {
    code: 'CN-PWR',
    title: 'Power Electronics Engineer',
    title_zh: '电力电子工程师',
    country: 'CN',
    opportunity_score: 75,
    breakdown: { salary: 72, competition: 58, growth: 80, barrier: 62, ai_resilience: 78, demand_growth: 82, remote: 12 },
    salary_display: '¥28K',
    salary_raw: 28000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025; 中汽协 CAAM 2025',
    skills: ['DC-DC Converter', 'Inverter Design', 'SiC/GaN', 'Thermal Design', 'EMI Suppression'],
    technology_skills: ['LTspice', 'PSIM', 'Altium Designer'],
    industry: 'electronics',
  },
  {
    code: 'CN-FPGA',
    title: 'FPGA Engineer',
    title_zh: 'FPGA工程师',
    country: 'CN',
    opportunity_score: 73,
    breakdown: { salary: 70, competition: 55, growth: 78, barrier: 68, ai_resilience: 75, demand_growth: 78, remote: 20 },
    salary_display: '¥28K',
    salary_raw: 28000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['Verilog/VHDL', 'Timing Closure', 'DSP', 'High-Speed Interface', 'Verification'],
    technology_skills: ['Xilinx Vivado', 'Intel Quartus', 'ModelSim'],
    industry: 'electronics',
  },
  {
    code: 'CN-TDE',
    title: 'Test Development Engineer',
    title_zh: '测试开发工程师',
    country: 'CN',
    opportunity_score: 65,
    breakdown: { salary: 60, competition: 50, growth: 65, barrier: 55, ai_resilience: 62, demand_growth: 68, remote: 15 },
    salary_display: '¥22K',
    salary_raw: 22000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['ATE Programming', 'Semiconductor Testing', 'Test Coverage', 'Yield Analysis', 'DFT'],
    technology_skills: ['Teradyne', 'Advantest', 'LabVIEW'],
    industry: 'electronics',
  },
  {
    code: 'CN-SMT',
    title: 'SMT Process Engineer',
    title_zh: 'SMT工艺工程师',
    country: 'CN',
    opportunity_score: 55,
    breakdown: { salary: 45, competition: 40, growth: 48, barrier: 50, ai_resilience: 62, demand_growth: 48, remote: 5 },
    salary_display: '¥13K',
    salary_raw: 13000,
    currency: 'CNY',
    source: 'Robert Walters Greater China Salary Survey 2025',
    skills: ['Reflow Soldering', 'Stencil Printing', 'AOI/SPI', 'IPC Standards', 'Yield Improvement'],
    technology_skills: ['Fuji/Panasonic Mounter', 'SPC Software'],
    industry: 'electronics',
  },
  {
    code: 'CN-OPT',
    title: 'Optical Engineer',
    title_zh: '光学工程师',
    country: 'CN',
    opportunity_score: 70,
    breakdown: { salary: 68, competition: 55, growth: 72, barrier: 65, ai_resilience: 78, demand_growth: 75, remote: 15 },
    salary_display: '¥25K',
    salary_raw: 25000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['Optical Design', 'LiDAR', 'Lens Design', 'Optical Testing', 'Thin Film Coating'],
    technology_skills: ['Zemax', 'CODE V', 'LightTools'],
    industry: 'electronics',
  },
  {
    code: 'CN-SNS',
    title: 'Sensor Engineer',
    title_zh: '传感器工程师',
    country: 'CN',
    opportunity_score: 73,
    breakdown: { salary: 68, competition: 55, growth: 80, barrier: 62, ai_resilience: 75, demand_growth: 82, remote: 15 },
    salary_display: '¥25K',
    salary_raw: 25000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['MEMS', 'Signal Conditioning', 'Calibration', 'IoT Protocols', 'Sensor Fusion'],
    technology_skills: ['COMSOL', 'LabVIEW', 'Python'],
    industry: 'electronics',
  },

  // ============================================================
  // Quality & Safety (质量/安全) ~10 jobs
  // ============================================================
  {
    code: 'CN-QE',
    title: 'Quality Engineer (QE)',
    title_zh: '质量工程师',
    country: 'CN',
    opportunity_score: 60,
    breakdown: { salary: 55, competition: 48, growth: 55, barrier: 48, ai_resilience: 62, demand_growth: 55, remote: 12 },
    salary_display: '¥17K',
    salary_raw: 17000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['SPC', 'FMEA', '8D', 'Core Tools', 'Audit', 'Root Cause Analysis'],
    technology_skills: ['Minitab', 'SAP QM', 'Power BI'],
    industry: 'quality',
  },
  {
    code: 'CN-QM',
    title: 'Quality Manager',
    title_zh: '质量经理',
    country: 'CN',
    opportunity_score: 67,
    breakdown: { salary: 68, competition: 52, growth: 60, barrier: 55, ai_resilience: 65, demand_growth: 58, remote: 15 },
    salary_display: '¥30K',
    salary_raw: 30000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['Quality System Management', 'IATF 16949', 'Team Leadership', 'Customer Interface', 'Cost of Quality'],
    technology_skills: ['SAP QM', 'Power BI', 'Minitab'],
    industry: 'quality',
  },
  {
    code: 'CN-RE',
    title: 'Reliability Engineer',
    title_zh: '可靠性工程师',
    country: 'CN',
    opportunity_score: 64,
    breakdown: { salary: 60, competition: 48, growth: 62, barrier: 58, ai_resilience: 68, demand_growth: 62, remote: 15 },
    salary_display: '¥22K',
    salary_raw: 22000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['HALT/HASS', 'Weibull Analysis', 'Accelerated Life Testing', 'FMECA', 'Physics of Failure'],
    technology_skills: ['Reliasoft', 'Minitab', 'MATLAB'],
    industry: 'quality',
  },
  {
    code: 'CN-MTE',
    title: 'Metrology Engineer',
    title_zh: '计量工程师',
    country: 'CN',
    opportunity_score: 56,
    breakdown: { salary: 48, competition: 42, growth: 50, barrier: 55, ai_resilience: 65, demand_growth: 50, remote: 8 },
    salary_display: '¥14K',
    salary_raw: 14000,
    currency: 'CNY',
    source: 'Robert Walters Greater China Salary Survey 2025',
    skills: ['CMM Operation', 'GD&T', 'MSA', 'Gauge R&R', 'Calibration'],
    technology_skills: ['PC-DMIS', 'PolyWorks', 'GOM ATOS'],
    industry: 'quality',
  },
  {
    code: 'CN-EHS',
    title: 'EHS Manager',
    title_zh: 'EHS经理',
    country: 'CN',
    opportunity_score: 63,
    breakdown: { salary: 60, competition: 48, growth: 62, barrier: 50, ai_resilience: 68, demand_growth: 65, remote: 12 },
    salary_display: '¥25K',
    salary_raw: 25000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['ISO 14001', 'ISO 45001', 'Risk Assessment', 'Emergency Response', 'Environmental Compliance', 'China EHS Law'],
    technology_skills: ['EHS Software', 'SAP EHS'],
    industry: 'quality',
  },
  {
    code: 'CN-FSE',
    title: 'Functional Safety Engineer',
    title_zh: '功能安全工程师',
    country: 'CN',
    opportunity_score: 74,
    breakdown: { salary: 72, competition: 58, growth: 78, barrier: 65, ai_resilience: 75, demand_growth: 80, remote: 20 },
    salary_display: '¥30K',
    salary_raw: 30000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['ISO 26262', 'FMEDA', 'FTA', 'SOTIF', 'ASPICE', 'Hazard Analysis'],
    technology_skills: ['Medini Analyze', 'DOORS', 'Enterprise Architect'],
    industry: 'quality',
  },
  {
    code: 'CN-IAT',
    title: 'IATF Auditor',
    title_zh: 'IATF审核员',
    country: 'CN',
    opportunity_score: 62,
    breakdown: { salary: 58, competition: 48, growth: 55, barrier: 55, ai_resilience: 62, demand_growth: 55, remote: 20 },
    salary_display: '¥22K',
    salary_raw: 22000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['IATF 16949', 'VDA 6.3', 'Process Audit', 'Lead Auditor', 'Corrective Action'],
    technology_skills: ['Audit Management Software'],
    industry: 'quality',
  },
  {
    code: 'CN-LMG',
    title: 'Lab Manager',
    title_zh: '实验室经理',
    country: 'CN',
    opportunity_score: 61,
    breakdown: { salary: 58, competition: 45, growth: 55, barrier: 55, ai_resilience: 68, demand_growth: 55, remote: 8 },
    salary_display: '¥22K',
    salary_raw: 22000,
    currency: 'CNY',
    source: 'Robert Walters Greater China Salary Survey 2025',
    skills: ['ISO 17025', 'Lab Equipment Management', 'Test Method Development', 'Team Management', 'CNAS Accreditation'],
    technology_skills: ['LIMS', 'Calibration Software'],
    industry: 'quality',
  },
  {
    code: 'CN-FAE',
    title: 'Failure Analysis Engineer',
    title_zh: '失效分析工程师',
    country: 'CN',
    opportunity_score: 65,
    breakdown: { salary: 60, competition: 50, growth: 65, barrier: 60, ai_resilience: 72, demand_growth: 65, remote: 10 },
    salary_display: '¥22K',
    salary_raw: 22000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Root Cause Analysis', 'Metallography', 'SEM/EDS', 'FIB', 'Material Science'],
    technology_skills: ['Cross-section Polisher', 'XRF', 'FTIR'],
    industry: 'quality',
  },
  {
    code: 'CN-CPE',
    title: 'Compliance Engineer',
    title_zh: '合规工程师',
    country: 'CN',
    opportunity_score: 62,
    breakdown: { salary: 58, competition: 48, growth: 60, barrier: 52, ai_resilience: 55, demand_growth: 62, remote: 25 },
    salary_display: '¥20K',
    salary_raw: 20000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['REACH/RoHS', 'CE Marking', 'CCC Certification', 'Export Control', 'Product Safety'],
    technology_skills: ['IMDS', 'BOMcheck', 'SAP EHS'],
    industry: 'quality',
  },

  // ============================================================
  // Supply Chain & Logistics (供应链/物流) ~10 jobs
  // ============================================================
  {
    code: 'CN-SCM',
    title: 'Supply Chain Manager',
    title_zh: '供应链经理',
    country: 'CN',
    opportunity_score: 68,
    breakdown: { salary: 68, competition: 55, growth: 65, barrier: 50, ai_resilience: 55, demand_growth: 68, remote: 20 },
    salary_display: '¥30K',
    salary_raw: 30000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['S&OP', 'Demand Planning', 'Inventory Optimization', 'Supplier Management', 'Cost Reduction'],
    technology_skills: ['SAP MM/PP', 'Oracle SCM', 'Power BI'],
    industry: 'supply-chain',
  },
  {
    code: 'CN-PRM',
    title: 'Procurement Manager',
    title_zh: '采购经理',
    country: 'CN',
    opportunity_score: 65,
    breakdown: { salary: 65, competition: 52, growth: 60, barrier: 48, ai_resilience: 52, demand_growth: 62, remote: 18 },
    salary_display: '¥28K',
    salary_raw: 28000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['Negotiation', 'Strategic Sourcing', 'Contract Management', 'Cost Analysis', 'Supplier Evaluation'],
    technology_skills: ['SAP MM', 'Ariba', 'Power BI'],
    industry: 'supply-chain',
  },
  {
    code: 'CN-CMM',
    title: 'Commodity Manager',
    title_zh: '品类经理',
    country: 'CN',
    opportunity_score: 66,
    breakdown: { salary: 65, competition: 52, growth: 62, barrier: 50, ai_resilience: 55, demand_growth: 65, remote: 20 },
    salary_display: '¥28K',
    salary_raw: 28000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Category Strategy', 'Should-Cost Modeling', 'Market Intelligence', 'Supplier Development', 'Risk Management'],
    technology_skills: ['SAP MM', 'Coupa', 'Power BI'],
    industry: 'supply-chain',
  },
  {
    code: 'CN-LGM',
    title: 'Logistics Manager',
    title_zh: '物流经理',
    country: 'CN',
    opportunity_score: 61,
    breakdown: { salary: 58, competition: 48, growth: 55, barrier: 45, ai_resilience: 48, demand_growth: 58, remote: 12 },
    salary_display: '¥22K',
    salary_raw: 22000,
    currency: 'CNY',
    source: 'Robert Walters Greater China Salary Survey 2025',
    skills: ['Warehouse Management', 'Transportation Planning', 'Customs', 'Incoterms', '3PL Management'],
    technology_skills: ['SAP WM', 'TMS', 'WMS'],
    industry: 'supply-chain',
  },
  {
    code: 'CN-DPL',
    title: 'Demand Planner',
    title_zh: '需求计划专员',
    country: 'CN',
    opportunity_score: 60,
    breakdown: { salary: 52, competition: 48, growth: 58, barrier: 45, ai_resilience: 45, demand_growth: 60, remote: 25 },
    salary_display: '¥18K',
    salary_raw: 18000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Forecasting', 'Statistical Analysis', 'S&OP', 'Inventory Planning', 'Collaboration'],
    technology_skills: ['SAP APO', 'Kinaxis', 'Excel/Power BI'],
    industry: 'supply-chain',
  },
  {
    code: 'CN-SOP',
    title: 'S&OP Manager',
    title_zh: 'S&OP经理',
    country: 'CN',
    opportunity_score: 67,
    breakdown: { salary: 65, competition: 52, growth: 65, barrier: 52, ai_resilience: 52, demand_growth: 68, remote: 20 },
    salary_display: '¥28K',
    salary_raw: 28000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['S&OP Process', 'Cross-functional Alignment', 'Scenario Planning', 'KPI Management', 'Executive Presentation'],
    technology_skills: ['SAP IBP', 'o9 Solutions', 'Power BI'],
    industry: 'supply-chain',
  },
  {
    code: 'CN-WHO',
    title: 'Warehouse Operations Manager',
    title_zh: '仓储运营经理',
    country: 'CN',
    opportunity_score: 56,
    breakdown: { salary: 50, competition: 42, growth: 48, barrier: 42, ai_resilience: 45, demand_growth: 50, remote: 5 },
    salary_display: '¥16K',
    salary_raw: 16000,
    currency: 'CNY',
    source: 'Robert Walters Greater China Salary Survey 2025',
    skills: ['Warehouse Layout', 'Pick/Pack Optimization', 'Labor Management', 'Safety', 'Lean Warehousing'],
    technology_skills: ['WMS', 'RF/Barcode Systems', 'SAP WM'],
    industry: 'supply-chain',
  },
  {
    code: 'CN-IES',
    title: 'Import/Export Specialist',
    title_zh: '进出口专员',
    country: 'CN',
    opportunity_score: 55,
    breakdown: { salary: 45, competition: 42, growth: 50, barrier: 45, ai_resilience: 42, demand_growth: 52, remote: 20 },
    salary_display: '¥13K',
    salary_raw: 13000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Customs Clearance', 'HS Code Classification', 'Trade Compliance', 'Incoterms', 'L/C Documentation'],
    technology_skills: ['China E-Port', 'SAP GTS'],
    industry: 'supply-chain',
  },
  {
    code: 'CN-SDE',
    title: 'Supplier Development Engineer',
    title_zh: '供应商开发工程师',
    country: 'CN',
    opportunity_score: 62,
    breakdown: { salary: 58, competition: 48, growth: 58, barrier: 50, ai_resilience: 65, demand_growth: 60, remote: 12 },
    salary_display: '¥19K',
    salary_raw: 19000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['Supplier Audit', 'Process Capability', 'APQP', 'Cost Reduction', 'Technical Evaluation'],
    technology_skills: ['SAP SRM', 'Minitab'],
    industry: 'supply-chain',
  },
  {
    code: 'CN-MAT',
    title: 'Materials Manager',
    title_zh: '物料经理',
    country: 'CN',
    opportunity_score: 60,
    breakdown: { salary: 55, competition: 48, growth: 55, barrier: 48, ai_resilience: 48, demand_growth: 55, remote: 10 },
    salary_display: '¥22K',
    salary_raw: 22000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['MRP', 'Inventory Control', 'Production Scheduling', 'Shortage Management', 'ERP'],
    technology_skills: ['SAP MM', 'Oracle', 'Excel VBA'],
    industry: 'supply-chain',
  },

  // ============================================================
  // IT & Digital Manufacturing (制造业IT) ~10 jobs
  // ============================================================
  {
    code: 'CN-MES',
    title: 'MES Engineer',
    title_zh: 'MES工程师',
    country: 'CN',
    opportunity_score: 70,
    breakdown: { salary: 65, competition: 55, growth: 75, barrier: 55, ai_resilience: 62, demand_growth: 78, remote: 20 },
    salary_display: '¥25K',
    salary_raw: 25000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['MES Implementation', 'SQL', 'OPC-UA', 'ISA-95', 'Production Workflow'],
    technology_skills: ['Siemens Opcenter', 'AVEVA', 'C#/.NET'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'CN-IIOT',
    title: 'IIoT Engineer',
    title_zh: '工业物联网工程师',
    country: 'CN',
    opportunity_score: 76,
    breakdown: { salary: 72, competition: 60, growth: 85, barrier: 58, ai_resilience: 68, demand_growth: 88, remote: 25 },
    salary_display: '¥28K',
    salary_raw: 28000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['IoT Protocols', 'Edge Computing', 'PLC Integration', 'Data Pipeline', 'Cloud Architecture'],
    technology_skills: ['MQTT', 'Node-RED', 'Azure IoT Hub', 'Python'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'CN-DTW',
    title: 'Digital Twin Engineer',
    title_zh: '数字孪生工程师',
    country: 'CN',
    opportunity_score: 79,
    breakdown: { salary: 78, competition: 62, growth: 88, barrier: 62, ai_resilience: 72, demand_growth: 90, remote: 30 },
    salary_display: '¥32K',
    salary_raw: 32000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['3D Modeling', 'Simulation', 'Real-time Data Integration', 'Physics Modeling', 'Optimization'],
    technology_skills: ['Siemens NX', 'Unity/Unreal', 'Python', 'Azure Digital Twins'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'CN-DCS',
    title: 'SCADA/DCS Engineer',
    title_zh: 'SCADA/DCS工程师',
    country: 'CN',
    opportunity_score: 64,
    breakdown: { salary: 58, competition: 48, growth: 62, barrier: 58, ai_resilience: 68, demand_growth: 65, remote: 10 },
    salary_display: '¥20K',
    salary_raw: 20000,
    currency: 'CNY',
    source: 'Robert Walters Greater China Salary Survey 2025',
    skills: ['SCADA Systems', 'DCS Configuration', 'HMI Design', 'PLC Programming', 'Process Control'],
    technology_skills: ['WinCC', 'iFIX', 'DeltaV', 'Siemens S7'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'CN-ERP',
    title: 'ERP Consultant (SAP)',
    title_zh: 'ERP顾问(SAP)',
    country: 'CN',
    opportunity_score: 68,
    breakdown: { salary: 68, competition: 55, growth: 62, barrier: 52, ai_resilience: 48, demand_growth: 62, remote: 35 },
    salary_display: '¥30K',
    salary_raw: 30000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['SAP PP/MM/QM', 'Business Process', 'ABAP Basics', 'Data Migration', 'User Training'],
    technology_skills: ['SAP S/4HANA', 'SAP Fiori', 'SQL'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'CN-MDA',
    title: 'Manufacturing Data Analyst',
    title_zh: '制造业数据分析师',
    country: 'CN',
    opportunity_score: 72,
    breakdown: { salary: 65, competition: 55, growth: 78, barrier: 50, ai_resilience: 55, demand_growth: 80, remote: 35 },
    salary_display: '¥25K',
    salary_raw: 25000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Python', 'SQL', 'Statistical Analysis', 'Machine Learning', 'Data Visualization', 'Manufacturing KPIs'],
    technology_skills: ['Power BI', 'Tableau', 'Python/Pandas', 'Databricks'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'CN-SMF',
    title: 'Smart Factory Engineer',
    title_zh: '智能工厂工程师',
    country: 'CN',
    opportunity_score: 77,
    breakdown: { salary: 75, competition: 60, growth: 85, barrier: 58, ai_resilience: 70, demand_growth: 88, remote: 20 },
    salary_display: '¥30K',
    salary_raw: 30000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025; 工信部智能制造报告 2025',
    skills: ['Industry 4.0', 'Automation', 'Robotics', 'MES/ERP Integration', 'Lean + Digital'],
    technology_skills: ['Siemens TIA Portal', 'KUKA/ABB Robots', 'Python'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'CN-PLM',
    title: 'PLM Engineer',
    title_zh: 'PLM工程师',
    country: 'CN',
    opportunity_score: 64,
    breakdown: { salary: 60, competition: 50, growth: 62, barrier: 52, ai_resilience: 55, demand_growth: 62, remote: 25 },
    salary_display: '¥22K',
    salary_raw: 22000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['PLM Implementation', 'BOM Management', 'Change Management', 'CAD Integration', 'Configuration'],
    technology_skills: ['Teamcenter', 'Windchill', 'ENOVIA'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'CN-ASW',
    title: 'Automation Software Engineer',
    title_zh: '自动化软件工程师',
    country: 'CN',
    opportunity_score: 74,
    breakdown: { salary: 72, competition: 58, growth: 80, barrier: 58, ai_resilience: 68, demand_growth: 82, remote: 25 },
    salary_display: '¥28K',
    salary_raw: 28000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['PLC Programming', 'Robot Programming', 'Vision Systems', 'Motion Control', 'C++/Python'],
    technology_skills: ['Siemens TIA Portal', 'Allen-Bradley', 'Cognex', 'KUKA KRL'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'CN-OTC',
    title: 'Cybersecurity Engineer (OT)',
    title_zh: 'OT网络安全工程师',
    country: 'CN',
    opportunity_score: 75,
    breakdown: { salary: 72, competition: 60, growth: 82, barrier: 62, ai_resilience: 72, demand_growth: 85, remote: 30 },
    salary_display: '¥30K',
    salary_raw: 30000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['ICS Security', 'IEC 62443', 'Network Segmentation', 'Threat Modeling', 'Incident Response'],
    technology_skills: ['Claroty', 'Nozomi Networks', 'Wireshark', 'Fortinet'],
    industry: 'digital-manufacturing',
  },

  // ============================================================
  // Management (制造业管理) ~10 jobs
  // ============================================================
  {
    code: 'CN-PDM',
    title: 'Production Manager',
    title_zh: '生产经理',
    country: 'CN',
    opportunity_score: 62,
    breakdown: { salary: 60, competition: 48, growth: 55, barrier: 48, ai_resilience: 65, demand_growth: 55, remote: 5 },
    salary_display: '¥25K',
    salary_raw: 25000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Production Planning', 'Lean Manufacturing', 'Team Leadership', 'KPI Management', 'Problem Solving'],
    technology_skills: ['SAP PP', 'MES', 'Power BI'],
    industry: 'management',
  },
  {
    code: 'CN-PLD',
    title: 'Plant Director',
    title_zh: '工厂厂长',
    country: 'CN',
    opportunity_score: 70,
    breakdown: { salary: 80, competition: 55, growth: 58, barrier: 60, ai_resilience: 72, demand_growth: 55, remote: 5 },
    salary_display: '¥50K',
    salary_raw: 50000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['P&L Management', 'Strategic Planning', 'Lean Transformation', 'Stakeholder Management', 'Capital Budgeting'],
    technology_skills: ['ERP Systems', 'Power BI', 'MS Office'],
    industry: 'management',
  },
  {
    code: 'CN-ENM',
    title: 'Engineering Manager',
    title_zh: '工程经理',
    country: 'CN',
    opportunity_score: 68,
    breakdown: { salary: 72, competition: 52, growth: 62, barrier: 55, ai_resilience: 68, demand_growth: 62, remote: 15 },
    salary_display: '¥35K',
    salary_raw: 35000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Team Management', 'Project Portfolio', 'Technical Decision Making', 'Budget Control', 'Cross-functional Leadership'],
    technology_skills: ['MS Project', 'SAP PS', 'PLM'],
    industry: 'management',
  },
  {
    code: 'CN-OPD',
    title: 'Operations Director',
    title_zh: '运营总监',
    country: 'CN',
    opportunity_score: 73,
    breakdown: { salary: 85, competition: 58, growth: 62, barrier: 62, ai_resilience: 70, demand_growth: 60, remote: 10 },
    salary_display: '¥60K',
    salary_raw: 60000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['Operational Excellence', 'P&L Ownership', 'Change Management', 'Multi-site Management', 'Strategy Execution'],
    technology_skills: ['ERP Systems', 'Business Intelligence', 'Power BI'],
    industry: 'management',
  },
  {
    code: 'CN-RDD',
    title: 'R&D Director',
    title_zh: '研发总监',
    country: 'CN',
    opportunity_score: 75,
    breakdown: { salary: 85, competition: 58, growth: 70, barrier: 68, ai_resilience: 75, demand_growth: 70, remote: 15 },
    salary_display: '¥55K',
    salary_raw: 55000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Technology Roadmap', 'IP Strategy', 'Team Building', 'Innovation Management', 'Budget Planning'],
    technology_skills: ['PLM', 'Patent Databases', 'MS Office'],
    industry: 'management',
  },
  {
    code: 'CN-QLD',
    title: 'Quality Director',
    title_zh: '质量总监',
    country: 'CN',
    opportunity_score: 69,
    breakdown: { salary: 78, competition: 55, growth: 60, barrier: 58, ai_resilience: 68, demand_growth: 58, remote: 10 },
    salary_display: '¥45K',
    salary_raw: 45000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['Quality Strategy', 'Customer Management', 'Regulatory Affairs', 'Cost of Quality', 'Organizational Development'],
    technology_skills: ['SAP QM', 'Power BI', 'Minitab'],
    industry: 'management',
  },
  {
    code: 'CN-SCD',
    title: 'Supply Chain Director',
    title_zh: '供应链总监',
    country: 'CN',
    opportunity_score: 72,
    breakdown: { salary: 82, competition: 58, growth: 65, barrier: 58, ai_resilience: 55, demand_growth: 65, remote: 15 },
    salary_display: '¥50K',
    salary_raw: 50000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['End-to-end SC Strategy', 'Digital SC Transformation', 'Risk Management', 'Global Sourcing', 'Team Leadership'],
    technology_skills: ['SAP IBP', 'Oracle SCM', 'Power BI'],
    industry: 'management',
  },
  {
    code: 'CN-ITM',
    title: 'IT Manager/CTO',
    title_zh: 'IT经理/CTO',
    country: 'CN',
    opportunity_score: 72,
    breakdown: { salary: 78, competition: 58, growth: 68, barrier: 58, ai_resilience: 60, demand_growth: 72, remote: 30 },
    salary_display: '¥45K',
    salary_raw: 45000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['IT Strategy', 'Digital Transformation', 'Team Management', 'Vendor Management', 'Cybersecurity'],
    technology_skills: ['Cloud Platforms', 'ERP/MES', 'Agile/DevOps'],
    industry: 'management',
  },
  {
    code: 'CN-PGM',
    title: 'Program Manager (Automotive)',
    title_zh: '项目总监(汽车)',
    country: 'CN',
    opportunity_score: 71,
    breakdown: { salary: 75, competition: 55, growth: 68, barrier: 58, ai_resilience: 65, demand_growth: 68, remote: 15 },
    salary_display: '¥40K',
    salary_raw: 40000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['APQP', 'Program Management', 'P&L Ownership', 'Customer Interface', 'Risk Management', 'Multi-project'],
    technology_skills: ['MS Project', 'SAP PS', 'Power BI'],
    industry: 'management',
  },
  {
    code: 'CN-TSD',
    title: 'Technical Sales Director',
    title_zh: '技术销售总监',
    country: 'CN',
    opportunity_score: 71,
    breakdown: { salary: 80, competition: 55, growth: 62, barrier: 52, ai_resilience: 62, demand_growth: 62, remote: 20 },
    salary_display: '¥50K',
    salary_raw: 50000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['Key Account Management', 'Technical Presentation', 'Contract Negotiation', 'Market Strategy', 'Team Building'],
    technology_skills: ['CRM', 'Power BI', 'MS Office'],
    industry: 'management',
  },

  // ============================================================
  // Consulting & Professional Services (咨询/服务) ~12 jobs
  // ============================================================
  {
    code: 'CN-MCN',
    title: 'Management Consultant (Manufacturing)',
    title_zh: '管理咨询顾问(制造业)',
    country: 'CN',
    opportunity_score: 69,
    breakdown: { salary: 72, competition: 38, growth: 68, barrier: 72, ai_resilience: 58, demand_growth: 68, remote: 35 },
    salary_display: '¥30K',
    salary_raw: 30000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Strategy Frameworks', 'Operations Analysis', 'Stakeholder Management', 'Presentation', 'Data Analysis', 'Change Management'],
    technology_skills: ['PowerPoint', 'Excel', 'Power BI', 'Python'],
    industry: 'consulting',
  },
  {
    code: 'CN-LSS',
    title: 'Lean/Six Sigma Consultant',
    title_zh: '精益/六西格玛顾问',
    country: 'CN',
    opportunity_score: 65,
    breakdown: { salary: 65, competition: 40, growth: 62, barrier: 68, ai_resilience: 62, demand_growth: 62, remote: 30 },
    salary_display: '¥25K',
    salary_raw: 25000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['Lean Manufacturing', 'Six Sigma Black Belt', 'Value Stream Mapping', 'Coaching', 'Change Management'],
    technology_skills: ['Minitab', 'Power BI', 'Process Simulation'],
    industry: 'consulting',
  },
  {
    code: 'CN-SCC',
    title: 'Supply Chain Consultant',
    title_zh: '供应链咨询顾问',
    country: 'CN',
    opportunity_score: 67,
    breakdown: { salary: 68, competition: 38, growth: 65, barrier: 70, ai_resilience: 55, demand_growth: 68, remote: 35 },
    salary_display: '¥28K',
    salary_raw: 28000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['SC Optimization', 'Network Design', 'S&OP', 'Digital SC', 'Project Management'],
    technology_skills: ['Llamasoft', 'SAP IBP', 'Python', 'Power BI'],
    industry: 'consulting',
  },
  {
    code: 'CN-DTC',
    title: 'Digital Transformation Consultant',
    title_zh: '数字化转型顾问',
    country: 'CN',
    opportunity_score: 74,
    breakdown: { salary: 75, competition: 42, growth: 82, barrier: 68, ai_resilience: 60, demand_growth: 82, remote: 40 },
    salary_display: '¥35K',
    salary_raw: 35000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025; 工信部智能制造报告 2025',
    skills: ['Industry 4.0 Strategy', 'Change Management', 'IT/OT Convergence', 'ROI Analysis', 'Stakeholder Management'],
    technology_skills: ['MES/ERP', 'Cloud Platforms', 'Power BI', 'Miro'],
    industry: 'consulting',
  },
  {
    code: 'CN-EHC',
    title: 'EHS Consultant',
    title_zh: 'EHS咨询顾问',
    country: 'CN',
    opportunity_score: 60,
    breakdown: { salary: 55, competition: 40, growth: 58, barrier: 65, ai_resilience: 65, demand_growth: 60, remote: 25 },
    salary_display: '¥20K',
    salary_raw: 20000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['ISO 14001/45001', 'Environmental Impact Assessment', 'Safety Audit', 'China EHS Regulation', 'Training'],
    technology_skills: ['EHS Software', 'GIS'],
    industry: 'consulting',
  },
  {
    code: 'CN-QSC',
    title: 'Quality Systems Consultant (ISO/IATF)',
    title_zh: '质量体系咨询顾问',
    country: 'CN',
    opportunity_score: 61,
    breakdown: { salary: 58, competition: 40, growth: 55, barrier: 68, ai_resilience: 60, demand_growth: 55, remote: 30 },
    salary_display: '¥22K',
    salary_raw: 22000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['IATF 16949', 'ISO 9001', 'VDA 6.3', 'Audit', 'Gap Analysis', 'Training'],
    technology_skills: ['Audit Management Software', 'Power BI'],
    industry: 'consulting',
  },
  {
    code: 'CN-TSE',
    title: 'Technical Sales Engineer',
    title_zh: '技术销售工程师',
    country: 'CN',
    opportunity_score: 63,
    breakdown: { salary: 60, competition: 42, growth: 60, barrier: 65, ai_resilience: 62, demand_growth: 62, remote: 25 },
    salary_display: '¥22K',
    salary_raw: 22000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Technical Presentation', 'Solution Selling', 'Customer Needs Analysis', 'Negotiation', 'Product Knowledge'],
    technology_skills: ['CRM', 'CAD Viewer', 'MS Office'],
    industry: 'consulting',
  },
  {
    code: 'CN-APE',
    title: 'Application Engineer',
    title_zh: '应用工程师',
    country: 'CN',
    opportunity_score: 62,
    breakdown: { salary: 58, competition: 45, growth: 58, barrier: 62, ai_resilience: 65, demand_growth: 60, remote: 20 },
    salary_display: '¥20K',
    salary_raw: 20000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['Technical Support', 'Product Demo', 'Troubleshooting', 'Customer Training', 'Feedback Loop'],
    technology_skills: ['Application-specific Software', 'CRM'],
    industry: 'consulting',
  },
  {
    code: 'CN-IPM',
    title: 'Product Manager (Industrial)',
    title_zh: '产品经理(工业)',
    country: 'CN',
    opportunity_score: 70,
    breakdown: { salary: 70, competition: 42, growth: 72, barrier: 65, ai_resilience: 58, demand_growth: 72, remote: 30 },
    salary_display: '¥30K',
    salary_raw: 30000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Product Strategy', 'Market Analysis', 'Requirements Management', 'Go-to-Market', 'P&L Ownership'],
    technology_skills: ['Jira', 'Confluence', 'Power BI', 'Figma'],
    industry: 'consulting',
  },
  {
    code: 'CN-BDM',
    title: 'Business Development Manager',
    title_zh: '业务拓展经理',
    country: 'CN',
    opportunity_score: 66,
    breakdown: { salary: 68, competition: 38, growth: 62, barrier: 68, ai_resilience: 58, demand_growth: 65, remote: 25 },
    salary_display: '¥30K',
    salary_raw: 30000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025',
    skills: ['Market Development', 'Partnership Building', 'Proposal Writing', 'Negotiation', 'Industry Networking'],
    technology_skills: ['CRM', 'LinkedIn Sales Navigator', 'Power BI'],
    industry: 'consulting',
  },
  {
    code: 'CN-MAA',
    title: 'M&A Analyst (Industrial)',
    title_zh: '并购分析师(工业)',
    country: 'CN',
    opportunity_score: 68,
    breakdown: { salary: 72, competition: 35, growth: 65, barrier: 72, ai_resilience: 52, demand_growth: 65, remote: 30 },
    salary_display: '¥32K',
    salary_raw: 32000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Financial Modeling', 'Due Diligence', 'Valuation', 'Industry Analysis', 'Deal Structuring'],
    technology_skills: ['Excel/VBA', 'Capital IQ', 'Power BI'],
    industry: 'consulting',
  },
  {
    code: 'CN-PAT',
    title: 'Patent Engineer',
    title_zh: '专利工程师',
    country: 'CN',
    opportunity_score: 63,
    breakdown: { salary: 60, competition: 42, growth: 60, barrier: 68, ai_resilience: 55, demand_growth: 62, remote: 35 },
    salary_display: '¥22K',
    salary_raw: 22000,
    currency: 'CNY',
    source: 'Robert Walters Greater China Salary Survey 2025',
    skills: ['Patent Drafting', 'Prior Art Search', 'IP Strategy', 'Technical Analysis', 'Patent Prosecution'],
    technology_skills: ['PatSnap', 'Innography', 'CNIPA Database'],
    industry: 'consulting',
  },

  // ============================================================
  // Energy & Sustainability (能源/可持续) ~6 jobs
  // ============================================================
  {
    code: 'CN-BSE',
    title: 'Battery Systems Engineer',
    title_zh: '电池系统工程师',
    country: 'CN',
    opportunity_score: 80,
    breakdown: { salary: 78, competition: 62, growth: 90, barrier: 62, ai_resilience: 78, demand_growth: 92, remote: 15 },
    salary_display: '¥32K',
    salary_raw: 32000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025; CATL Industry Report 2025',
    skills: ['Battery Pack Design', 'Thermal Management', 'BMS Integration', 'Safety Standards', 'Cell Selection'],
    technology_skills: ['MATLAB/Simulink', 'ANSYS Fluent', 'Star-CCM+'],
    industry: 'energy',
  },
  {
    code: 'CN-SWE',
    title: 'Solar/Wind Engineer',
    title_zh: '光伏/风电工程师',
    country: 'CN',
    opportunity_score: 74,
    breakdown: { salary: 68, competition: 55, growth: 82, barrier: 55, ai_resilience: 72, demand_growth: 85, remote: 15 },
    salary_display: '¥25K',
    salary_raw: 25000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025; 国家能源局 2025',
    skills: ['PV System Design', 'Wind Turbine Technology', 'Grid Integration', 'Energy Storage', 'O&M'],
    technology_skills: ['PVsyst', 'HOMER', 'AutoCAD'],
    industry: 'energy',
  },
  {
    code: 'CN-ESG',
    title: 'Carbon Accountant/ESG Analyst',
    title_zh: '碳核算/ESG分析师',
    country: 'CN',
    opportunity_score: 72,
    breakdown: { salary: 65, competition: 55, growth: 82, barrier: 50, ai_resilience: 55, demand_growth: 85, remote: 35 },
    salary_display: '¥25K',
    salary_raw: 25000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['Carbon Accounting', 'GHG Protocol', 'CBAM', 'ESG Reporting', 'Life Cycle Assessment'],
    technology_skills: ['SimaPro', 'Power BI', 'Python'],
    industry: 'energy',
  },
  {
    code: 'CN-EME',
    title: 'Energy Management Engineer',
    title_zh: '能源管理工程师',
    country: 'CN',
    opportunity_score: 68,
    breakdown: { salary: 62, competition: 50, growth: 75, barrier: 50, ai_resilience: 65, demand_growth: 78, remote: 20 },
    salary_display: '¥22K',
    salary_raw: 22000,
    currency: 'CNY',
    source: 'Robert Walters Greater China Salary Survey 2025',
    skills: ['ISO 50001', 'Energy Audit', 'HVAC Optimization', 'Compressed Air', 'Energy Monitoring'],
    technology_skills: ['EMS Software', 'BMS', 'Power BI'],
    industry: 'energy',
  },
  {
    code: 'CN-HFC',
    title: 'Hydrogen/Fuel Cell Engineer',
    title_zh: '氢能/燃料电池工程师',
    country: 'CN',
    opportunity_score: 76,
    breakdown: { salary: 72, competition: 62, growth: 88, barrier: 68, ai_resilience: 80, demand_growth: 88, remote: 10 },
    salary_display: '¥30K',
    salary_raw: 30000,
    currency: 'CNY',
    source: 'Michael Page Greater China Salary Guide 2025; 国家能源局 2025',
    skills: ['PEM Fuel Cell', 'Hydrogen Storage', 'Stack Design', 'Electrochemistry', 'System Integration'],
    technology_skills: ['COMSOL', 'ANSYS Fluent', 'LabVIEW'],
    industry: 'energy',
  },
  {
    code: 'CN-SUS',
    title: 'Sustainability Manager',
    title_zh: '可持续发展经理',
    country: 'CN',
    opportunity_score: 70,
    breakdown: { salary: 68, competition: 52, growth: 78, barrier: 50, ai_resilience: 58, demand_growth: 80, remote: 30 },
    salary_display: '¥28K',
    salary_raw: 28000,
    currency: 'CNY',
    source: 'Hays Asia Salary Guide 2025',
    skills: ['ESG Strategy', 'Carbon Neutrality Roadmap', 'Stakeholder Engagement', 'Circular Economy', 'Reporting (GRI/TCFD)'],
    technology_skills: ['SimaPro', 'Power BI', 'SAP Sustainability'],
    industry: 'energy',
  },
];
