import type { Job } from './data';

export const germanyJobs: Job[] = [
  // ============================================================
  // Manufacturing Engineering (Fertigungstechnik) — 15 jobs
  // ============================================================
  {
    code: 'DE-MFG-001',
    title: 'Process Engineer',
    title_zh: '工艺工程师',
    title_de: 'Prozessingenieur',
    country: 'DE',
    opportunity_score: 72,
    breakdown: { salary: 65, competition: 78, growth: 70, barrier: 45, ai_resilience: 75, demand_growth: 72, remote: 20 },
    salary_display: '€58K',
    salary_raw: 58000,
    currency: 'EUR',
    source: 'Stepstone Gehaltsreport 2025',
    skills: ['Lean Manufacturing', 'Six Sigma', 'SPC', 'FMEA', 'APQP'],
    technology_skills: ['Minitab', 'SAP PP', 'AutoCAD'],
    industry: 'manufacturing',
  },
  {
    code: 'DE-MFG-002',
    title: 'Manufacturing Engineer',
    title_zh: '制造工程师',
    title_de: 'Fertigungsingenieur',
    country: 'DE',
    opportunity_score: 70,
    breakdown: { salary: 62, competition: 76, growth: 68, barrier: 42, ai_resilience: 74, demand_growth: 70, remote: 15 },
    salary_display: '€56K',
    salary_raw: 56000,
    currency: 'EUR',
    source: 'Hays DE 2025, BA Statistik',
    skills: ['Production Planning', 'Lean Manufacturing', 'Time Study', 'Kaizen', 'PFMEA'],
    technology_skills: ['SAP PP', 'CATIA', 'SolidWorks'],
    industry: 'manufacturing',
  },
  {
    code: 'DE-MFG-003',
    title: 'CNC Programmer',
    title_zh: 'CNC编程员',
    title_de: 'CNC-Programmierer',
    country: 'DE',
    opportunity_score: 68,
    breakdown: { salary: 55, competition: 82, growth: 60, barrier: 50, ai_resilience: 70, demand_growth: 65, remote: 5 },
    salary_display: '€50K',
    salary_raw: 50000,
    currency: 'EUR',
    source: 'BA Statistik, Stepstone 2025',
    skills: ['G-Code', 'CAM Programming', 'GD&T', 'CNC Machining'],
    technology_skills: ['Mastercam', 'Siemens NX CAM', 'Heidenhain'],
    industry: 'manufacturing',
  },
  {
    code: 'DE-MFG-004',
    title: 'Tooling Engineer',
    title_zh: '模具/工装工程师',
    title_de: 'Werkzeugmacher',
    country: 'DE',
    opportunity_score: 66,
    breakdown: { salary: 55, competition: 80, growth: 55, barrier: 55, ai_resilience: 78, demand_growth: 58, remote: 5 },
    salary_display: '€50K',
    salary_raw: 50000,
    currency: 'EUR',
    source: 'BA Statistik, Hays DE 2025',
    skills: ['Tool Design', 'Die Making', 'GD&T', 'Injection Molding'],
    technology_skills: ['CATIA', 'SolidWorks', 'Moldflow'],
    industry: 'manufacturing',
  },
  {
    code: 'DE-MFG-005',
    title: 'Plant Engineer',
    title_zh: '工厂工程师',
    title_de: 'Betriebsingenieur',
    country: 'DE',
    opportunity_score: 69,
    breakdown: { salary: 62, competition: 75, growth: 65, barrier: 45, ai_resilience: 72, demand_growth: 68, remote: 10 },
    salary_display: '€56K',
    salary_raw: 56000,
    currency: 'EUR',
    source: 'Stepstone Gehaltsreport 2025',
    skills: ['Facility Management', 'Maintenance Planning', 'Energy Management', 'Budget Planning'],
    technology_skills: ['SAP PM', 'AutoCAD', 'MS Project'],
    industry: 'manufacturing',
  },
  {
    code: 'DE-MFG-006',
    title: 'Maintenance Engineer',
    title_zh: '维护工程师',
    title_de: 'Instandhaltungsingenieur',
    country: 'DE',
    opportunity_score: 67,
    breakdown: { salary: 58, competition: 80, growth: 60, barrier: 40, ai_resilience: 76, demand_growth: 65, remote: 5 },
    salary_display: '€52K',
    salary_raw: 52000,
    currency: 'EUR',
    source: 'BA Statistik, Hays DE 2025',
    skills: ['Preventive Maintenance', 'TPM', 'Root Cause Analysis', 'PLC Troubleshooting'],
    technology_skills: ['SAP PM', 'CMMS', 'TIA Portal'],
    industry: 'manufacturing',
  },
  {
    code: 'DE-MFG-007',
    title: 'Lean Specialist',
    title_zh: '精益生产专家',
    title_de: 'Lean-Spezialist',
    country: 'DE',
    opportunity_score: 71,
    breakdown: { salary: 65, competition: 70, growth: 72, barrier: 40, ai_resilience: 68, demand_growth: 70, remote: 30 },
    salary_display: '€60K',
    salary_raw: 60000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['Lean Manufacturing', 'Value Stream Mapping', 'Kaizen', '5S', 'Kanban', 'Six Sigma'],
    technology_skills: ['Minitab', 'Power BI', 'SAP'],
    industry: 'manufacturing',
  },
  {
    code: 'DE-MFG-008',
    title: 'NPI Engineer',
    title_zh: '新产品导入工程师',
    title_de: 'NPI-Ingenieur',
    country: 'DE',
    opportunity_score: 73,
    breakdown: { salary: 66, competition: 75, growth: 72, barrier: 48, ai_resilience: 72, demand_growth: 74, remote: 20 },
    salary_display: '€60K',
    salary_raw: 60000,
    currency: 'EUR',
    source: 'Stepstone 2025, VDA 2025',
    skills: ['APQP', 'PPAP', 'Project Management', 'DFMEA', 'PFMEA', 'Launch Management'],
    technology_skills: ['SAP', 'MS Project', 'CATIA'],
    industry: 'manufacturing',
  },
  {
    code: 'DE-MFG-009',
    title: 'R&D Engineer',
    title_zh: '研发工程师',
    title_de: 'Entwicklungsingenieur',
    country: 'DE',
    opportunity_score: 75,
    breakdown: { salary: 72, competition: 72, growth: 75, barrier: 55, ai_resilience: 70, demand_growth: 74, remote: 30 },
    salary_display: '€65K',
    salary_raw: 65000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['Product Development', 'DOE', 'Prototyping', 'FEA', 'Technical Writing'],
    technology_skills: ['SolidWorks', 'ANSYS', 'MATLAB', 'Python'],
    industry: 'manufacturing',
  },
  {
    code: 'DE-MFG-010',
    title: 'Welding Engineer',
    title_zh: '焊接工程师',
    title_de: 'Schweißingenieur',
    country: 'DE',
    opportunity_score: 65,
    breakdown: { salary: 58, competition: 82, growth: 55, barrier: 55, ai_resilience: 80, demand_growth: 58, remote: 5 },
    salary_display: '€52K',
    salary_raw: 52000,
    currency: 'EUR',
    source: 'BA Statistik, DVS Verband',
    skills: ['MIG/MAG', 'TIG', 'Laser Welding', 'IWE Certification', 'NDT'],
    technology_skills: ['Fronius', 'KUKA', 'Weld Simulation'],
    industry: 'manufacturing',
  },
  {
    code: 'DE-MFG-011',
    title: 'Casting/Forging Engineer',
    title_zh: '铸造/锻造工程师',
    title_de: 'Gieß-/Schmiedeingenieur',
    country: 'DE',
    opportunity_score: 62,
    breakdown: { salary: 55, competition: 82, growth: 50, barrier: 58, ai_resilience: 82, demand_growth: 52, remote: 5 },
    salary_display: '€50K',
    salary_raw: 50000,
    currency: 'EUR',
    source: 'BA Statistik, BDG Statistik',
    skills: ['Metallurgy', 'Die Casting', 'Sand Casting', 'Forging Process', 'Heat Treatment'],
    technology_skills: ['MAGMA', 'ProCAST', 'SolidWorks'],
    industry: 'manufacturing',
  },
  {
    code: 'DE-MFG-012',
    title: 'Surface Treatment Engineer',
    title_zh: '表面处理工程师',
    title_de: 'Oberflächentechnik-Ingenieur',
    country: 'DE',
    opportunity_score: 61,
    breakdown: { salary: 52, competition: 78, growth: 52, barrier: 50, ai_resilience: 78, demand_growth: 55, remote: 5 },
    salary_display: '€48K',
    salary_raw: 48000,
    currency: 'EUR',
    source: 'BA Statistik, ZVO Verband',
    skills: ['Electroplating', 'Anodizing', 'PVD/CVD', 'Corrosion Protection', 'Paint Technology'],
    technology_skills: ['SEM/EDX', 'XRF', 'Salt Spray Testing'],
    industry: 'manufacturing',
  },
  {
    code: 'DE-MFG-013',
    title: 'Assembly Engineer',
    title_zh: '装配工程师',
    title_de: 'Montageingenieur',
    country: 'DE',
    opportunity_score: 66,
    breakdown: { salary: 55, competition: 78, growth: 60, barrier: 40, ai_resilience: 72, demand_growth: 62, remote: 10 },
    salary_display: '€50K',
    salary_raw: 50000,
    currency: 'EUR',
    source: 'Stepstone 2025, BA Statistik',
    skills: ['Assembly Line Design', 'Ergonomics', 'Time Study', 'Poka-Yoke', 'PFMEA'],
    technology_skills: ['AutoCAD', 'SAP PP', 'Teamcenter'],
    industry: 'manufacturing',
  },
  {
    code: 'DE-MFG-014',
    title: 'Industrial Engineer',
    title_zh: '工业工程师',
    title_de: 'Wirtschaftsingenieur',
    country: 'DE',
    opportunity_score: 74,
    breakdown: { salary: 68, competition: 72, growth: 72, barrier: 45, ai_resilience: 65, demand_growth: 72, remote: 30 },
    salary_display: '€62K',
    salary_raw: 62000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['Work Study', 'Process Optimization', 'Cost Analysis', 'Ergonomics', 'Capacity Planning'],
    technology_skills: ['SAP', 'Power BI', 'Python', 'Excel VBA'],
    industry: 'manufacturing',
  },
  {
    code: 'DE-MFG-015',
    title: 'Packaging Engineer',
    title_zh: '包装工程师',
    title_de: 'Verpackungsingenieur',
    country: 'DE',
    opportunity_score: 60,
    breakdown: { salary: 50, competition: 72, growth: 55, barrier: 35, ai_resilience: 68, demand_growth: 58, remote: 15 },
    salary_display: '€46K',
    salary_raw: 46000,
    currency: 'EUR',
    source: 'Stepstone 2025, BA Statistik',
    skills: ['Packaging Design', 'Sustainability', 'Logistics Optimization', 'ISTA Testing'],
    technology_skills: ['SolidWorks', 'ArtiosCAD', 'SAP MM'],
    industry: 'manufacturing',
  },

  // ============================================================
  // Automotive (Automobil) — 15 jobs
  // ============================================================
  {
    code: 'DE-AUTO-001',
    title: 'EV Powertrain Engineer',
    title_zh: '电动汽车动力总成工程师',
    title_de: 'EV-Antriebsstrangingenieur',
    country: 'DE',
    opportunity_score: 82,
    breakdown: { salary: 78, competition: 85, growth: 88, barrier: 60, ai_resilience: 78, demand_growth: 90, remote: 25 },
    salary_display: '€75K',
    salary_raw: 75000,
    currency: 'EUR',
    source: 'VDA 2025, Stepstone 2025',
    skills: ['E-Motor Design', 'Power Electronics', 'Vehicle Dynamics', 'Battery Integration', 'Thermal Management'],
    technology_skills: ['MATLAB/Simulink', 'CATIA', 'dSPACE', 'Python'],
    industry: 'automotive',
  },
  {
    code: 'DE-AUTO-002',
    title: 'ADAS Engineer',
    title_zh: 'ADAS高级辅助驾驶工程师',
    title_de: 'ADAS-Ingenieur',
    country: 'DE',
    opportunity_score: 84,
    breakdown: { salary: 82, competition: 88, growth: 90, barrier: 65, ai_resilience: 60, demand_growth: 92, remote: 35 },
    salary_display: '€80K',
    salary_raw: 80000,
    currency: 'EUR',
    source: 'VDA 2025, Bitkom, Hays DE 2025',
    skills: ['Sensor Fusion', 'Computer Vision', 'Radar/Lidar', 'Functional Safety', 'SOTIF'],
    technology_skills: ['Python', 'C++', 'ROS2', 'TensorFlow', 'MATLAB/Simulink'],
    industry: 'automotive',
  },
  {
    code: 'DE-AUTO-003',
    title: 'Battery/BMS Engineer',
    title_zh: '电池/BMS工程师',
    title_de: 'Batterie-/BMS-Ingenieur',
    country: 'DE',
    opportunity_score: 83,
    breakdown: { salary: 80, competition: 86, growth: 88, barrier: 62, ai_resilience: 75, demand_growth: 90, remote: 20 },
    salary_display: '€76K',
    salary_raw: 76000,
    currency: 'EUR',
    source: 'VDA 2025, Stepstone 2025',
    skills: ['Battery Chemistry', 'BMS Design', 'Cell Testing', 'Thermal Management', 'Pack Integration'],
    technology_skills: ['MATLAB/Simulink', 'LabVIEW', 'Python', 'Altium Designer'],
    industry: 'automotive',
  },
  {
    code: 'DE-AUTO-004',
    title: 'Vehicle Integration Engineer',
    title_zh: '整车集成工程师',
    title_de: 'Fahrzeugintegrationssingenieur',
    country: 'DE',
    opportunity_score: 76,
    breakdown: { salary: 72, competition: 78, growth: 74, barrier: 55, ai_resilience: 72, demand_growth: 76, remote: 20 },
    salary_display: '€68K',
    salary_raw: 68000,
    currency: 'EUR',
    source: 'VDA 2025, Stepstone 2025',
    skills: ['Systems Engineering', 'V-Model', 'Requirements Management', 'Integration Testing'],
    technology_skills: ['DOORS', 'CATIA', 'CANoe', 'MATLAB/Simulink'],
    industry: 'automotive',
  },
  {
    code: 'DE-AUTO-005',
    title: 'Chassis Engineer',
    title_zh: '底盘工程师',
    title_de: 'Fahrwerksingenieur',
    country: 'DE',
    opportunity_score: 70,
    breakdown: { salary: 68, competition: 75, growth: 62, barrier: 55, ai_resilience: 75, demand_growth: 65, remote: 15 },
    salary_display: '€62K',
    salary_raw: 62000,
    currency: 'EUR',
    source: 'VDA 2025, Hays DE 2025',
    skills: ['Vehicle Dynamics', 'Suspension Design', 'FEA', 'Kinematics', 'NVH'],
    technology_skills: ['CATIA', 'ADAMS', 'ANSYS', 'MATLAB'],
    industry: 'automotive',
  },
  {
    code: 'DE-AUTO-006',
    title: 'Body-in-White Engineer',
    title_zh: '白车身工程师',
    title_de: 'Rohbauingenieur',
    country: 'DE',
    opportunity_score: 66,
    breakdown: { salary: 62, competition: 76, growth: 58, barrier: 52, ai_resilience: 76, demand_growth: 60, remote: 10 },
    salary_display: '€56K',
    salary_raw: 56000,
    currency: 'EUR',
    source: 'VDA 2025, BA Statistik',
    skills: ['Sheet Metal Design', 'Spot Welding', 'Adhesive Bonding', 'Lightweight Construction', 'Crash Simulation'],
    technology_skills: ['CATIA', 'AutoForm', 'LS-DYNA', 'SolidWorks'],
    industry: 'automotive',
  },
  {
    code: 'DE-AUTO-007',
    title: 'APQP/Launch Engineer',
    title_zh: 'APQP/项目启动工程师',
    title_de: 'APQP-/Anlaufingenieur',
    country: 'DE',
    opportunity_score: 71,
    breakdown: { salary: 65, competition: 76, growth: 68, barrier: 45, ai_resilience: 70, demand_growth: 70, remote: 20 },
    salary_display: '€58K',
    salary_raw: 58000,
    currency: 'EUR',
    source: 'VDA 2025, Hays DE 2025',
    skills: ['APQP', 'PPAP', 'Launch Management', 'Risk Assessment', 'Timing Plans', 'Cross-functional Leadership'],
    technology_skills: ['MS Project', 'SAP', 'JIRA'],
    industry: 'automotive',
  },
  {
    code: 'DE-AUTO-008',
    title: 'Supplier Quality Engineer',
    title_zh: '供应商质量工程师',
    title_de: 'Lieferantenqualitätsingenieur (SQE)',
    country: 'DE',
    opportunity_score: 70,
    breakdown: { salary: 62, competition: 78, growth: 65, barrier: 42, ai_resilience: 72, demand_growth: 68, remote: 20 },
    salary_display: '€56K',
    salary_raw: 56000,
    currency: 'EUR',
    source: 'VDA 2025, Stepstone 2025',
    skills: ['Supplier Auditing', 'PPAP', '8D', 'FMEA', 'VDA 6.3', 'Problem Solving'],
    technology_skills: ['SAP QM', 'Minitab', 'IQMS'],
    industry: 'automotive',
  },
  {
    code: 'DE-AUTO-009',
    title: 'Customer Quality Engineer',
    title_zh: '客户质量工程师',
    title_de: 'Kundenqualitätsingenieur (CQE)',
    country: 'DE',
    opportunity_score: 68,
    breakdown: { salary: 60, competition: 75, growth: 62, barrier: 40, ai_resilience: 70, demand_growth: 65, remote: 20 },
    salary_display: '€54K',
    salary_raw: 54000,
    currency: 'EUR',
    source: 'Hays DE 2025, BA Statistik',
    skills: ['Customer Claims', '8D', 'Complaint Management', 'VDA 6.3', 'FMEA'],
    technology_skills: ['SAP QM', 'Power BI', 'Babtec'],
    industry: 'automotive',
  },
  {
    code: 'DE-AUTO-010',
    title: 'Stamping Engineer',
    title_zh: '冲压工程师',
    title_de: 'Presswerk-Ingenieur',
    country: 'DE',
    opportunity_score: 63,
    breakdown: { salary: 55, competition: 80, growth: 52, barrier: 52, ai_resilience: 78, demand_growth: 55, remote: 5 },
    salary_display: '€50K',
    salary_raw: 50000,
    currency: 'EUR',
    source: 'BA Statistik, VDA 2025',
    skills: ['Stamping Process', 'Die Design', 'Sheet Metal Forming', 'Tryout', 'Quality Control'],
    technology_skills: ['AutoForm', 'CATIA', 'PAM-STAMP'],
    industry: 'automotive',
  },
  {
    code: 'DE-AUTO-011',
    title: 'Painting Engineer',
    title_zh: '涂装工程师',
    title_de: 'Lackieringenieur',
    country: 'DE',
    opportunity_score: 62,
    breakdown: { salary: 55, competition: 78, growth: 52, barrier: 48, ai_resilience: 76, demand_growth: 55, remote: 5 },
    salary_display: '€50K',
    salary_raw: 50000,
    currency: 'EUR',
    source: 'BA Statistik, VDA 2025',
    skills: ['Paint Process', 'Cathodic Dip Coating', 'Color Matching', 'Environmental Compliance'],
    technology_skills: ['RobotStudio', 'SAP QM', 'Spectrophotometry'],
    industry: 'automotive',
  },
  {
    code: 'DE-AUTO-012',
    title: 'EV Charging Engineer',
    title_zh: '电动汽车充电工程师',
    title_de: 'Ladeinfrastruktur-Ingenieur',
    country: 'DE',
    opportunity_score: 79,
    breakdown: { salary: 72, competition: 85, growth: 85, barrier: 50, ai_resilience: 72, demand_growth: 88, remote: 30 },
    salary_display: '€68K',
    salary_raw: 68000,
    currency: 'EUR',
    source: 'Bitkom, BDEW 2025, Stepstone 2025',
    skills: ['OCPP', 'AC/DC Charging', 'Power Electronics', 'Grid Integration', 'ISO 15118'],
    technology_skills: ['Python', 'Embedded C', 'LabVIEW', 'PLC'],
    industry: 'automotive',
  },
  {
    code: 'DE-AUTO-013',
    title: 'Connected Car/V2X Engineer',
    title_zh: '车联网/V2X工程师',
    title_de: 'Connected-Car-/V2X-Ingenieur',
    country: 'DE',
    opportunity_score: 80,
    breakdown: { salary: 78, competition: 85, growth: 85, barrier: 60, ai_resilience: 62, demand_growth: 88, remote: 35 },
    salary_display: '€74K',
    salary_raw: 74000,
    currency: 'EUR',
    source: 'VDA 2025, Bitkom, Hays DE 2025',
    skills: ['V2X Communication', '5G/C-V2X', 'Cybersecurity', 'OTA Updates', 'AUTOSAR Adaptive'],
    technology_skills: ['C++', 'Python', 'Linux', 'MQTT', 'Docker'],
    industry: 'automotive',
  },
  {
    code: 'DE-AUTO-014',
    title: 'Automotive Testing Engineer',
    title_zh: '汽车测试工程师',
    title_de: 'Erprobungsingenieur',
    country: 'DE',
    opportunity_score: 69,
    breakdown: { salary: 62, competition: 76, growth: 65, barrier: 48, ai_resilience: 72, demand_growth: 66, remote: 15 },
    salary_display: '€56K',
    salary_raw: 56000,
    currency: 'EUR',
    source: 'VDA 2025, Stepstone 2025',
    skills: ['Vehicle Testing', 'Test Planning', 'Data Acquisition', 'Durability Testing', 'EMC Testing'],
    technology_skills: ['LabVIEW', 'CANape', 'INCA', 'MATLAB'],
    industry: 'automotive',
  },
  {
    code: 'DE-AUTO-015',
    title: 'Homologation Engineer',
    title_zh: '整车认证工程师',
    title_de: 'Homologationsingenieur',
    country: 'DE',
    opportunity_score: 68,
    breakdown: { salary: 62, competition: 78, growth: 62, barrier: 50, ai_resilience: 65, demand_growth: 65, remote: 20 },
    salary_display: '€56K',
    salary_raw: 56000,
    currency: 'EUR',
    source: 'VDA 2025, Hays DE 2025',
    skills: ['EU Type Approval', 'ECE Regulations', 'WLTP', 'RDE', 'UNECE Standards'],
    technology_skills: ['SAP', 'DOORS', 'MS Office'],
    industry: 'automotive',
  },

  // ============================================================
  // Electronics / Semiconductor (Elektronik/Halbleiter) — 12 jobs
  // ============================================================
  {
    code: 'DE-ELEC-001',
    title: 'IC Design Engineer',
    title_zh: '集成电路设计工程师',
    title_de: 'IC-Design-Ingenieur',
    country: 'DE',
    opportunity_score: 83,
    breakdown: { salary: 82, competition: 90, growth: 85, barrier: 70, ai_resilience: 72, demand_growth: 88, remote: 30 },
    salary_display: '€82K',
    salary_raw: 82000,
    currency: 'EUR',
    source: 'Bitkom, Stepstone 2025, ZVEI 2025',
    skills: ['Analog/Digital IC Design', 'CMOS Design', 'Verification', 'DFT', 'Layout'],
    technology_skills: ['Cadence', 'Synopsys', 'Verilog/VHDL', 'Python'],
    industry: 'electronics',
  },
  {
    code: 'DE-ELEC-002',
    title: 'Semiconductor Process Engineer',
    title_zh: '半导体工艺工程师',
    title_de: 'Halbleiterprozess-Ingenieur',
    country: 'DE',
    opportunity_score: 81,
    breakdown: { salary: 78, competition: 88, growth: 82, barrier: 65, ai_resilience: 75, demand_growth: 85, remote: 10 },
    salary_display: '€76K',
    salary_raw: 76000,
    currency: 'EUR',
    source: 'ZVEI 2025, Stepstone 2025',
    skills: ['Wafer Fabrication', 'Lithography', 'Etching', 'Thin Film', 'Cleanroom'],
    technology_skills: ['SPC', 'JMP', 'Python', 'TCAD'],
    industry: 'electronics',
  },
  {
    code: 'DE-ELEC-003',
    title: 'PCB Design Engineer',
    title_zh: 'PCB设计工程师',
    title_de: 'Leiterplattendesigner',
    country: 'DE',
    opportunity_score: 68,
    breakdown: { salary: 60, competition: 76, growth: 62, barrier: 48, ai_resilience: 68, demand_growth: 65, remote: 35 },
    salary_display: '€55K',
    salary_raw: 55000,
    currency: 'EUR',
    source: 'Hays DE 2025, BA Statistik',
    skills: ['PCB Layout', 'Signal Integrity', 'Power Integrity', 'DFM', 'High-Speed Design'],
    technology_skills: ['Altium Designer', 'Cadence Allegro', 'ZUKEN', 'HyperLynx'],
    industry: 'electronics',
  },
  {
    code: 'DE-ELEC-004',
    title: 'EMC Engineer',
    title_zh: 'EMC电磁兼容工程师',
    title_de: 'EMV-Ingenieur',
    country: 'DE',
    opportunity_score: 72,
    breakdown: { salary: 65, competition: 80, growth: 68, barrier: 55, ai_resilience: 75, demand_growth: 70, remote: 20 },
    salary_display: '€60K',
    salary_raw: 60000,
    currency: 'EUR',
    source: 'Stepstone 2025, ZVEI 2025',
    skills: ['EMI/EMC Testing', 'Shielding Design', 'CE Marking', 'Filter Design', 'CISPR Standards'],
    technology_skills: ['CST Studio', 'ANSYS HFSS', 'Spectrum Analyzers', 'LabVIEW'],
    industry: 'electronics',
  },
  {
    code: 'DE-ELEC-005',
    title: 'Firmware/Embedded Engineer',
    title_zh: '固件/嵌入式工程师',
    title_de: 'Firmware-/Embedded-Ingenieur',
    country: 'DE',
    opportunity_score: 78,
    breakdown: { salary: 72, competition: 82, growth: 78, barrier: 55, ai_resilience: 68, demand_growth: 80, remote: 40 },
    salary_display: '€68K',
    salary_raw: 68000,
    currency: 'EUR',
    source: 'Bitkom, Stepstone 2025, Hays DE 2025',
    skills: ['Embedded C/C++', 'RTOS', 'Device Drivers', 'Bootloader', 'ARM Architecture'],
    technology_skills: ['STM32', 'FreeRTOS', 'Keil/IAR', 'Git', 'JTAG/SWD'],
    industry: 'electronics',
  },
  {
    code: 'DE-ELEC-006',
    title: 'RF Engineer',
    title_zh: '射频工程师',
    title_de: 'HF-Ingenieur',
    country: 'DE',
    opportunity_score: 76,
    breakdown: { salary: 72, competition: 85, growth: 75, barrier: 62, ai_resilience: 78, demand_growth: 78, remote: 20 },
    salary_display: '€68K',
    salary_raw: 68000,
    currency: 'EUR',
    source: 'Bitkom, Stepstone 2025',
    skills: ['RF Design', 'Antenna Design', 'Impedance Matching', '5G/mmWave', 'Radar'],
    technology_skills: ['ADS', 'CST', 'VNA', 'MATLAB', 'Python'],
    industry: 'electronics',
  },
  {
    code: 'DE-ELEC-007',
    title: 'Power Electronics Engineer',
    title_zh: '电力电子工程师',
    title_de: 'Leistungselektronik-Ingenieur',
    country: 'DE',
    opportunity_score: 79,
    breakdown: { salary: 75, competition: 85, growth: 80, barrier: 58, ai_resilience: 78, demand_growth: 82, remote: 15 },
    salary_display: '€70K',
    salary_raw: 70000,
    currency: 'EUR',
    source: 'ZVEI 2025, VDA 2025, Stepstone 2025',
    skills: ['Inverter Design', 'DC-DC Converter', 'SiC/GaN', 'Thermal Management', 'EMC'],
    technology_skills: ['PLECS', 'LTspice', 'Altium Designer', 'MATLAB/Simulink'],
    industry: 'electronics',
  },
  {
    code: 'DE-ELEC-008',
    title: 'FPGA Engineer',
    title_zh: 'FPGA工程师',
    title_de: 'FPGA-Ingenieur',
    country: 'DE',
    opportunity_score: 77,
    breakdown: { salary: 72, competition: 85, growth: 75, barrier: 62, ai_resilience: 72, demand_growth: 78, remote: 35 },
    salary_display: '€68K',
    salary_raw: 68000,
    currency: 'EUR',
    source: 'Bitkom, Stepstone 2025',
    skills: ['FPGA Design', 'RTL Coding', 'Verification', 'Timing Closure', 'DSP'],
    technology_skills: ['Vivado', 'Quartus', 'VHDL', 'Verilog', 'ModelSim'],
    industry: 'electronics',
  },
  {
    code: 'DE-ELEC-009',
    title: 'Test Development Engineer',
    title_zh: '测试开发工程师',
    title_de: 'Testentwicklungsingenieur',
    country: 'DE',
    opportunity_score: 69,
    breakdown: { salary: 62, competition: 76, growth: 65, barrier: 48, ai_resilience: 68, demand_growth: 68, remote: 25 },
    salary_display: '€56K',
    salary_raw: 56000,
    currency: 'EUR',
    source: 'Stepstone 2025, ZVEI 2025',
    skills: ['ATE Development', 'Test Strategy', 'Boundary Scan', 'ICT/FCT', 'DFT'],
    technology_skills: ['LabVIEW', 'Python', 'National Instruments', 'Keysight'],
    industry: 'electronics',
  },
  {
    code: 'DE-ELEC-010',
    title: 'SMT Process Engineer',
    title_zh: 'SMT工艺工程师',
    title_de: 'SMT-Prozessingenieur',
    country: 'DE',
    opportunity_score: 64,
    breakdown: { salary: 55, competition: 78, growth: 58, barrier: 45, ai_resilience: 72, demand_growth: 60, remote: 5 },
    salary_display: '€50K',
    salary_raw: 50000,
    currency: 'EUR',
    source: 'BA Statistik, ZVEI 2025',
    skills: ['SMT Process', 'Reflow Soldering', 'Solder Paste Inspection', 'AOI', 'Stencil Design'],
    technology_skills: ['SPI', 'AOI Systems', 'SAP QM', 'SPC'],
    industry: 'electronics',
  },
  {
    code: 'DE-ELEC-011',
    title: 'Optical Engineer',
    title_zh: '光学工程师',
    title_de: 'Optik-Ingenieur',
    country: 'DE',
    opportunity_score: 74,
    breakdown: { salary: 70, competition: 82, growth: 72, barrier: 60, ai_resilience: 78, demand_growth: 75, remote: 20 },
    salary_display: '€65K',
    salary_raw: 65000,
    currency: 'EUR',
    source: 'Stepstone 2025, Spectaris 2025',
    skills: ['Optical Design', 'Photonics', 'Laser Technology', 'Interferometry', 'Lens Design'],
    technology_skills: ['Zemax', 'COMSOL', 'MATLAB', 'Python'],
    industry: 'electronics',
  },
  {
    code: 'DE-ELEC-012',
    title: 'Sensor Engineer',
    title_zh: '传感器工程师',
    title_de: 'Sensorik-Ingenieur',
    country: 'DE',
    opportunity_score: 76,
    breakdown: { salary: 70, competition: 82, growth: 76, barrier: 55, ai_resilience: 75, demand_growth: 78, remote: 20 },
    salary_display: '€65K',
    salary_raw: 65000,
    currency: 'EUR',
    source: 'AMA Verband 2025, Stepstone 2025',
    skills: ['Sensor Design', 'MEMS', 'Signal Conditioning', 'Calibration', 'IoT Sensors'],
    technology_skills: ['COMSOL', 'MATLAB', 'LabVIEW', 'Python', 'Altium'],
    industry: 'electronics',
  },

  // ============================================================
  // Quality & Safety (Qualität/Sicherheit) — 10 jobs
  // ============================================================
  {
    code: 'DE-QUA-001',
    title: 'Quality Engineer',
    title_zh: '质量工程师',
    title_de: 'Qualitätsingenieur',
    country: 'DE',
    opportunity_score: 70,
    breakdown: { salary: 62, competition: 78, growth: 65, barrier: 40, ai_resilience: 72, demand_growth: 68, remote: 20 },
    salary_display: '€56K',
    salary_raw: 56000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['FMEA', 'SPC', '8D', 'PPAP', 'Control Plans', 'Root Cause Analysis'],
    technology_skills: ['Minitab', 'SAP QM', 'Power BI'],
    industry: 'quality',
  },
  {
    code: 'DE-QUA-002',
    title: 'Quality Manager',
    title_zh: '质量经理',
    title_de: 'Qualitätsleiter',
    country: 'DE',
    opportunity_score: 74,
    breakdown: { salary: 72, competition: 75, growth: 68, barrier: 48, ai_resilience: 70, demand_growth: 70, remote: 25 },
    salary_display: '€68K',
    salary_raw: 68000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['QMS Management', 'IATF 16949', 'ISO 9001', 'Team Leadership', 'Audit Management', 'Budget Planning'],
    technology_skills: ['SAP QM', 'Babtec', 'Power BI', 'MS Office'],
    industry: 'quality',
  },
  {
    code: 'DE-QUA-003',
    title: 'Reliability Engineer',
    title_zh: '可靠性工程师',
    title_de: 'Zuverlässigkeitsingenieur',
    country: 'DE',
    opportunity_score: 72,
    breakdown: { salary: 68, competition: 80, growth: 70, barrier: 55, ai_resilience: 72, demand_growth: 72, remote: 25 },
    salary_display: '€62K',
    salary_raw: 62000,
    currency: 'EUR',
    source: 'Stepstone 2025, VDA 2025',
    skills: ['HALT/HASS', 'Weibull Analysis', 'FMECA', 'Accelerated Life Testing', 'MTBF'],
    technology_skills: ['Minitab', 'Weibull++', 'Python', 'JMP'],
    industry: 'quality',
  },
  {
    code: 'DE-QUA-004',
    title: 'Metrology Engineer',
    title_zh: '计量工程师',
    title_de: 'Messtechnik-Ingenieur',
    country: 'DE',
    opportunity_score: 67,
    breakdown: { salary: 58, competition: 78, growth: 60, barrier: 50, ai_resilience: 74, demand_growth: 62, remote: 10 },
    salary_display: '€52K',
    salary_raw: 52000,
    currency: 'EUR',
    source: 'BA Statistik, Stepstone 2025',
    skills: ['CMM Programming', 'GD&T', 'MSA', 'Gage R&R', 'Optical Metrology'],
    technology_skills: ['Zeiss Calypso', 'PolyWorks', 'PC-DMIS', 'ATOS'],
    industry: 'quality',
  },
  {
    code: 'DE-QUA-005',
    title: 'EHS Manager',
    title_zh: '环境健康安全经理',
    title_de: 'Arbeitssicherheitsmanager',
    country: 'DE',
    opportunity_score: 69,
    breakdown: { salary: 65, competition: 72, growth: 68, barrier: 45, ai_resilience: 68, demand_growth: 70, remote: 20 },
    salary_display: '€60K',
    salary_raw: 60000,
    currency: 'EUR',
    source: 'Stepstone 2025, BA Statistik',
    skills: ['ISO 14001', 'ISO 45001', 'Risk Assessment', 'Incident Investigation', 'German Safety Law'],
    technology_skills: ['Quentic', 'SAP EHS', 'Power BI'],
    industry: 'quality',
  },
  {
    code: 'DE-QUA-006',
    title: 'Functional Safety Engineer',
    title_zh: '功能安全工程师',
    title_de: 'FuSi-Ingenieur',
    country: 'DE',
    opportunity_score: 80,
    breakdown: { salary: 78, competition: 85, growth: 80, barrier: 62, ai_resilience: 75, demand_growth: 82, remote: 30 },
    salary_display: '€74K',
    salary_raw: 74000,
    currency: 'EUR',
    source: 'VDA 2025, Stepstone 2025, Hays DE 2025',
    skills: ['ISO 26262', 'IEC 61508', 'FMEA', 'FTA', 'ASIL Decomposition', 'Safety Case'],
    technology_skills: ['Medini Analyze', 'DOORS', 'Enterprise Architect', 'MATLAB'],
    industry: 'quality',
  },
  {
    code: 'DE-QUA-007',
    title: 'IATF Auditor',
    title_zh: 'IATF审核员',
    title_de: 'IATF-Auditor',
    country: 'DE',
    opportunity_score: 71,
    breakdown: { salary: 68, competition: 75, growth: 65, barrier: 52, ai_resilience: 70, demand_growth: 68, remote: 30 },
    salary_display: '€62K',
    salary_raw: 62000,
    currency: 'EUR',
    source: 'VDA 2025, Hays DE 2025',
    skills: ['IATF 16949', 'VDA 6.3', 'Process Auditing', 'Core Tools', 'Lead Auditor'],
    technology_skills: ['Audit Software', 'SAP QM', 'MS Office'],
    industry: 'quality',
  },
  {
    code: 'DE-QUA-008',
    title: 'Lab Manager',
    title_zh: '实验室经理',
    title_de: 'Laborleiter',
    country: 'DE',
    opportunity_score: 68,
    breakdown: { salary: 65, competition: 72, growth: 60, barrier: 50, ai_resilience: 72, demand_growth: 62, remote: 10 },
    salary_display: '€60K',
    salary_raw: 60000,
    currency: 'EUR',
    source: 'Stepstone 2025, BA Statistik',
    skills: ['ISO 17025', 'Lab Management', 'Materials Testing', 'Team Leadership', 'Method Validation'],
    technology_skills: ['LIMS', 'SAP', 'Statistical Software'],
    industry: 'quality',
  },
  {
    code: 'DE-QUA-009',
    title: 'Failure Analysis Engineer',
    title_zh: '失效分析工程师',
    title_de: 'Schadensanalytiker',
    country: 'DE',
    opportunity_score: 70,
    breakdown: { salary: 65, competition: 80, growth: 65, barrier: 55, ai_resilience: 75, demand_growth: 68, remote: 10 },
    salary_display: '€58K',
    salary_raw: 58000,
    currency: 'EUR',
    source: 'VDA 2025, Stepstone 2025',
    skills: ['Root Cause Analysis', 'Metallography', 'SEM/EDX', 'FIB', 'Fracture Analysis'],
    technology_skills: ['SEM', 'Cross-Section', 'ImageJ', 'Minitab'],
    industry: 'quality',
  },
  {
    code: 'DE-QUA-010',
    title: 'Compliance Engineer',
    title_zh: '合规工程师',
    title_de: 'Compliance-Ingenieur',
    country: 'DE',
    opportunity_score: 69,
    breakdown: { salary: 65, competition: 72, growth: 68, barrier: 48, ai_resilience: 62, demand_growth: 70, remote: 35 },
    salary_display: '€60K',
    salary_raw: 60000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['REACH', 'RoHS', 'CE Marking', 'Product Liability', 'Regulatory Affairs'],
    technology_skills: ['IMDS', 'SAP EHS', 'MS Office'],
    industry: 'quality',
  },

  // ============================================================
  // Supply Chain & Logistics (Lieferkette/Logistik) — 10 jobs
  // ============================================================
  {
    code: 'DE-SCM-001',
    title: 'Supply Chain Manager',
    title_zh: '供应链经理',
    title_de: 'Supply-Chain-Manager',
    country: 'DE',
    opportunity_score: 74,
    breakdown: { salary: 72, competition: 72, growth: 72, barrier: 45, ai_resilience: 62, demand_growth: 75, remote: 35 },
    salary_display: '€68K',
    salary_raw: 68000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['S&OP', 'Demand Planning', 'Supplier Management', 'Risk Management', 'Inventory Optimization'],
    technology_skills: ['SAP MM/PP', 'Power BI', 'Excel Advanced', 'Kinaxis'],
    industry: 'supply-chain',
  },
  {
    code: 'DE-SCM-002',
    title: 'Procurement Manager',
    title_zh: '采购经理',
    title_de: 'Einkaufsleiter',
    country: 'DE',
    opportunity_score: 72,
    breakdown: { salary: 70, competition: 70, growth: 68, barrier: 42, ai_resilience: 60, demand_growth: 70, remote: 30 },
    salary_display: '€65K',
    salary_raw: 65000,
    currency: 'EUR',
    source: 'Stepstone 2025, BME Einkaufsmonitor 2025',
    skills: ['Strategic Sourcing', 'Negotiation', 'Supplier Evaluation', 'Cost Analysis', 'Contract Management'],
    technology_skills: ['SAP MM', 'Ariba', 'Power BI', 'Excel'],
    industry: 'supply-chain',
  },
  {
    code: 'DE-SCM-003',
    title: 'Commodity Manager',
    title_zh: '品类经理',
    title_de: 'Commodity-Manager',
    country: 'DE',
    opportunity_score: 73,
    breakdown: { salary: 72, competition: 72, growth: 70, barrier: 45, ai_resilience: 58, demand_growth: 72, remote: 30 },
    salary_display: '€66K',
    salary_raw: 66000,
    currency: 'EUR',
    source: 'BME Einkaufsmonitor 2025, Hays DE 2025',
    skills: ['Category Strategy', 'Market Analysis', 'Negotiation', 'Cost Modeling', 'Supplier Development'],
    technology_skills: ['SAP MM', 'Should-Cost Tools', 'Power BI'],
    industry: 'supply-chain',
  },
  {
    code: 'DE-SCM-004',
    title: 'Logistics Manager',
    title_zh: '物流经理',
    title_de: 'Logistikleiter',
    country: 'DE',
    opportunity_score: 68,
    breakdown: { salary: 62, competition: 70, growth: 62, barrier: 40, ai_resilience: 58, demand_growth: 65, remote: 20 },
    salary_display: '€58K',
    salary_raw: 58000,
    currency: 'EUR',
    source: 'Stepstone 2025, BVL Logistik 2025',
    skills: ['Warehouse Management', 'Transport Optimization', 'Incoterms', 'Team Leadership', 'KPI Management'],
    technology_skills: ['SAP WM/EWM', 'TMS', 'Power BI', 'Excel'],
    industry: 'supply-chain',
  },
  {
    code: 'DE-SCM-005',
    title: 'Demand Planner',
    title_zh: '需求计划员',
    title_de: 'Bedarfsplaner',
    country: 'DE',
    opportunity_score: 66,
    breakdown: { salary: 58, competition: 70, growth: 65, barrier: 38, ai_resilience: 52, demand_growth: 68, remote: 40 },
    salary_display: '€52K',
    salary_raw: 52000,
    currency: 'EUR',
    source: 'Stepstone 2025, BA Statistik',
    skills: ['Statistical Forecasting', 'S&OP', 'Inventory Planning', 'Data Analysis'],
    technology_skills: ['SAP APO/IBP', 'Excel', 'Power BI', 'Python'],
    industry: 'supply-chain',
  },
  {
    code: 'DE-SCM-006',
    title: 'S&OP Manager',
    title_zh: '销售与运营计划经理',
    title_de: 'S&OP-Manager',
    country: 'DE',
    opportunity_score: 73,
    breakdown: { salary: 72, competition: 72, growth: 70, barrier: 48, ai_resilience: 60, demand_growth: 72, remote: 30 },
    salary_display: '€66K',
    salary_raw: 66000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['S&OP Process', 'Demand-Supply Balancing', 'Cross-functional Alignment', 'Executive Communication'],
    technology_skills: ['SAP IBP', 'Kinaxis', 'Power BI', 'Excel'],
    industry: 'supply-chain',
  },
  {
    code: 'DE-SCM-007',
    title: 'Warehouse Manager',
    title_zh: '仓库经理',
    title_de: 'Lagerleiter',
    country: 'DE',
    opportunity_score: 60,
    breakdown: { salary: 50, competition: 68, growth: 55, barrier: 35, ai_resilience: 58, demand_growth: 58, remote: 5 },
    salary_display: '€46K',
    salary_raw: 46000,
    currency: 'EUR',
    source: 'BA Statistik, BVL Logistik 2025',
    skills: ['Warehouse Operations', 'Inventory Management', 'Team Leadership', 'Safety Management'],
    technology_skills: ['SAP WM/EWM', 'WMS', 'Barcode/RFID'],
    industry: 'supply-chain',
  },
  {
    code: 'DE-SCM-008',
    title: 'Import/Export Specialist',
    title_zh: '进出口/关务专员',
    title_de: 'Zollspezialist',
    country: 'DE',
    opportunity_score: 63,
    breakdown: { salary: 52, competition: 72, growth: 58, barrier: 42, ai_resilience: 55, demand_growth: 62, remote: 30 },
    salary_display: '€48K',
    salary_raw: 48000,
    currency: 'EUR',
    source: 'BA Statistik, Stepstone 2025',
    skills: ['Customs Regulations', 'Incoterms', 'Export Control', 'Trade Compliance', 'HS Classification'],
    technology_skills: ['SAP GTS', 'ATLAS', 'MS Office'],
    industry: 'supply-chain',
  },
  {
    code: 'DE-SCM-009',
    title: 'Supplier Development Engineer',
    title_zh: '供应商开发工程师',
    title_de: 'Lieferantenentwicklungsingenieur',
    country: 'DE',
    opportunity_score: 71,
    breakdown: { salary: 65, competition: 78, growth: 68, barrier: 45, ai_resilience: 72, demand_growth: 70, remote: 20 },
    salary_display: '€58K',
    salary_raw: 58000,
    currency: 'EUR',
    source: 'VDA 2025, Hays DE 2025',
    skills: ['Supplier Auditing', 'Process Improvement', 'VDA 6.3', 'APQP', 'Problem Solving'],
    technology_skills: ['SAP QM', 'Minitab', 'Power BI'],
    industry: 'supply-chain',
  },
  {
    code: 'DE-SCM-010',
    title: 'Materials Manager',
    title_zh: '物料管理经理',
    title_de: 'Materialwirtschaftsleiter',
    country: 'DE',
    opportunity_score: 66,
    breakdown: { salary: 62, competition: 70, growth: 60, barrier: 40, ai_resilience: 58, demand_growth: 62, remote: 15 },
    salary_display: '€56K',
    salary_raw: 56000,
    currency: 'EUR',
    source: 'Stepstone 2025, BA Statistik',
    skills: ['Materials Planning', 'MRP', 'Inventory Control', 'Shortage Management', 'Team Leadership'],
    technology_skills: ['SAP MM', 'Excel', 'Power BI'],
    industry: 'supply-chain',
  },

  // ============================================================
  // IT & Digital Manufacturing (Industrie 4.0) — 10 jobs
  // ============================================================
  {
    code: 'DE-DIG-001',
    title: 'MES Engineer',
    title_zh: 'MES系统工程师',
    title_de: 'MES-Ingenieur',
    country: 'DE',
    opportunity_score: 76,
    breakdown: { salary: 70, competition: 82, growth: 78, barrier: 52, ai_resilience: 65, demand_growth: 80, remote: 30 },
    salary_display: '€65K',
    salary_raw: 65000,
    currency: 'EUR',
    source: 'Bitkom, Stepstone 2025',
    skills: ['MES Implementation', 'ISA-95', 'Production IT', 'OPC UA', 'Data Integration'],
    technology_skills: ['MPDV Hydra', 'Siemens Opcenter', 'SQL', 'Python'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'DE-DIG-002',
    title: 'IIoT Engineer',
    title_zh: '工业物联网工程师',
    title_de: 'Industrie-4.0-Ingenieur',
    country: 'DE',
    opportunity_score: 80,
    breakdown: { salary: 72, competition: 85, growth: 85, barrier: 55, ai_resilience: 62, demand_growth: 88, remote: 35 },
    salary_display: '€68K',
    salary_raw: 68000,
    currency: 'EUR',
    source: 'Bitkom, Plattform Industrie 4.0, Stepstone 2025',
    skills: ['IIoT Architecture', 'Edge Computing', 'OPC UA', 'MQTT', 'Sensor Integration'],
    technology_skills: ['Python', 'Node-RED', 'Azure IoT', 'Docker', 'Grafana'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'DE-DIG-003',
    title: 'Digital Twin Engineer',
    title_zh: '数字孪生工程师',
    title_de: 'Digital-Twin-Ingenieur',
    country: 'DE',
    opportunity_score: 81,
    breakdown: { salary: 75, competition: 88, growth: 88, barrier: 60, ai_resilience: 60, demand_growth: 90, remote: 35 },
    salary_display: '€72K',
    salary_raw: 72000,
    currency: 'EUR',
    source: 'Bitkom, Stepstone 2025, Plattform I4.0',
    skills: ['Digital Twin Modeling', 'Simulation', 'Data Analytics', 'Physics-based Modeling'],
    technology_skills: ['Siemens NX', 'Unity/Unreal', 'Python', 'Azure', 'MATLAB'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'DE-DIG-004',
    title: 'SCADA/DCS Engineer',
    title_zh: 'SCADA/DCS工程师',
    title_de: 'Leittechnik-Ingenieur',
    country: 'DE',
    opportunity_score: 70,
    breakdown: { salary: 62, competition: 78, growth: 65, barrier: 50, ai_resilience: 72, demand_growth: 68, remote: 15 },
    salary_display: '€58K',
    salary_raw: 58000,
    currency: 'EUR',
    source: 'Hays DE 2025, BA Statistik',
    skills: ['SCADA Systems', 'DCS Configuration', 'PLC Programming', 'Process Control', 'Alarm Management'],
    technology_skills: ['WinCC', 'TIA Portal', 'Siemens PCS7', 'Codesys'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'DE-DIG-005',
    title: 'SAP Consultant',
    title_zh: 'SAP顾问',
    title_de: 'SAP-Berater',
    country: 'DE',
    opportunity_score: 75,
    breakdown: { salary: 75, competition: 72, growth: 70, barrier: 48, ai_resilience: 55, demand_growth: 72, remote: 50 },
    salary_display: '€72K',
    salary_raw: 72000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['SAP S/4HANA', 'Business Process', 'Customizing', 'Data Migration', 'Change Management'],
    technology_skills: ['SAP PP/MM/QM', 'ABAP', 'Fiori', 'SQL'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'DE-DIG-006',
    title: 'Manufacturing Data Analyst',
    title_zh: '制造数据分析师',
    title_de: 'Fertigungsdatenanalyst',
    country: 'DE',
    opportunity_score: 77,
    breakdown: { salary: 68, competition: 80, growth: 80, barrier: 45, ai_resilience: 55, demand_growth: 82, remote: 45 },
    salary_display: '€62K',
    salary_raw: 62000,
    currency: 'EUR',
    source: 'Bitkom, Stepstone 2025',
    skills: ['Data Analysis', 'Statistical Modeling', 'Machine Learning', 'Process Mining', 'KPI Development'],
    technology_skills: ['Python', 'Power BI', 'SQL', 'Grafana', 'Tableau'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'DE-DIG-007',
    title: 'Smart Factory Engineer',
    title_zh: '智能工厂工程师',
    title_de: 'Smart-Factory-Ingenieur',
    country: 'DE',
    opportunity_score: 79,
    breakdown: { salary: 72, competition: 85, growth: 82, barrier: 55, ai_resilience: 62, demand_growth: 85, remote: 25 },
    salary_display: '€68K',
    salary_raw: 68000,
    currency: 'EUR',
    source: 'Plattform I4.0, Bitkom, Stepstone 2025',
    skills: ['Industry 4.0', 'Automation Strategy', 'IIoT', 'Lean Digital', 'Change Management'],
    technology_skills: ['Siemens Xcelerator', 'Python', 'Azure/AWS', 'OPC UA'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'DE-DIG-008',
    title: 'PLM Engineer',
    title_zh: 'PLM工程师',
    title_de: 'PLM-Ingenieur',
    country: 'DE',
    opportunity_score: 71,
    breakdown: { salary: 65, competition: 75, growth: 68, barrier: 48, ai_resilience: 60, demand_growth: 70, remote: 35 },
    salary_display: '€60K',
    salary_raw: 60000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['PLM Implementation', 'BOM Management', 'Configuration Management', 'Change Management'],
    technology_skills: ['Teamcenter', 'Windchill', 'SAP PLM', 'Python'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'DE-DIG-009',
    title: 'Automation Software Engineer',
    title_zh: '自动化软件工程师',
    title_de: 'SPS-Softwareentwickler',
    country: 'DE',
    opportunity_score: 76,
    breakdown: { salary: 68, competition: 82, growth: 75, barrier: 52, ai_resilience: 68, demand_growth: 78, remote: 20 },
    salary_display: '€62K',
    salary_raw: 62000,
    currency: 'EUR',
    source: 'Hays DE 2025, ZVEI 2025',
    skills: ['PLC Programming', 'Motion Control', 'Robot Programming', 'Safety PLC', 'HMI Design'],
    technology_skills: ['TIA Portal', 'Codesys', 'KUKA KRL', 'Beckhoff TwinCAT'],
    industry: 'digital-manufacturing',
  },
  {
    code: 'DE-DIG-010',
    title: 'OT Cybersecurity Engineer',
    title_zh: 'OT网络安全工程师',
    title_de: 'OT-Cybersecurity-Ingenieur',
    country: 'DE',
    opportunity_score: 82,
    breakdown: { salary: 78, competition: 90, growth: 85, barrier: 58, ai_resilience: 65, demand_growth: 90, remote: 40 },
    salary_display: '€78K',
    salary_raw: 78000,
    currency: 'EUR',
    source: 'BSI, Bitkom, Stepstone 2025',
    skills: ['ICS Security', 'IEC 62443', 'Network Segmentation', 'Threat Analysis', 'Incident Response'],
    technology_skills: ['Nozomi', 'Claroty', 'Wireshark', 'Python', 'Linux'],
    industry: 'digital-manufacturing',
  },

  // ============================================================
  // Management (Führungskräfte) — 10 jobs
  // ============================================================
  {
    code: 'DE-MGT-001',
    title: 'Production Manager',
    title_zh: '生产经理',
    title_de: 'Fertigungsleiter',
    country: 'DE',
    opportunity_score: 72,
    breakdown: { salary: 72, competition: 72, growth: 65, barrier: 48, ai_resilience: 75, demand_growth: 68, remote: 10 },
    salary_display: '€70K',
    salary_raw: 70000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['Production Planning', 'Team Leadership', 'Lean Manufacturing', 'KPI Management', 'Budget Management'],
    technology_skills: ['SAP PP', 'MES', 'Power BI', 'MS Office'],
    industry: 'management',
  },
  {
    code: 'DE-MGT-002',
    title: 'Plant Director',
    title_zh: '工厂厂长',
    title_de: 'Werksleiter',
    country: 'DE',
    opportunity_score: 78,
    breakdown: { salary: 85, competition: 68, growth: 65, barrier: 55, ai_resilience: 78, demand_growth: 65, remote: 10 },
    salary_display: '€95K',
    salary_raw: 95000,
    currency: 'EUR',
    source: 'Stepstone 2025, Kienbaum 2025',
    skills: ['P&L Management', 'Strategic Planning', 'Change Management', 'Lean Transformation', 'Stakeholder Management'],
    technology_skills: ['SAP', 'Power BI', 'MS Office'],
    industry: 'management',
  },
  {
    code: 'DE-MGT-003',
    title: 'Engineering Manager',
    title_zh: '工程经理',
    title_de: 'Technischer Leiter',
    country: 'DE',
    opportunity_score: 76,
    breakdown: { salary: 80, competition: 72, growth: 70, barrier: 52, ai_resilience: 72, demand_growth: 72, remote: 25 },
    salary_display: '€82K',
    salary_raw: 82000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['Team Leadership', 'Project Portfolio Management', 'Technical Strategy', 'Budget Planning', 'Mentoring'],
    technology_skills: ['MS Project', 'JIRA', 'SAP', 'Power BI'],
    industry: 'management',
  },
  {
    code: 'DE-MGT-004',
    title: 'Operations Director',
    title_zh: '运营总监',
    title_de: 'Betriebsleiter',
    country: 'DE',
    opportunity_score: 79,
    breakdown: { salary: 85, competition: 68, growth: 68, barrier: 55, ai_resilience: 75, demand_growth: 68, remote: 15 },
    salary_display: '€98K',
    salary_raw: 98000,
    currency: 'EUR',
    source: 'Kienbaum 2025, Stepstone 2025',
    skills: ['Operations Strategy', 'P&L Management', 'Lean/TPS', 'Multi-site Management', 'Executive Leadership'],
    technology_skills: ['SAP', 'Power BI', 'MS Office'],
    industry: 'management',
  },
  {
    code: 'DE-MGT-005',
    title: 'R&D Director',
    title_zh: '研发总监',
    title_de: 'F&E-Leiter',
    country: 'DE',
    opportunity_score: 80,
    breakdown: { salary: 88, competition: 72, growth: 72, barrier: 60, ai_resilience: 70, demand_growth: 75, remote: 20 },
    salary_display: '€105K',
    salary_raw: 105000,
    currency: 'EUR',
    source: 'Kienbaum 2025, Stepstone 2025',
    skills: ['Innovation Management', 'IP Strategy', 'Team Building', 'Technical Vision', 'Budget Planning', 'Stakeholder Management'],
    technology_skills: ['PLM', 'JIRA', 'MS Office'],
    industry: 'management',
  },
  {
    code: 'DE-MGT-006',
    title: 'Quality Director',
    title_zh: '质量总监',
    title_de: 'Qualitätsdirektor',
    country: 'DE',
    opportunity_score: 76,
    breakdown: { salary: 82, competition: 72, growth: 65, barrier: 52, ai_resilience: 72, demand_growth: 68, remote: 20 },
    salary_display: '€88K',
    salary_raw: 88000,
    currency: 'EUR',
    source: 'Kienbaum 2025, Hays DE 2025',
    skills: ['QMS Strategy', 'IATF 16949', 'Team Leadership', 'Warranty Reduction', 'Customer Interface'],
    technology_skills: ['SAP QM', 'Power BI', 'Babtec'],
    industry: 'management',
  },
  {
    code: 'DE-MGT-007',
    title: 'Supply Chain Director',
    title_zh: '供应链总监',
    title_de: 'Supply-Chain-Direktor',
    country: 'DE',
    opportunity_score: 78,
    breakdown: { salary: 85, competition: 70, growth: 72, barrier: 52, ai_resilience: 62, demand_growth: 75, remote: 25 },
    salary_display: '€92K',
    salary_raw: 92000,
    currency: 'EUR',
    source: 'Kienbaum 2025, Stepstone 2025',
    skills: ['Supply Chain Strategy', 'Risk Management', 'Procurement Excellence', 'S&OP', 'Digitalization'],
    technology_skills: ['SAP SCM', 'Kinaxis', 'Power BI'],
    industry: 'management',
  },
  {
    code: 'DE-MGT-008',
    title: 'IT Manager / CTO',
    title_zh: 'IT经理/CTO',
    title_de: 'IT-Leiter / CTO',
    country: 'DE',
    opportunity_score: 80,
    breakdown: { salary: 85, competition: 75, growth: 78, barrier: 55, ai_resilience: 58, demand_growth: 80, remote: 40 },
    salary_display: '€95K',
    salary_raw: 95000,
    currency: 'EUR',
    source: 'Bitkom, Stepstone 2025, Kienbaum 2025',
    skills: ['IT Strategy', 'Digital Transformation', 'Team Leadership', 'Cybersecurity', 'Budget Management'],
    technology_skills: ['Cloud Platforms', 'SAP', 'JIRA', 'Enterprise Architecture'],
    industry: 'management',
  },
  {
    code: 'DE-MGT-009',
    title: 'Program Manager Automotive',
    title_zh: '汽车项目经理',
    title_de: 'Projektleiter Automotive',
    country: 'DE',
    opportunity_score: 75,
    breakdown: { salary: 78, competition: 72, growth: 70, barrier: 50, ai_resilience: 72, demand_growth: 72, remote: 25 },
    salary_display: '€78K',
    salary_raw: 78000,
    currency: 'EUR',
    source: 'VDA 2025, Stepstone 2025',
    skills: ['Program Management', 'APQP', 'Risk Management', 'Customer Management', 'Cross-functional Leadership'],
    technology_skills: ['MS Project', 'SAP PS', 'JIRA', 'Power BI'],
    industry: 'management',
  },
  {
    code: 'DE-MGT-010',
    title: 'Technical Sales Director',
    title_zh: '技术销售总监',
    title_de: 'Vertriebsleiter Technik',
    country: 'DE',
    opportunity_score: 77,
    breakdown: { salary: 82, competition: 70, growth: 72, barrier: 48, ai_resilience: 72, demand_growth: 72, remote: 30 },
    salary_display: '€88K',
    salary_raw: 88000,
    currency: 'EUR',
    source: 'Stepstone 2025, Kienbaum 2025',
    skills: ['Key Account Management', 'Technical Presentations', 'Strategic Sales', 'Pricing Strategy', 'Team Leadership'],
    technology_skills: ['CRM (Salesforce)', 'SAP SD', 'Power BI'],
    industry: 'management',
  },

  // ============================================================
  // Consulting & Professional Services (Beratung) — 12 jobs
  // ============================================================
  {
    code: 'DE-CON-001',
    title: 'Management Consultant Manufacturing',
    title_zh: '制造业管理咨询顾问',
    title_de: 'Unternehmensberater Industrie',
    country: 'DE',
    opportunity_score: 76,
    breakdown: { salary: 78, competition: 68, growth: 72, barrier: 52, ai_resilience: 58, demand_growth: 72, remote: 40 },
    salary_display: '€78K',
    salary_raw: 78000,
    currency: 'EUR',
    source: 'Stepstone 2025, BDU 2025',
    skills: ['Strategy Consulting', 'Operational Excellence', 'Data Analysis', 'Stakeholder Management', 'Presentation'],
    technology_skills: ['Power BI', 'Python', 'Excel Advanced', 'PowerPoint'],
    industry: 'consulting',
  },
  {
    code: 'DE-CON-002',
    title: 'Lean/Six Sigma Consultant',
    title_zh: '精益/六西格玛咨询师',
    title_de: 'Lean-Berater',
    country: 'DE',
    opportunity_score: 72,
    breakdown: { salary: 70, competition: 70, growth: 68, barrier: 45, ai_resilience: 65, demand_growth: 70, remote: 35 },
    salary_display: '€65K',
    salary_raw: 65000,
    currency: 'EUR',
    source: 'Stepstone 2025, BDU 2025',
    skills: ['Lean Manufacturing', 'Six Sigma Black Belt', 'Value Stream Mapping', 'Kaizen Facilitation', 'Change Management'],
    technology_skills: ['Minitab', 'Power BI', 'Visio'],
    industry: 'consulting',
  },
  {
    code: 'DE-CON-003',
    title: 'Supply Chain Consultant',
    title_zh: '供应链咨询师',
    title_de: 'SCM-Berater',
    country: 'DE',
    opportunity_score: 74,
    breakdown: { salary: 75, competition: 70, growth: 72, barrier: 48, ai_resilience: 58, demand_growth: 74, remote: 40 },
    salary_display: '€72K',
    salary_raw: 72000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['Supply Chain Design', 'Network Optimization', 'S&OP', 'Risk Modeling', 'Presentation'],
    technology_skills: ['SAP SCM', 'Kinaxis', 'Python', 'Power BI'],
    industry: 'consulting',
  },
  {
    code: 'DE-CON-004',
    title: 'Digital Transformation Consultant',
    title_zh: '数字化转型咨询师',
    title_de: 'Digitalberater',
    country: 'DE',
    opportunity_score: 79,
    breakdown: { salary: 78, competition: 75, growth: 82, barrier: 50, ai_resilience: 55, demand_growth: 82, remote: 50 },
    salary_display: '€76K',
    salary_raw: 76000,
    currency: 'EUR',
    source: 'Bitkom, BDU 2025, Stepstone 2025',
    skills: ['Digital Strategy', 'Industry 4.0', 'Change Management', 'Process Digitalization', 'Agile Methodology'],
    technology_skills: ['Power BI', 'Python', 'Cloud Platforms', 'JIRA'],
    industry: 'consulting',
  },
  {
    code: 'DE-CON-005',
    title: 'EHS Consultant',
    title_zh: '环境健康安全咨询师',
    title_de: 'Arbeitssicherheitsberater',
    country: 'DE',
    opportunity_score: 66,
    breakdown: { salary: 60, competition: 72, growth: 65, barrier: 45, ai_resilience: 68, demand_growth: 68, remote: 30 },
    salary_display: '€55K',
    salary_raw: 55000,
    currency: 'EUR',
    source: 'BA Statistik, Stepstone 2025',
    skills: ['ISO 14001', 'ISO 45001', 'Environmental Auditing', 'Risk Assessment', 'German Safety Regulations'],
    technology_skills: ['Quentic', 'Power BI', 'MS Office'],
    industry: 'consulting',
  },
  {
    code: 'DE-CON-006',
    title: 'Quality Systems Consultant ISO/IATF',
    title_zh: '质量体系咨询师',
    title_de: 'Qualitätsberater',
    country: 'DE',
    opportunity_score: 70,
    breakdown: { salary: 68, competition: 72, growth: 65, barrier: 48, ai_resilience: 65, demand_growth: 68, remote: 35 },
    salary_display: '€62K',
    salary_raw: 62000,
    currency: 'EUR',
    source: 'VDA 2025, Hays DE 2025',
    skills: ['IATF 16949', 'ISO 9001', 'VDA 6.3', 'Audit Leadership', 'QMS Implementation'],
    technology_skills: ['Audit Tools', 'SAP QM', 'MS Office'],
    industry: 'consulting',
  },
  {
    code: 'DE-CON-007',
    title: 'Technical Sales Engineer',
    title_zh: '技术销售工程师',
    title_de: 'Technischer Vertriebsingenieur',
    country: 'DE',
    opportunity_score: 72,
    breakdown: { salary: 68, competition: 72, growth: 68, barrier: 42, ai_resilience: 72, demand_growth: 70, remote: 30 },
    salary_display: '€64K',
    salary_raw: 64000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['Technical Presentations', 'Solution Selling', 'Customer Relationship', 'Proposal Writing', 'Negotiation'],
    technology_skills: ['CRM', 'CAD Viewers', 'SAP SD', 'MS Office'],
    industry: 'consulting',
  },
  {
    code: 'DE-CON-008',
    title: 'Application Engineer',
    title_zh: '应用工程师',
    title_de: 'Applikationsingenieur',
    country: 'DE',
    opportunity_score: 71,
    breakdown: { salary: 65, competition: 76, growth: 68, barrier: 45, ai_resilience: 70, demand_growth: 70, remote: 25 },
    salary_display: '€60K',
    salary_raw: 60000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['Product Application', 'Customer Support', 'Technical Training', 'Problem Solving', 'Demo/POC'],
    technology_skills: ['Product-specific Tools', 'CRM', 'Python', 'MS Office'],
    industry: 'consulting',
  },
  {
    code: 'DE-CON-009',
    title: 'Product Manager Industrial',
    title_zh: '工业产品经理',
    title_de: 'Produktmanager Industrie',
    country: 'DE',
    opportunity_score: 75,
    breakdown: { salary: 75, competition: 70, growth: 72, barrier: 48, ai_resilience: 62, demand_growth: 74, remote: 35 },
    salary_display: '€72K',
    salary_raw: 72000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['Product Strategy', 'Market Analysis', 'Roadmapping', 'P&L Ownership', 'Cross-functional Leadership'],
    technology_skills: ['JIRA', 'Confluence', 'Power BI', 'SAP'],
    industry: 'consulting',
  },
  {
    code: 'DE-CON-010',
    title: 'Business Development Manager',
    title_zh: '商务拓展经理',
    title_de: 'Business-Development-Manager',
    country: 'DE',
    opportunity_score: 73,
    breakdown: { salary: 72, competition: 68, growth: 70, barrier: 42, ai_resilience: 65, demand_growth: 72, remote: 35 },
    salary_display: '€68K',
    salary_raw: 68000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['Market Development', 'Strategic Partnerships', 'Pipeline Management', 'Presentation', 'Negotiation'],
    technology_skills: ['CRM (Salesforce)', 'Power BI', 'LinkedIn Sales Navigator'],
    industry: 'consulting',
  },
  {
    code: 'DE-CON-011',
    title: 'M&A Analyst Industrial',
    title_zh: '工业并购分析师',
    title_de: 'M&A-Analyst Industrie',
    country: 'DE',
    opportunity_score: 74,
    breakdown: { salary: 78, competition: 65, growth: 70, barrier: 58, ai_resilience: 55, demand_growth: 70, remote: 40 },
    salary_display: '€75K',
    salary_raw: 75000,
    currency: 'EUR',
    source: 'Stepstone 2025, Kienbaum 2025',
    skills: ['Financial Modeling', 'Due Diligence', 'Valuation', 'Industry Analysis', 'Deal Structuring'],
    technology_skills: ['Excel Advanced', 'Power BI', 'Bloomberg', 'PowerPoint'],
    industry: 'consulting',
  },
  {
    code: 'DE-CON-012',
    title: 'Patent Engineer',
    title_zh: '专利工程师',
    title_de: 'Patentingenieur',
    country: 'DE',
    opportunity_score: 71,
    breakdown: { salary: 70, competition: 72, growth: 65, barrier: 58, ai_resilience: 62, demand_growth: 68, remote: 40 },
    salary_display: '€66K',
    salary_raw: 66000,
    currency: 'EUR',
    source: 'Stepstone 2025, PAK Verband',
    skills: ['Patent Drafting', 'Prior Art Search', 'IP Strategy', 'Freedom-to-Operate', 'Patent Litigation Support'],
    technology_skills: ['Patent Databases', 'Espacenet', 'MS Office'],
    industry: 'consulting',
  },

  // ============================================================
  // Energy & Sustainability (Energie/Nachhaltigkeit) — 6 jobs
  // ============================================================
  {
    code: 'DE-ENR-001',
    title: 'Battery Systems Engineer',
    title_zh: '电池系统工程师',
    title_de: 'Batteriesystem-Ingenieur',
    country: 'DE',
    opportunity_score: 82,
    breakdown: { salary: 78, competition: 88, growth: 88, barrier: 58, ai_resilience: 75, demand_growth: 90, remote: 20 },
    salary_display: '€74K',
    salary_raw: 74000,
    currency: 'EUR',
    source: 'VDA 2025, Stepstone 2025, VDMA 2025',
    skills: ['Battery Pack Design', 'BMS', 'Thermal Management', 'Cell Chemistry', 'Safety Testing'],
    technology_skills: ['MATLAB/Simulink', 'ANSYS', 'Python', 'Altium Designer'],
    industry: 'energy',
  },
  {
    code: 'DE-ENR-002',
    title: 'Wind/Solar Engineer',
    title_zh: '风能/太阳能工程师',
    title_de: 'Wind-/Solaringenieur',
    country: 'DE',
    opportunity_score: 77,
    breakdown: { salary: 70, competition: 80, growth: 82, barrier: 52, ai_resilience: 75, demand_growth: 85, remote: 25 },
    salary_display: '€65K',
    salary_raw: 65000,
    currency: 'EUR',
    source: 'BWE 2025, Stepstone 2025, BDEW',
    skills: ['Renewable Energy Systems', 'Grid Integration', 'Energy Yield Assessment', 'Structural Analysis', 'Project Development'],
    technology_skills: ['PVsyst', 'WindPRO', 'MATLAB', 'AutoCAD'],
    industry: 'energy',
  },
  {
    code: 'DE-ENR-003',
    title: 'Carbon Accountant / ESG Analyst',
    title_zh: '碳核算/ESG分析师',
    title_de: 'CO2-Bilanzierungsexperte',
    country: 'DE',
    opportunity_score: 75,
    breakdown: { salary: 65, competition: 78, growth: 82, barrier: 42, ai_resilience: 55, demand_growth: 85, remote: 50 },
    salary_display: '€60K',
    salary_raw: 60000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['GHG Protocol', 'CSRD Reporting', 'Life Cycle Assessment', 'ESG Frameworks', 'Carbon Footprint Calculation'],
    technology_skills: ['SimaPro', 'GaBi', 'Power BI', 'Excel', 'Python'],
    industry: 'energy',
  },
  {
    code: 'DE-ENR-004',
    title: 'Energy Management Engineer',
    title_zh: '能源管理工程师',
    title_de: 'Energiemanager',
    country: 'DE',
    opportunity_score: 73,
    breakdown: { salary: 65, competition: 78, growth: 75, barrier: 45, ai_resilience: 68, demand_growth: 80, remote: 25 },
    salary_display: '€60K',
    salary_raw: 60000,
    currency: 'EUR',
    source: 'BDEW, Stepstone 2025',
    skills: ['ISO 50001', 'Energy Auditing', 'Energy Efficiency', 'Renewable Integration', 'Cost Optimization'],
    technology_skills: ['Energy Monitoring Systems', 'Power BI', 'BACnet', 'Python'],
    industry: 'energy',
  },
  {
    code: 'DE-ENR-005',
    title: 'Hydrogen/Fuel Cell Engineer',
    title_zh: '氢能/燃料电池工程师',
    title_de: 'Wasserstoff-Ingenieur',
    country: 'DE',
    opportunity_score: 80,
    breakdown: { salary: 75, competition: 88, growth: 85, barrier: 60, ai_resilience: 78, demand_growth: 88, remote: 15 },
    salary_display: '€72K',
    salary_raw: 72000,
    currency: 'EUR',
    source: 'NOW GmbH 2025, Stepstone 2025, VDMA',
    skills: ['PEM/SOFC Technology', 'Hydrogen Storage', 'Electrolyzer Design', 'System Integration', 'Safety (ATEX)'],
    technology_skills: ['COMSOL', 'ANSYS Fluent', 'MATLAB', 'LabVIEW'],
    industry: 'energy',
  },
  {
    code: 'DE-ENR-006',
    title: 'Sustainability Manager',
    title_zh: '可持续发展经理',
    title_de: 'Nachhaltigkeitsmanager',
    country: 'DE',
    opportunity_score: 74,
    breakdown: { salary: 68, competition: 72, growth: 78, barrier: 42, ai_resilience: 60, demand_growth: 82, remote: 40 },
    salary_display: '€64K',
    salary_raw: 64000,
    currency: 'EUR',
    source: 'Stepstone 2025, Hays DE 2025',
    skills: ['CSRD/EU Taxonomy', 'Sustainability Strategy', 'Stakeholder Engagement', 'Circular Economy', 'Supply Chain Due Diligence'],
    technology_skills: ['ESG Software', 'Power BI', 'GaBi/SimaPro', 'MS Office'],
    industry: 'energy',
  },
];
