import type { IndustryCareerMap } from './types';

export const aerospaceCareerMap: IndustryCareerMap = {
  id: 'aerospace',
  name: 'Aerospace',
  name_zh: '航空航天',
  name_de: 'Luft- und Raumfahrt',
  icon: '✈️',
  description: 'Aerospace offers 10-15% salary premiums over general manufacturing due to stringent safety requirements and specialized expertise. China\'s COMAC C919 program and expanding space sector are driving strong domestic demand.',
  description_zh: '航空航天行业因严格的安全要求和专业技能门槛，薪资比一般制造业高10-15%。中国商飞C919项目和不断扩展的航天领域正在推动强劲的国内需求。',
  description_de: 'Die Luft- und Raumfahrt bietet 10-15% Gehaltsaufschlag gegenüber dem allgemeinen Maschinenbau aufgrund strenger Sicherheitsanforderungen und spezialisierter Fachkenntnisse.',
  avg_salary_cn: 24,
  avg_salary_de: 75,
  top_benefits: ['Security clearance bonus', 'Flight benefits', '13th month salary', 'Relocation package', 'Continued education funding'],
  top_benefits_zh: ['涉密岗位津贴', '机票福利', '13薪', '搬迁补贴', '继续教育资助'],
  ranking_2026: 4,
  sub_categories: [
    { name: 'Commercial Aviation', name_zh: '民航', name_de: 'Zivilluftfahrt', icon: '✈️' },
    { name: 'Defense & Space', name_zh: '国防与航天', name_de: 'Verteidigung & Raumfahrt', icon: '🚀' },
    { name: 'UAV/Drone', name_zh: '无人机', name_de: 'Drohnen', icon: '🛸' },
  ],
  roles: [
    {
      id: 'aero-structural-engineer',
      title: 'Structural Engineer',
      title_zh: '结构工程师',
      title_de: 'Strukturingenieur',
      function_area: 'Engineering',
      function_area_zh: '工程',
      core_skills: ['FEA (NASTRAN/ABAQUS)', 'CATIA/NX', 'Fatigue & Damage Tolerance', 'Composite Materials', 'Structural Test'],
      growth_outlook: 'medium',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 10, mid: 14, high: 18 }, salary_de: { low: 48, mid: 55, high: 63 }, key_skills: ['Stress Analysis Reports', 'CAD Modeling'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 16, mid: 23, high: 32 }, salary_de: { low: 62, mid: 74, high: 88 }, key_skills: ['Damage Tolerance Analysis', 'Certification Compliance (CS-25)'] },
        { level: 'lead', level_zh: '结构主管', level_de: 'Teamleiter Struktur', years_experience: '5-8', salary_cn: { low: 26, mid: 36, high: 48 }, salary_de: { low: 80, mid: 95, high: 112 }, key_skills: ['Structural Design Authority', 'Test Correlation'] },
        { level: 'manager', level_zh: '结构经理', level_de: 'Strukturmanager', years_experience: '8-12', salary_cn: { low: 38, mid: 52, high: 70 }, salary_de: { low: 98, mid: 118, high: 140 }, key_skills: ['Certification Program Management', 'Team Leadership'] },
        { level: 'director', level_zh: '结构总监', level_de: 'Strukturdirektor', years_experience: '12+', salary_cn: { low: 58, mid: 80, high: 110 }, salary_de: { low: 125, mid: 152, high: 190 }, key_skills: ['Aircraft Structural Strategy', 'Airworthiness Authority Interface'] },
      ],
    },
    {
      id: 'aero-avionics-engineer',
      title: 'Avionics Engineer',
      title_zh: '航电工程师',
      title_de: 'Avionik-Ingenieur',
      function_area: 'R&D',
      function_area_zh: '研发',
      core_skills: ['DO-178C', 'DO-254', 'ARINC 429/664', 'MIL-STD-1553', 'Embedded Systems'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 12, mid: 16, high: 22 }, salary_de: { low: 50, mid: 58, high: 67 }, key_skills: ['Requirements Analysis', 'Lab Testing'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 20, mid: 28, high: 40 }, salary_de: { low: 65, mid: 78, high: 92 }, key_skills: ['System Integration', 'Software Verification', 'RTCA Standards'] },
        { level: 'lead', level_zh: '航电主管', level_de: 'Teamleiter Avionik', years_experience: '5-8', salary_cn: { low: 32, mid: 45, high: 60 }, salary_de: { low: 85, mid: 100, high: 118 }, key_skills: ['Avionics Architecture', 'Flight Deck Design'] },
        { level: 'manager', level_zh: '航电经理', level_de: 'Avionik-Manager', years_experience: '8-12', salary_cn: { low: 48, mid: 65, high: 85 }, salary_de: { low: 105, mid: 125, high: 150 }, key_skills: ['Avionics Program Management', 'Supplier Coordination'] },
        { level: 'director', level_zh: '航电总监', level_de: 'Avionik-Direktor', years_experience: '12+', salary_cn: { low: 70, mid: 95, high: 130 }, salary_de: { low: 135, mid: 162, high: 200 }, key_skills: ['Next-Gen Avionics Strategy', 'Certification Authority Relations'] },
      ],
    },
    {
      id: 'aero-systems-engineer',
      title: 'Systems Engineer',
      title_zh: '系统工程师',
      title_de: 'Systemingenieur',
      function_area: 'Engineering',
      function_area_zh: '工程',
      core_skills: ['MBSE (SysML/UML)', 'DOORS', 'V-Model', 'ARP 4754A', 'Requirements Management'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 11, mid: 15, high: 20 }, salary_de: { low: 48, mid: 56, high: 65 }, key_skills: ['Requirements Capture', 'Interface Documentation'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 18, mid: 26, high: 36 }, salary_de: { low: 64, mid: 76, high: 90 }, key_skills: ['System Architecture', 'Trade Study Analysis'] },
        { level: 'lead', level_zh: '系统主管', level_de: 'Teamleiter Systeme', years_experience: '5-8', salary_cn: { low: 30, mid: 42, high: 55 }, salary_de: { low: 82, mid: 98, high: 115 }, key_skills: ['Integration & Verification', 'Safety Assessment'] },
        { level: 'manager', level_zh: '系统经理', level_de: 'Systemmanager', years_experience: '8-12', salary_cn: { low: 45, mid: 60, high: 80 }, salary_de: { low: 100, mid: 120, high: 145 }, key_skills: ['Multi-system Integration', 'Type Certificate Interface'] },
        { level: 'director', level_zh: '系统总监', level_de: 'Systemdirektor', years_experience: '12+', salary_cn: { low: 65, mid: 90, high: 120 }, salary_de: { low: 130, mid: 158, high: 195 }, key_skills: ['Aircraft-level System Strategy', 'Digital Twin Roadmap'] },
      ],
    },
    {
      id: 'aero-flight-test',
      title: 'Flight Test Engineer',
      title_zh: '飞行试验工程师',
      title_de: 'Flugversuchsingenieur',
      function_area: 'Test & Certification',
      function_area_zh: '试验/适航',
      core_skills: ['Flight Test Instrumentation', 'Data Acquisition', 'Telemetry', 'Flight Mechanics', 'Test Plan Development'],
      growth_outlook: 'medium',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 12, mid: 16, high: 22 }, salary_de: { low: 50, mid: 58, high: 68 }, key_skills: ['Data Reduction', 'Instrumentation Setup'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 20, mid: 28, high: 38 }, salary_de: { low: 66, mid: 78, high: 92 }, key_skills: ['Test Point Development', 'Real-time Monitoring'] },
        { level: 'lead', level_zh: '试飞主管', level_de: 'Teamleiter Flugversuch', years_experience: '5-8', salary_cn: { low: 32, mid: 44, high: 58 }, salary_de: { low: 85, mid: 100, high: 118 }, key_skills: ['Flight Test Campaign Management', 'Safety Review Board'] },
        { level: 'manager', level_zh: '试飞经理', level_de: 'Flugversuchsmanager', years_experience: '8-12', salary_cn: { low: 46, mid: 62, high: 82 }, salary_de: { low: 102, mid: 122, high: 148 }, key_skills: ['Certification Flight Test Program', 'Authority Coordination'] },
        { level: 'director', level_zh: '试飞总监', level_de: 'Flugversuchsdirektor', years_experience: '12+', salary_cn: { low: 68, mid: 92, high: 125 }, salary_de: { low: 132, mid: 160, high: 198 }, key_skills: ['Flight Test Strategy', 'Airworthiness Certification Authority'] },
      ],
    },
    {
      id: 'aero-quality-as9100',
      title: 'Quality Engineer (AS9100)',
      title_zh: '质量工程师（AS9100）',
      title_de: 'Qualitätsingenieur (AS9100)',
      function_area: 'Quality',
      function_area_zh: '质量',
      core_skills: ['AS9100/AS9102', 'FAI (First Article Inspection)', 'NADCAP', 'Root Cause Analysis', 'APQP for Aerospace'],
      growth_outlook: 'medium',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 9, mid: 12, high: 16 }, salary_de: { low: 45, mid: 52, high: 60 }, key_skills: ['Inspection Planning', 'NCR Processing'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 15, mid: 22, high: 30 }, salary_de: { low: 58, mid: 70, high: 82 }, key_skills: ['Audit Lead (AS9100)', 'Supplier Quality'] },
        { level: 'lead', level_zh: '质量主管', level_de: 'Teamleiter Qualität', years_experience: '5-8', salary_cn: { low: 25, mid: 34, high: 45 }, salary_de: { low: 75, mid: 88, high: 105 }, key_skills: ['NADCAP Audit Management', 'Quality System Design'] },
        { level: 'manager', level_zh: '质量经理', level_de: 'Qualitätsmanager', years_experience: '8-12', salary_cn: { low: 36, mid: 48, high: 65 }, salary_de: { low: 92, mid: 110, high: 132 }, key_skills: ['Quality Program Management', 'Customer Quality Interface'] },
        { level: 'director', level_zh: '质量总监', level_de: 'Qualitätsdirektor', years_experience: '12+', salary_cn: { low: 55, mid: 75, high: 100 }, salary_de: { low: 118, mid: 145, high: 180 }, key_skills: ['Airworthiness Quality Strategy', 'Regulatory Authority Interface'] },
      ],
    },
    {
      id: 'aero-manufacturing-engineer',
      title: 'Manufacturing Engineer',
      title_zh: '制造工程师',
      title_de: 'Fertigungsingenieur',
      function_area: 'Manufacturing',
      function_area_zh: '制造',
      core_skills: ['CNC Programming', 'Composite Layup', 'Special Processes', 'Lean Manufacturing', 'MES Systems'],
      growth_outlook: 'medium',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 9, mid: 12, high: 16 }, salary_de: { low: 44, mid: 52, high: 60 }, key_skills: ['Process Documentation', 'Tool Design Basics'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 15, mid: 21, high: 30 }, salary_de: { low: 58, mid: 70, high: 82 }, key_skills: ['Process Optimization', 'Fixture Design', 'Automation'] },
        { level: 'lead', level_zh: '制造主管', level_de: 'Teamleiter Fertigung', years_experience: '5-8', salary_cn: { low: 24, mid: 33, high: 44 }, salary_de: { low: 75, mid: 88, high: 104 }, key_skills: ['Production Line Design', 'Rate Readiness'] },
        { level: 'manager', level_zh: '制造经理', level_de: 'Fertigungsmanager', years_experience: '8-12', salary_cn: { low: 36, mid: 48, high: 65 }, salary_de: { low: 92, mid: 110, high: 132 }, key_skills: ['Factory Layout', 'MRB Authority', 'Budget Management'] },
        { level: 'director', level_zh: '制造总监', level_de: 'Fertigungsdirektor', years_experience: '12+', salary_cn: { low: 55, mid: 75, high: 100 }, salary_de: { low: 118, mid: 145, high: 180 }, key_skills: ['Manufacturing Strategy', 'Multi-site Operations', 'Industry 4.0'] },
      ],
    },
    {
      id: 'aero-propulsion-engineer',
      title: 'Propulsion Engineer',
      title_zh: '推进系统工程师',
      title_de: 'Antriebsingenieur',
      function_area: 'R&D',
      function_area_zh: '研发',
      core_skills: ['Thermodynamics', 'CFD (ANSYS Fluent)', 'Engine Performance', 'Materials (Superalloys)', 'FADEC'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 12, mid: 16, high: 22 }, salary_de: { low: 50, mid: 58, high: 67 }, key_skills: ['CFD Meshing', 'Test Data Analysis'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 20, mid: 28, high: 40 }, salary_de: { low: 66, mid: 80, high: 95 }, key_skills: ['Component Design (Turbine/Compressor)', 'Engine Cycle Analysis'] },
        { level: 'lead', level_zh: '推进主管', level_de: 'Teamleiter Antrieb', years_experience: '5-8', salary_cn: { low: 33, mid: 46, high: 62 }, salary_de: { low: 88, mid: 105, high: 125 }, key_skills: ['Engine Architecture', 'Performance Optimization'] },
        { level: 'manager', level_zh: '推进经理', level_de: 'Antriebsmanager', years_experience: '8-12', salary_cn: { low: 48, mid: 65, high: 88 }, salary_de: { low: 108, mid: 128, high: 155 }, key_skills: ['Engine Development Program', 'Certification (FAR Part 33)'] },
        { level: 'director', level_zh: '推进总监', level_de: 'Antriebsdirektor', years_experience: '12+', salary_cn: { low: 72, mid: 98, high: 135 }, salary_de: { low: 138, mid: 168, high: 208 }, key_skills: ['Propulsion Technology Roadmap', 'Sustainable Aviation Fuel Strategy'] },
      ],
    },
  ],
};
