import type { IndustryCareerMap } from './types';

export const automotiveCareerMap: IndustryCareerMap = {
  id: 'automotive',
  name: 'Automotive',
  name_zh: '汽车工业',
  name_de: 'Automobilindustrie',
  icon: '🚗',
  description: 'The automotive industry is undergoing its biggest transformation with EV, autonomous driving, and software-defined vehicles. Engineers with both traditional and new-energy skills command premium salaries.',
  description_zh: '汽车行业正经历电动化、自动驾驶和软件定义汽车的最大变革。同时掌握传统和新能源技能的工程师薪资溢价显著。',
  description_de: 'Die Automobilindustrie durchläuft die größte Transformation mit E-Mobilität, autonomem Fahren und Software-definierten Fahrzeugen.',
  avg_salary_cn: 22,
  avg_salary_de: 68,
  top_benefits: ['Company car / car discount', '13th month salary', 'Relocation package', 'Patent bonus'],
  top_benefits_zh: ['公司配车/购车优惠', '13薪', '搬迁补贴', '专利奖金'],
  ranking_2026: 3,
  sub_categories: [
    { name: 'Electric Vehicles', name_zh: '电动汽车', name_de: 'Elektrofahrzeuge', icon: '🔋' },
    { name: 'Autonomous Driving', name_zh: '自动驾驶', name_de: 'Autonomes Fahren', icon: '🛞' },
    { name: 'Connected Car', name_zh: '智能网联', name_de: 'Vernetztes Fahrzeug', icon: '📡' },
    { name: 'Traditional Powertrain', name_zh: '传统动力总成', name_de: 'Konventioneller Antrieb', icon: '⚙️' },
  ],
  roles: [
    {
      id: 'auto-quality-engineer',
      title: 'Quality Engineer',
      title_zh: '质量工程师',
      title_de: 'Qualitätsingenieur',
      soc_code: '17-2112.00',
      kldb_code: '27314',
      function_area: 'Quality',
      function_area_zh: '质量',
      core_skills: ['IATF 16949', 'FMEA', 'APQP', 'PPAP', 'SPC', 'MSA'],
      growth_outlook: 'medium',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 8, mid: 10, high: 13 }, salary_de: { low: 42, mid: 48, high: 55 }, key_skills: ['8D Report', 'Control Plan'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 13, mid: 18, high: 25 }, salary_de: { low: 55, mid: 65, high: 75 }, key_skills: ['VDA 6.3 Auditor', 'Supplier Development'] },
        { level: 'lead', level_zh: '质量主管', level_de: 'Teamleiter Qualität', years_experience: '5-8', salary_cn: { low: 22, mid: 28, high: 35 }, salary_de: { low: 70, mid: 80, high: 92 }, key_skills: ['Team Leadership', 'Customer Quality'] },
        { level: 'manager', level_zh: '质量经理', level_de: 'Qualitätsmanager', years_experience: '8-12', salary_cn: { low: 30, mid: 40, high: 55 }, salary_de: { low: 85, mid: 100, high: 120 }, key_skills: ['Quality Strategy', 'Budget Management', 'Plant-level KPIs'] },
        { level: 'director', level_zh: '质量总监', level_de: 'Qualitätsdirektor', years_experience: '12+', salary_cn: { low: 50, mid: 70, high: 100 }, salary_de: { low: 110, mid: 135, high: 170 }, key_skills: ['Global Quality Strategy', 'Board Reporting', 'M&A Due Diligence'] },
      ],
    },
    {
      id: 'auto-process-engineer',
      title: 'Process Engineer',
      title_zh: '工艺工程师',
      title_de: 'Prozessingenieur',
      soc_code: '17-2112.00',
      kldb_code: '27214',
      function_area: 'Manufacturing',
      function_area_zh: '制造',
      core_skills: ['Lean Manufacturing', 'Six Sigma', 'PFMEA', 'SPC', 'GD&T'],
      growth_outlook: 'medium',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 7, mid: 9, high: 12 }, salary_de: { low: 40, mid: 46, high: 52 }, key_skills: ['Process Documentation', 'Time Study'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 12, mid: 16, high: 22 }, salary_de: { low: 52, mid: 62, high: 72 }, key_skills: ['Process Optimization', 'Kaizen Leader'] },
        { level: 'lead', level_zh: '工艺主管', level_de: 'Teamleiter Prozess', years_experience: '5-8', salary_cn: { low: 20, mid: 26, high: 33 }, salary_de: { low: 68, mid: 78, high: 90 }, key_skills: ['New Launch Management', 'Line Layout Design'] },
        { level: 'manager', level_zh: '工艺经理', level_de: 'Prozessmanager', years_experience: '8-12', salary_cn: { low: 28, mid: 38, high: 50 }, salary_de: { low: 82, mid: 95, high: 115 }, key_skills: ['Plant Layout', 'CapEx Planning', 'Automation Strategy'] },
        { level: 'director', level_zh: '制造总监', level_de: 'Fertigungsdirektor', years_experience: '12+', salary_cn: { low: 45, mid: 65, high: 90 }, salary_de: { low: 105, mid: 130, high: 160 }, key_skills: ['Multi-plant Operations', 'Industry 4.0 Roadmap'] },
      ],
    },
    {
      id: 'auto-adas-engineer',
      title: 'ADAS / AD Engineer',
      title_zh: 'ADAS/自动驾驶工程师',
      title_de: 'ADAS-/AD-Ingenieur',
      soc_code: '17-2199.00',
      kldb_code: '25234',
      function_area: 'R&D',
      function_area_zh: '研发',
      core_skills: ['C/C++', 'Python', 'ROS', 'Computer Vision', 'Sensor Fusion'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 15, mid: 20, high: 28 }, salary_de: { low: 50, mid: 58, high: 68 }, key_skills: ['OpenCV', 'LIDAR Processing'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 25, mid: 35, high: 50 }, salary_de: { low: 65, mid: 78, high: 95 }, key_skills: ['Deep Learning', 'AUTOSAR', 'Functional Safety'] },
        { level: 'lead', level_zh: '技术主管', level_de: 'Teamleiter', years_experience: '5-8', salary_cn: { low: 40, mid: 55, high: 75 }, salary_de: { low: 85, mid: 100, high: 120 }, key_skills: ['System Architecture', 'Algorithm Design'] },
        { level: 'manager', level_zh: '研发经理', level_de: 'Entwicklungsmanager', years_experience: '8-12', salary_cn: { low: 55, mid: 75, high: 100 }, salary_de: { low: 100, mid: 120, high: 150 }, key_skills: ['Product Roadmap', 'OEM Partnership'] },
        { level: 'director', level_zh: '研发总监', level_de: 'Entwicklungsdirektor', years_experience: '12+', salary_cn: { low: 80, mid: 110, high: 150 }, salary_de: { low: 130, mid: 160, high: 200 }, key_skills: ['Technology Strategy', 'Patent Portfolio'] },
      ],
    },
    {
      id: 'auto-ev-powertrain',
      title: 'EV Powertrain Engineer',
      title_zh: '新能源动力系统工程师',
      title_de: 'EV-Antriebsingenieur',
      soc_code: '17-2199.00',
      kldb_code: '26134',
      function_area: 'R&D',
      function_area_zh: '研发',
      core_skills: ['Battery Systems', 'Power Electronics', 'MATLAB/Simulink', 'BMS', 'Thermal Management'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 12, mid: 16, high: 22 }, salary_de: { low: 48, mid: 55, high: 65 }, key_skills: ['Cell Testing', 'CANape'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 20, mid: 30, high: 42 }, salary_de: { low: 62, mid: 75, high: 90 }, key_skills: ['Pack Design', 'HIL Testing', 'ISO 26262'] },
        { level: 'lead', level_zh: '技术主管', level_de: 'Teamleiter', years_experience: '5-8', salary_cn: { low: 35, mid: 48, high: 65 }, salary_de: { low: 80, mid: 95, high: 115 }, key_skills: ['Platform Architecture', 'Supplier Management'] },
        { level: 'manager', level_zh: '动力系统经理', level_de: 'Antriebsmanager', years_experience: '8-12', salary_cn: { low: 50, mid: 68, high: 90 }, salary_de: { low: 95, mid: 115, high: 140 }, key_skills: ['Multi-project Management', 'Cost Optimization'] },
        { level: 'director', level_zh: '动力系统总监', level_de: 'Antriebsdirektor', years_experience: '12+', salary_cn: { low: 70, mid: 100, high: 140 }, salary_de: { low: 125, mid: 155, high: 190 }, key_skills: ['EV Strategy', 'Global R&D Coordination'] },
      ],
    },
    {
      id: 'auto-sqe',
      title: 'Supplier Quality Engineer',
      title_zh: '供应商质量工程师 (SQE)',
      title_de: 'Lieferantenqualitätsingenieur',
      soc_code: '17-2112.00',
      kldb_code: '27314',
      function_area: 'Quality / Supply Chain',
      function_area_zh: '质量/供应链',
      core_skills: ['VDA 6.3', 'APQP', 'PPAP', 'Supplier Audit', 'Problem Solving'],
      growth_outlook: 'medium',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级SQE', level_de: 'Junior SQE', years_experience: '0-2', salary_cn: { low: 8, mid: 11, high: 14 }, salary_de: { low: 43, mid: 50, high: 58 }, key_skills: ['Incoming Inspection', 'Supplier Audit'] },
        { level: 'senior', level_zh: '高级SQE', level_de: 'Senior SQE', years_experience: '3-5', salary_cn: { low: 14, mid: 20, high: 28 }, salary_de: { low: 58, mid: 68, high: 80 }, key_skills: ['Supplier Development', 'Cost Recovery (PPM)'] },
        { level: 'lead', level_zh: 'SQE主管', level_de: 'SQE Teamleiter', years_experience: '5-8', salary_cn: { low: 24, mid: 32, high: 40 }, salary_de: { low: 72, mid: 85, high: 98 }, key_skills: ['Commodity Strategy', 'Risk Assessment'] },
        { level: 'manager', level_zh: 'SQE经理', level_de: 'SQE Manager', years_experience: '8-12', salary_cn: { low: 35, mid: 45, high: 60 }, salary_de: { low: 88, mid: 105, high: 125 }, key_skills: ['Global Supplier Strategy', 'Team Building'] },
        { level: 'director', level_zh: '供应链质量总监', level_de: 'Direktor Lieferantenqualität', years_experience: '12+', salary_cn: { low: 55, mid: 75, high: 100 }, salary_de: { low: 115, mid: 140, high: 175 }, key_skills: ['Supply Chain Risk', 'Executive Reporting'] },
      ],
    },
    {
      id: 'auto-me-design',
      title: 'Mechanical Design Engineer',
      title_zh: '机械设计工程师',
      title_de: 'Konstruktionsingenieur',
      soc_code: '17-2141.00',
      kldb_code: '27124',
      function_area: 'Engineering',
      function_area_zh: '工程',
      core_skills: ['CATIA/NX', 'GD&T', 'DFM/DFA', 'FEA', 'Materials Science'],
      growth_outlook: 'medium',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '初级设计工程师', level_de: 'Junior-Konstrukteur', years_experience: '0-2', salary_cn: { low: 8, mid: 11, high: 15 }, salary_de: { low: 42, mid: 50, high: 58 }, key_skills: ['3D Modeling', 'Drawing Standards'] },
        { level: 'senior', level_zh: '高级设计工程师', level_de: 'Senior-Konstrukteur', years_experience: '3-5', salary_cn: { low: 14, mid: 20, high: 28 }, salary_de: { low: 55, mid: 66, high: 78 }, key_skills: ['Tolerance Stack-up', 'Prototype Management'] },
        { level: 'lead', level_zh: '设计主管', level_de: 'Teamleiter Konstruktion', years_experience: '5-8', salary_cn: { low: 22, mid: 30, high: 40 }, salary_de: { low: 72, mid: 84, high: 98 }, key_skills: ['System-level Design', 'Cross-functional Coordination'] },
        { level: 'manager', level_zh: '设计经理', level_de: 'Konstruktionsmanager', years_experience: '8-12', salary_cn: { low: 32, mid: 42, high: 58 }, salary_de: { low: 88, mid: 102, high: 122 }, key_skills: ['Design Standards', 'IP Management'] },
        { level: 'director', level_zh: '工程总监', level_de: 'Engineering-Direktor', years_experience: '12+', salary_cn: { low: 50, mid: 70, high: 95 }, salary_de: { low: 112, mid: 138, high: 170 }, key_skills: ['Product Strategy', 'Platform Architecture'] },
      ],
    },
    {
      id: 'auto-test-validation',
      title: 'Test & Validation Engineer',
      title_zh: '测试验证工程师',
      title_de: 'Test- und Validierungsingenieur',
      soc_code: '17-2141.02',
      kldb_code: '27314',
      function_area: 'Engineering',
      function_area_zh: '工程',
      core_skills: ['DVP&R', 'DFMEA', 'Test Planning', 'Data Analysis', 'Lab Equipment'],
      growth_outlook: 'medium',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级测试工程师', level_de: 'Junior Testingenieur', years_experience: '0-2', salary_cn: { low: 7, mid: 10, high: 13 }, salary_de: { low: 40, mid: 47, high: 54 }, key_skills: ['Test Execution', 'Report Writing'] },
        { level: 'senior', level_zh: '高级测试工程师', level_de: 'Senior Testingenieur', years_experience: '3-5', salary_cn: { low: 12, mid: 17, high: 24 }, salary_de: { low: 52, mid: 63, high: 75 }, key_skills: ['Test Automation', 'HIL/SIL', 'Environmental Testing'] },
        { level: 'lead', level_zh: '测试主管', level_de: 'Teamleiter Test', years_experience: '5-8', salary_cn: { low: 20, mid: 27, high: 35 }, salary_de: { low: 68, mid: 80, high: 94 }, key_skills: ['Lab Management', 'Certification (ECE/FMVSS)'] },
        { level: 'manager', level_zh: '测试经理', level_de: 'Testmanager', years_experience: '8-12', salary_cn: { low: 30, mid: 40, high: 52 }, salary_de: { low: 85, mid: 98, high: 118 }, key_skills: ['Global Test Strategy', 'Homologation'] },
        { level: 'director', level_zh: '测试验证总监', level_de: 'Validierungsdirektor', years_experience: '12+', salary_cn: { low: 48, mid: 65, high: 88 }, salary_de: { low: 108, mid: 132, high: 165 }, key_skills: ['Proving Ground Strategy', 'Virtual Validation Roadmap'] },
      ],
    },
    {
      id: 'auto-embedded-sw',
      title: 'Embedded Software Engineer',
      title_zh: '嵌入式软件工程师',
      title_de: 'Embedded-Software-Ingenieur',
      soc_code: '15-1252.00',
      kldb_code: '43414',
      function_area: 'Software',
      function_area_zh: '软件',
      core_skills: ['C/C++', 'AUTOSAR', 'CAN/LIN', 'RTOS', 'MISRA'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级软件工程师', level_de: 'Junior SW-Ingenieur', years_experience: '0-2', salary_cn: { low: 12, mid: 16, high: 22 }, salary_de: { low: 48, mid: 56, high: 65 }, key_skills: ['Unit Testing', 'Debugging'] },
        { level: 'senior', level_zh: '高级软件工程师', level_de: 'Senior SW-Ingenieur', years_experience: '3-5', salary_cn: { low: 20, mid: 28, high: 40 }, salary_de: { low: 62, mid: 75, high: 90 }, key_skills: ['AUTOSAR BSW', 'Model-Based Design'] },
        { level: 'lead', level_zh: '软件主管', level_de: 'SW-Teamleiter', years_experience: '5-8', salary_cn: { low: 33, mid: 45, high: 60 }, salary_de: { low: 82, mid: 96, high: 115 }, key_skills: ['Architecture Design', 'CI/CD', 'ISO 26262 ASIL'] },
        { level: 'manager', level_zh: '软件经理', level_de: 'SW-Manager', years_experience: '8-12', salary_cn: { low: 45, mid: 62, high: 85 }, salary_de: { low: 98, mid: 118, high: 145 }, key_skills: ['ASPICE', 'Cross-ECU Integration'] },
        { level: 'director', level_zh: '软件总监', level_de: 'SW-Direktor', years_experience: '12+', salary_cn: { low: 70, mid: 95, high: 130 }, salary_de: { low: 128, mid: 155, high: 195 }, key_skills: ['SDV Strategy', 'OEM SW Platform'] },
      ],
    },
    {
      id: 'auto-purchasing',
      title: 'Purchasing / Procurement',
      title_zh: '采购工程师',
      title_de: 'Einkaufsingenieur',
      soc_code: '13-1023.00',
      kldb_code: '61214',
      function_area: 'Supply Chain',
      function_area_zh: '供应链',
      core_skills: ['Negotiation', 'Cost Analysis', 'Supplier Management', 'SAP MM', 'Contract Law'],
      growth_outlook: 'medium',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '初级采购', level_de: 'Junior Einkäufer', years_experience: '0-2', salary_cn: { low: 7, mid: 9, high: 12 }, salary_de: { low: 40, mid: 46, high: 53 }, key_skills: ['RFQ Process', 'SAP MM'] },
        { level: 'senior', level_zh: '高级采购', level_de: 'Senior Einkäufer', years_experience: '3-5', salary_cn: { low: 12, mid: 16, high: 22 }, salary_de: { low: 52, mid: 62, high: 74 }, key_skills: ['Should-Cost Modeling', 'LTA Negotiation'] },
        { level: 'lead', level_zh: '采购主管', level_de: 'Teamleiter Einkauf', years_experience: '5-8', salary_cn: { low: 18, mid: 25, high: 33 }, salary_de: { low: 68, mid: 80, high: 95 }, key_skills: ['Category Management', 'Risk Mitigation'] },
        { level: 'manager', level_zh: '采购经理', level_de: 'Einkaufsmanager', years_experience: '8-12', salary_cn: { low: 28, mid: 38, high: 50 }, salary_de: { low: 85, mid: 100, high: 120 }, key_skills: ['Global Sourcing Strategy', 'Team Management'] },
        { level: 'director', level_zh: '采购总监', level_de: 'Einkaufsdirektor', years_experience: '12+', salary_cn: { low: 45, mid: 62, high: 85 }, salary_de: { low: 110, mid: 135, high: 170 }, key_skills: ['Supply Chain Transformation', 'Board-level Strategy'] },
      ],
    },
    {
      id: 'auto-project-mgmt',
      title: 'Project Manager',
      title_zh: '项目经理',
      title_de: 'Projektmanager',
      soc_code: '11-9199.00',
      kldb_code: '27214',
      function_area: 'Management',
      function_area_zh: '管理',
      core_skills: ['PMP/IPMA', 'APQP', 'MS Project', 'Risk Management', 'Cross-functional Leadership'],
      growth_outlook: 'medium',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '项目协调员', level_de: 'Projektkoordinator', years_experience: '0-2', salary_cn: { low: 8, mid: 11, high: 15 }, salary_de: { low: 43, mid: 50, high: 58 }, key_skills: ['MS Project', 'APQP Timing Plan'] },
        { level: 'senior', level_zh: '项目经理', level_de: 'Projektmanager', years_experience: '3-5', salary_cn: { low: 15, mid: 22, high: 30 }, salary_de: { low: 58, mid: 70, high: 85 }, key_skills: ['Multi-project Management', 'Customer Interface'] },
        { level: 'lead', level_zh: '高级项目经理', level_de: 'Senior Projektmanager', years_experience: '5-8', salary_cn: { low: 25, mid: 35, high: 48 }, salary_de: { low: 78, mid: 92, high: 108 }, key_skills: ['Program Management', 'Launch Management'] },
        { level: 'manager', level_zh: '项目管理经理', level_de: 'Leiter Projektmanagement', years_experience: '8-12', salary_cn: { low: 38, mid: 50, high: 68 }, salary_de: { low: 95, mid: 112, high: 135 }, key_skills: ['PMO Setup', 'Portfolio Management'] },
        { level: 'director', level_zh: '项目总监', level_de: 'Programmdirektor', years_experience: '12+', salary_cn: { low: 55, mid: 75, high: 105 }, salary_de: { low: 120, mid: 148, high: 185 }, key_skills: ['Strategic Program Planning', 'P&L Responsibility'] },
      ],
    },
  ],
};
