import type { IndustryCareerMap } from './types';

export const consultingCareerMap: IndustryCareerMap = {
  id: 'consulting',
  name: 'Management Consulting',
  name_zh: '管理咨询',
  name_de: 'Managementberatung',
  icon: '💼',
  description: 'Management consulting offers steep salary progression and rapid career advancement. Top-tier firms (MBB) command significant premiums. The industry rewards analytical rigor, client management, and the ability to drive transformation.',
  description_zh: '管理咨询行业薪资增长陡峭，职业晋升快速。顶级咨询公司（MBB）薪资溢价显著。行业重视分析能力、客户管理和推动变革的能力。',
  description_de: 'Managementberatung bietet steile Gehaltsentwicklung und schnellen Karriereaufstieg. Top-Firmen (MBB) zahlen erhebliche Prämien. Die Branche belohnt analytische Strenge und Transformationskompetenz.',
  avg_salary_cn: 28,
  avg_salary_de: 82,
  top_benefits: ['Performance bonus (20-100%)', 'MBA sponsorship', 'Business class travel', 'Annual offsite retreat', 'Professional development budget'],
  top_benefits_zh: ['绩效奖金（20-100%）', 'MBA赞助', '商务舱出差', '年度团建', '专业发展预算'],
  ranking_2026: 5,
  sub_categories: [
    { name: 'Strategy', name_zh: '战略咨询', name_de: 'Strategieberatung', icon: '🎯' },
    { name: 'Operations', name_zh: '运营咨询', name_de: 'Operationsberatung', icon: '📊' },
    { name: 'IT/Digital', name_zh: 'IT/数字化咨询', name_de: 'IT-/Digitalberatung', icon: '💻' },
  ],
  roles: [
    {
      id: 'consult-strategy',
      title: 'Strategy Consultant',
      title_zh: '战略咨询顾问',
      title_de: 'Strategieberater',
      function_area: 'Strategy',
      function_area_zh: '战略',
      core_skills: ['Market Sizing', 'Competitive Analysis', 'Financial Modeling', 'Executive Presentation', 'Hypothesis-driven Problem Solving'],
      growth_outlook: 'high',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '分析师', level_de: 'Analyst', years_experience: '0-2', salary_cn: { low: 15, mid: 22, high: 35 }, salary_de: { low: 55, mid: 65, high: 78 }, key_skills: ['Data Analysis', 'Slide Design', 'Research'] },
        { level: 'senior', level_zh: '咨询顾问', level_de: 'Berater', years_experience: '2-4', salary_cn: { low: 28, mid: 40, high: 55 }, salary_de: { low: 72, mid: 88, high: 105 }, key_skills: ['Workstream Lead', 'Client Workshop Facilitation'] },
        { level: 'lead', level_zh: '高级顾问/项目经理', level_de: 'Senior-Berater / Projektleiter', years_experience: '4-7', salary_cn: { low: 45, mid: 65, high: 90 }, salary_de: { low: 95, mid: 115, high: 140 }, key_skills: ['Project Management', 'Team Coaching', 'Proposal Writing'] },
        { level: 'manager', level_zh: '董事/总监', level_de: 'Direktor / Principal', years_experience: '7-11', salary_cn: { low: 70, mid: 100, high: 140 }, salary_de: { low: 130, mid: 160, high: 200 }, key_skills: ['Client Relationship', 'Practice Building', 'Thought Leadership'] },
        { level: 'director', level_zh: '合伙人', level_de: 'Partner', years_experience: '11+', salary_cn: { low: 120, mid: 180, high: 300 }, salary_de: { low: 200, mid: 300, high: 500 }, key_skills: ['Business Development', 'Firm Governance', 'C-suite Advisory'] },
      ],
    },
    {
      id: 'consult-operations',
      title: 'Operations Consultant',
      title_zh: '运营咨询顾问',
      title_de: 'Operationsberater',
      function_area: 'Operations',
      function_area_zh: '运营',
      core_skills: ['Lean/Six Sigma', 'Process Mapping', 'Cost Optimization', 'Change Management', 'Supply Chain Analysis'],
      growth_outlook: 'medium',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '分析师', level_de: 'Analyst', years_experience: '0-2', salary_cn: { low: 12, mid: 18, high: 28 }, salary_de: { low: 50, mid: 60, high: 72 }, key_skills: ['Process Documentation', 'Data Collection'] },
        { level: 'senior', level_zh: '咨询顾问', level_de: 'Berater', years_experience: '2-4', salary_cn: { low: 22, mid: 32, high: 45 }, salary_de: { low: 65, mid: 80, high: 95 }, key_skills: ['Value Stream Mapping', 'Workshop Delivery'] },
        { level: 'lead', level_zh: '高级顾问/项目经理', level_de: 'Senior-Berater / Projektleiter', years_experience: '4-7', salary_cn: { low: 38, mid: 55, high: 75 }, salary_de: { low: 85, mid: 105, high: 128 }, key_skills: ['Implementation Management', 'Stakeholder Alignment'] },
        { level: 'manager', level_zh: '董事/总监', level_de: 'Direktor / Principal', years_experience: '7-11', salary_cn: { low: 60, mid: 85, high: 120 }, salary_de: { low: 120, mid: 148, high: 185 }, key_skills: ['Practice Development', 'Multi-project Portfolio'] },
        { level: 'director', level_zh: '合伙人', level_de: 'Partner', years_experience: '11+', salary_cn: { low: 100, mid: 150, high: 250 }, salary_de: { low: 180, mid: 260, high: 420 }, key_skills: ['Operational Transformation Advisory', 'Equity Stake'] },
      ],
    },
    {
      id: 'consult-it',
      title: 'IT Consultant',
      title_zh: 'IT咨询顾问',
      title_de: 'IT-Berater',
      function_area: 'Technology',
      function_area_zh: '技术',
      core_skills: ['IT Architecture', 'Digital Transformation', 'ERP (SAP/Oracle)', 'Cloud Strategy', 'Agile/DevOps'],
      growth_outlook: 'high',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '分析师', level_de: 'Analyst', years_experience: '0-2', salary_cn: { low: 14, mid: 20, high: 30 }, salary_de: { low: 48, mid: 58, high: 70 }, key_skills: ['Requirements Gathering', 'System Configuration'] },
        { level: 'senior', level_zh: '咨询顾问', level_de: 'Berater', years_experience: '2-4', salary_cn: { low: 25, mid: 35, high: 50 }, salary_de: { low: 68, mid: 82, high: 98 }, key_skills: ['Solution Design', 'Integration Architecture'] },
        { level: 'lead', level_zh: '高级顾问/项目经理', level_de: 'Senior-Berater / Projektleiter', years_experience: '4-7', salary_cn: { low: 42, mid: 60, high: 82 }, salary_de: { low: 90, mid: 110, high: 135 }, key_skills: ['Program Management', 'Enterprise Architecture'] },
        { level: 'manager', level_zh: '董事/总监', level_de: 'Direktor / Principal', years_experience: '7-11', salary_cn: { low: 65, mid: 92, high: 128 }, salary_de: { low: 125, mid: 155, high: 195 }, key_skills: ['Digital Strategy', 'Large-scale Delivery'] },
        { level: 'director', level_zh: '合伙人', level_de: 'Partner', years_experience: '11+', salary_cn: { low: 110, mid: 165, high: 270 }, salary_de: { low: 190, mid: 280, high: 450 }, key_skills: ['Technology Vision', 'Alliance Partnerships (AWS/Azure/GCP)'] },
      ],
    },
    {
      id: 'consult-supply-chain',
      title: 'Supply Chain Consultant',
      title_zh: '供应链咨询顾问',
      title_de: 'Supply-Chain-Berater',
      function_area: 'Operations',
      function_area_zh: '运营',
      core_skills: ['S&OP Planning', 'Network Optimization', 'Inventory Management', 'Procurement Strategy', 'Analytics (Python/R)'],
      growth_outlook: 'high',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '分析师', level_de: 'Analyst', years_experience: '0-2', salary_cn: { low: 12, mid: 17, high: 25 }, salary_de: { low: 48, mid: 57, high: 68 }, key_skills: ['Data Analysis', 'Supplier Assessment'] },
        { level: 'senior', level_zh: '咨询顾问', level_de: 'Berater', years_experience: '2-4', salary_cn: { low: 22, mid: 32, high: 45 }, salary_de: { low: 65, mid: 78, high: 95 }, key_skills: ['Supply Chain Diagnostics', 'Category Management'] },
        { level: 'lead', level_zh: '高级顾问/项目经理', level_de: 'Senior-Berater / Projektleiter', years_experience: '4-7', salary_cn: { low: 38, mid: 52, high: 72 }, salary_de: { low: 85, mid: 105, high: 128 }, key_skills: ['End-to-end Supply Chain Transformation', 'Client Leadership'] },
        { level: 'manager', level_zh: '董事/总监', level_de: 'Direktor / Principal', years_experience: '7-11', salary_cn: { low: 58, mid: 82, high: 115 }, salary_de: { low: 118, mid: 145, high: 182 }, key_skills: ['Supply Chain Strategy', 'Multi-regional Programs'] },
        { level: 'director', level_zh: '合伙人', level_de: 'Partner', years_experience: '11+', salary_cn: { low: 95, mid: 145, high: 240 }, salary_de: { low: 175, mid: 255, high: 410 }, key_skills: ['Global Supply Chain Advisory', 'Thought Leadership (Publications)'] },
      ],
    },
    {
      id: 'consult-hr',
      title: 'HR Consultant',
      title_zh: '人力资源咨询顾问',
      title_de: 'HR-Berater',
      function_area: 'Human Resources',
      function_area_zh: '人力资源',
      core_skills: ['Organizational Design', 'Compensation & Benefits', 'Talent Strategy', 'Change Management', 'HR Analytics'],
      growth_outlook: 'medium',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '分析师', level_de: 'Analyst', years_experience: '0-2', salary_cn: { low: 10, mid: 15, high: 22 }, salary_de: { low: 45, mid: 54, high: 65 }, key_skills: ['Survey Design', 'Benchmarking Analysis'] },
        { level: 'senior', level_zh: '咨询顾问', level_de: 'Berater', years_experience: '2-4', salary_cn: { low: 18, mid: 26, high: 38 }, salary_de: { low: 60, mid: 72, high: 88 }, key_skills: ['Job Architecture', 'Executive Compensation'] },
        { level: 'lead', level_zh: '高级顾问/项目经理', level_de: 'Senior-Berater / Projektleiter', years_experience: '4-7', salary_cn: { low: 32, mid: 45, high: 62 }, salary_de: { low: 80, mid: 98, high: 118 }, key_skills: ['Org Transformation', 'Leadership Assessment'] },
        { level: 'manager', level_zh: '董事/总监', level_de: 'Direktor / Principal', years_experience: '7-11', salary_cn: { low: 50, mid: 72, high: 100 }, salary_de: { low: 110, mid: 135, high: 168 }, key_skills: ['HR Strategy', 'Board Advisory'] },
        { level: 'director', level_zh: '合伙人', level_de: 'Partner', years_experience: '11+', salary_cn: { low: 85, mid: 130, high: 210 }, salary_de: { low: 165, mid: 240, high: 380 }, key_skills: ['People Strategy Advisory', 'Firm Leadership'] },
      ],
    },
    {
      id: 'consult-financial-advisory',
      title: 'Financial Advisory Consultant',
      title_zh: '财务咨询顾问',
      title_de: 'Finanzberater',
      function_area: 'Finance',
      function_area_zh: '财务',
      core_skills: ['Financial Modeling', 'Valuation (DCF/Multiples)', 'Due Diligence', 'M&A Analysis', 'Restructuring'],
      growth_outlook: 'high',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '分析师', level_de: 'Analyst', years_experience: '0-2', salary_cn: { low: 15, mid: 22, high: 32 }, salary_de: { low: 52, mid: 62, high: 75 }, key_skills: ['Excel/VBA Modeling', 'Industry Research'] },
        { level: 'senior', level_zh: '咨询顾问', level_de: 'Berater', years_experience: '2-4', salary_cn: { low: 28, mid: 40, high: 55 }, salary_de: { low: 72, mid: 88, high: 108 }, key_skills: ['Deal Execution', 'Client Deliverables'] },
        { level: 'lead', level_zh: '高级顾问/项目经理', level_de: 'Senior-Berater / Projektleiter', years_experience: '4-7', salary_cn: { low: 48, mid: 68, high: 92 }, salary_de: { low: 98, mid: 120, high: 148 }, key_skills: ['Transaction Management', 'Negotiation Support'] },
        { level: 'manager', level_zh: '董事/总监', level_de: 'Direktor / Principal', years_experience: '7-11', salary_cn: { low: 75, mid: 108, high: 150 }, salary_de: { low: 140, mid: 172, high: 215 }, key_skills: ['Deal Origination', 'Client Relationship Management'] },
        { level: 'director', level_zh: '合伙人', level_de: 'Partner', years_experience: '11+', salary_cn: { low: 130, mid: 200, high: 350 }, salary_de: { low: 220, mid: 330, high: 550 }, key_skills: ['Market-making Deals', 'Firm Equity Partner'] },
      ],
    },
  ],
};
