import type { IndustryCareerMap } from './types';

export const electronicsCareerMap: IndustryCareerMap = {
  id: 'electronics',
  name: 'Electronics / Semiconductor',
  name_zh: '电子/半导体',
  name_de: 'Elektronik / Halbleiter',
  icon: '🔬',
  description: 'The semiconductor industry is experiencing unprecedented demand driven by AI chips, EVs, and IoT. IC design engineers in China command some of the highest engineering salaries, and fab expansion is a national priority.',
  description_zh: '半导体行业在AI芯片、电动汽车和物联网驱动下需求空前。中国IC设计工程师薪资位居工程类最高水平，晶圆厂扩产是国家战略重点。',
  description_de: 'Die Halbleiterindustrie erlebt eine beispiellose Nachfrage, angetrieben durch KI-Chips, E-Fahrzeuge und IoT. Der Ausbau der Chipfertigung ist eine nationale Priorität.',
  avg_salary_cn: 25,
  avg_salary_de: 72,
  top_benefits: ['Stock options / RSU', 'Signing bonus', 'Relocation package', 'Education subsidy', 'Cleanroom allowance'],
  top_benefits_zh: ['股票期权/RSU', '签约奖金', '搬迁补贴', '学历深造补贴', '洁净室津贴'],
  ranking_2026: 3,
  sub_categories: [
    { name: 'IC/Semiconductor', name_zh: '集成电路/半导体', name_de: 'IC/Halbleiter', icon: '🧮' },
    { name: 'PCB/SMT', name_zh: 'PCB/贴片', name_de: 'Leiterplatte/SMT', icon: '🔌' },
    { name: 'Power Electronics', name_zh: '电力电子', name_de: 'Leistungselektronik', icon: '⚡' },
    { name: 'RF/Communication', name_zh: '射频/通信', name_de: 'HF/Kommunikation', icon: '📶' },
  ],
  roles: [
    {
      id: 'elec-ic-design',
      title: 'IC Design Engineer',
      title_zh: 'IC设计工程师',
      title_de: 'IC-Design-Ingenieur',
      soc_code: '17-2072.00',
      kldb_code: '26314',
      function_area: 'R&D',
      function_area_zh: '研发',
      core_skills: ['Verilog/VHDL', 'Synopsys Design Compiler', 'Cadence Virtuoso', 'SPICE Simulation', 'Digital/Analog Design'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 18, mid: 25, high: 35 }, salary_de: { low: 52, mid: 60, high: 70 }, key_skills: ['RTL Coding', 'Gate-level Simulation'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 30, mid: 45, high: 65 }, salary_de: { low: 68, mid: 82, high: 98 }, key_skills: ['Timing Closure', 'Low-Power Design', 'DFT'] },
        { level: 'lead', level_zh: '技术主管', level_de: 'Teamleiter', years_experience: '5-8', salary_cn: { low: 50, mid: 70, high: 95 }, salary_de: { low: 88, mid: 105, high: 125 }, key_skills: ['Architecture Design', 'IP Integration', 'Tape-out Management'] },
        { level: 'manager', level_zh: '设计经理', level_de: 'Design-Manager', years_experience: '8-12', salary_cn: { low: 70, mid: 95, high: 130 }, salary_de: { low: 105, mid: 125, high: 155 }, key_skills: ['Chip Architecture', 'Multi-project Coordination', 'Foundry Interface'] },
        { level: 'director', level_zh: '设计总监', level_de: 'Design-Direktor', years_experience: '12+', salary_cn: { low: 100, mid: 140, high: 200 }, salary_de: { low: 135, mid: 165, high: 210 }, key_skills: ['Product Roadmap', 'Patent Strategy', 'Semiconductor IP Portfolio'] },
      ],
    },
    {
      id: 'elec-pcb-design',
      title: 'PCB Design Engineer',
      title_zh: 'PCB设计工程师',
      title_de: 'PCB-Layout-Ingenieur',
      soc_code: '17-2072.00',
      kldb_code: '26314',
      function_area: 'Engineering',
      function_area_zh: '工程',
      core_skills: ['Altium Designer', 'Cadence Allegro', 'Signal Integrity', 'EMC Design', 'High-Speed Layout'],
      growth_outlook: 'medium',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 8, mid: 11, high: 15 }, salary_de: { low: 40, mid: 47, high: 55 }, key_skills: ['Schematic Capture', '2-layer/4-layer Layout'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 14, mid: 20, high: 28 }, salary_de: { low: 54, mid: 64, high: 76 }, key_skills: ['Multi-layer HDI', 'Impedance Control', 'SI/PI Analysis'] },
        { level: 'lead', level_zh: '设计主管', level_de: 'Teamleiter Layout', years_experience: '5-8', salary_cn: { low: 22, mid: 30, high: 40 }, salary_de: { low: 70, mid: 82, high: 95 }, key_skills: ['Design Review Lead', 'DFM Optimization'] },
        { level: 'manager', level_zh: '硬件经理', level_de: 'Hardware-Manager', years_experience: '8-12', salary_cn: { low: 32, mid: 42, high: 55 }, salary_de: { low: 85, mid: 100, high: 120 }, key_skills: ['Hardware Team Management', 'NPI Process'] },
        { level: 'director', level_zh: '硬件总监', level_de: 'Hardware-Direktor', years_experience: '12+', salary_cn: { low: 48, mid: 65, high: 90 }, salary_de: { low: 110, mid: 135, high: 170 }, key_skills: ['Hardware Platform Strategy', 'Vendor Technology Roadmap'] },
      ],
    },
    {
      id: 'elec-test-engineer',
      title: 'Test Engineer',
      title_zh: '测试工程师',
      title_de: 'Testingenieur',
      soc_code: '17-2072.00',
      kldb_code: '26314',
      function_area: 'Quality / Test',
      function_area_zh: '质量/测试',
      core_skills: ['ATE Programming', 'Teradyne/Advantest', 'Test Plan Development', 'Yield Analysis', 'Failure Analysis'],
      growth_outlook: 'medium',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '初级测试工程师', level_de: 'Junior Testingenieur', years_experience: '0-2', salary_cn: { low: 10, mid: 14, high: 18 }, salary_de: { low: 42, mid: 50, high: 58 }, key_skills: ['Test Procedure Development', 'Data Collection'] },
        { level: 'senior', level_zh: '高级测试工程师', level_de: 'Senior Testingenieur', years_experience: '3-5', salary_cn: { low: 16, mid: 24, high: 33 }, salary_de: { low: 56, mid: 68, high: 80 }, key_skills: ['Test Program Development', 'Yield Improvement'] },
        { level: 'lead', level_zh: '测试主管', level_de: 'Teamleiter Test', years_experience: '5-8', salary_cn: { low: 26, mid: 35, high: 45 }, salary_de: { low: 72, mid: 85, high: 100 }, key_skills: ['Test Strategy', 'ATE Correlation'] },
        { level: 'manager', level_zh: '测试经理', level_de: 'Testmanager', years_experience: '8-12', salary_cn: { low: 38, mid: 50, high: 65 }, salary_de: { low: 90, mid: 108, high: 128 }, key_skills: ['Test Cost Optimization', 'Multi-site Coordination'] },
        { level: 'director', level_zh: '测试总监', level_de: 'Testdirektor', years_experience: '12+', salary_cn: { low: 55, mid: 75, high: 100 }, salary_de: { low: 115, mid: 140, high: 175 }, key_skills: ['Quality Strategy', 'Test Technology Roadmap'] },
      ],
    },
    {
      id: 'elec-rf-engineer',
      title: 'RF Engineer',
      title_zh: '射频工程师',
      title_de: 'HF-Ingenieur',
      soc_code: '17-2072.00',
      kldb_code: '26314',
      function_area: 'R&D',
      function_area_zh: '研发',
      core_skills: ['ADS/HFSS', 'Network Analyzer', 'Matching Network', 'Antenna Design', 'RF Circuit Design'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 12, mid: 17, high: 24 }, salary_de: { low: 48, mid: 56, high: 65 }, key_skills: ['S-Parameter Measurement', 'PCB Tuning'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 22, mid: 32, high: 45 }, salary_de: { low: 64, mid: 78, high: 92 }, key_skills: ['mmWave Design', '5G NR', 'PA Design'] },
        { level: 'lead', level_zh: '射频主管', level_de: 'Teamleiter HF', years_experience: '5-8', salary_cn: { low: 35, mid: 50, high: 68 }, salary_de: { low: 85, mid: 100, high: 118 }, key_skills: ['System Architecture', 'RFIC Co-design'] },
        { level: 'manager', level_zh: '射频经理', level_de: 'HF-Manager', years_experience: '8-12', salary_cn: { low: 50, mid: 70, high: 95 }, salary_de: { low: 100, mid: 120, high: 145 }, key_skills: ['RF Product Roadmap', 'Certification (FCC/CE)'] },
        { level: 'director', level_zh: '射频总监', level_de: 'HF-Direktor', years_experience: '12+', salary_cn: { low: 75, mid: 105, high: 140 }, salary_de: { low: 130, mid: 158, high: 195 }, key_skills: ['Wireless Technology Strategy', 'Standards Committee (3GPP)'] },
      ],
    },
    {
      id: 'elec-fpga-engineer',
      title: 'FPGA Engineer',
      title_zh: 'FPGA工程师',
      title_de: 'FPGA-Ingenieur',
      soc_code: '17-2061.00',
      kldb_code: '26314',
      function_area: 'R&D',
      function_area_zh: '研发',
      core_skills: ['Verilog/VHDL', 'Xilinx Vivado', 'Intel Quartus', 'Timing Analysis', 'High-Speed Interface'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 13, mid: 18, high: 25 }, salary_de: { low: 48, mid: 56, high: 65 }, key_skills: ['RTL Design', 'Functional Simulation'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 22, mid: 32, high: 45 }, salary_de: { low: 62, mid: 75, high: 90 }, key_skills: ['High-Speed SerDes', 'DSP Implementation', 'Embedded Processor Integration'] },
        { level: 'lead', level_zh: '技术主管', level_de: 'Teamleiter', years_experience: '5-8', salary_cn: { low: 35, mid: 48, high: 65 }, salary_de: { low: 82, mid: 98, high: 115 }, key_skills: ['System Architecture', 'Prototype-to-ASIC Migration'] },
        { level: 'manager', level_zh: 'FPGA经理', level_de: 'FPGA-Manager', years_experience: '8-12', salary_cn: { low: 50, mid: 68, high: 90 }, salary_de: { low: 98, mid: 118, high: 142 }, key_skills: ['FPGA Platform Strategy', 'Cross-team Coordination'] },
        { level: 'director', level_zh: '硬件研发总监', level_de: 'Hardware-Entwicklungsdirektor', years_experience: '12+', salary_cn: { low: 72, mid: 100, high: 135 }, salary_de: { low: 125, mid: 155, high: 192 }, key_skills: ['Hardware/Software Co-design Strategy', 'IP Licensing'] },
      ],
    },
    {
      id: 'elec-process-fab',
      title: 'Process Engineer (Fab)',
      title_zh: '制程工程师（晶圆厂）',
      title_de: 'Prozessingenieur (Fab)',
      soc_code: '17-2112.00',
      kldb_code: '27214',
      function_area: 'Manufacturing',
      function_area_zh: '制造',
      core_skills: ['Photolithography', 'Etching', 'Deposition (CVD/PVD)', 'CMP', 'SPC/APC'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 12, mid: 16, high: 22 }, salary_de: { low: 48, mid: 55, high: 64 }, key_skills: ['Cleanroom Protocol', 'Wafer Inspection'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 20, mid: 28, high: 40 }, salary_de: { low: 62, mid: 74, high: 88 }, key_skills: ['Process Integration', 'Defect Reduction', 'DOE'] },
        { level: 'lead', level_zh: '制程主管', level_de: 'Teamleiter Prozess', years_experience: '5-8', salary_cn: { low: 32, mid: 45, high: 60 }, salary_de: { low: 80, mid: 95, high: 112 }, key_skills: ['Technology Node Migration', 'Yield Ramp'] },
        { level: 'manager', level_zh: '制程经理', level_de: 'Prozessmanager', years_experience: '8-12', salary_cn: { low: 45, mid: 62, high: 82 }, salary_de: { low: 95, mid: 115, high: 140 }, key_skills: ['Fab Module Management', 'Equipment Qualification'] },
        { level: 'director', level_zh: '制程总监', level_de: 'Prozessdirektor', years_experience: '12+', salary_cn: { low: 68, mid: 95, high: 130 }, salary_de: { low: 125, mid: 152, high: 190 }, key_skills: ['Technology Roadmap (Moore\'s Law)', 'New Fab Ramp-up'] },
      ],
    },
    {
      id: 'elec-equipment-engineer',
      title: 'Equipment Engineer',
      title_zh: '设备工程师',
      title_de: 'Anlagentechniker',
      soc_code: '17-2112.00',
      kldb_code: '25114',
      function_area: 'Manufacturing',
      function_area_zh: '制造',
      core_skills: ['AMAT/Lam/TEL Equipment', 'PM Scheduling', 'Troubleshooting', 'PLC/SCADA', 'Vacuum Systems'],
      growth_outlook: 'medium',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 9, mid: 12, high: 16 }, salary_de: { low: 40, mid: 47, high: 55 }, key_skills: ['Preventive Maintenance', 'Equipment Log'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 14, mid: 20, high: 28 }, salary_de: { low: 52, mid: 63, high: 75 }, key_skills: ['Root Cause Analysis', 'Recipe Optimization'] },
        { level: 'lead', level_zh: '设备主管', level_de: 'Teamleiter Anlagen', years_experience: '5-8', salary_cn: { low: 22, mid: 30, high: 40 }, salary_de: { low: 68, mid: 80, high: 95 }, key_skills: ['Equipment Upgrade Projects', 'OEE Improvement'] },
        { level: 'manager', level_zh: '设备经理', level_de: 'Anlagenmanager', years_experience: '8-12', salary_cn: { low: 32, mid: 42, high: 56 }, salary_de: { low: 85, mid: 100, high: 120 }, key_skills: ['CapEx Planning', 'Vendor Management'] },
        { level: 'director', level_zh: '设备总监', level_de: 'Anlagendirektor', years_experience: '12+', salary_cn: { low: 48, mid: 65, high: 88 }, salary_de: { low: 108, mid: 132, high: 165 }, key_skills: ['Fab Equipment Strategy', 'New Line Installation'] },
      ],
    },
    {
      id: 'elec-product-engineer',
      title: 'Product Engineer',
      title_zh: '产品工程师',
      title_de: 'Produktingenieur',
      soc_code: '17-2072.00',
      kldb_code: '26314',
      function_area: 'Engineering',
      function_area_zh: '工程',
      core_skills: ['Characterization', 'Reliability Testing', 'Datasheet Creation', 'Yield Analysis', 'Customer Support'],
      growth_outlook: 'medium',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 10, mid: 14, high: 19 }, salary_de: { low: 43, mid: 50, high: 58 }, key_skills: ['Bench Testing', 'Data Analysis'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 17, mid: 25, high: 35 }, salary_de: { low: 56, mid: 68, high: 82 }, key_skills: ['Product Qualification', 'Failure Mode Analysis'] },
        { level: 'lead', level_zh: '产品主管', level_de: 'Teamleiter Produkt', years_experience: '5-8', salary_cn: { low: 28, mid: 38, high: 50 }, salary_de: { low: 74, mid: 88, high: 105 }, key_skills: ['Product Lifecycle Management', 'Cross-functional Coordination'] },
        { level: 'manager', level_zh: '产品经理', level_de: 'Produktmanager', years_experience: '8-12', salary_cn: { low: 40, mid: 55, high: 72 }, salary_de: { low: 92, mid: 110, high: 132 }, key_skills: ['Product Portfolio Strategy', 'Key Account Management'] },
        { level: 'director', level_zh: '产品总监', level_de: 'Produktdirektor', years_experience: '12+', salary_cn: { low: 60, mid: 82, high: 110 }, salary_de: { low: 118, mid: 145, high: 180 }, key_skills: ['Market Strategy', 'Product Line P&L'] },
      ],
    },
    {
      id: 'elec-application-engineer',
      title: 'Application Engineer',
      title_zh: '应用工程师',
      title_de: 'Applikationsingenieur',
      soc_code: '17-2072.00',
      kldb_code: '26314',
      function_area: 'Sales / Technical',
      function_area_zh: '销售/技术',
      core_skills: ['Technical Presentation', 'Reference Design', 'Customer Debug', 'Schematic Review', 'System Integration'],
      growth_outlook: 'medium',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 10, mid: 14, high: 18 }, salary_de: { low: 43, mid: 50, high: 58 }, key_skills: ['Demo Setup', 'Customer Training'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 16, mid: 24, high: 33 }, salary_de: { low: 56, mid: 68, high: 80 }, key_skills: ['Solution Architecture', 'Design-in Support'] },
        { level: 'lead', level_zh: '应用主管', level_de: 'Teamleiter Applikation', years_experience: '5-8', salary_cn: { low: 26, mid: 35, high: 48 }, salary_de: { low: 72, mid: 86, high: 102 }, key_skills: ['Key Account Technical Lead', 'Reference Platform'] },
        { level: 'manager', level_zh: '应用经理', level_de: 'Applikationsmanager', years_experience: '8-12', salary_cn: { low: 38, mid: 50, high: 68 }, salary_de: { low: 90, mid: 108, high: 130 }, key_skills: ['FAE Team Management', 'Revenue Target'] },
        { level: 'director', level_zh: '应用总监', level_de: 'Applikationsdirektor', years_experience: '12+', salary_cn: { low: 55, mid: 75, high: 100 }, salary_de: { low: 115, mid: 140, high: 175 }, key_skills: ['Global Application Strategy', 'Strategic Partnerships'] },
      ],
    },
  ],
};
