import type { IndustryCareerMap } from './types';

export const energyCareerMap: IndustryCareerMap = {
  id: 'energy',
  name: 'New Energy',
  name_zh: '新能源',
  name_de: 'Neue Energien',
  icon: '⚡',
  description: 'New energy is the fastest-growing industrial sector globally. China dominates solar and battery manufacturing, while Europe leads in wind and hydrogen. Battery engineers are among the most sought-after professionals with rapidly rising salaries.',
  description_zh: '新能源是全球增长最快的工业领域。中国在光伏和电池制造方面占据主导地位，欧洲在风能和氢能方面领先。电池工程师是最抢手的专业人才之一，薪资增长迅猛。',
  description_de: 'Neue Energien sind der am schnellsten wachsende Industriesektor weltweit. China dominiert Solar- und Batteriefertigung, Europa führt bei Wind und Wasserstoff.',
  avg_salary_cn: 23,
  avg_salary_de: 70,
  top_benefits: ['Green energy subsidy', 'Stock options (startups)', '13th month salary', 'Remote work flexibility', 'Training & certification budget'],
  top_benefits_zh: ['绿色能源补贴', '股票期权（初创企业）', '13薪', '远程办公灵活性', '培训认证预算'],
  ranking_2026: 1,
  sub_categories: [
    { name: 'Solar/PV', name_zh: '光伏', name_de: 'Solarenergie', icon: '☀️' },
    { name: 'Wind Power', name_zh: '风电', name_de: 'Windenergie', icon: '🌬️' },
    { name: 'Battery/Storage', name_zh: '储能', name_de: 'Energiespeicher', icon: '🔋' },
    { name: 'Hydrogen', name_zh: '氢能', name_de: 'Wasserstoff', icon: '💧' },
  ],
  roles: [
    {
      id: 'energy-solar',
      title: 'Solar Engineer',
      title_zh: '光伏工程师',
      title_de: 'Solaringenieur',
      function_area: 'Engineering',
      function_area_zh: '工程',
      core_skills: ['PV System Design', 'PVsyst', 'Inverter Technology', 'Grid Connection', 'IEC 61215/61730'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 8, mid: 11, high: 15 }, salary_de: { low: 42, mid: 50, high: 58 }, key_skills: ['Site Assessment', 'AutoCAD Layout'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 14, mid: 20, high: 28 }, salary_de: { low: 55, mid: 66, high: 78 }, key_skills: ['Yield Optimization', 'SCADA Integration'] },
        { level: 'lead', level_zh: '光伏主管', level_de: 'Teamleiter Solar', years_experience: '5-8', salary_cn: { low: 22, mid: 30, high: 42 }, salary_de: { low: 72, mid: 85, high: 100 }, key_skills: ['Project Development', 'EPC Management'] },
        { level: 'manager', level_zh: '光伏经理', level_de: 'Solarmanager', years_experience: '8-12', salary_cn: { low: 32, mid: 45, high: 60 }, salary_de: { low: 88, mid: 105, high: 128 }, key_skills: ['Portfolio Management', 'PPA Negotiation'] },
        { level: 'director', level_zh: '光伏总监', level_de: 'Solardirektor', years_experience: '12+', salary_cn: { low: 50, mid: 70, high: 95 }, salary_de: { low: 112, mid: 138, high: 172 }, key_skills: ['Solar Strategy', 'GW-scale Development'] },
      ],
    },
    {
      id: 'energy-wind',
      title: 'Wind Engineer',
      title_zh: '风电工程师',
      title_de: 'Windkraftingenieur',
      function_area: 'Engineering',
      function_area_zh: '工程',
      core_skills: ['Wind Resource Assessment', 'Turbine Technology', 'SCADA', 'Structural Analysis (Blades/Tower)', 'IEC 61400'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 8, mid: 12, high: 16 }, salary_de: { low: 44, mid: 52, high: 60 }, key_skills: ['Wind Data Analysis', 'Site Survey'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 14, mid: 21, high: 30 }, salary_de: { low: 58, mid: 70, high: 82 }, key_skills: ['Wake Analysis', 'Turbine Selection', 'Grid Code Compliance'] },
        { level: 'lead', level_zh: '风电主管', level_de: 'Teamleiter Windkraft', years_experience: '5-8', salary_cn: { low: 24, mid: 33, high: 45 }, salary_de: { low: 75, mid: 88, high: 105 }, key_skills: ['Offshore Foundation Design', 'Farm Layout Optimization'] },
        { level: 'manager', level_zh: '风电经理', level_de: 'Windkraftmanager', years_experience: '8-12', salary_cn: { low: 35, mid: 48, high: 65 }, salary_de: { low: 92, mid: 110, high: 135 }, key_skills: ['Wind Farm Development', 'Permitting & Environmental'] },
        { level: 'director', level_zh: '风电总监', level_de: 'Windkraftdirektor', years_experience: '12+', salary_cn: { low: 52, mid: 72, high: 98 }, salary_de: { low: 118, mid: 145, high: 180 }, key_skills: ['Offshore Strategy', 'Floating Wind Technology'] },
      ],
    },
    {
      id: 'energy-battery',
      title: 'Battery Engineer',
      title_zh: '电池工程师',
      title_de: 'Batterieingenieur',
      function_area: 'R&D',
      function_area_zh: '研发',
      core_skills: ['Electrochemistry', 'Cell Design', 'BMS', 'Thermal Management', 'Battery Testing (Arbin/Maccor)'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 12, mid: 17, high: 24 }, salary_de: { low: 48, mid: 56, high: 66 }, key_skills: ['Cell Testing', 'Data Logging'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 22, mid: 32, high: 48 }, salary_de: { low: 64, mid: 78, high: 95 }, key_skills: ['Cell Chemistry Optimization', 'Pack Design', 'Safety Testing (UN 38.3)'] },
        { level: 'lead', level_zh: '电池主管', level_de: 'Teamleiter Batterie', years_experience: '5-8', salary_cn: { low: 38, mid: 52, high: 72 }, salary_de: { low: 85, mid: 102, high: 122 }, key_skills: ['Battery System Architecture', 'Supplier Qualification'] },
        { level: 'manager', level_zh: '电池经理', level_de: 'Batteriemanager', years_experience: '8-12', salary_cn: { low: 55, mid: 75, high: 100 }, salary_de: { low: 105, mid: 125, high: 152 }, key_skills: ['Battery Platform Strategy', 'Mass Production Ramp-up'] },
        { level: 'director', level_zh: '电池总监', level_de: 'Batteriedirektor', years_experience: '12+', salary_cn: { low: 80, mid: 110, high: 150 }, salary_de: { low: 132, mid: 162, high: 200 }, key_skills: ['Next-gen Battery Technology (Solid-state)', 'Gigafactory Planning'] },
      ],
    },
    {
      id: 'energy-grid',
      title: 'Grid Engineer',
      title_zh: '电网工程师',
      title_de: 'Netzingenieur',
      function_area: 'Engineering',
      function_area_zh: '工程',
      core_skills: ['Power Systems Analysis', 'ETAP/PSS/E', 'Grid Code', 'Protection Relay', 'HVDC/FACTS'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 8, mid: 11, high: 15 }, salary_de: { low: 44, mid: 52, high: 60 }, key_skills: ['Load Flow Analysis', 'Single Line Diagram'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 14, mid: 20, high: 28 }, salary_de: { low: 56, mid: 68, high: 80 }, key_skills: ['Short Circuit Analysis', 'Relay Coordination', 'Grid Connection Study'] },
        { level: 'lead', level_zh: '电网主管', level_de: 'Teamleiter Netz', years_experience: '5-8', salary_cn: { low: 22, mid: 32, high: 42 }, salary_de: { low: 72, mid: 86, high: 102 }, key_skills: ['Substation Design', 'Grid Stability Analysis'] },
        { level: 'manager', level_zh: '电网经理', level_de: 'Netzmanager', years_experience: '8-12', salary_cn: { low: 34, mid: 46, high: 62 }, salary_de: { low: 90, mid: 108, high: 130 }, key_skills: ['Grid Modernization Program', 'Regulatory Interface'] },
        { level: 'director', level_zh: '电网总监', level_de: 'Netzdirektor', years_experience: '12+', salary_cn: { low: 50, mid: 70, high: 95 }, salary_de: { low: 115, mid: 142, high: 178 }, key_skills: ['Smart Grid Strategy', 'Ultra-high Voltage Planning'] },
      ],
    },
    {
      id: 'energy-storage',
      title: 'Energy Storage Engineer',
      title_zh: '储能工程师',
      title_de: 'Energiespeicheringenieur',
      function_area: 'Engineering',
      function_area_zh: '工程',
      core_skills: ['BESS Design', 'Power Conversion Systems', 'Energy Management System', 'Safety Standards (UL 9540)', 'Project Economics'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 10, mid: 14, high: 19 }, salary_de: { low: 45, mid: 53, high: 62 }, key_skills: ['System Sizing', 'Component Selection'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 18, mid: 26, high: 36 }, salary_de: { low: 58, mid: 70, high: 85 }, key_skills: ['Grid-scale BESS Design', 'PCS Integration'] },
        { level: 'lead', level_zh: '储能主管', level_de: 'Teamleiter Speicher', years_experience: '5-8', salary_cn: { low: 28, mid: 40, high: 55 }, salary_de: { low: 78, mid: 92, high: 110 }, key_skills: ['Hybrid System Architecture', 'Commissioning Management'] },
        { level: 'manager', level_zh: '储能经理', level_de: 'Speichermanager', years_experience: '8-12', salary_cn: { low: 42, mid: 58, high: 78 }, salary_de: { low: 95, mid: 115, high: 140 }, key_skills: ['Storage Portfolio Strategy', 'Revenue Stacking'] },
        { level: 'director', level_zh: '储能总监', level_de: 'Speicherdirektor', years_experience: '12+', salary_cn: { low: 62, mid: 85, high: 115 }, salary_de: { low: 120, mid: 148, high: 185 }, key_skills: ['Long-duration Storage Strategy', 'Technology Scouting'] },
      ],
    },
    {
      id: 'energy-hydrogen',
      title: 'Hydrogen Engineer',
      title_zh: '氢能工程师',
      title_de: 'Wasserstoffingenieur',
      function_area: 'R&D',
      function_area_zh: '研发',
      core_skills: ['Electrolyzer Technology (PEM/Alkaline)', 'Fuel Cell Systems', 'Hydrogen Storage', 'Process Simulation (Aspen)', 'Safety (ATEX/IECEx)'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 10, mid: 14, high: 20 }, salary_de: { low: 46, mid: 54, high: 64 }, key_skills: ['Lab Testing', 'Process Documentation'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 18, mid: 26, high: 38 }, salary_de: { low: 60, mid: 72, high: 88 }, key_skills: ['Stack Design', 'Balance of Plant', 'Degradation Analysis'] },
        { level: 'lead', level_zh: '氢能主管', level_de: 'Teamleiter Wasserstoff', years_experience: '5-8', salary_cn: { low: 30, mid: 42, high: 58 }, salary_de: { low: 80, mid: 95, high: 115 }, key_skills: ['System Integration', 'Pilot Plant Management'] },
        { level: 'manager', level_zh: '氢能经理', level_de: 'Wasserstoffmanager', years_experience: '8-12', salary_cn: { low: 45, mid: 62, high: 85 }, salary_de: { low: 100, mid: 120, high: 148 }, key_skills: ['Hydrogen Value Chain Strategy', 'Green H2 Project Development'] },
        { level: 'director', level_zh: '氢能总监', level_de: 'Wasserstoffdirektor', years_experience: '12+', salary_cn: { low: 65, mid: 90, high: 125 }, salary_de: { low: 128, mid: 158, high: 195 }, key_skills: ['Hydrogen Economy Strategy', 'Government Relations & Funding'] },
      ],
    },
    {
      id: 'energy-ehs',
      title: 'EHS Engineer',
      title_zh: 'EHS工程师',
      title_de: 'EHS-Ingenieur',
      function_area: 'Safety / Compliance',
      function_area_zh: '安全/合规',
      core_skills: ['ISO 14001', 'ISO 45001', 'Risk Assessment', 'Environmental Impact Assessment', 'Incident Investigation'],
      growth_outlook: 'medium',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 7, mid: 10, high: 14 }, salary_de: { low: 40, mid: 47, high: 55 }, key_skills: ['Safety Inspection', 'Permit Management'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 12, mid: 18, high: 25 }, salary_de: { low: 52, mid: 63, high: 75 }, key_skills: ['Hazard Analysis', 'Environmental Monitoring', 'Training Program'] },
        { level: 'lead', level_zh: 'EHS主管', level_de: 'EHS-Teamleiter', years_experience: '5-8', salary_cn: { low: 20, mid: 28, high: 38 }, salary_de: { low: 68, mid: 80, high: 95 }, key_skills: ['EHS Management System', 'Regulatory Compliance'] },
        { level: 'manager', level_zh: 'EHS经理', level_de: 'EHS-Manager', years_experience: '8-12', salary_cn: { low: 30, mid: 42, high: 55 }, salary_de: { low: 85, mid: 100, high: 122 }, key_skills: ['EHS Strategy', 'Corporate Sustainability Reporting'] },
        { level: 'director', level_zh: 'EHS总监', level_de: 'EHS-Direktor', years_experience: '12+', salary_cn: { low: 45, mid: 62, high: 85 }, salary_de: { low: 108, mid: 132, high: 168 }, key_skills: ['Global EHS Governance', 'ESG Strategy', 'Carbon Neutrality Roadmap'] },
      ],
    },
  ],
};
