import type { IndustryCareerMap } from './types';

export const industrialAutomationCareerMap: IndustryCareerMap = {
  id: 'industrial-automation',
  name: 'Industrial Automation',
  name_zh: '工业自动化',
  name_de: 'Industrielle Automatisierung',
  icon: '🤖',
  description: 'Industrial automation is booming as manufacturers invest in smart factories, robotics, and Industry 4.0. Robotics engineers and PLC programmers are in extremely high demand, with salaries rising 15-20% year-over-year in key markets.',
  description_zh: '随着制造企业大力投资智能工厂、机器人和工业4.0，工业自动化行业正在蓬勃发展。机器人工程师和PLC程序员需求旺盛，关键市场薪资年增长15-20%。',
  description_de: 'Die industrielle Automatisierung boomt, da Hersteller in Smart Factories, Robotik und Industrie 4.0 investieren. Robotikingenieure und SPS-Programmierer sind stark nachgefragt.',
  avg_salary_cn: 20,
  avg_salary_de: 65,
  top_benefits: ['Overtime premium (field work)', 'Travel allowance', 'Training budget', 'Tool/equipment stipend'],
  top_benefits_zh: ['加班补贴（现场工作）', '差旅津贴', '培训经费', '工具/设备补贴'],
  ranking_2026: 6,
  sub_categories: [
    { name: 'PLC/DCS', name_zh: 'PLC/DCS控制', name_de: 'SPS/DCS-Steuerung', icon: '🎛️' },
    { name: 'Machine Vision', name_zh: '机器视觉', name_de: 'Bildverarbeitung', icon: '👁️' },
    { name: 'SCADA/IIoT', name_zh: '数据采集/工业物联网', name_de: 'SCADA/IIoT', icon: '📡' },
  ],
  roles: [
    {
      id: 'ia-plc-programmer',
      title: 'PLC Programmer',
      title_zh: 'PLC程序员',
      title_de: 'SPS-Programmierer',
      soc_code: '17-3023.00',
      kldb_code: '26124',
      function_area: 'Controls Engineering',
      function_area_zh: '控制工程',
      core_skills: ['Siemens TIA Portal', 'Allen-Bradley RSLogix', 'Ladder Logic', 'Structured Text', 'HMI Design'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级PLC工程师', level_de: 'Junior SPS-Programmierer', years_experience: '0-2', salary_cn: { low: 7, mid: 10, high: 13 }, salary_de: { low: 38, mid: 45, high: 52 }, key_skills: ['Basic I/O Configuration', 'Simple Sequence Programs'] },
        { level: 'senior', level_zh: '高级PLC工程师', level_de: 'Senior SPS-Programmierer', years_experience: '3-5', salary_cn: { low: 13, mid: 18, high: 25 }, salary_de: { low: 52, mid: 62, high: 74 }, key_skills: ['Motion Control', 'Profinet/EtherCAT', 'Multi-PLC Systems'] },
        { level: 'lead', level_zh: 'PLC主管', level_de: 'Teamleiter SPS', years_experience: '5-8', salary_cn: { low: 22, mid: 28, high: 38 }, salary_de: { low: 68, mid: 80, high: 94 }, key_skills: ['System Architecture', 'Standard Library Development'] },
        { level: 'manager', level_zh: '控制工程经理', level_de: 'Leiter Steuerungstechnik', years_experience: '8-12', salary_cn: { low: 30, mid: 40, high: 55 }, salary_de: { low: 82, mid: 98, high: 118 }, key_skills: ['Project Portfolio', 'Vendor Management', 'Budget Planning'] },
        { level: 'director', level_zh: '自动化总监', level_de: 'Automatisierungsdirektor', years_experience: '12+', salary_cn: { low: 48, mid: 65, high: 90 }, salary_de: { low: 108, mid: 132, high: 165 }, key_skills: ['Automation Strategy', 'Digital Transformation Roadmap'] },
      ],
    },
    {
      id: 'ia-robotics-engineer',
      title: 'Robotics Engineer',
      title_zh: '机器人工程师',
      title_de: 'Robotikingenieur',
      soc_code: '17-2199.00',
      kldb_code: '26124',
      function_area: 'Robotics',
      function_area_zh: '机器人',
      core_skills: ['FANUC/KUKA/ABB Programming', 'Robot Kinematics', 'Path Planning', 'Offline Programming', 'Safety Standards (ISO 10218)'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级机器人工程师', level_de: 'Junior Robotikingenieur', years_experience: '0-2', salary_cn: { low: 10, mid: 14, high: 18 }, salary_de: { low: 45, mid: 52, high: 60 }, key_skills: ['Teach Pendant Programming', 'Basic Cell Layout'] },
        { level: 'senior', level_zh: '高级机器人工程师', level_de: 'Senior Robotikingenieur', years_experience: '3-5', salary_cn: { low: 18, mid: 25, high: 35 }, salary_de: { low: 60, mid: 72, high: 88 }, key_skills: ['Cobot Integration', 'Vision-Guided Robotics', 'Multi-robot Coordination'] },
        { level: 'lead', level_zh: '机器人主管', level_de: 'Teamleiter Robotik', years_experience: '5-8', salary_cn: { low: 30, mid: 40, high: 52 }, salary_de: { low: 78, mid: 92, high: 110 }, key_skills: ['Cell Design', 'Simulation (RobotStudio/ROBOGUIDE)', 'Commissioning Lead'] },
        { level: 'manager', level_zh: '机器人经理', level_de: 'Robotikmanager', years_experience: '8-12', salary_cn: { low: 42, mid: 55, high: 75 }, salary_de: { low: 95, mid: 115, high: 140 }, key_skills: ['Automation CapEx', 'ROI Analysis', 'Global Deployment'] },
        { level: 'director', level_zh: '机器人总监', level_de: 'Robotikdirektor', years_experience: '12+', salary_cn: { low: 60, mid: 85, high: 120 }, salary_de: { low: 125, mid: 150, high: 190 }, key_skills: ['Robotics Strategy', 'AI/ML Integration Roadmap'] },
      ],
    },
    {
      id: 'ia-controls-engineer',
      title: 'Controls Engineer',
      title_zh: '控制工程师',
      title_de: 'Regelungstechniker',
      soc_code: '17-2071.00',
      kldb_code: '26124',
      function_area: 'Controls Engineering',
      function_area_zh: '控制工程',
      core_skills: ['PID Control', 'Electrical Schematics (EPLAN)', 'Drive Configuration (VFD/Servo)', 'Industrial Networks', 'Panel Design'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级控制工程师', level_de: 'Junior Regelungstechniker', years_experience: '0-2', salary_cn: { low: 8, mid: 11, high: 14 }, salary_de: { low: 40, mid: 47, high: 55 }, key_skills: ['Wiring Diagrams', 'Basic Troubleshooting'] },
        { level: 'senior', level_zh: '高级控制工程师', level_de: 'Senior Regelungstechniker', years_experience: '3-5', salary_cn: { low: 14, mid: 19, high: 26 }, salary_de: { low: 55, mid: 65, high: 78 }, key_skills: ['Servo Tuning', 'Fieldbus Configuration', 'Electrical Design'] },
        { level: 'lead', level_zh: '控制工程主管', level_de: 'Teamleiter Regelungstechnik', years_experience: '5-8', salary_cn: { low: 23, mid: 30, high: 40 }, salary_de: { low: 72, mid: 84, high: 98 }, key_skills: ['System Integration', 'UL/CE Compliance'] },
        { level: 'manager', level_zh: '控制工程经理', level_de: 'Leiter Regelungstechnik', years_experience: '8-12', salary_cn: { low: 32, mid: 42, high: 58 }, salary_de: { low: 88, mid: 105, high: 125 }, key_skills: ['Department Management', 'Standards Development', 'CapEx Justification'] },
        { level: 'director', level_zh: '工程总监', level_de: 'Engineering-Direktor', years_experience: '12+', salary_cn: { low: 50, mid: 68, high: 95 }, salary_de: { low: 112, mid: 138, high: 172 }, key_skills: ['Technology Roadmap', 'Multi-site Engineering'] },
      ],
    },
    {
      id: 'ia-vision-engineer',
      title: 'Vision System Engineer',
      title_zh: '视觉系统工程师',
      title_de: 'Bildverarbeitungsingenieur',
      soc_code: '17-2199.00',
      kldb_code: '26124',
      function_area: 'Machine Vision',
      function_area_zh: '机器视觉',
      core_skills: ['Cognex/Keyence', 'Image Processing', 'Camera Calibration', 'Lighting Design', 'Defect Detection Algorithms'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级视觉工程师', level_de: 'Junior Bildverarbeitungsingenieur', years_experience: '0-2', salary_cn: { low: 10, mid: 13, high: 17 }, salary_de: { low: 44, mid: 52, high: 60 }, key_skills: ['Camera Setup', 'Basic Inspection Programs'] },
        { level: 'senior', level_zh: '高级视觉工程师', level_de: 'Senior Bildverarbeitungsingenieur', years_experience: '3-5', salary_cn: { low: 17, mid: 24, high: 33 }, salary_de: { low: 58, mid: 70, high: 85 }, key_skills: ['Deep Learning Vision', '3D Vision', 'OCR/OCV'] },
        { level: 'lead', level_zh: '视觉系统主管', level_de: 'Teamleiter Bildverarbeitung', years_experience: '5-8', salary_cn: { low: 28, mid: 38, high: 48 }, salary_de: { low: 76, mid: 90, high: 108 }, key_skills: ['Multi-camera Systems', 'GigE Vision Architecture'] },
        { level: 'manager', level_zh: '视觉系统经理', level_de: 'Leiter Bildverarbeitung', years_experience: '8-12', salary_cn: { low: 38, mid: 50, high: 68 }, salary_de: { low: 92, mid: 110, high: 132 }, key_skills: ['Vision Strategy', 'AI Inspection Roadmap'] },
        { level: 'director', level_zh: '智能检测总监', level_de: 'Direktor Intelligente Inspektion', years_experience: '12+', salary_cn: { low: 55, mid: 78, high: 105 }, salary_de: { low: 118, mid: 145, high: 180 }, key_skills: ['Quality 4.0 Strategy', 'Global Standards'] },
      ],
    },
    {
      id: 'ia-scada-engineer',
      title: 'SCADA Engineer',
      title_zh: 'SCADA工程师',
      title_de: 'SCADA-Ingenieur',
      soc_code: '17-2071.00',
      kldb_code: '26124',
      function_area: 'Supervisory Control',
      function_area_zh: '监控系统',
      core_skills: ['WinCC/Ignition/FactoryTalk', 'SQL Database', 'OPC UA', 'Historian', 'Network Architecture'],
      growth_outlook: 'medium',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '初级SCADA工程师', level_de: 'Junior SCADA-Ingenieur', years_experience: '0-2', salary_cn: { low: 8, mid: 11, high: 14 }, salary_de: { low: 40, mid: 47, high: 55 }, key_skills: ['Screen Design', 'Tag Configuration'] },
        { level: 'senior', level_zh: '高级SCADA工程师', level_de: 'Senior SCADA-Ingenieur', years_experience: '3-5', salary_cn: { low: 14, mid: 19, high: 26 }, salary_de: { low: 54, mid: 64, high: 76 }, key_skills: ['Scripting (VBA/Python)', 'Alarming Strategy', 'Reporting'] },
        { level: 'lead', level_zh: 'SCADA主管', level_de: 'Teamleiter SCADA', years_experience: '5-8', salary_cn: { low: 22, mid: 30, high: 38 }, salary_de: { low: 70, mid: 82, high: 96 }, key_skills: ['System Architecture', 'Redundancy Design', 'Multi-site Deployment'] },
        { level: 'manager', level_zh: 'SCADA经理', level_de: 'SCADA-Manager', years_experience: '8-12', salary_cn: { low: 30, mid: 40, high: 52 }, salary_de: { low: 85, mid: 100, high: 120 }, key_skills: ['IT/OT Convergence', 'Cybersecurity Compliance'] },
        { level: 'director', level_zh: '信息化总监', level_de: 'Direktor Leitsysteme', years_experience: '12+', salary_cn: { low: 48, mid: 65, high: 88 }, salary_de: { low: 108, mid: 132, high: 168 }, key_skills: ['Digital Factory Strategy', 'Vendor Selection'] },
      ],
    },
    {
      id: 'ia-mes-engineer',
      title: 'MES Engineer',
      title_zh: 'MES工程师',
      title_de: 'MES-Ingenieur',
      soc_code: '15-1252.00',
      kldb_code: '43414',
      function_area: 'Manufacturing IT',
      function_area_zh: '制造信息化',
      core_skills: ['SIMATIC IT/Wonderware', 'ISA-95', 'SQL/Database', 'API Integration', 'Production Workflow'],
      growth_outlook: 'high',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '初级MES工程师', level_de: 'Junior MES-Ingenieur', years_experience: '0-2', salary_cn: { low: 9, mid: 12, high: 16 }, salary_de: { low: 42, mid: 50, high: 58 }, key_skills: ['Data Collection Config', 'Basic Workflow Setup'] },
        { level: 'senior', level_zh: '高级MES工程师', level_de: 'Senior MES-Ingenieur', years_experience: '3-5', salary_cn: { low: 16, mid: 22, high: 30 }, salary_de: { low: 56, mid: 68, high: 80 }, key_skills: ['Custom Module Development', 'ERP Integration', 'OEE Reporting'] },
        { level: 'lead', level_zh: 'MES主管', level_de: 'Teamleiter MES', years_experience: '5-8', salary_cn: { low: 26, mid: 35, high: 45 }, salary_de: { low: 74, mid: 88, high: 104 }, key_skills: ['Solution Architecture', 'Multi-plant Rollout'] },
        { level: 'manager', level_zh: 'MES经理', level_de: 'MES-Manager', years_experience: '8-12', salary_cn: { low: 35, mid: 48, high: 62 }, salary_de: { low: 90, mid: 108, high: 128 }, key_skills: ['Digital Manufacturing Strategy', 'Vendor Evaluation'] },
        { level: 'director', level_zh: '制造信息化总监', level_de: 'Direktor Manufacturing IT', years_experience: '12+', salary_cn: { low: 52, mid: 72, high: 98 }, salary_de: { low: 115, mid: 140, high: 175 }, key_skills: ['Smart Factory Roadmap', 'Industry 4.0 Strategy'] },
      ],
    },
    {
      id: 'ia-commissioning-engineer',
      title: 'Commissioning Engineer',
      title_zh: '调试工程师',
      title_de: 'Inbetriebnahmeingenieur',
      soc_code: '17-2199.00',
      kldb_code: '26124',
      function_area: 'Field Service',
      function_area_zh: '现场服务',
      core_skills: ['PLC Debugging', 'Mechanical Alignment', 'Electrical Testing', 'Process Validation', 'Customer Training'],
      growth_outlook: 'medium',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级调试工程师', level_de: 'Junior Inbetriebnahmeingenieur', years_experience: '0-2', salary_cn: { low: 8, mid: 11, high: 15 }, salary_de: { low: 40, mid: 48, high: 56 }, key_skills: ['Punch List Execution', 'Test Protocols'] },
        { level: 'senior', level_zh: '高级调试工程师', level_de: 'Senior Inbetriebnahmeingenieur', years_experience: '3-5', salary_cn: { low: 15, mid: 20, high: 28 }, salary_de: { low: 55, mid: 66, high: 78 }, key_skills: ['Complex System Startup', 'Troubleshooting', 'FAT/SAT'] },
        { level: 'lead', level_zh: '调试主管', level_de: 'Teamleiter Inbetriebnahme', years_experience: '5-8', salary_cn: { low: 24, mid: 32, high: 42 }, salary_de: { low: 72, mid: 85, high: 100 }, key_skills: ['Multi-trade Coordination', 'Commissioning Planning'] },
        { level: 'manager', level_zh: '调试经理', level_de: 'Inbetriebnahmemanager', years_experience: '8-12', salary_cn: { low: 35, mid: 45, high: 60 }, salary_de: { low: 88, mid: 105, high: 125 }, key_skills: ['Global Travel Coordination', 'Customer Relationship'] },
        { level: 'director', level_zh: '现场服务总监', level_de: 'Direktor Inbetriebnahme', years_experience: '12+', salary_cn: { low: 50, mid: 68, high: 92 }, salary_de: { low: 110, mid: 135, high: 170 }, key_skills: ['Service Business Strategy', 'Global Field Team Management'] },
      ],
    },
    {
      id: 'ia-safety-engineer',
      title: 'Safety Engineer (Machinery)',
      title_zh: '机械安全工程师',
      title_de: 'Maschinensicherheitsingenieur',
      soc_code: '17-2111.00',
      kldb_code: '53414',
      function_area: 'Safety',
      function_area_zh: '安全',
      core_skills: ['ISO 13849', 'IEC 62443', 'Risk Assessment (EN ISO 12100)', 'Safety PLC (Pilz/Sick)', 'CE Marking'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级安全工程师', level_de: 'Junior Sicherheitsingenieur', years_experience: '0-2', salary_cn: { low: 8, mid: 11, high: 14 }, salary_de: { low: 42, mid: 50, high: 58 }, key_skills: ['Safety Circuit Design', 'Risk Assessment Basics'] },
        { level: 'senior', level_zh: '高级安全工程师', level_de: 'Senior Sicherheitsingenieur', years_experience: '3-5', salary_cn: { low: 14, mid: 20, high: 28 }, salary_de: { low: 56, mid: 68, high: 80 }, key_skills: ['SIL/PL Calculation', 'Safety Validation', 'SISTEMA'] },
        { level: 'lead', level_zh: '安全主管', level_de: 'Teamleiter Maschinensicherheit', years_experience: '5-8', salary_cn: { low: 24, mid: 32, high: 42 }, salary_de: { low: 74, mid: 88, high: 104 }, key_skills: ['Safety Concept Development', 'Notified Body Interface'] },
        { level: 'manager', level_zh: '安全经理', level_de: 'Sicherheitsmanager', years_experience: '8-12', salary_cn: { low: 35, mid: 45, high: 60 }, salary_de: { low: 90, mid: 108, high: 128 }, key_skills: ['Safety Culture Program', 'Regulatory Compliance Strategy'] },
        { level: 'director', level_zh: '安全总监', level_de: 'Sicherheitsdirektor', years_experience: '12+', salary_cn: { low: 50, mid: 70, high: 95 }, salary_de: { low: 115, mid: 142, high: 178 }, key_skills: ['Global Safety Standards', 'Executive Safety Reporting'] },
      ],
    },
  ],
};
