import type { IndustryCareerMap } from './types';

export const itManufacturingCareerMap: IndustryCareerMap = {
  id: 'it-manufacturing',
  name: 'Manufacturing IT',
  name_zh: '制造业IT',
  name_de: 'Fertigungs-IT',
  icon: '💻',
  description: 'IT roles in manufacturing pay 20-30% less than pure tech companies but offer better work-life balance, lower layoff risk, and unique domain expertise that becomes increasingly valuable as Industry 4.0 accelerates. Digital twin and IoT engineers are the fastest-growing roles.',
  description_zh: '制造业IT岗位薪资比纯科技公司低20-30%，但工作生活平衡更好，裁员风险更低，且随着工业4.0加速推进，独特的行业领域知识愈发珍贵。数字孪生和物联网工程师是增长最快的岗位。',
  description_de: 'IT-Rollen in der Fertigung zahlen 20-30% weniger als reine Technologieunternehmen, bieten aber bessere Work-Life-Balance und einzigartiges Domänenwissen, das mit Industrie 4.0 immer wertvoller wird.',
  avg_salary_cn: 19,
  avg_salary_de: 62,
  top_benefits: ['Remote work (hybrid)', 'Training/certification budget', 'Stable employment', 'Regular working hours'],
  top_benefits_zh: ['远程办公（混合模式）', '培训/认证经费', '稳定就业', '规律工作时间'],
  ranking_2026: 8,
  sub_categories: [
    { name: 'MES/ERP', name_zh: '生产执行/ERP', name_de: 'MES/ERP', icon: '🏭' },
    { name: 'IoT Platform', name_zh: '物联网平台', name_de: 'IoT-Plattform', icon: '🌐' },
    { name: 'Digital Twin', name_zh: '数字孪生', name_de: 'Digitaler Zwilling', icon: '🔮' },
  ],
  roles: [
    {
      id: 'itm-mes-developer',
      title: 'MES Developer',
      title_zh: 'MES开发工程师',
      title_de: 'MES-Entwickler',
      soc_code: '15-1252.00',
      kldb_code: '43414',
      function_area: 'Manufacturing IT',
      function_area_zh: '制造信息化',
      core_skills: ['C#/.NET', 'SQL Server', 'ISA-95', 'REST API', 'SIMATIC IT/Camstar/Wonderware'],
      growth_outlook: 'high',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '初级MES开发', level_de: 'Junior MES-Entwickler', years_experience: '0-2', salary_cn: { low: 9, mid: 12, high: 16 }, salary_de: { low: 42, mid: 50, high: 58 }, key_skills: ['Basic CRUD Development', 'Database Queries'] },
        { level: 'senior', level_zh: '高级MES开发', level_de: 'Senior MES-Entwickler', years_experience: '3-5', salary_cn: { low: 16, mid: 22, high: 30 }, salary_de: { low: 56, mid: 68, high: 80 }, key_skills: ['Custom Module Development', 'ERP Integration', 'Performance Tuning'] },
        { level: 'lead', level_zh: 'MES开发主管', level_de: 'Teamleiter MES-Entwicklung', years_experience: '5-8', salary_cn: { low: 26, mid: 35, high: 45 }, salary_de: { low: 72, mid: 86, high: 102 }, key_skills: ['Solution Architecture', 'Multi-plant Rollout', 'Team Mentoring'] },
        { level: 'manager', level_zh: 'MES开发经理', level_de: 'MES-Entwicklungsmanager', years_experience: '8-12', salary_cn: { low: 35, mid: 48, high: 62 }, salary_de: { low: 88, mid: 105, high: 125 }, key_skills: ['Vendor Management', 'Roadmap Planning', 'Budget Control'] },
        { level: 'director', level_zh: 'MES总监', level_de: 'MES-Direktor', years_experience: '12+', salary_cn: { low: 52, mid: 70, high: 95 }, salary_de: { low: 110, mid: 135, high: 170 }, key_skills: ['Digital Manufacturing Strategy', 'Platform Selection'] },
      ],
    },
    {
      id: 'itm-erp-consultant',
      title: 'ERP Consultant (SAP)',
      title_zh: 'ERP顾问 (SAP)',
      title_de: 'ERP-Berater (SAP)',
      soc_code: '15-1211.00',
      kldb_code: '43344',
      function_area: 'Enterprise Systems',
      function_area_zh: '企业系统',
      core_skills: ['SAP PP/MM/QM', 'ABAP', 'S/4HANA', 'Business Process Mapping', 'Data Migration'],
      growth_outlook: 'medium',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '初级SAP顾问', level_de: 'Junior SAP-Berater', years_experience: '0-2', salary_cn: { low: 10, mid: 14, high: 18 }, salary_de: { low: 45, mid: 52, high: 60 }, key_skills: ['Module Configuration', 'Test Script Execution'] },
        { level: 'senior', level_zh: '高级SAP顾问', level_de: 'Senior SAP-Berater', years_experience: '3-5', salary_cn: { low: 18, mid: 26, high: 36 }, salary_de: { low: 60, mid: 74, high: 90 }, key_skills: ['Cross-module Integration', 'Custom Development', 'S/4HANA Migration'] },
        { level: 'lead', level_zh: 'SAP主管', level_de: 'Teamleiter SAP', years_experience: '5-8', salary_cn: { low: 30, mid: 40, high: 52 }, salary_de: { low: 78, mid: 94, high: 112 }, key_skills: ['Solution Architecture', 'Blueprint Design', 'Cutover Planning'] },
        { level: 'manager', level_zh: 'SAP经理', level_de: 'SAP-Manager', years_experience: '8-12', salary_cn: { low: 42, mid: 55, high: 75 }, salary_de: { low: 95, mid: 115, high: 140 }, key_skills: ['Program Management', 'Multi-site Rollout', 'Change Management'] },
        { level: 'director', level_zh: 'ERP总监', level_de: 'ERP-Direktor', years_experience: '12+', salary_cn: { low: 60, mid: 82, high: 115 }, salary_de: { low: 120, mid: 148, high: 185 }, key_skills: ['Enterprise Architecture', 'Digital Transformation Strategy'] },
      ],
    },
    {
      id: 'itm-data-engineer',
      title: 'Data Engineer',
      title_zh: '数据工程师',
      title_de: 'Dateningenieur',
      soc_code: '15-1243.00',
      kldb_code: '43114',
      function_area: 'Data & Analytics',
      function_area_zh: '数据与分析',
      core_skills: ['Python', 'SQL', 'ETL/ELT', 'Data Warehouse', 'Power BI/Tableau'],
      growth_outlook: 'high',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '初级数据工程师', level_de: 'Junior Dateningenieur', years_experience: '0-2', salary_cn: { low: 10, mid: 14, high: 18 }, salary_de: { low: 44, mid: 52, high: 60 }, key_skills: ['Data Pipeline Basics', 'SQL Optimization'] },
        { level: 'senior', level_zh: '高级数据工程师', level_de: 'Senior Dateningenieur', years_experience: '3-5', salary_cn: { low: 18, mid: 25, high: 35 }, salary_de: { low: 58, mid: 72, high: 88 }, key_skills: ['Data Lake Architecture', 'Spark/Databricks', 'Real-time Streaming'] },
        { level: 'lead', level_zh: '数据主管', level_de: 'Teamleiter Daten', years_experience: '5-8', salary_cn: { low: 28, mid: 38, high: 50 }, salary_de: { low: 76, mid: 90, high: 108 }, key_skills: ['Data Platform Design', 'Data Governance', 'ML Pipeline'] },
        { level: 'manager', level_zh: '数据经理', level_de: 'Datenmanager', years_experience: '8-12', salary_cn: { low: 38, mid: 52, high: 70 }, salary_de: { low: 92, mid: 112, high: 135 }, key_skills: ['Analytics Strategy', 'Data-driven Manufacturing', 'Team Building'] },
        { level: 'director', level_zh: '数据总监', level_de: 'Datendirektor', years_experience: '12+', salary_cn: { low: 55, mid: 78, high: 108 }, salary_de: { low: 118, mid: 145, high: 182 }, key_skills: ['Enterprise Data Strategy', 'AI/ML Roadmap'] },
      ],
    },
    {
      id: 'itm-iot-engineer',
      title: 'IoT Platform Engineer',
      title_zh: '物联网平台工程师',
      title_de: 'IoT-Plattformingenieur',
      soc_code: '15-1252.00',
      kldb_code: '43414',
      function_area: 'IoT / Edge Computing',
      function_area_zh: '物联网/边缘计算',
      core_skills: ['MQTT/OPC UA', 'Edge Computing', 'Cloud (AWS IoT/Azure IoT)', 'Python/Node.js', 'Time-series Databases'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级IoT工程师', level_de: 'Junior IoT-Ingenieur', years_experience: '0-2', salary_cn: { low: 10, mid: 14, high: 18 }, salary_de: { low: 44, mid: 52, high: 60 }, key_skills: ['Sensor Integration', 'Basic Dashboard Development'] },
        { level: 'senior', level_zh: '高级IoT工程师', level_de: 'Senior IoT-Ingenieur', years_experience: '3-5', salary_cn: { low: 18, mid: 25, high: 35 }, salary_de: { low: 58, mid: 72, high: 88 }, key_skills: ['Edge Gateway Design', 'Protocol Translation', 'Predictive Maintenance'] },
        { level: 'lead', level_zh: 'IoT主管', level_de: 'Teamleiter IoT', years_experience: '5-8', salary_cn: { low: 30, mid: 40, high: 52 }, salary_de: { low: 78, mid: 92, high: 110 }, key_skills: ['Platform Architecture', 'Multi-site Deployment', 'Data Model Design'] },
        { level: 'manager', level_zh: 'IoT经理', level_de: 'IoT-Manager', years_experience: '8-12', salary_cn: { low: 40, mid: 55, high: 72 }, salary_de: { low: 95, mid: 115, high: 138 }, key_skills: ['IoT Strategy', 'Vendor Ecosystem Management', 'ROI Analysis'] },
        { level: 'director', level_zh: 'IoT总监', level_de: 'IoT-Direktor', years_experience: '12+', salary_cn: { low: 58, mid: 80, high: 110 }, salary_de: { low: 122, mid: 150, high: 188 }, key_skills: ['Connected Factory Strategy', 'Digital Thread Architecture'] },
      ],
    },
    {
      id: 'itm-ot-cybersecurity',
      title: 'Cybersecurity Specialist (OT)',
      title_zh: 'OT网络安全专家',
      title_de: 'OT-Cybersicherheitsspezialist',
      soc_code: '15-1212.00',
      kldb_code: '43114',
      function_area: 'Cybersecurity',
      function_area_zh: '网络安全',
      core_skills: ['IEC 62443', 'NIST CSF', 'Network Segmentation', 'OT Protocol Analysis', 'Vulnerability Assessment'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级OT安全工程师', level_de: 'Junior OT-Sicherheitsingenieur', years_experience: '0-2', salary_cn: { low: 11, mid: 15, high: 20 }, salary_de: { low: 46, mid: 55, high: 64 }, key_skills: ['Asset Inventory', 'Baseline Monitoring'] },
        { level: 'senior', level_zh: '高级OT安全工程师', level_de: 'Senior OT-Sicherheitsingenieur', years_experience: '3-5', salary_cn: { low: 20, mid: 28, high: 38 }, salary_de: { low: 62, mid: 76, high: 92 }, key_skills: ['Penetration Testing (OT)', 'Incident Response', 'Firewall/DMZ Design'] },
        { level: 'lead', level_zh: 'OT安全主管', level_de: 'Teamleiter OT-Sicherheit', years_experience: '5-8', salary_cn: { low: 32, mid: 42, high: 55 }, salary_de: { low: 80, mid: 96, high: 115 }, key_skills: ['Security Architecture', 'Risk Assessment', 'Compliance Audit'] },
        { level: 'manager', level_zh: 'OT安全经理', level_de: 'OT-Sicherheitsmanager', years_experience: '8-12', salary_cn: { low: 42, mid: 58, high: 78 }, salary_de: { low: 98, mid: 118, high: 142 }, key_skills: ['Security Program Management', 'Incident Recovery Planning'] },
        { level: 'director', level_zh: 'OT安全总监', level_de: 'Direktor OT-Cybersicherheit', years_experience: '12+', salary_cn: { low: 62, mid: 85, high: 118 }, salary_de: { low: 128, mid: 158, high: 195 }, key_skills: ['Enterprise OT Security Strategy', 'Regulatory Compliance', 'IEC 62443'] },
      ],
    },
    {
      id: 'itm-digital-twin',
      title: 'Digital Twin Engineer',
      title_zh: '数字孪生工程师',
      title_de: 'Digital-Twin-Ingenieur',
      soc_code: '15-1252.00',
      kldb_code: '43414',
      function_area: 'Simulation & Digital Twin',
      function_area_zh: '仿真与数字孪生',
      core_skills: ['Unity/Unreal (Industrial)', 'Siemens Tecnomatix', 'Python', '3D Modeling', 'Physics Simulation'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级数字孪生工程师', level_de: 'Junior Digital-Twin-Ingenieur', years_experience: '0-2', salary_cn: { low: 12, mid: 16, high: 22 }, salary_de: { low: 46, mid: 55, high: 64 }, key_skills: ['3D Scene Building', 'Basic Data Binding'] },
        { level: 'senior', level_zh: '高级数字孪生工程师', level_de: 'Senior Digital-Twin-Ingenieur', years_experience: '3-5', salary_cn: { low: 22, mid: 30, high: 42 }, salary_de: { low: 62, mid: 76, high: 92 }, key_skills: ['Real-time Synchronization', 'Process Simulation', 'Virtual Commissioning'] },
        { level: 'lead', level_zh: '数字孪生主管', level_de: 'Teamleiter Digital Twin', years_experience: '5-8', salary_cn: { low: 35, mid: 45, high: 60 }, salary_de: { low: 80, mid: 96, high: 115 }, key_skills: ['Platform Architecture', 'Multi-domain Integration'] },
        { level: 'manager', level_zh: '数字孪生经理', level_de: 'Digital-Twin-Manager', years_experience: '8-12', salary_cn: { low: 45, mid: 60, high: 80 }, salary_de: { low: 98, mid: 118, high: 142 }, key_skills: ['Digital Twin Strategy', 'Vendor Ecosystem', 'ROI Demonstration'] },
        { level: 'director', level_zh: '数字化总监', level_de: 'Direktor Digitalisierung', years_experience: '12+', salary_cn: { low: 62, mid: 88, high: 120 }, salary_de: { low: 125, mid: 155, high: 192 }, key_skills: ['Digital Transformation Leadership', 'Metaverse/Industrial Web Strategy'] },
      ],
    },
  ],
};
