import type { IndustryCareerMap } from './types';

export const medicalDevicesCareerMap: IndustryCareerMap = {
  id: 'medical-devices',
  name: 'Medical Devices',
  name_zh: '医疗器械',
  name_de: 'Medizintechnik',
  icon: '🏥',
  description: 'The medical device industry offers exceptional job stability and premium salaries for regulatory and quality experts. ISO 13485, FDA 21 CFR 820, and EU MDR expertise are in short supply globally. Regulatory affairs specialists command a significant salary premium.',
  description_zh: '医疗器械行业为法规和质量专家提供出色的工作稳定性和高薪。全球范围内ISO 13485、FDA 21 CFR 820和EU MDR专业人才紧缺，法规事务专家薪资溢价显著。',
  description_de: 'Die Medizintechnikbranche bietet hervorragende Arbeitsplatzsicherheit und Premiumgehälter für Regulierungs- und Qualitätsexperten. ISO 13485, FDA und EU-MDR-Expertise sind weltweit Mangelware.',
  avg_salary_cn: 21,
  avg_salary_de: 67,
  top_benefits: ['Annual conference budget', 'Certification sponsorship', 'Flexible hours', 'Health insurance premium'],
  top_benefits_zh: ['年度会议预算', '认证资助', '弹性工作时间', '高端医疗保险'],
  ranking_2026: 7,
  sub_categories: [
    { name: 'Implants', name_zh: '植入物', name_de: 'Implantate', icon: '🦴' },
    { name: 'Diagnostics', name_zh: '诊断设备', name_de: 'Diagnostik', icon: '🔬' },
    { name: 'Surgical Devices', name_zh: '手术器械', name_de: 'Chirurgische Geräte', icon: '🏥' },
  ],
  roles: [
    {
      id: 'md-quality-engineer',
      title: 'Quality Engineer (ISO 13485)',
      title_zh: '质量工程师 (ISO 13485)',
      title_de: 'Qualitätsingenieur (ISO 13485)',
      function_area: 'Quality',
      function_area_zh: '质量',
      core_skills: ['ISO 13485', 'FDA 21 CFR 820', 'CAPA', 'Risk Management (ISO 14971)', 'Internal Auditing'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级质量工程师', level_de: 'Junior Qualitätsingenieur', years_experience: '0-2', salary_cn: { low: 9, mid: 12, high: 16 }, salary_de: { low: 44, mid: 52, high: 60 }, key_skills: ['Document Control', 'Complaint Handling'] },
        { level: 'senior', level_zh: '高级质量工程师', level_de: 'Senior Qualitätsingenieur', years_experience: '3-5', salary_cn: { low: 16, mid: 22, high: 30 }, salary_de: { low: 58, mid: 70, high: 82 }, key_skills: ['Supplier Audit', 'Process Validation (IQ/OQ/PQ)', 'Statistical Methods'] },
        { level: 'lead', level_zh: '质量主管', level_de: 'Teamleiter Qualität', years_experience: '5-8', salary_cn: { low: 26, mid: 34, high: 45 }, salary_de: { low: 75, mid: 88, high: 104 }, key_skills: ['QMS Management', 'Notified Body Interface', 'Design Control'] },
        { level: 'manager', level_zh: '质量经理', level_de: 'Qualitätsmanager', years_experience: '8-12', salary_cn: { low: 38, mid: 50, high: 68 }, salary_de: { low: 92, mid: 110, high: 132 }, key_skills: ['Quality Strategy', 'FDA Inspection Readiness', 'Team Leadership'] },
        { level: 'director', level_zh: '质量总监', level_de: 'Qualitätsdirektor', years_experience: '12+', salary_cn: { low: 58, mid: 80, high: 110 }, salary_de: { low: 120, mid: 148, high: 185 }, key_skills: ['Global QMS Strategy', 'Regulatory Agency Relations', 'M&A Quality Due Diligence'] },
      ],
    },
    {
      id: 'md-rd-engineer',
      title: 'R&D Engineer',
      title_zh: '研发工程师',
      title_de: 'Entwicklungsingenieur',
      function_area: 'R&D',
      function_area_zh: '研发',
      core_skills: ['Design Control (ISO 13485)', 'SolidWorks/Creo', 'Biocompatibility (ISO 10993)', 'Prototyping', 'Design for Manufacturability'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级研发工程师', level_de: 'Junior Entwicklungsingenieur', years_experience: '0-2', salary_cn: { low: 10, mid: 14, high: 18 }, salary_de: { low: 46, mid: 54, high: 62 }, key_skills: ['3D Modeling', 'Test Protocol Execution'] },
        { level: 'senior', level_zh: '高级研发工程师', level_de: 'Senior Entwicklungsingenieur', years_experience: '3-5', salary_cn: { low: 18, mid: 25, high: 35 }, salary_de: { low: 60, mid: 72, high: 88 }, key_skills: ['Design Verification', 'FEA/CFD', 'Usability Engineering (IEC 62366)'] },
        { level: 'lead', level_zh: '研发主管', level_de: 'Teamleiter Entwicklung', years_experience: '5-8', salary_cn: { low: 30, mid: 40, high: 52 }, salary_de: { low: 80, mid: 95, high: 112 }, key_skills: ['Design History File', 'Cross-functional Project Lead'] },
        { level: 'manager', level_zh: '研发经理', level_de: 'Entwicklungsmanager', years_experience: '8-12', salary_cn: { low: 42, mid: 58, high: 78 }, salary_de: { low: 98, mid: 118, high: 142 }, key_skills: ['Product Roadmap', 'IP Strategy', 'Budget Management'] },
        { level: 'director', level_zh: '研发总监', level_de: 'Entwicklungsdirektor', years_experience: '12+', salary_cn: { low: 65, mid: 90, high: 125 }, salary_de: { low: 128, mid: 158, high: 195 }, key_skills: ['Technology Strategy', 'Clinical Advisory Board', 'Patent Portfolio'] },
      ],
    },
    {
      id: 'md-regulatory-affairs',
      title: 'Regulatory Affairs Specialist',
      title_zh: '法规事务专家',
      title_de: 'Regulatory Affairs Spezialist',
      function_area: 'Regulatory',
      function_area_zh: '法规',
      core_skills: ['EU MDR 2017/745', 'FDA 510(k)/PMA', 'NMPA (China)', 'Technical Documentation', 'Clinical Evaluation'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级法规专员', level_de: 'Junior RA-Spezialist', years_experience: '0-2', salary_cn: { low: 10, mid: 13, high: 17 }, salary_de: { low: 46, mid: 54, high: 62 }, key_skills: ['Document Preparation', 'Registration Tracking'] },
        { level: 'senior', level_zh: '高级法规专家', level_de: 'Senior RA-Spezialist', years_experience: '3-5', salary_cn: { low: 18, mid: 26, high: 36 }, salary_de: { low: 62, mid: 76, high: 92 }, key_skills: ['510(k) Submission', 'CE Marking (MDR)', 'Post-Market Surveillance'] },
        { level: 'lead', level_zh: '法规主管', level_de: 'Teamleiter Regulatory Affairs', years_experience: '5-8', salary_cn: { low: 32, mid: 42, high: 55 }, salary_de: { low: 82, mid: 98, high: 118 }, key_skills: ['Regulatory Strategy', 'Multi-market Submissions', 'Notified Body Management'] },
        { level: 'manager', level_zh: '法规经理', level_de: 'RA-Manager', years_experience: '8-12', salary_cn: { low: 45, mid: 60, high: 82 }, salary_de: { low: 100, mid: 122, high: 148 }, key_skills: ['Global Regulatory Strategy', 'Agency Negotiations', 'Team Development'] },
        { level: 'director', level_zh: '法规总监', level_de: 'RA-Direktor', years_experience: '12+', salary_cn: { low: 68, mid: 95, high: 130 }, salary_de: { low: 132, mid: 162, high: 200 }, key_skills: ['Executive Regulatory Strategy', 'Health Authority Relations', 'Due Diligence'] },
      ],
    },
    {
      id: 'md-validation-engineer',
      title: 'Validation Engineer',
      title_zh: '验证工程师',
      title_de: 'Validierungsingenieur',
      function_area: 'Quality / Engineering',
      function_area_zh: '质量/工程',
      core_skills: ['IQ/OQ/PQ', 'Process Validation', 'CSV (Computer System Validation)', 'Statistical Methods', 'Protocol Writing'],
      growth_outlook: 'medium',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级验证工程师', level_de: 'Junior Validierungsingenieur', years_experience: '0-2', salary_cn: { low: 8, mid: 11, high: 15 }, salary_de: { low: 42, mid: 50, high: 58 }, key_skills: ['Protocol Execution', 'Data Collection'] },
        { level: 'senior', level_zh: '高级验证工程师', level_de: 'Senior Validierungsingenieur', years_experience: '3-5', salary_cn: { low: 15, mid: 21, high: 28 }, salary_de: { low: 56, mid: 66, high: 78 }, key_skills: ['Protocol Writing', 'TMV (Test Method Validation)', 'Cleaning Validation'] },
        { level: 'lead', level_zh: '验证主管', level_de: 'Teamleiter Validierung', years_experience: '5-8', salary_cn: { low: 24, mid: 32, high: 42 }, salary_de: { low: 72, mid: 85, high: 100 }, key_skills: ['Validation Master Plan', 'Deviation Management'] },
        { level: 'manager', level_zh: '验证经理', level_de: 'Validierungsmanager', years_experience: '8-12', salary_cn: { low: 35, mid: 45, high: 60 }, salary_de: { low: 88, mid: 105, high: 125 }, key_skills: ['Site Validation Strategy', 'Regulatory Inspection Support'] },
        { level: 'director', level_zh: '验证总监', level_de: 'Validierungsdirektor', years_experience: '12+', salary_cn: { low: 52, mid: 70, high: 95 }, salary_de: { low: 112, mid: 138, high: 172 }, key_skills: ['Global Validation Strategy', 'Continuous Process Verification'] },
      ],
    },
    {
      id: 'md-manufacturing-engineer',
      title: 'Manufacturing Engineer',
      title_zh: '制造工程师',
      title_de: 'Fertigungsingenieur',
      function_area: 'Manufacturing',
      function_area_zh: '制造',
      core_skills: ['GMP', 'Lean Manufacturing', 'Process Development', 'Cleanroom Operations', 'Equipment Qualification'],
      growth_outlook: 'medium',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级制造工程师', level_de: 'Junior Fertigungsingenieur', years_experience: '0-2', salary_cn: { low: 8, mid: 10, high: 14 }, salary_de: { low: 40, mid: 47, high: 55 }, key_skills: ['Work Instructions', 'Line Balancing'] },
        { level: 'senior', level_zh: '高级制造工程师', level_de: 'Senior Fertigungsingenieur', years_experience: '3-5', salary_cn: { low: 13, mid: 18, high: 25 }, salary_de: { low: 54, mid: 64, high: 76 }, key_skills: ['Process Optimization', 'Fixture Design', 'Yield Improvement'] },
        { level: 'lead', level_zh: '制造主管', level_de: 'Teamleiter Fertigung', years_experience: '5-8', salary_cn: { low: 22, mid: 28, high: 38 }, salary_de: { low: 70, mid: 82, high: 96 }, key_skills: ['NPI (New Product Introduction)', 'Transfer to Manufacturing'] },
        { level: 'manager', level_zh: '制造经理', level_de: 'Fertigungsmanager', years_experience: '8-12', salary_cn: { low: 32, mid: 42, high: 55 }, salary_de: { low: 85, mid: 100, high: 120 }, key_skills: ['Plant Layout', 'CapEx Planning', 'Automation Strategy'] },
        { level: 'director', level_zh: '制造总监', level_de: 'Fertigungsdirektor', years_experience: '12+', salary_cn: { low: 50, mid: 68, high: 92 }, salary_de: { low: 108, mid: 132, high: 168 }, key_skills: ['Multi-site Operations', 'Manufacturing Strategy'] },
      ],
    },
    {
      id: 'md-biomedical-engineer',
      title: 'Biomedical Engineer',
      title_zh: '生物医学工程师',
      title_de: 'Biomediziningenieur',
      function_area: 'R&D',
      function_area_zh: '研发',
      core_skills: ['Biomaterials', 'Biomechanics', 'Signal Processing', 'MATLAB', 'Biocompatibility Testing'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级生物医学工程师', level_de: 'Junior Biomediziningenieur', years_experience: '0-2', salary_cn: { low: 10, mid: 13, high: 17 }, salary_de: { low: 44, mid: 52, high: 60 }, key_skills: ['Lab Testing', 'Data Analysis'] },
        { level: 'senior', level_zh: '高级生物医学工程师', level_de: 'Senior Biomediziningenieur', years_experience: '3-5', salary_cn: { low: 17, mid: 24, high: 32 }, salary_de: { low: 58, mid: 70, high: 85 }, key_skills: ['In-vitro Testing', 'Animal Study Design', 'Tissue Engineering'] },
        { level: 'lead', level_zh: '生物医学主管', level_de: 'Teamleiter Biomedizin', years_experience: '5-8', salary_cn: { low: 28, mid: 38, high: 50 }, salary_de: { low: 78, mid: 92, high: 110 }, key_skills: ['Research Program Lead', 'Cross-disciplinary Collaboration'] },
        { level: 'manager', level_zh: '生物医学经理', level_de: 'Biomedizinmanager', years_experience: '8-12', salary_cn: { low: 40, mid: 55, high: 72 }, salary_de: { low: 95, mid: 115, high: 138 }, key_skills: ['Innovation Pipeline', 'Grant/Funding Management'] },
        { level: 'director', level_zh: '生物医学总监', level_de: 'Direktor Biomedizintechnik', years_experience: '12+', salary_cn: { low: 60, mid: 82, high: 115 }, salary_de: { low: 122, mid: 150, high: 188 }, key_skills: ['Research Strategy', 'KOL Network', 'Technology Scouting'] },
      ],
    },
    {
      id: 'md-clinical-engineer',
      title: 'Clinical Engineer',
      title_zh: '临床工程师',
      title_de: 'Klinischer Ingenieur',
      function_area: 'Clinical',
      function_area_zh: '临床',
      core_skills: ['Clinical Evaluation (MEDDEV 2.7/1)', 'Clinical Investigation Design', 'Biostatistics', 'GCP', 'Literature Review'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级临床工程师', level_de: 'Junior Klinischer Ingenieur', years_experience: '0-2', salary_cn: { low: 9, mid: 12, high: 16 }, salary_de: { low: 44, mid: 52, high: 60 }, key_skills: ['Literature Search', 'Data Entry/Cleaning'] },
        { level: 'senior', level_zh: '高级临床工程师', level_de: 'Senior Klinischer Ingenieur', years_experience: '3-5', salary_cn: { low: 16, mid: 22, high: 30 }, salary_de: { low: 58, mid: 70, high: 84 }, key_skills: ['CER Writing', 'PMCF Planning', 'Statistical Analysis'] },
        { level: 'lead', level_zh: '临床主管', level_de: 'Teamleiter Klinische Bewertung', years_experience: '5-8', salary_cn: { low: 26, mid: 35, high: 45 }, salary_de: { low: 76, mid: 90, high: 106 }, key_skills: ['Clinical Investigation Management', 'Ethics Committee Interface'] },
        { level: 'manager', level_zh: '临床经理', level_de: 'Klinischer Manager', years_experience: '8-12', salary_cn: { low: 38, mid: 50, high: 65 }, salary_de: { low: 92, mid: 112, high: 135 }, key_skills: ['Clinical Strategy', 'KOL Management', 'Multi-site Studies'] },
        { level: 'director', level_zh: '临床总监', level_de: 'Direktor Klinische Angelegenheiten', years_experience: '12+', salary_cn: { low: 55, mid: 78, high: 105 }, salary_de: { low: 118, mid: 145, high: 182 }, key_skills: ['Global Clinical Strategy', 'Health Economics', 'Advisory Board Leadership'] },
      ],
    },
  ],
};
