import type { IndustryCareerMap } from './types';

export const roboticsCareerMap: IndustryCareerMap = {
  id: 'robotics',
  name: 'Robotics & Intelligent Systems',
  name_zh: '机器人与智能系统',
  name_de: 'Robotik & Intelligente Systeme',
  icon: '🦾',
  description: 'Robotics spans industrial, collaborative, and service robots. China is the world\'s largest robot market (over 50% of global installations), while Germany leads Europe through KUKA, Franka Emika, and a deep automation tradition. Demand for robotics engineers far outpaces supply, especially in vision/AI and mobile robotics.',
  description_zh: '机器人领域涵盖工业机器人、协作机器人和服务机器人。中国是全球最大的机器人市场（占全球装机量50%以上），德国则凭借KUKA、Franka Emika及深厚的自动化传统引领欧洲。机器人工程师需求远超供给，尤其在视觉/AI和移动机器人领域。',
  description_de: 'Robotik umfasst Industrie-, Kollaborations- und Serviceroboter. China ist der weltweit größte Robotermarkt (über 50 % der globalen Installationen), während Deutschland mit KUKA, Franka Emika und einer tiefen Automatisierungstradition Europas Spitzenreiter ist.',
  avg_salary_cn: 24,
  avg_salary_de: 72,
  top_benefits: ['Innovation bonus', 'Patent bonus', 'International travel', 'Flexible work hours'],
  top_benefits_zh: ['创新奖金', '专利奖金', '国际出差', '弹性工作'],
  ranking_2026: 2,
  roles: [
    {
      id: 'robo-application-engineer',
      title: 'Robot Application Engineer',
      title_zh: '机器人应用工程师',
      title_de: 'Roboterapplikationsingenieur',
      soc_code: '17-2199.00',
      kldb_code: '26124',
      function_area: 'Application Engineering',
      function_area_zh: '应用工程',
      core_skills: ['FANUC TP/KAREL', 'KUKA KRL', 'ABB RAPID', 'Robot Calibration', 'PLC Integration'],
      growth_outlook: 'medium',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 8, mid: 11, high: 15 }, salary_de: { low: 42, mid: 50, high: 58 }, key_skills: ['Robot Teaching', 'Basic Programming'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 14, mid: 20, high: 28 }, salary_de: { low: 55, mid: 65, high: 78 }, key_skills: ['Offline Programming', 'Arc/Spot Welding Cells', 'Commissioning'] },
        { level: 'lead', level_zh: '应用主管', level_de: 'Teamleiter Applikation', years_experience: '5-8', salary_cn: { low: 22, mid: 30, high: 40 }, salary_de: { low: 72, mid: 84, high: 98 }, key_skills: ['Multi-brand Integration', 'Customer Training'] },
        { level: 'manager', level_zh: '应用经理', level_de: 'Applikationsmanager', years_experience: '8-12', salary_cn: { low: 32, mid: 42, high: 55 }, salary_de: { low: 88, mid: 102, high: 120 }, key_skills: ['Application Strategy', 'Key Account Management'] },
        { level: 'director', level_zh: '应用总监', level_de: 'Applikationsdirektor', years_experience: '12+', salary_cn: { low: 50, mid: 68, high: 90 }, salary_de: { low: 110, mid: 135, high: 165 }, key_skills: ['Global Application Standards', 'Technology Roadmap'] },
      ],
    },
    {
      id: 'robo-mechanical-design',
      title: 'Robot Mechanical Design Engineer',
      title_zh: '机器人机械设计工程师',
      title_de: 'Roboter-Konstruktionsingenieur',
      soc_code: '17-2141.00',
      kldb_code: '27124',
      function_area: 'Mechanical Engineering',
      function_area_zh: '机械工程',
      core_skills: ['SolidWorks/CATIA', 'FEA (ANSYS)', 'GD&T', 'Harmonic/Cycloidal Drives', 'Materials Selection'],
      growth_outlook: 'medium',
      ai_risk: 'medium',
      levels: [
        { level: 'junior', level_zh: '初级设计工程师', level_de: 'Junior-Konstrukteur', years_experience: '0-2', salary_cn: { low: 9, mid: 12, high: 16 }, salary_de: { low: 44, mid: 52, high: 60 }, key_skills: ['3D Modeling', 'Gripper Design'] },
        { level: 'senior', level_zh: '高级设计工程师', level_de: 'Senior-Konstrukteur', years_experience: '3-5', salary_cn: { low: 15, mid: 22, high: 30 }, salary_de: { low: 58, mid: 70, high: 82 }, key_skills: ['End-Effector Design', 'Topology Optimization', 'Prototype Testing'] },
        { level: 'lead', level_zh: '设计主管', level_de: 'Teamleiter Konstruktion', years_experience: '5-8', salary_cn: { low: 25, mid: 33, high: 42 }, salary_de: { low: 75, mid: 88, high: 102 }, key_skills: ['Robot Arm Architecture', 'DFM/DFA'] },
        { level: 'manager', level_zh: '设计经理', level_de: 'Konstruktionsmanager', years_experience: '8-12', salary_cn: { low: 35, mid: 48, high: 62 }, salary_de: { low: 92, mid: 108, high: 128 }, key_skills: ['Platform Standardization', 'IP Management'] },
        { level: 'director', level_zh: '机械总监', level_de: 'Direktor Mechanik', years_experience: '12+', salary_cn: { low: 55, mid: 75, high: 100 }, salary_de: { low: 115, mid: 142, high: 170 }, key_skills: ['Next-gen Robot Architecture', 'Make-or-Buy Strategy'] },
      ],
    },
    {
      id: 'robo-motion-control',
      title: 'Motion Control Engineer',
      title_zh: '运动控制工程师',
      title_de: 'Ingenieur für Bewegungssteuerung',
      soc_code: '17-2199.00',
      kldb_code: '26124',
      function_area: 'Controls Engineering',
      function_area_zh: '控制工程',
      core_skills: ['Servo Systems', 'PID/Advanced Control', 'Trajectory Planning', 'MATLAB/Simulink', 'EtherCAT/PROFINET'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 10, mid: 14, high: 18 }, salary_de: { low: 46, mid: 54, high: 62 }, key_skills: ['Motor Tuning', 'Basic Kinematics'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 18, mid: 25, high: 35 }, salary_de: { low: 60, mid: 72, high: 86 }, key_skills: ['Inverse Kinematics', 'Force Control', 'Real-time Linux'] },
        { level: 'lead', level_zh: '控制主管', level_de: 'Teamleiter Steuerung', years_experience: '5-8', salary_cn: { low: 30, mid: 40, high: 52 }, salary_de: { low: 80, mid: 94, high: 110 }, key_skills: ['Motion Platform Architecture', 'Model Predictive Control'] },
        { level: 'manager', level_zh: '控制经理', level_de: 'Leiter Steuerungstechnik', years_experience: '8-12', salary_cn: { low: 42, mid: 55, high: 72 }, salary_de: { low: 96, mid: 115, high: 138 }, key_skills: ['Control Strategy', 'Multi-axis Coordination', 'Patent Development'] },
        { level: 'director', level_zh: '控制总监', level_de: 'Direktor Steuerungstechnik', years_experience: '12+', salary_cn: { low: 60, mid: 85, high: 115 }, salary_de: { low: 120, mid: 148, high: 175 }, key_skills: ['Next-gen Motion Platform', 'Global R&D Leadership'] },
      ],
    },
    {
      id: 'robo-vision-engineer',
      title: 'Robot Vision Engineer',
      title_zh: '机器人视觉工程师',
      title_de: 'Roboter-Vision-Ingenieur',
      soc_code: '17-2199.00',
      kldb_code: '26124',
      function_area: 'AI & Perception',
      function_area_zh: 'AI与感知',
      core_skills: ['OpenCV', '3D Vision (Structured Light/ToF)', 'Deep Learning (PyTorch)', 'Point Cloud Processing', 'Camera Calibration'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 12, mid: 17, high: 24 }, salary_de: { low: 50, mid: 58, high: 68 }, key_skills: ['Image Processing', '2D Inspection'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 22, mid: 32, high: 45 }, salary_de: { low: 66, mid: 80, high: 96 }, key_skills: ['3D Bin Picking', 'AI Defect Detection', 'Hand-Eye Calibration'] },
        { level: 'lead', level_zh: '视觉主管', level_de: 'Teamleiter Vision', years_experience: '5-8', salary_cn: { low: 38, mid: 50, high: 68 }, salary_de: { low: 88, mid: 102, high: 120 }, key_skills: ['Vision System Architecture', 'Edge AI Deployment'] },
        { level: 'manager', level_zh: '视觉经理', level_de: 'Leiter Bildverarbeitung', years_experience: '8-12', salary_cn: { low: 52, mid: 70, high: 95 }, salary_de: { low: 105, mid: 125, high: 150 }, key_skills: ['Perception Strategy', 'Multi-sensor Fusion', 'Team Scaling'] },
        { level: 'director', level_zh: '视觉/AI总监', level_de: 'Direktor Vision & KI', years_experience: '12+', salary_cn: { low: 75, mid: 105, high: 140 }, salary_de: { low: 130, mid: 158, high: 195 }, key_skills: ['AI Roadmap', 'Research Partnerships', 'Patent Portfolio'] },
      ],
    },
    {
      id: 'robo-cobot-integration',
      title: 'Cobot Integration Engineer',
      title_zh: '协作机器人集成工程师',
      title_de: 'Cobot-Integrationsingenieur',
      soc_code: '17-2199.00',
      kldb_code: '26124',
      function_area: 'System Integration',
      function_area_zh: '系统集成',
      core_skills: ['UR/Doosan/AUBO Programming', 'ISO/TS 15066', 'Risk Assessment (ISO 12100)', 'Safety PLC', 'Cell Layout Design'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 9, mid: 12, high: 16 }, salary_de: { low: 44, mid: 52, high: 60 }, key_skills: ['Cobot Setup', 'Basic Safety Assessment'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 16, mid: 23, high: 32 }, salary_de: { low: 58, mid: 70, high: 84 }, key_skills: ['Force-limited Cell Design', 'CE Marking', 'HRC Validation'] },
        { level: 'lead', level_zh: '集成主管', level_de: 'Teamleiter Integration', years_experience: '5-8', salary_cn: { low: 26, mid: 35, high: 46 }, salary_de: { low: 76, mid: 90, high: 105 }, key_skills: ['Multi-cobot Workcells', 'Safety Certification Lead'] },
        { level: 'manager', level_zh: '集成经理', level_de: 'Integrationsmanager', years_experience: '8-12', salary_cn: { low: 38, mid: 50, high: 65 }, salary_de: { low: 92, mid: 110, high: 130 }, key_skills: ['Cobot Strategy', 'ROI Analysis', 'Key Account Development'] },
        { level: 'director', level_zh: '集成总监', level_de: 'Direktor Systemintegration', years_experience: '12+', salary_cn: { low: 55, mid: 75, high: 100 }, salary_de: { low: 115, mid: 140, high: 170 }, key_skills: ['HRC Innovation Strategy', 'Industry Standards Leadership'] },
      ],
    },
    {
      id: 'robo-ros-navigation',
      title: 'ROS/Navigation Engineer',
      title_zh: 'ROS/导航工程师',
      title_de: 'ROS-/Navigationsingenieur',
      soc_code: '15-1252.00',
      kldb_code: '43414',
      function_area: 'Mobile Robotics',
      function_area_zh: '移动机器人',
      core_skills: ['ROS/ROS 2', 'SLAM (Cartographer/ORB-SLAM)', 'Path Planning (A*/D*)', 'C++/Python', 'Gazebo/Isaac Sim'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级工程师', level_de: 'Junior-Ingenieur', years_experience: '0-2', salary_cn: { low: 12, mid: 16, high: 22 }, salary_de: { low: 48, mid: 56, high: 65 }, key_skills: ['ROS Nodes/Topics', 'LiDAR Mapping'] },
        { level: 'senior', level_zh: '高级工程师', level_de: 'Senior-Ingenieur', years_experience: '3-5', salary_cn: { low: 22, mid: 30, high: 42 }, salary_de: { low: 64, mid: 78, high: 92 }, key_skills: ['Multi-robot Fleet Management', 'Visual SLAM', 'Nav2'] },
        { level: 'lead', level_zh: '导航主管', level_de: 'Teamleiter Navigation', years_experience: '5-8', salary_cn: { low: 35, mid: 48, high: 62 }, salary_de: { low: 85, mid: 98, high: 115 }, key_skills: ['AMR Platform Architecture', 'Sensor Fusion'] },
        { level: 'manager', level_zh: '导航经理', level_de: 'Leiter Navigation', years_experience: '8-12', salary_cn: { low: 48, mid: 65, high: 85 }, salary_de: { low: 100, mid: 120, high: 145 }, key_skills: ['Fleet Intelligence Strategy', 'Cloud Robotics'] },
        { level: 'director', level_zh: '移动机器人总监', level_de: 'Direktor Mobile Robotik', years_experience: '12+', salary_cn: { low: 70, mid: 95, high: 130 }, salary_de: { low: 125, mid: 155, high: 190 }, key_skills: ['AMR Product Roadmap', 'Autonomous Systems Strategy'] },
      ],
    },
    {
      id: 'robo-software-engineer',
      title: 'Robot Software Engineer',
      title_zh: '机器人软件工程师',
      title_de: 'Roboter-Softwareingenieur',
      soc_code: '15-1252.00',
      kldb_code: '43414',
      function_area: 'Software',
      function_area_zh: '软件',
      core_skills: ['C++', 'Python', 'Embedded Linux', 'Real-time Systems', 'Git/CI/CD'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '初级软件工程师', level_de: 'Junior SW-Ingenieur', years_experience: '0-2', salary_cn: { low: 12, mid: 16, high: 22 }, salary_de: { low: 48, mid: 56, high: 65 }, key_skills: ['Unit Testing', 'Driver Development'] },
        { level: 'senior', level_zh: '高级软件工程师', level_de: 'Senior SW-Ingenieur', years_experience: '3-5', salary_cn: { low: 20, mid: 28, high: 40 }, salary_de: { low: 62, mid: 76, high: 92 }, key_skills: ['RTOS', 'Simulation (Gazebo/Isaac)', 'gRPC/DDS'] },
        { level: 'lead', level_zh: '软件主管', level_de: 'SW-Teamleiter', years_experience: '5-8', salary_cn: { low: 33, mid: 45, high: 60 }, salary_de: { low: 82, mid: 96, high: 115 }, key_skills: ['Software Architecture', 'Code Review', 'DevOps for Robotics'] },
        { level: 'manager', level_zh: '软件经理', level_de: 'SW-Manager', years_experience: '8-12', salary_cn: { low: 45, mid: 62, high: 82 }, salary_de: { low: 98, mid: 118, high: 142 }, key_skills: ['Digital Twin Platform', 'Team Scaling', 'Agile for Hardware'] },
        { level: 'director', level_zh: '软件总监', level_de: 'SW-Direktor', years_experience: '12+', salary_cn: { low: 68, mid: 92, high: 125 }, salary_de: { low: 125, mid: 152, high: 188 }, key_skills: ['Robot OS/Platform Strategy', 'Open-source Governance'] },
      ],
    },
    {
      id: 'robo-project-manager',
      title: 'Robotics Project Manager',
      title_zh: '机器人项目经理',
      title_de: 'Robotik-Projektmanager',
      soc_code: '11-9041.00',
      kldb_code: '27214',
      function_area: 'Management',
      function_area_zh: '管理',
      core_skills: ['PMP/PRINCE2', 'System Integration', 'Risk Management', 'Stakeholder Management', 'Budget Planning'],
      growth_outlook: 'high',
      ai_risk: 'low',
      levels: [
        { level: 'junior', level_zh: '项目协调员', level_de: 'Projektkoordinator', years_experience: '0-2', salary_cn: { low: 9, mid: 12, high: 16 }, salary_de: { low: 44, mid: 52, high: 60 }, key_skills: ['Project Documentation', 'Schedule Tracking'] },
        { level: 'senior', level_zh: '项目经理', level_de: 'Projektmanager', years_experience: '3-5', salary_cn: { low: 16, mid: 24, high: 33 }, salary_de: { low: 60, mid: 72, high: 86 }, key_skills: ['Multi-robot Line Projects', 'System Integration'] },
        { level: 'lead', level_zh: '高级项目经理', level_de: 'Senior Projektmanager', years_experience: '5-8', salary_cn: { low: 28, mid: 38, high: 50 }, salary_de: { low: 80, mid: 94, high: 110 }, key_skills: ['Turnkey System Delivery', 'Subcontractor Management'] },
        { level: 'manager', level_zh: '项目管理经理', level_de: 'Leiter Projektmanagement', years_experience: '8-12', salary_cn: { low: 40, mid: 55, high: 72 }, salary_de: { low: 96, mid: 115, high: 138 }, key_skills: ['PMO Setup', 'Portfolio Management', 'P&L Ownership'] },
        { level: 'director', level_zh: '项目总监', level_de: 'Programmdirektor', years_experience: '12+', salary_cn: { low: 60, mid: 82, high: 110 }, salary_de: { low: 118, mid: 145, high: 178 }, key_skills: ['Strategic Program Planning', 'Global Delivery Operations'] },
      ],
    },
  ],
};
