import type { CourseEntry, EvidenceEntry, MajorFamily, SkillEntry, WorkTaskEntry } from './types';

export const majorFamilies: MajorFamily[] = [
  {
    id: 'mechanical',
    labels: { en: 'Mechanical Engineering', zh: '机械类', gameLabel: '机械门', gameCategory: 'faction' },
    courseIds: ['engineering-mechanics', 'mechanical-design', 'cad-foundation'],
    skillIds: ['cad', 'gd-t', 'mechanical-design', 'root-cause-analysis'],
    roleCodes: ['CN-ME', 'CN-RDE', 'CN-TE', 'DE-MFG-002', 'DE-MFG-009'],
  },
  {
    id: 'automation',
    labels: { en: 'Automation', zh: '自动化类', gameLabel: '自动化宗', gameCategory: 'faction' },
    courseIds: ['control-theory', 'sensor-systems', 'plc-foundation'],
    skillIds: ['plc', 'python', 'sensor-systems', 'control-systems'],
    roleCodes: ['CN-MNE', 'CN-IE', 'DE-MFG-006', 'DE-MFG-007'],
  },
  {
    id: 'electronics',
    labels: { en: 'Electronic Information', zh: '电子信息类', gameLabel: '电子谷', gameCategory: 'faction' },
    courseIds: ['circuit-analysis', 'embedded-systems', 'signal-processing'],
    skillIds: ['embedded-c', 'circuit-analysis', 'testing-validation', 'python'],
    roleCodes: ['CN-RDE', 'DE-MFG-009'],
  },
  {
    id: 'computer-data',
    labels: { en: 'Computer and Data', zh: '计算机/数据类', gameLabel: '计算机派', gameCategory: 'faction' },
    courseIds: ['data-structures', 'database-foundation', 'data-analysis'],
    skillIds: ['python', 'sql', 'power-bi', 'data-analysis'],
    roleCodes: ['CN-IE', 'CN-LEAN', 'DE-MFG-007'],
  },
  {
    id: 'energy',
    labels: { en: 'Energy and Power', zh: '能源动力类', gameLabel: '能源殿', gameCategory: 'faction' },
    courseIds: ['thermodynamics', 'battery-systems', 'energy-management'],
    skillIds: ['energy-management', 'testing-validation', 'data-analysis', 'root-cause-analysis'],
    roleCodes: ['CN-RDE', 'CN-NPI', 'DE-MFG-008', 'DE-MFG-009'],
  },
];

export const courses: CourseEntry[] = [
  { id: 'engineering-mechanics', labels: { en: 'Engineering Mechanics', zh: '工程力学', gameLabel: '力学心法' }, majorFamilyIds: ['mechanical'], skillIds: ['mechanical-design', 'root-cause-analysis'], difficulty: 'foundation' },
  { id: 'mechanical-design', labels: { en: 'Mechanical Design', zh: '机械设计', gameLabel: '结构锻造术' }, majorFamilyIds: ['mechanical'], skillIds: ['cad', 'mechanical-design', 'gd-t'], difficulty: 'intermediate' },
  { id: 'cad-foundation', labels: { en: 'CAD Foundation', zh: 'CAD基础', gameLabel: '制图器法' }, majorFamilyIds: ['mechanical'], skillIds: ['cad'], difficulty: 'foundation' },
  { id: 'control-theory', labels: { en: 'Control Theory', zh: '控制原理', gameLabel: '控制心法' }, majorFamilyIds: ['automation'], skillIds: ['control-systems', 'sensor-systems'], difficulty: 'intermediate' },
  { id: 'sensor-systems', labels: { en: 'Sensor Systems', zh: '传感器与检测', gameLabel: '感知术' }, majorFamilyIds: ['automation', 'electronics'], skillIds: ['sensor-systems', 'testing-validation'], difficulty: 'intermediate' },
  { id: 'plc-foundation', labels: { en: 'PLC Foundation', zh: 'PLC基础', gameLabel: '机关控制术' }, majorFamilyIds: ['automation'], skillIds: ['plc', 'control-systems'], difficulty: 'intermediate' },
  { id: 'circuit-analysis', labels: { en: 'Circuit Analysis', zh: '电路分析', gameLabel: '电路心法' }, majorFamilyIds: ['electronics'], skillIds: ['circuit-analysis'], difficulty: 'foundation' },
  { id: 'embedded-systems', labels: { en: 'Embedded Systems', zh: '嵌入式系统', gameLabel: '嵌入式机关术' }, majorFamilyIds: ['electronics'], skillIds: ['embedded-c', 'testing-validation'], difficulty: 'advanced' },
  { id: 'signal-processing', labels: { en: 'Signal Processing', zh: '信号处理', gameLabel: '信号辨识术' }, majorFamilyIds: ['electronics'], skillIds: ['python', 'data-analysis'], difficulty: 'advanced' },
  { id: 'data-structures', labels: { en: 'Data Structures', zh: '数据结构', gameLabel: '算法心法' }, majorFamilyIds: ['computer-data'], skillIds: ['python'], difficulty: 'foundation' },
  { id: 'database-foundation', labels: { en: 'Database Foundation', zh: '数据库基础', gameLabel: '数据仓术' }, majorFamilyIds: ['computer-data'], skillIds: ['sql'], difficulty: 'foundation' },
  { id: 'data-analysis', labels: { en: 'Data Analysis', zh: '数据分析', gameLabel: '洞察镜法' }, majorFamilyIds: ['computer-data'], skillIds: ['python', 'sql', 'power-bi', 'data-analysis'], difficulty: 'intermediate' },
  { id: 'thermodynamics', labels: { en: 'Thermodynamics', zh: '热力学', gameLabel: '热能心法' }, majorFamilyIds: ['energy'], skillIds: ['energy-management'], difficulty: 'foundation' },
  { id: 'battery-systems', labels: { en: 'Battery Systems', zh: '电池系统', gameLabel: '储能术' }, majorFamilyIds: ['energy'], skillIds: ['testing-validation', 'data-analysis'], difficulty: 'advanced' },
  { id: 'energy-management', labels: { en: 'Energy Management', zh: '能源管理', gameLabel: '能效阵法' }, majorFamilyIds: ['energy'], skillIds: ['energy-management', 'power-bi'], difficulty: 'intermediate' },
];

export const skills: SkillEntry[] = [
  { id: 'cad', labels: { en: 'CAD', zh: 'CAD制图' }, category: 'engineering', roleCodes: ['CN-ME', 'CN-RDE', 'DE-MFG-002'], evidenceIds: ['mechanical-assembly-project'], learningWeeks: 4 },
  { id: 'gd-t', labels: { en: 'GD&T', zh: 'GD&T几何尺寸与公差' }, category: 'engineering', roleCodes: ['CN-ME', 'CN-CNC', 'DE-MFG-002'], evidenceIds: ['mechanical-assembly-project'], learningWeeks: 3 },
  { id: 'mechanical-design', labels: { en: 'Mechanical Design', zh: '机械设计' }, category: 'engineering', roleCodes: ['CN-ME', 'CN-RDE', 'DE-MFG-009'], evidenceIds: ['mechanical-assembly-project'], learningWeeks: 6 },
  { id: 'plc', labels: { en: 'PLC', zh: 'PLC控制' }, category: 'automation', roleCodes: ['CN-MNE', 'DE-MFG-006'], evidenceIds: ['plc-mini-line-project'], learningWeeks: 6 },
  { id: 'python', labels: { en: 'Python', zh: 'Python' }, category: 'data', roleCodes: ['CN-IE', 'CN-LEAN', 'DE-MFG-007'], evidenceIds: ['quality-dashboard-project', 'plc-mini-line-project'], learningWeeks: 6 },
  { id: 'sensor-systems', labels: { en: 'Sensor Systems', zh: '传感器应用' }, category: 'automation', roleCodes: ['CN-MNE', 'DE-MFG-006'], evidenceIds: ['plc-mini-line-project'], learningWeeks: 4 },
  { id: 'control-systems', labels: { en: 'Control Systems', zh: '控制系统' }, category: 'automation', roleCodes: ['CN-MNE', 'DE-MFG-006'], evidenceIds: ['plc-mini-line-project'], learningWeeks: 8 },
  { id: 'sql', labels: { en: 'SQL', zh: 'SQL' }, category: 'data', roleCodes: ['CN-IE', 'CN-LEAN'], evidenceIds: ['quality-dashboard-project'], learningWeeks: 4 },
  { id: 'power-bi', labels: { en: 'Power BI', zh: 'Power BI' }, category: 'data', roleCodes: ['CN-IE', 'CN-LEAN', 'DE-MFG-007'], evidenceIds: ['quality-dashboard-project'], learningWeeks: 3 },
  { id: 'data-analysis', labels: { en: 'Data Analysis', zh: '数据分析' }, category: 'data', roleCodes: ['CN-IE', 'CN-LEAN', 'DE-MFG-007'], evidenceIds: ['quality-dashboard-project'], learningWeeks: 5 },
  { id: 'root-cause-analysis', labels: { en: 'Root Cause Analysis', zh: '根因分析' }, category: 'quality', roleCodes: ['CN-PE', 'CN-ME', 'DE-MFG-001'], evidenceIds: ['8d-achievement-case'], learningWeeks: 3 },
  { id: 'testing-validation', labels: { en: 'Testing and Validation', zh: '测试验证' }, category: 'engineering', roleCodes: ['CN-RDE', 'CN-NPI', 'DE-MFG-008'], evidenceIds: ['test-validation-report'], learningWeeks: 5 },
  { id: 'embedded-c', labels: { en: 'Embedded C', zh: '嵌入式C' }, category: 'automation', roleCodes: ['CN-RDE', 'DE-MFG-009'], evidenceIds: ['test-validation-report'], learningWeeks: 8 },
  { id: 'circuit-analysis', labels: { en: 'Circuit Analysis', zh: '电路分析' }, category: 'engineering', roleCodes: ['CN-RDE', 'DE-MFG-009'], evidenceIds: ['test-validation-report'], learningWeeks: 6 },
  { id: 'energy-management', labels: { en: 'Energy Management', zh: '能源管理' }, category: 'engineering', roleCodes: ['CN-PLE', 'DE-MFG-005'], evidenceIds: ['energy-efficiency-report'], learningWeeks: 5 },
];

export const workTasks: WorkTaskEntry[] = [
  { id: 'quality-complaint-8d', labels: { en: 'Customer complaint and 8D closure', zh: '客户投诉与8D闭环' }, skillIds: ['root-cause-analysis', 'data-analysis'], evidenceIds: ['8d-achievement-case'], adjacentRoleCodes: ['CN-PE', 'CN-LEAN', 'DE-MFG-001'] },
  { id: 'production-efficiency', labels: { en: 'Production efficiency improvement', zh: '生产效率改善' }, skillIds: ['root-cause-analysis', 'power-bi', 'data-analysis'], evidenceIds: ['quality-dashboard-project'], adjacentRoleCodes: ['CN-IE', 'CN-LEAN', 'DE-MFG-007'] },
  { id: 'equipment-troubleshooting', labels: { en: 'Equipment troubleshooting', zh: '设备故障排查' }, skillIds: ['plc', 'sensor-systems', 'root-cause-analysis'], evidenceIds: ['plc-mini-line-project'], adjacentRoleCodes: ['CN-MNE', 'DE-MFG-006'] },
  { id: 'supplier-coordination', labels: { en: 'Supplier coordination', zh: '供应商协调' }, skillIds: ['root-cause-analysis', 'testing-validation'], evidenceIds: ['8d-achievement-case'], adjacentRoleCodes: ['CN-NPI', 'DE-MFG-008'] },
  { id: 'engineering-data-reporting', labels: { en: 'Engineering data reporting', zh: '工程数据报表' }, skillIds: ['sql', 'power-bi', 'data-analysis'], evidenceIds: ['quality-dashboard-project'], adjacentRoleCodes: ['CN-IE', 'CN-LEAN', 'DE-MFG-007'] },
];

export const evidence: EvidenceEntry[] = [
  {
    id: 'mechanical-assembly-project',
    labels: { en: 'Mechanical assembly design project', zh: '机械装配设计项目', gameLabel: '结构装配副本' },
    provesSkillIds: ['cad', 'gd-t', 'mechanical-design'],
    roleCodes: ['CN-ME', 'CN-RDE', 'DE-MFG-002', 'DE-MFG-009'],
    deliverables: ['assembly model', '2D drawing package', 'tolerance stack note'],
    deliverablesZh: ['装配模型', '二维工程图包', '公差分析说明'],
    resumeBulletPatternZh: '完成机械装配设计项目，输出三维模型、工程图和关键公差说明。',
    resumeBulletPatternEn: 'Completed a mechanical assembly design project with 3D models, engineering drawings, and tolerance notes.',
    evidenceType: 'student-project',
    estimatedWeeks: 5,
  },
  {
    id: 'plc-mini-line-project',
    labels: { en: 'Mini production-line control project', zh: '小型产线控制项目', gameLabel: '小车控制副本' },
    provesSkillIds: ['plc', 'sensor-systems', 'control-systems', 'python'],
    roleCodes: ['CN-MNE', 'DE-MFG-006'],
    deliverables: ['control logic diagram', 'short demo video', 'sensor input and output table'],
    deliverablesZh: ['控制逻辑图', '演示视频', '传感器输入输出表'],
    resumeBulletPatternZh: '完成一个小型产线控制项目，设计PLC/传感器逻辑并输出可演示的控制流程。',
    resumeBulletPatternEn: 'Built a mini production-line control project with PLC and sensor logic, including a demo workflow and input-output documentation.',
    evidenceType: 'student-project',
    estimatedWeeks: 6,
  },
  {
    id: 'quality-dashboard-project',
    labels: { en: 'Quality data dashboard', zh: '质量数据看板' },
    provesSkillIds: ['python', 'sql', 'power-bi', 'data-analysis'],
    roleCodes: ['CN-IE', 'CN-LEAN', 'DE-MFG-007'],
    deliverables: ['sample dataset', 'Pareto analysis', 'SPC chart', 'dashboard screenshot'],
    deliverablesZh: ['样例数据集', '帕累托分析', 'SPC图表', '看板截图'],
    resumeBulletPatternZh: '基于质量数据构建分析看板，输出不良分布、趋势追踪和改善优先级。',
    resumeBulletPatternEn: 'Built a quality analytics dashboard covering defect distribution, trend tracking, and improvement priorities.',
    evidenceType: 'portfolio-project',
    estimatedWeeks: 4,
  },
  {
    id: '8d-achievement-case',
    labels: { en: '8D problem-solving case', zh: '8D问题解决案例' },
    provesSkillIds: ['root-cause-analysis', 'data-analysis', 'testing-validation'],
    roleCodes: ['CN-PE', 'CN-LEAN', 'DE-MFG-001'],
    deliverables: ['problem statement', 'root cause tree', 'corrective action list', 'before-after metric'],
    deliverablesZh: ['问题描述', '根因树', '纠正措施清单', '改善前后指标'],
    resumeBulletPatternZh: '主导客户投诉8D分析，协调生产、工艺和供应商团队完成根因定位与纠正预防措施。',
    resumeBulletPatternEn: 'Led an 8D analysis for customer complaints by coordinating production, process, and supplier teams to identify root causes and corrective actions.',
    evidenceType: 'professional-achievement',
    estimatedWeeks: 2,
  },
  {
    id: 'test-validation-report',
    labels: { en: 'Test validation report', zh: '测试验证报告' },
    provesSkillIds: ['testing-validation', 'embedded-c', 'circuit-analysis'],
    roleCodes: ['CN-RDE', 'CN-NPI', 'DE-MFG-008'],
    deliverables: ['test plan', 'test data', 'failure analysis', 'final report'],
    deliverablesZh: ['测试计划', '测试数据', '失效分析', '最终报告'],
    resumeBulletPatternZh: '完成产品测试验证报告，覆盖测试计划、失效分析和改进建议。',
    resumeBulletPatternEn: 'Completed a product validation report covering test planning, failure analysis, and improvement recommendations.',
    evidenceType: 'student-project',
    estimatedWeeks: 5,
  },
  {
    id: 'energy-efficiency-report',
    labels: { en: 'Energy efficiency report', zh: '能效改善报告' },
    provesSkillIds: ['energy-management', 'data-analysis', 'power-bi'],
    roleCodes: ['CN-PLE', 'DE-MFG-005'],
    deliverables: ['baseline estimate', 'energy loss map', 'improvement proposal', 'savings estimate'],
    deliverablesZh: ['能耗基线估算', '能耗损失地图', '改善方案', '节省估算'],
    resumeBulletPatternZh: '完成能效改善分析，识别主要能耗损失点并提出节能改善方案。',
    resumeBulletPatternEn: 'Completed an energy-efficiency analysis identifying major loss points and improvement actions.',
    evidenceType: 'portfolio-project',
    estimatedWeeks: 4,
  },
];
